### DISCUSSION TITLE
The 'threads' and 'req-condition' template attributes cannot be used simulatenously

### DISCUSSION THREAD

**Discussion by ehsandeep** [projectdiscovery/nuclei#1259] [General]
### Nuclei version:
dev

Template using `req-condition` misses valid matches if `threads` is used.

### Steps To Reproduce:

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    threads: 1
    req-condition: true
    extractors:
      - type: kval
        kval:
          - status_code_1
```

```
echo https://example.com | nuclei -t test.yaml
```
