### DISCUSSION TITLE
how extractors all href convert url path to next request

### DISCUSSION THREAD

**Discussion by hktalent** [projectdiscovery/nuclei#1860] [Q&A] [answered]
how extractors all href convert url path to next request
```
requests:
  - path:
      - https://example.com
      - https://example.com/{{URLPath}}
    extractors:
      - type: regex
        part: body
        name: URLPath
        regex:
          - 'href="(.*)"'
        group: 1
        internal: true 
```

**Comment by ehsandeep** [comment, marked as answer]
@hktalent You can do it using `iterate-all` attribute, for example:

```yaml
requests:
  - path:
      - https://example.com
      - https://example.com/{{URLPath}}

    iterate-all: true
    extractors:
      - type: regex
        part: body
        name: URLPath
        group: 1
        regex:
          - 'href="(.*)"'
        internal: true 
```
