### DISCUSSION TITLE
How to match specific words in SSL section?

### DISCUSSION THREAD

**Discussion by 0xAwali** [projectdiscovery/nuclei#1992] [Q&A] [answered]
Hi , I'm trying to match specific word when using ssl e.g.

```
id: 0x00

info:
  name: test
  author: 0xAwali
  severity: info
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"

    matchers:
      - type: word
        words:
          - 'Facebook, Inc.'
```

`nuclei -u 'https://www.facebook.com' -t ssl-dns-names.yaml`

but I can't , any hint please

**Comment by geeknik** [comment]
Take a look at the existing ssl-dns-names.yaml template: 

```
id: ssl-dns-names

info:
  name: SSL DNS Names
  author: pdteam
  severity: info
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"

    extractors:
      - type: json
        json:
          - " .dns_names[]"
```

👍🏻

**Comment by 0xAwali** [comment]
no , I don't want extract dns_names but I wanna match **specific** pattern into ssl response

**Comment by ehsandeep** [comment, marked as answer]
```yaml
id: 0x00

info:
  name: test
  author: 0xAwali
  severity: info
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"

    matchers:
      - type: word
        part: response
        words:
          - 'Facebook, Inc.'
```

@0xAwali
