### DISCUSSION TITLE
how use other requests raw extractors name data

### DISCUSSION THREAD

**Discussion by hktalent** [projectdiscovery/nuclei#2095] [Q&A] [answered]
@ehsandeep 
how use other requests raw extractors name data
in
Fragile password detection, and then file upload detection

```
id: Login-dome

info:
  name: Login-dome
  author: dome
  tags: login,explode
  severity: high 
  description: 
    Fragile password detection, and then file upload detection

variables:

requests:
  - raw:
    ....
    payloads:
      usernames:
        - "user"
        - "root"
        - "test"
        - "admin"
      passwords:
        - "123456"
        - "111111"
        - "admin"
        - "test"
        - "000000"
        - "password"
    attack: clusterbomb 

    extractors:
      - type: regex
        regex:
          - "name='user_token' *?value='(.*)'"
        group: 1
        part: body
        name: user_token
        internal: true
  - raw:

    # how use user_token  here
```

**Comment by ehsandeep** [comment, marked as answer]
@hktalent, you can reuse extracted data within same raw request block and not outside of it or 2nd raw block, here is valid example -

```yaml
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

      - |
        GET /?x={{user_token}} HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
```
