### DISCUSSION TITLE
How to apply arithmetic operations on variables defined in a template

### DISCUSSION THREAD

**Discussion by hktalent** [projectdiscovery/nuclei#2125] [Q&A] [answered]
```
id: xxx
info:
  name: xxx
  author: 51pwn
  severity: critical
  reference:
    - https://github.com/hktalent/nuclei-templates
    - https://51pwn.com

variables:
   xxx: 22

.....

matchers:
      - type: dsl
        part: header
        dsl:
          - 'contains(all_headers,xxx*3)'
```
same can not work
          - 'contains(all_headers,to_string(xxx*3))'

**Comment by forgedhallpass** [comment, marked as answer]
By default variables defined, under the `variables` attribute are considered strings.

If you would like to transform a specific variable to a number, you can use the `to_number` DSL function.

```yaml
variables:
  xxx: 22
...
  dsl:
    - print_debug(xxx+'a') # = 22a
    - print_debug(to_number(xxx)*2) # = 44
```
