### DISCUSSION TITLE
All templates of http1.1 may be modified in the future

### DISCUSSION THREAD

**Discussion by capiton0** [projectdiscovery/nuclei#2651] [Q&A] [answered]
nuclei's templates support raw loading of raw http requests:
```
requests:
  - raw:
      - |-
        GET / HTTP/1.1
        Host: {{Hostname}}

```
In all current nuclei templates
Most of the requests using raw are HTTP/1.1
In the future, if the http protocol is upgraded
Does it mean that many templates will need to be reworked
and re-tested
This is a very big project
I am also worried about
For example
There are some templates that need to continue to follow HTTP/1.1
And there are some templates that need to be upgraded to HTTP/2.0
How should this situation be differentiated at that time
