### DISCUSSION TITLE
Is there a way to automatically identify the xpath path in headless mode

### DISCUSSION THREAD

**Discussion by capiton0** [projectdiscovery/nuclei#2652] [Q&A] [answered]
I want to use headless to automatically recognize the text of the login box
Implement automatic recognition of login pages
Then auto-populate the account password
Automatically submit
Perform account password blasting
```
headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload
```
Now there is a problem that I have to specify the detailed path of the xpath
But different sites have different xpath paths
```
      - args:
          by: xpath
          xpath: /html/body/div/div[2]/form/fieldset/input
```
Is there any way to fuzzy input xpath path
Or use `extractors:` to identify input tags
Return the detailed path of the xpath
