### DISCUSSION TITLE
When using conditional workflows, only subtemplate shows in output

### DISCUSSION THREAD

**Discussion by tryeng** [projectdiscovery/nuclei#2683] [General]
Workflow:
```
id: test

info:
  name: test workflow
  author: t
  description: Simple workflow running templates

workflows:
  - template: mydevice.yaml 
    subtemplates:
        - template: mydevice-default-password-check.yaml 
```
Output:
```
$ ./nuclei -w nuclei-templates/workflows/test.yaml -l input.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Workflows loaded for scan: 1
[2022-09-05 15:50:24] [mydevice-default-password-check] [http] [info] http://localhost:10001/
```

I would expect this to also show matches on the `mydevice` template. Currently this can be done by running `mydevice` twice, but that will take twice the number of requests and more cluttered workflow files.

**Comment by CosasDePuma** [comment]
Any update about? I also want to show parent's output without duplicate any code.

**Reply by MetzinAround** [reply]
https://docs.nuclei.sh/template-guide/workflows

There should be some updated information here. 

What do your templates and subtemplates look like? Could you share more information about your situation as it may be diffferent from OP's post.

**Reply by CosasDePuma** [reply]
I want to show the parent template's features in addition to the children's without replicating the template.

This would be the template I have as an example:

```yaml
workflows:
  - template: technologies/jira-detect.yaml # Want to display this template finding via stdout
    subtemplates:
      - tags: jira
      - template: exploits/jira/
```

One possibility is to replicate the parent template, but that's just what I'm looking to avoid:

```yaml
workflows:
  - template: technologies/jira-detect.yaml # As parent
    subtemplates:
      - tags: jira
      - template: exploits/jira/
      - template: technologies/jira-detect.yaml # As child
```

I haven't found anything in the documentation, but something like this would be nice:

```yaml
workflows:
  - template: technologies/jira-detect.yaml
    verbose: true # An optional parameter to show findings
    subtemplates:
      - tags: jira
      - template: exploits/jira/
```
