### DISCUSSION TITLE
How do I set the template to use the helpers/wordlists file of the directory I defined

### DISCUSSION THREAD

**Discussion by boluoha** [projectdiscovery/nuclei#2769] [Q&A] [answered]
I have tried to copy a template to another directory, and then set USERPROFILE and HOMEPATH as the parameters of the copied directory, but it seems to be useless?
I would like to know how to set the parameters of the helpers/wordlists file, can you help me?

**Comment by forgedhallpass** [comment, marked as answer]
In order to make use of a wordlist in a template, you can use the following syntax:
```yaml
payloads:
   usernames: path_to_usernames.txt  # <-- this uses a wordlist file
   passwords:  # <-- this uses the pre-defined values below
     - root
     - toor
     - admin 
```

The path for wordlists can be either an absolute path, or a path relative to your nuclei-templates directory, which points to `~/nuclei-templates`. To make sure, you can check it using the following one-liner:
```shell
 cat ~/.config/nuclei/.templates-config.json | jq '."nuclei-templates-directory"'
```

If you would like to temporary override the configurations, you can use the `-config` flag to point to an alternative configuration file.
