### DISCUSSION TITLE
Use external file dictonary as word matcher

### DISCUSSION THREAD

**Discussion by octavioricci** [projectdiscovery/nuclei#2866] [Q&A] [answered]
Hello guys.

Do you know if it is possible to use an external dictionary file as a word matcher for the response content of different web files?
For example, to search for hardcoded passwords in files.

Here is what I´ve done, but it doesn´t seem to work.

```yaml
id: password-disclosure-wordlist

info: 
  name: hardcoded-password
  author: octavio
  severity: critical
  tags: password,hardcoded,disclosure,exposure

variables:
  var1: "/home/octavio/1kpasswords.txt"**
  
requests:
  - method: GET
    path: 
      - "{{BaseURL}}"
           
    matchers:
      - type: word
        part: body
        words:
          - "{{var1}}"
          
    extractors:
      - type: regex
        part: body
        regex:
          - '\w+'
```

Thanks a lot!

Regards
