### DISCUSSION TITLE
Run a DNS query for every nameserver

### DISCUSSION THREAD

**Discussion by JaneX8** [projectdiscovery/nuclei#2934] [Q&A] [answered]
I want to write a template that firstly gets the nameservers of the domain input and then for every nameserver performs a request on that nameserver.

```yaml
dns:
  - name: "{{RDN}}"
    type: NS
    class: inet
    recursion: true
    retries: 5
```

Above gets me the nameservers but I can't find documentation on how to use those results for a following DNS request.
