### DISCUSSION TITLE
Simple RXSS detection template issue

### DISCUSSION THREAD

**Discussion by rut9er** [projectdiscovery/nuclei#3022] [Q&A] [answered]
Hi!

Testing a slightly tweaked [simple XSS prober](https://github.com/projectdiscovery/nuclei-templates/blob/main/cves/2018/CVE-2018-18570.yaml) to validate the presence of the payload ```2><script>alert("XSS")</script>``` in the body keeps resulting in a syntax error. See output here:

![image](https://user-images.githubusercontent.com/78957676/206924780-fca5f676-00d8-4bdd-ad08-f86aa8f0d32a.png)

See template used below:
```yaml
id: xsscheck

info:
  name: RXSS Checker
  author: Name
  severity: low

requests:
  - method: GET
    path:
      - '{{BaseURL}}/listproducts.php?cat=2><script>alert("XSS")</script>'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "2><script>alert("XSS")</script>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header

```

Sorry for my ignorance! Can't seem to get this to work🙃
