### DISCUSSION TITLE
Special string URL encoding problem

### DISCUSSION THREAD

**Discussion by ltfafei** [projectdiscovery/nuclei#3697] [Q&A]
I found:
```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/v1/docs//..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\/windows/win.ini"
```

can't Pass detection. 

I want string \\ escape \, Resplice /，but nuclei Impossible to achieve

I don't want it to URL encode. but I found method: GET or raw request, They're URL encoded

**Comment by ltfafei** [comment]
![image](https://github.com/projectdiscovery/nuclei/assets/43526141/bc0ac802-cc13-4c02-b381-09bca5694d87)

**Comment by ltfafei** [comment]
why can't this:
![image](https://github.com/projectdiscovery/nuclei/assets/43526141/304c1b5e-0046-4c51-839c-f017e2955894)

**Comment by ehsandeep** [comment]
@ltfafei see https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#unsafe-http-requests

and use `unsafe`:

```yaml
http:
  - method: GET
    path:
      - '{{BaseURL}}/v1/docs//..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\/windows/win.ini'

    unsafe: true
```
