### DISCUSSION TITLE
Unsafe rawhttp requests are not sending as intended

### DISCUSSION THREAD

**Discussion by rpaul-ghostsec** [projectdiscovery/nuclei#3910] [Q&A]
### Nuclei version:
v2.9.7

### Current Behavior:

This has been driving me nuts, since I am trying to create a template of my own for SSRF/Request smuggling. However, I notice the behavior is the same in all templates under `nuclei-templates/misconfiguration/proxy/metadata-*.yaml`. 

Take for example, `metadata-aws.yaml`. It defines its request here:

```yaml
requests:
  - raw:
      - |+
        GET http://{{hostval}}/latest/meta-data/ HTTP/1.1
        Host: {{hostval}}

    payloads:
      hostval:
        - aws.oast.online
        - 169.254.169.254
    unsafe: true
```

However, it generates two requests like this:

```
GET /latest/meta-data/ HTTP/1.1
Host: 169.254.169.254
Connection: close
```

```
GET /latest/meta-data/ HTTP/1.1
Host: aws.oast.online
Connection: close
```

Additionally if you try to create an unsafe rawhttp request with something like `{{BaseURL}}` it will not fill in, or `{{Hostname}}` or another custom variable it will truncate and remove `http://<whatever>/`.

`python -m http.server 8443`

`nuclei -u http://localhost:8443/ -v -proxy=http://127.0.0.1:8080 -t ./test.yaml`

```yaml
id: test
info:
  name: test
  author: Smitty Werbenjägermanjensen
  severity: info
requests:
  - raw:
      - |+
        GET http://{{Hostname}}/metadata/instance?api-version=2021-02-01 HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

Results in:

```
GET metadata/instance?api-version=2021-02-01 HTTP/1.1
Host: localhost:8443
Connection: close
```

```yaml
id: test
info:
  name: test
  author: Smitty Werbenjägermanjensen
  severity: info
requests:
  - raw:
      - |+
        GET {{BaseURL}}/metadata/instance?api-version=2021-02-01 HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

Generated request:

```
GET /metadata/instance?api-version=2021-02-01 HTTP/1.1
Host: localhost:8443
Connection: close
```

Here's one with custom variables:

```yaml
id: test
info:
  name: test
  author: Smitty Werbenjägermanjensen
  severity: info
requests:
  - raw:
      - |+
        GET http://{{TheRussiansAreNukingUs}}/metadata/instance?api-version=2021-02-01 HTTP/1.1
        Host: {{Hostname}}
    payloads:
      TheRussiansAreNukingUs:
        - Putin
        - Prigozhin
    unsafe: true
```

And like the failed Russian coup attempt, it times out eventually:

```
[DBG] Final Protocol request variables: 
        1. RootURL => http://localhost:8443
        2. Input => http://localhost:8443/
        3. Port => 8443
        4. FQDN => localhost
        5. Hostname => localhost:8443
        6. ip => 
        7. Path => /
        8. File => /
        9. BaseURL => http://localhost:8443/
        10. Scheme => http
        11. Host => localhost
        12. TheRussiansAreNukingUs => Putin

[INF] [test] Dumped HTTP request for http://localhost:8443/metadata/instance?api-version=2021-02-01

GET metadata/instance?api-version=2021-02-01 HTTP/1.1
Host: localhost:8443
[DBG] Final Protocol request variables: 
        1. FQDN => localhost
        2. BaseURL => http://localhost:8443/
        3. File => /
        4. Scheme => http
        5. Path => /
        6. RootURL => http://localhost:8443
        7. ip => 
        8. Host => localhost
        9. Hostname => localhost:8443
        10. Port => 8443
        11. Input => http://localhost:8443/
        12. TheRussiansAreNukingUs => Prigozhin

[INF] [test] Dumped HTTP request for http://localhost:8443/metadata/instance?api-version=2021-02-01

GET metadata/instance?api-version=2021-02-01 HTTP/1.1
Host: localhost:8443
[WRN] [test] Could not execute request for http://localhost:8443/: ReadStatusLine: read tcp 127.0.0.1:53475->127.0.0.1:8443: i/o timeout
[INF] No results found. Better luck next time!
```

I tried adding hosts entries for anything defined in `payloads` and it still times out. 

EDIT: If I remove the proxy (using BurpSuite) it will still reach its intended server, however it's still truncating where the variable should be present:

```
127.0.0.1 - - [27/Jun/2023 22:18:38] "GET metadata/instance?api-version=2021-02-01 HTTP/1.1
```

More specifically, here is what its picking up on the receiving end. 

```json
{
  "requestline": "GET metadata/instance?api-version=2021-02-01 HTTP/1.1",
  "path": "metadata/instance?api-version=2021-02-01"
}
```

### Expected Behavior:

The requests generated should look like the following for templates like `metadata-aws.yaml`:

```
GET http://169.254.169.254/latest/metadata/ HTTP/1.1
Host: 169.254.169.254
Connection: close
```

```
GET http://aws.oast.online/latest/metadata/ HTTP/1.1
Host: aws.oast.online
Connection: close
```
