### DISCUSSION TITLE
raw type req will append BaseURL into the request && internal varible question

### DISCUSSION THREAD

**Discussion by breaking153** [projectdiscovery/nuclei#4053] [Q&A] [answered]
### Nuclei version:
2.9.10

### Current Behavior:
my raw template will request URL appended by {{BaseURL}},like:
```yaml
http:
  - raw: 
    - |
      GET /attachment/index0.php HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
      Accept: */*
      Accept-Encoding: gzip, deflates
      Accept-Language: zh-CN,zh;q=0.9
      Connection: close
    stop-at-first-match: false
    matchers-condition: or
    matchers:
      - type: regex
        regex:
          - "ASSASIN"`
```

and command line:
```
nuclei.exe -u http://xx.x.xxx.x/path -id xx  -p http://127.0.0.1:8080 -duc
```
will request:
![图片](https://github.com/projectdiscovery/nuclei/assets/49428332/84f8a43a-ce9d-47ba-bcfb-82743b88d79d)

### Expected Behavior:
request raw data,not url append {{BaseURL}}

### Anything else:

btw,is the Extractor internal var only available to current block?
will it possible to write someting like:

```yaml
http:
  - raw: 
    - |
      GET /attachment/index0.php HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
      Accept: */*
      Accept-Encoding: gzip, deflates
      Accept-Language: zh-CN,zh;q=0.9
      Connection: close
    stop-at-first-match: false
    extractors:
      - type: regex
        part: body
        name: test  # var here wants to be used
        regex:
          - '\c{10}'
    matchers:
      - type: regex
        regex:
          - "ASSASIN"
  - method: GET
    path:
      - "{{RootURL}}/{{test}}"  # test var used here
```
