### DISCUSSION TITLE
How to replay request in yaml repeat:10 time first request

### DISCUSSION THREAD

**Discussion by hktalent** [projectdiscovery/nuclei#4185] [Q&A] [answered]
hello @ehsandeep Sorry to bother you again
```
http:
  - raw:
    - |+
      POST / HTTP/1.1
      Host: {{Hostname}}
      Content-Length: {{90+len(Hostname)}}
      

      xxxxx...

    - |+
      GET /vulsCheck/xxx/{{Hostname}}/login HTTP/1.1
      Host: {{Hostname}}

```
In yaml, I need to repeat the first request n times before executing the second request. Can you tell me how to achieve this? I searched for "repeat" in the source code and found no reference content. terribly sorry

**Comment by hktalent** [comment]
```
http:
  - raw:
    - |+
      POST / HTTP/1.1
      Host: {{Hostname}}
      Content-Length: {{90+len(Hostname)}}
      X-Ignore: {{payload1}}

    attack: pitchfork
    payloads:
      payload1:
        - n1
        - n2
        - n3
        - n4
        - n5
        - n6
        - n7
        - n8
        - n9
        - n10
```
@ehsandeep 
If you have a better way, please let me know. Thank you so much

**Reply by MetzinAround** [reply]
hi @hktalent 
We have a helper function that might be able to help. 

`repeat(str string, count uint) string`
https://docs.nuclei.sh/template-guide/helper-functions

**Reply by hktalent** [reply]
I want to repeat the first request n times

**Reply by MetzinAround** [reply]
I THINK this helper function should do it. 

payload: '{{repeat("request", n)}}'

This template uses the repeat function inside a payload like you would like to. 

https://github.com/projectdiscovery/nuclei-templates/blob/627e654d30ee2e63b524e085222a4e429ebf6d21/http/cves/2019/CVE-2019-15043.yaml#L33

**Reply by hktalent** [reply]
```
http:
  - raw:
    - |+
      POST / HTTP/1.1
      Host: {{Hostname}}
      Content-Length: {{90+len(Hostname)}}
      

      xxxxx...

    - |+
      GET /vulsCheck/xxx/{{Hostname}}/login HTTP/1.1
      Host: {{Hostname}}

```
Thank you for your patient answer
What I mean is that I hope that after completing the first request n times (for example: 10 times) in succession, I will continue to send the second and nth requests.
That is, the first request needs to be issued multiple times in a row before continuing with subsequent requests.

**Reply by tarunKoyalwar** [reply]
@hktalent the example you mentioned seems to be correct . if you don't want to add extra header etc you can put the payload in `url fragment` . and anything put in url fragment is not sent to server. example

```yaml
http:
  - raw:
    - |+
      POST /#ignore{{payload1}} HTTP/1.1
      Host: {{Hostname}}
      Content-Length: {{90+len(Hostname)}}

    attack: pitchfork
    payloads:
      payload1:
        - n1
        - n2
        - n3
        - n4
        - n5
        - n6
        - n7
        - n8
        - n9
        - n10
 ```
