### DISCUSSION TITLE
[bug] nuclei templates variables recreate

### DISCUSSION THREAD

**Discussion by sp4rkw** [projectdiscovery/nuclei#4225] [Q&A] [answered]
hi，when I wrote the vulnerability detection yaml, I found a problem that I have not been able to solve. the yaml like this

```
variables:
  filename: "{{rand_base(5)}}"
  rstr2: "{{to_lower(rand_base(32))}}"
  rboundary: "{{to_lower(rand_base(8))}}"
  payload: "<% out.println(\"{{rstr2}}\");new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>"

http:
  - raw:
      - |
        POST /dir1 HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}

        ------WebKitFormBoundary{{rboundary}}
        Content-Disposition: form-data; filename="{{filename}}.jsp"

        {{payload}}
        ------WebKitFormBoundary{{rboundary}}--

      - |
        GET /{{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}

    req-condition: true
    matchers-condition: and
    matchers:
      - type: dsl
        dsl: 
          - status_code_1 == 200
          - body_2 == rstr2
          - status_code_2 == 200
        condition: and
```

however, the variables rstr2 and filename are duplicated in the first packet and the second packet, making vulnerability detection impossible

I used --debug --svd to confirm that it was a variable value duplicate generation issue, plus I verified on linux and windows respectively and both had the issue, the nuclei version is v2.9.15

**Comment by MetzinAround** [comment]
Thanks for the discussion, @sp4rkw. Gonna tag @olearycrew to see if he can see where the variables are somehow being duplicated. Any idea, Brendan?

**Comment by ehsandeep** [comment]
@sp4rkw you can use `{{randstr}}` for this - https://docs.nuclei.sh/template-guide/preprocessors

**Reply by sp4rkw** [reply]
It doesn't seem to be possible to specify the length of **randstr**. Is there a way for **variables** to be set as global variables that don't get generated over and over again? If it needs to be duplicated, don't you just create a different variable name to solve the problem?

**Reply by ehsandeep** [reply]
@sp4rkw I'm unable to repro the scenario you mentioned, do you have a reference/information of what vuln you are trying to recreate to debug this further?

**Reply by sp4rkw** [reply, marked as answer]
I found the problem.
When I move the **payload** from **variables** to http data, the other variable will not be regenerated. example：
```
variables:
  filename: "{{rand_base(5)}}"
  rstr2: "{{to_lower(rand_base(32))}}"
  rboundary: "{{to_lower(rand_base(8))}}"

http:
  - raw:
      - |
        POST /dir1 HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}

        ------WebKitFormBoundary{{rboundary}}
        Content-Disposition: form-data; filename="{{filename}}.jsp"

        <% out.println("{{rstr2}}");new java.io.File(application.getRealPath(request.getServletPath())).delete(); %>
        ------WebKitFormBoundary{{rboundary}}--
```

this all right


I think the problem is in the handling of a certain character, I hope this helps you guys in troubleshooting the issue
Anyway, thank you very much for your patient replies
