### DISCUSSION TITLE
How to iterate over json

### DISCUSSION THREAD

**Discussion by hktalent** [projectdiscovery/nuclei#4251] [Q&A] [answered]
```
  extractors:
      - type: json
        part: body
        name: pkgname
        internal: true
        json:
          - ".xx1"
          - ".xx2"
```

data:
```
{
	"xx1":{
	  "k1":"v1",
	  "k2":"v2"
	}
}

```
Now we need to extract k1 and k2 and iterate them into the payload.
So how to achieve it?
