### DISCUSSION TITLE
URL ending with trailing `?` get removed

### DISCUSSION THREAD

**Discussion by Chi11-H** [projectdiscovery/nuclei#4282] [Q&A] [answered]
When sending a request using the following template, the "?" at the end of the URL will be lost abnormally. I was wondering how to retain this "?"

```yaml
http:
  - raw:
      - |+
        POST /general/appbuilder/web/portal/gateway/? HTTP/1.1
        Host: {{Hostname}}`
```

The following request was actually sent:

```http
POST /general/appbuilder/web/portal/gateway/ HTTP/1.1
Host: x.x.x.x
```
