### DISCUSSION TITLE
Cannot run code template

### DISCUSSION THREAD

**Discussion by tower111** [projectdiscovery/nuclei#4463] [Q&A] [answered]
When I run the given example there is no message emitted
https://docs.projectdiscovery.io/templates/protocols/code

```console
➜  testvul nuclei -p http://192.168.1.69:8080 -t test_code.yaml -code  -u xxxxxx -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.4

                projectdiscovery.io

[VER] Using http://192.168.1.69:8080 as proxy server
[VER] Started metrics server at localhost:9092
[WRN] Found 1 unsigned or tampered code template (carefully examine before using it & use -sign flag to sign them)
[INF] Current nuclei version: v3.0.4 (latest)
[INF] Current nuclei-templates version: v9.6.9 (latest)
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

My template content is as follows

```yaml
id: code-template

info:
  name: example code template
  author: pdteam
  severity: info

variables:
  OAST: "{{interactsh-url}}"

code:
  - engine:
      - sh
      - bash
    source: |
      echo "$OAST" | base64

  - engine:
      - py
      - python3
    source: |
      import base64
      import os

      text = os.getenv('OAST')
      text_bytes = text.encode('utf-8') 
      base64_bytes = base64.b64encode(text_bytes) 
      base64_text = base64_bytes.decode('utf-8')
      
      print(base64_text)

http:
  - method: GET
    path:
      - "{{BaseURL}}/?x={{code_1_response}}"
      - "{{BaseURL}}/?x={{code_2_response}}"
```
