### DISCUSSION TITLE
URL ending with trailing `?` get removed

### DISCUSSION THREAD

**Discussion by ehsandeep** [projectdiscovery/nuclei#4572] [Q&A] [answered]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/4282

When sending a request using the following template, the "?" at the end of the URL will be lost abnormally. I was wondering how to retain this "?"

```yaml
http:
  - raw:
      - |+
        POST /general/appbuilder/web/portal/gateway/? HTTP/1.1
        Host: {{Hostname}}`
```

The following request was actually sent:

```http
POST /general/appbuilder/web/portal/gateway/ HTTP/1.1
Host: x.x.x.x
```

**Expected request:**

```http
POST /general/appbuilder/web/portal/gateway/? HTTP/1.1
Host: x.x.x.x
```

**Comment by dogancanbakir** [comment]
Depends on https://github.com/projectdiscovery/utils/pull/301

**Comment by tarunKoyalwar** [comment]
@stefanocoding , @Chi11-H , wouldn't just adding a random query param work ? something like

```
http:
  - raw:
      - |+
        POST /general/appbuilder/web/portal/gateway/?utm_source=abc HTTP/1.1
        Host: {{Hostname}}`
```

if not can you share example reference where you require this . because `?` is seperator used to seperate path and query param and without any query params its not possible to include it (according to RFC and generally)

**Reply by stefanocoding** [reply]
In my case, I got a file that returned 403 by adding a `?` at the end of the URL. It was a few months ago, so I don't remember if it worked by adding parameters too. Reading the report I submitted, my guess is that adding parameters didn't return the same response, but I can't confirm because it's fixed now. I will just add parameters as you suggest.  Thank you for your time to answer.

**Comment by tarunKoyalwar** [comment, marked as answer]
@stefanocoding. , @Chi11-H , to address such outliers (edgecases that are rare and conflict with normal behaviour of parsing libraries) you can use newly introduced javascript protocol and it has no any kind of restriction and it is request is written line by line

### example template

```yaml
id: net-https

info:
  name: net-https
  author: pdteam
  severity: info
  description: send and receive https data using net module


javascript:
  - code: |
      let m = require('nuclei/net');
      let name=Host+':'+Port;
      let conn = m.OpenTLS('tcp', name);
      // send http request line by line
      conn.Send('GET / HTTP/1.1\r\n')
      conn.Send('Host:'+name+'\r\n')
      conn.Send('Connection: close\r\n')
      conn.Send('\r\n');
      conn.RecvString(); // get response

    args:
      Host: "{{Host}}"
      Port: "443"

    matchers:
      - type: word
        words:
          - "HTTP/1.1 200 OK"
```

### example run

```console
$ ./nuclei -t a.yaml -v -svd -u scanme.sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.4-dev

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.1.4-dev (development)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[DBG] Javascript Protocol request variables: 
	1. DN => scanme
	2. FQDN => scanme.sh
	3. Host => scanme.sh
	4. Hostname => scanme.sh:443
	5. Port => 443
	6. RDN => scanme.sh
	7. SD => 
	8. TLD => sh

[VER] [net-https] Sent Javascript request to scanme.sh:443
[DBG] Javascript Protocol response variables: 
	1. DN => scanme
	2. FQDN => scanme.sh
	3. Host => scanme.sh
	4. Hostname => scanme.sh:443
	5. Port => 443
	6. RDN => scanme.sh
	7. SD => 
	8. TLD => sh
	9. host => scanme.sh:443
	10. interactsh-server => 
	11. matched => scanme.sh:443
	12. request => let m = require('nuclei/n .... String(); // get response
	13. response => HTTP/1.1 200 OK  Date: Th ....   Connection: close    ok
	14. success => true
	15. template-id => net-https
	16. template-info => {net-https pdteam  send a .... nil> {info} map[] <nil> }
	17. template-path => /Users/tarun/Codebase/nuclei/a.yaml
	18. type => javascript

[net-https] [javascript] [info] scanme.sh:443
```
