### DISCUSSION TITLE
Option to not add path to raw requests

### DISCUSSION THREAD

**Discussion by hipotermia** [projectdiscovery/nuclei#4928] [Q&A] [answered]
Is there any option to not automatically add the provided path to raw requests?

While having a template like the following:

```yaml
http:
  - raw:
      - |+
        GET /xxx HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

And providing `https://aaa.com/kkkkk`, I would like to request `https://aaa.com/xxx` instead of `https://aaa.com/kkkkk/xxx`.

![image](https://github.com/projectdiscovery/nuclei/assets/46414327/27c7ceb0-ac62-47e3-babc-d0d70a273641)

To add more context, I would like to be able to do this to use the `code` functionality to modify and replace provided paths.

Thanks!
