### DISCUSSION TITLE
Dynamic JQ Selector Variable is not processed

### DISCUSSION THREAD

**Discussion by Thamaraiselvan942** [projectdiscovery/nuclei#5003] [General]
Hi Team,
In some cases, I need to pass the JSON selector value as a variable, as shown below. But, the variable is not processed. 

```
 extractors:
          - type: json
            part: body_1
            name: delete_user_id
            group: 1
            json:
              - '.data.users[]| select(.email_address == "{{user_email}}") | .user_id'
              
```
