### DISCUSSION TITLE
time out in dsl

### DISCUSSION THREAD

**Discussion by exploit-io** [projectdiscovery/nuclei#5156] [Q&A]
I have a template, which may cause request time out
I want `nuclei` to log the time outed requests for me in the `matchers`, How can I do that?

```
    matchers:
      - type: dsl
        name: Time
        dsl:
          - "[timeout == true]"
```
