### DISCUSSION TITLE
HTTP header configured in template is overridden by global configuration

### DISCUSSION THREAD

**Discussion by Joeeyy** [projectdiscovery/nuclei#5305] [Q&A]
HTTP header defined in template is overridden by global config. is that a desired behavior? 

my template: 
```yaml
id: fetch-http-body

info:
  name: fetch-http-body
  author: x
  severity: info
  tags: test
  description: test

http:
  - method: GET
    path:
      - "http://{{Hostname}}"
    headers:
      User-Agent: "curl/7.84"

    extractors:
      - type: dsl
        name: body
        dsl:
          - body
```

my global config:
```yaml
# Headers to include with all HTTP request
header:
  - "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"

rate-limit: 500
bulk-size: 50
concurrency: 50
duc: true

```
