### DISCUSSION TITLE
Feature Request: Add `-loop` Flag for Repeated Template Scanning to Enhance Load Balancer Vulnerability Detection

### DISCUSSION THREAD

**Discussion by Nishantbhagat57** [projectdiscovery/nuclei#5351] [Ideas]
Hey ProjectDiscovery Team,

I would like to request a feature to further improve nuclei template scanning and enhance the accuracy of finding vulnerabilities.

I suggest adding a `-loop` flag (or a similarly named flag) that accepts the number of times a template should be scanned. For example, if a user adds the `-loop 5` argument, then nuclei should scan the same template 5 times on the current scan target.

Additionally, it would be great if nuclei could intelligently identify a load balancer. In such cases, a `-loop 5 --loop_when_loadbalancer` flag would loop the template scan only if a load balancer is detected.

# Theory
A load balancer is a proxy (in front) that works to distribute the workload across multiple servers.
Usually, those servers have similar structures, so the applications inside them also need to be similar.

![GQ3TSskaQAEzAP3](https://github.com/projectdiscovery/nuclei/assets/64642374/f4e01e8f-2535-41ea-8c76-85da7c7562f7)

But, the issue lies in:

- Server A - Failed
- Server B - Failed
- Server C - Exploitable!

![GQ3TcvWbwAEenrD](https://github.com/projectdiscovery/nuclei/assets/64642374/6aa8658d-8f41-4455-b995-356062000610)

By doing 10x loops on nuclei the issue is exploitable.

![GQ3T48ibwAEjqkD](https://github.com/projectdiscovery/nuclei/assets/64642374/9b8e477a-7de5-42a4-9c5c-30cffecae21f)

## Why?

1. The first request might go to the server with the latest app.
2. The second request might also go there; our session will be directed to the newest version.

So, multiple requests are needed for our session to be directed to the vulnerable server.

# Reference
https://twitter.com/xchopath/status/1805331064958894177?t=WWddaLg9BzXCqVYvq1YmJQ&s=19

# Credits
https://x.com/xchopath
https://github.com/xchopath

cc: @ehsandeep @princechaddha

**Comment by princechaddha** [comment]
Hi @Nishantbhagat57, Thank you for taking the time to create this issue and for contributing to this project 🍻

You can achieve what you described in the issue by using flow. Please confirm if this is what you intended to do with the loop.

## Example:

```yaml
id: test-template

info:
  name: Test Template
  author: princechaddha
  severity: info
  tags: tech

flow: |
  for (let i = 0; i < 10; i++) {
    http(1)
  }

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "<title>Example</title>"

      - type: status
        status:
          - 200
```
