### DISCUSSION TITLE
How to use `stop-at-first-match` with flow?

### DISCUSSION THREAD

**Discussion by iambouali** [projectdiscovery/nuclei#5410] [Q&A] [answered]
When using the `stop-at-first-match` feature in combination with a flow block, it appears that the `stop-at-first-match` functionality is not working as expected. The flow block continues to execute all iterations even after a match is found.

```yaml
id: test

info:
  name: test
  author: iambouali
  severity: high

flow: |
  for (let i = 0; i < 10; i++) {
    http(1)
  }

http: 
  - raw:
     - |
       GET /?cb=test HTTP/1.1
       Host: {{Hostname}}

       stop-at-first-match: true
       matchers:
          - type: word
             part: header
             words:
                - "X-Cache: hit"
```

**Comment by ehsandeep** [comment, marked as answer]
@iambouali we confirmed that `stop-at-first-match` doesn't work with flow and it's expected, instead you can use another trick to do the same using flow, refer to below template that works in same way without using `stop-at-first-match`.

```yaml
id: test

info:
  name: test
  author: iambouali
  severity: high

flow: |
  for (let i = 0; i < 10; i++) {
    if (http(1)){
      break;
    }
  }

http: 
  - raw:
     - |
       GET /?cb=test HTTP/1.1
       Host: {{Hostname}}

    matchers:
      - type: status
        status:
          - 200
```
