### DISCUSSION TITLE
Nuclei throwing "no templates provided for scan" error even when i provide it with one

### DISCUSSION THREAD

**Discussion by ayushkr12** [projectdiscovery/nuclei#5607] [Q&A]
my nuclei template:

```yaml
id: ref-xss-detect

info:
  name: Reflected XSS Detection
  author: dat-ayush
  severity: medium
  description: Detects Potential Reflected XSS on a domain

requests:
  - method: GET
    matchers:
      - type: regex
        regex:
          - "[(?i){{reflection}}]"

    payloads:
      reflection:
        - "zenshell\">"

    stop-at-first-match: true
    fuzzing:
      - part: query
        mode: single
        fuzz:
          - "{{reflection}}"
```

when i run it. the error

```
$ nuclei -u "https://google.com?query=w" -t ref-xss-detect.yaml -debug
 
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.2

                projectdiscovery.io

[WRN] Excluded 1 dast template[s] (disabled as default), use -dast option to run dast templates.
[INF] Current nuclei version: v3.3.2 (latest)
[INF] Current nuclei-templates version: v9.9.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

but when i run (in the same directory)

```
$ nuclei -t ref-xss-detect.yaml -validate

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.2

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] All templates validated successfully
```

Even when I use `-debug` flag it doesn't tell me that there is something wrong with template (assuming there is) so how can I tell nuclei to give me more debug statements to understand the error properly. 

P.S.: Am new to nuclei templates and trying to learn, I did read the docs but was unable to find solution to my question. Even when running an example fuzzing [template](https://docs.projectdiscovery.io/templates/protocols/http/fuzzing-overview) written by pd team itself, I get the same error, so I can't tell what is causing it
