### DISCUSSION TITLE
[BUG] Ampersand symbol issues in unsafe raw HTTP request

### DISCUSSION THREAD

**Discussion by KGorbakon** [projectdiscovery/nuclei#5620] [General]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

In raw http requests with option _unsafe: true_ ampersand symbol ("&") disappears if it was placed in the end of URL.
`GET /some_page/start.xml?=====& HTTP/1.1` transforms to `GET /some_page/start.xml?====` in result request.
Also, if there more than two ampersands in the end of the query:  "GET /some_page/start.xml?=====&&&& HTTP/1.1", the request transforms into `GET /some_page/start.xml?=====&=&= HTTP/1.1`.

 POCs from https://cloud.projectdiscovery.io/templates:
![image](https://github.com/user-attachments/assets/b1b166e1-64cd-4360-8810-3f860288a30c)
![image](https://github.com/user-attachments/assets/b602c4c1-dad8-4c7f-b3d3-b18c2614671f)

### Expected Behavior

Request shouldn't be transformed if option unsafe marked as true. Ampersand in the end of URL sometimes breaks logic of web-server and may be used as safecheck for CVEs in nuclei templates.

### Steps To Reproduce

Send such requests with debug mode to reproduce the issue and look how they will be trasnformed: 

```
http:
  - raw:
      - |+
        GET /some_page/start.xml?=====& HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```
```
http:
  - raw:
      - |+
        GET /some_page/start.xml?=====&&&& HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

### Environment

```markdown
- OS: Windows 10
- Nuclei: v3.3.1
- Go: go1.22.3 windows/amd64
```
