### DISCUSSION TITLE
Access to payload helper file denied

### DISCUSSION THREAD

**Discussion by TimMaasGeesteranus** [projectdiscovery/nuclei#5719] [Q&A] [answered]
I am having trouble accessing the `payloads.txt` file in a very specific folder structure with Nuclei. Below is the structure of the files and folders:

#### **poc.yaml:**

```yaml
id: poc

info:
  name: poc payloads error
  author: tim
  severity: high
  description: proof of concept for payloads error

requests:      
  - method: GET
    path:
      - "{{BaseURL}}/api/users?page={{pagenumber}}"

    payloads:
      pagenumber: /payloads/payloads.txt
```

#### **payloads.txt:**

```
1
2
3
```

When the folder structure is like this, everything works fine:

```
poc/
├── payloads/
│   └── payloads.txt
└── poc.yaml
```

However, when I move `poc.yaml` into a separate **templates** folder like this, it fails:

```
poc/
├── payloads/
│   └── payloads.txt
└── templates/
    └── poc.yaml
```

When I try to validate the template with the following command:

```bash
nuclei -t templates/poc.yaml -validate
```

I get the following error:

```
[ERR] Error occurred parsing template /home/directories/poc/templates/poc.yaml: could not compile request: could not parse payloads: could not load payload file: [:RUNTIME] access to helper file /home/directories/poc/payloads/payloads.txt denied

[FTL] Could not validate templates: errors occurred during template validation
```

All files mentioned have rwx permission

My Nuclei version is 3.3.4
