### DISCUSSION TITLE
Authenticated scan error.

### DISCUSSION THREAD

**Discussion by Th3l3mic** [projectdiscovery/nuclei#6174] [Q&A]
Hi! I 'm trying unsuccessfully to perform authenticated scanning on a locally hosted DVWA, and no matter what I do with the secret file, I receive an error: "field dynamic not found in type templates" :( 

Probably Im doing something wrong :/

Below screenshots from the secret file and login.yaml

Thank you in advance for your help.

![screen1](https://github.com/user-attachments/assets/c9ce2780-1b14-48d5-bd78-8dd606ece0c9)
![screen2](https://github.com/user-attachments/assets/08a857ec-14ee-4ced-a232-d18db99a1bb5)

**Comment by GeorginaReeder** [comment]
Hey @Th3l3mic ! Sure, let's take a look into this :)

The '"field dynamic not found in type templates"' error usually shows up when Nuclei can’t understand or properly parse something in your secret file, specifically when trying to use authentication (like tokens, sessions, etc.) via the secret.yaml file.

First thing - I can see that there's a `dynamic:` field in your secret file. It could be that the field isn't supported in the version of Nuclei you're using, or you're using the wrong syntax for dynamic authentication.

So I'd say definitely check your Nuclei version first and update to the latest version. After that, check your secret file and make sure it looks like this:

```
id: dvwa-auth

type: http

authentication:
  - type: jwt
    token: "{{token}}"
    header: Authorization

  - type: cookie
    cookie: "PHPSESSID={{session_id}}"
```

But for dynamic login (like posting to /login.php), it should look more like this:


```
id: dvwa-auth

type: http

authentication:
  - type: header
    header: Cookie
    value: "PHPSESSID={{session_id}}"

  - type: bearer
    token: "{{token}}"

variables:
  session_id:
    type: internal
    method: POST
    url: http://localhost/login.php
    body: "username=admin&password=password&Login=Login"
    extract:
      type: regex
      regex:
        - 'PHPSESSID=([a-zA-Z0-9]+)'
```


Either way, everything is under `variables:` and `authentication:` instead of `dynamic:`.

Let us know if that helps or not, and we can then take a closer look!
