### DISCUSSION TITLE
How to judge when two matchers rule conflict(coverage)?

### DISCUSSION THREAD

**Discussion by t43Wiu6** [projectdiscovery/nuclei#647] [Q&A] [answered]
there is a fingerprint in `nuclei-templates/blob/master/technologies/tech-detect.yaml`
```yaml
    matchers-condition: or
    matchers:
      - type: word
        name: apache
        words:
          - "Apache"
        part: header
```
and i append some rules

```yaml
      - type: word
        name: apache
        words:
          - "Apache"
        part: header
      - type: word
        name: tomcat
        words:
          - "successfully installed Tomcat"
        part: body
```
the detect result is tomcat when i got a page that meets both criteria， it depends on what? 
Is there a possibility that could be a conflict would interfere with normal fingerprint identification.
I had already try to modify the sequence, always hapend.

**Comment by ehsandeep** [comment]
@t43Wiu6 we define matchers condition in the template, in [this case](https://github.com/projectdiscovery/nuclei-templates/blob/18ffc0c2674294e63f27e7ed13f68f55b393b8ee/technologies/tech-detect.yaml#L13
) it's OR, so you will see match when either of the condition is matched, the idea of this template is make all the tech-based fingerprints with `name:` attribute, so you get all matched technology in use for given URLs.


```
    matchers-condition: or
```

If you wanted to write a template which requires more conditions or AND condition, it is suggested to write a separate template.

**Reply by t43Wiu6** [reply]
I know that i can see the match value when the condition is matched.

In my test case, I got a page resp just like this
```
HTTP/1.1 200 OK
...
Server: Apache-Coyote

successfully installed Tomcat
```
of course, will match both, it make me feel confused.

the match result is `tomcat`, why not `apache`?is that mean the result will be `apahce` in sometime?because it satisfies both...

in workflow template, this may cause the wrong poc to be used

**Reply by ehsandeep** [reply]
@t43Wiu6 because as default, matcher looking within `response body`, unless you specified where to look for.

You can use `part: all` and if you want to look into the body and header at the same time, `part: header` if you only want to look into the header.

**Reply by t43Wiu6** [reply]
oops，it seems that you didnt got me
i have defind `part: body` already...
```
      - type: word
        name: apache
        words:
          - "Apache"
        part: header
      - type: word
        name: tomcat
        words:
          - "successfully installed Tomcat"
        part: body
```
matcher looking the key word `successfully installed Tomcat` in exp body，should return true
and when it looking the header，there
is another rules ，match result shoud be true too.

so the latest result is a magic? Obviously, it cannot be both Tomcat and Apache，because the result just return one word.
