### ISSUE TITLE
[issue] Full url gets mingeled with base url

### ISSUE THREAD

**Issue by Backfighter** [projectdiscovery/nuclei#1000]
**Describe the bug**
Full URLs are first parsed and inserted as path. They still include the full host etc:
https://github.com/projectdiscovery/nuclei/blob/79421aa08808ece0a7144da036f28a07b408c25f/v2/pkg/protocols/http/raw/raw.go#L96

But then the path gets combined with the base url:
https://github.com/projectdiscovery/nuclei/blob/79421aa08808ece0a7144da036f28a07b408c25f/v2/pkg/protocols/http/raw/raw.go#L110

This results in invalid URLs.

**Nuclei version**
2.5.0

**Screenshot of the error or bug**
Example:
```yaml
#...
requests:
  - raw:
    - |
    GET http://example.com HTTP/1.1
```

Using `nuclei -u http://example2.com` will result in the invalid URL `http://example2.comhttp//example.com`.

**Comment by geeknik** [comment]
You'll need to use the `unsafe: true` setting in your template. 

For example:
```
requests:
  - raw:
      - |+
        GET http://example.com HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko)
        Accept-Language: */*
        Connection: close

    unsafe: true
```

Testing against a host I can view the logs on shows the correct payload is sent:
```
xxx.xxx.xxx.xxx - - [07/Sep/2021:19:47:20 +0000] "GET http://example.com HTTP/1.1" 200 3419 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko)"
```

**Comment by geeknik** [comment]
However, there is an console display display issue in the nuclei output that should be addressed:

```
[2021-09-07 14:52:07] [debug-test] [http] [info] https://mydomain.tldhttp://example.com
```

But that doesn't appear to affect the payload when the `unsafe: true` flag is set in the template.

**Comment by Backfighter** [comment]
Ok so I think I understand the issue. I wanted to send a request to a host different from the target but this is not supported by nuclei. You cannot tell nuclei to send a request to a different host using the request target in a http request. The machine you are sending the request to and the request target in the first line of the http message are not necessarily the same (https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages). 

For example if you send a request via a proxy you send the http message to the proxy but the request target in the message is not the proxy itself but some other server on the internet.

In any case paths shouldn't be concatenated if the request target is an absolute url. So I will keep this issue open.

**Comment by geeknik** [comment]
Well, the paths aren't concatenated in the actual request if you use the proper template format. I've been using a template that calls `GET {{interactsh-url}} HTTP/0.9` for some time and it works great. You can also use `CONNECT` to great effect as well. 👍🏻  We were able to find a nice bug impacting ProtonVPN's proxy network with this template.

**Comment by Backfighter** [comment]
They do get concatenated. See for example:
```yaml
id: basic-raw-http-example

info:
  name: Test RAW GET Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET http://127.0.0.1:8071/test2 HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
```
If you run this with `nuclei -t path/to/template.yaml -u http://127.0.0.1:8069/test1`. You get the following output:
```
[INF] [basic-raw-http-example] Dumped HTTP request for http://127.0.0.1:8069/test1

GET /test1http://127.0.0.1:8071/test2 HTTP/1.1
Host: 127.0.0.1:8071
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
Connection: close
Origin: http://127.0.0.1:8069/test1
Accept-Encoding: gzip

[WRN] [basic-raw-http-example] Could not execute request for http://127.0.0.1:8069/test1: GET http://127.0.0.1:8069/test1http://127.0.0.1:8071/test2 giving up after 2 attempts: Get "http://127.0.0.1:8069/test1http://127.0.0.1:8071/test2": no address found for host
```
You would expect the request to look like:
```
[INF] [basic-raw-http-example] Dumped HTTP request for http://127.0.0.1:8069/test1

GET http://127.0.0.1:8071/test2 HTTP/1.1
Host: http://127.0.0.1:8069
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
Connection: close
Origin: http://127.0.0.1:8069
Accept-Encoding: gzip
```

This is a valid use case assuming http://127.0.0.1:8069/test1 is a proxy you are testing and you are telling the proxy to contact http://127.0.0.1:8071/test2.
