### ISSUE TITLE
Additional fields support under info block

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1003]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

New fields:-

```
  classification: # optional
    cvss-metrics: 3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2018-14064
    cwe-id: CWE-22
```

```
remediation:  # optional
```

Example template:-

```yaml
id: CVE-2018-14064

info:
  name: VelotiSmart Wifi - Directory Traversal
  author: 0x_Akoko
  severity: high
  tags: cve,cve2018,lfi,camera,iot
  description: The uc-http service 1.0.0 on VelotiSmart WiFi B-380 camera devices allows Directory Traversal, as demonstrated by /../../etc/passwd on TCP port 80.
  classification:
    cvss-metrics: 3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2018-14064
    cwe-id: CWE-22
  reference:
    - https://medium.com/@s1kr10s/velotismart-0day-ca5056bcdcac
    - https://www.exploit-db.com/exploits/45030
```
