### ISSUE TITLE
Allow sending requests to different hosts in a single attack

### ISSUE THREAD

**Issue by Backfighter** [projectdiscovery/nuclei#1005]
**Is your feature request related to a problem? Please describe.**
As soon as an exploit involves more than one party, requests need to be send to different hosts. This is currently not supported by nuclei.
Take for example a site protected by keycloak. In order to log in one has to enter the site, get redirected to the keycloak login page, extract the login url form the page, send a post request with user data to that login url, get redirected back to the original page with a valid session.

**Describe the solution you'd like**
An additional property to specify a different target could be added:
```yaml
id: different-host-http-example

info:
  name: Test template involing multiple parties
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /rel/path HTTP/1.1
    target: "http://different.host"
  - raw:
      - |
        GET {{replace_regex(different-host-link, "https?:\/\/[^/]+", "")}} HTTP/1.1
    target: "{{replace(different-host-link, replace_regex(different-host-link, \"https?:\/\/[^/]+\", \"\"), \"\"}}"
 ```
This could also be used to tackle #290 (one would need to check wether all requests have targets specified).
