### ISSUE TITLE
Allow running system commands and working on output in templates

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#106]

**Comment by manuelbua** [comment]
As the last year i implemented a similar tool to `nuclei` by wrapping a modified `zgrab` (https://github.com/manuelbua/zgrab/tree/manuel) in a Python3 program, i can dump here some of the ideas i implemented, as i also have used YAML "recipes" for detection as well lol.

In my implementation I can define either a `request` section or single `requests` section with multiple `request` sections and each one can have a `verify` section on its own, or a global `verify` sections for all the requests to match, no boolean operators have never been implemented :\ 

My `verify` section worked like this: for each command to execute (`fgrep`, `jq`, ..) build a command line with its own args, then pipe the output to the next command in the chain.

So, I actually run `zgrab` on the targets by building and issuing the specified HTTP request (verb, headers, ..) as per the rule, then saved the compressed HTTP response for archival and piped it to the `verify` command chain: the final output is a "PoC.txt" file with the URLs that matched the payload and the full command line to reproduce it.

For example, this is my recipe for checking the existence of Oracle Weblogic:
```yaml
name: Oracle WebLogic
requests:
    - request:
        verb: 'GET'
        endpoint: '/wls-wsat/CoordinatorPortType'
    - request:
        verb: 'GET'
        endpoint: '/_async/AsyncResponseService'
verify:
    - egrep:
        - '-i'
        - '<h1>Web Services|<h1>Welcome to the {|AsyncResponseService home page| home page<h3>'
```

This is the redacted text output in the `PoC.txt` file:
```
--------------------------------------------------------------------------------
2019-09-08 20:09:42.462349
PoC for recipe "Oracle WebLogic", request 1 of 2, GET /wls-wsat/CoordinatorPortType
(4 results)
# xzcat /tmp/zprobe/20190908/oracle-weblogic-443-tls/1-get-wls-wsat-coordi.res.xz | egrep -i '<h1>Web Services|<h1>Welcome to the {|AsyncResponseService home page| home page<h3>' | zurls.sh

x.y.a.w text/html;charset=UTF-8 1629 GET https://any.matching.target2.com/wls-wsat/CoordinatorPortType
x.y.b.w text/html; charset=utf-8 1656 GET https://any.matching.target3.com/wls-wsat/CoordinatorPortType
x.y.e.w text/html; charset=utf-8 1677 GET https://any.matching.target6.com/wls-wsat/CoordinatorPortType
x.y.f.w text/html; charset=utf-8 1677 GET https://any.matching.target7.com/wls-wsat/CoordinatorPortType

--------------------------------------------------------------------------------
2019-09-08 20:10:13.078754
PoC for recipe "Oracle WebLogic", request 2 of 2, GET /_async/AsyncResponseService
(7 results)
# xzcat /tmp/zprobe/20190908/oracle-weblogic-443-tls/2-get-async-asyncres.res.xz | egrep -i '<h1>Web Services|<h1>Welcome to the {|AsyncResponseService home page| home page<h3>' | zurls.sh

x.y.z.w  330 GET https://any.matching.target.com/_async/AsyncResponseService
x.y.a.w  332 GET https://any.matching.target2.com/_async/AsyncResponseService
x.y.b.w  332 GET https://any.matching.target3.com/_async/AsyncResponseService
x.y.c.w  340 GET https://any.matching.target4.com/_async/AsyncResponseService
x.y.d.w  348 GET https://any.matching.target5.com/_async/AsyncResponseService
x.y.e.w  362 GET https://any.matching.target6.com/_async/AsyncResponseService
x.y.f.w  362 GET https://any.matching.target7.com/_async/AsyncResponseService
```

In my implementation however, in order to match pure words multiple times, i had to chain multiple `fgrep` commands, for example looking for a Splunk infoleak:
```yaml
name: Splunk information leak
requests:
    - request:
        verb: GET
        endpoint: /en-US/splunkd/__raw/services/server/info/server-info?output_mode=json
verify:
    - fgrep: '200 OK'
    - fgrep: 'kvStoreStatus'
    - fgrep: 'master_guid'
    - fgrep: 'physicalMemoryMB'
    - fgrep: 'serverName'
    - fgrep: 'server_roles'
```

**Comment by manuelbua** [comment]
As another example of a very basic and simple request flow is this one:
```yaml
name: Try PUT /dudez.txt
requests:
    - request:
        verb: PUT
        endpoint: /dudez.txt
        body: true
        headers:
            Accept: '*/*'
            Content-Type: text/plain
        verify:
            - fgrep:
                - '-i'
                - '200 OK'
    - request:
        verb: GET
        endpoint: /dudez.txt
        verify:
            - fgrep:
                - '-i'
                - 'dudez was here'
```

I never bothered to make the scanner "intelligent" and only issue request 2 if request 1 was verified successully (my steps were 1. issue requests, 2. call the verify chain and write the output), but this permitted me to inspect the output file and correlate the fact the `PUT` request was working because followed by a successful `GET`. 

The `body: true` rule had the effect for the scanner to look for a file named the same as the rule with a `.body` extension and read the body request form that (rule named `put-dudez-txt.yaml`, look for `put-dudez-txt.body`).
