### ISSUE TITLE
CLI Variable (var) to support file input

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1073]
**Is your feature request related to a problem? Please describe.**
Currently, it's possible to define `{{variable}}` in the template and pass the input dynamically using CLI `var` flag, but it only supports string input and not file input.

**Describe the solution you'd like**
Ability to feed both string and file input that includes multiline payloads, wordlist, etc.

```yaml
requests:
  - method: GET
    path:
      - "https://app.asana.com/api/1.0/users/me"
    headers:
      Authorization: Bearer {{token}}
```

Current support:- 

```
nuclei -t test.yaml -var token=my_token
```

After update:- 

```
nuclei -t test.yaml -var token=token.txt
nuclei -t test.yaml -var token=my_token
```
