### ISSUE TITLE
[issue] Binary matcher always returns true if the input cannot be decoded as hex

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1085]
Example template:
```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/uploads/tmm_db_migrate/tmm_db_migrate.zip"

    matchers:
      - type: binary
        name: "Binary"
        binary:
          - "somethingcompletelyrandom" # the length must be un-even
```

Should not match:
![image](https://user-images.githubusercontent.com/13679401/136032955-1aba8342-b683-411c-af0e-744eb34ee8f6.png)
