### ISSUE TITLE
Add Support for Query Parameter Autodetect

### ISSUE THREAD

**Issue by cfsdes** [projectdiscovery/nuclei#1087]
Please add a new feature to detect parameters and automatically inject payloads.

For example. Template:

```yaml
id: parameter-fuzzing


requests:
  - query: {{payload}}
    payloads:
      payload: wordlist.txt

  - body: {{payload}}
    payloads:
      payload: wordlist.txt
```

Command:
```
nuclei -u "http://example.com/?id=1" -t template.yaml
```

Will automatically identify the id parameter value and replace it with the payloads from our wordlist.
(the body option is to identify and replace for POST requests)
