### ISSUE TITLE
[issue] Not Able To use "&" on template

### ISSUE THREAD

**Issue by cfsdes** [projectdiscovery/nuclei#1090]
When I try to use the "&", the request is not sent

```yaml
 - method: GET
    path:
      - "{{BaseURL}}&cb=1204210"
    redirects: true
    race: true
    race_count: 2

```
