### ISSUE TITLE
Also validate the binary matcher if template validation was requested

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1092]
Example:
```yaml
matchers:
  - type: binary
     binary:
       - "504B0304"
```

```golang
func (m *Matcher) MatchBinary(corpus string) (bool, []string) {
...
// DecodeString expects that src contains only hexadecimal characters and that src has even length.
// If the input is malformed, DecodeString returns the bytes decoded before the error.
hex, err := hex.DecodeString(binary)
...
}
```

Search for other usages of `DecodeString` and make sure the error is handled correctly.
