### ISSUE TITLE
Add option to exclude file/directory in file template

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#1093]
**Is your feature request related to a problem? Please describe.**
Currently when scanning a local directory for the purposes of static analysis with a file template, nuclei does not provide an option to ignore sub-directories, which leads to false positives when iterating through various `test(s|ing)` directories.

**Describe the solution you'd like**
Add option to static analysis file templates so some directories can be ignored, limiting false positives. Thank you.

Example:-

```yaml
id: test-exclude

info:
  name: test
  author: pdteam
  severity: info

file:
  - extensions:
      - all

    exclude:
      - test/
      - misc/test.txt

    matchers:
      - type: word
        words:
          - "test"
```
