### ISSUE TITLE
[feature] Add/Expose Headless action that waits until an element appears

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1096]
Dynamic waits are preferred over static ones, because they offers more stability and flexibility. For example if a 1 second static wait is defined and the page loads slower, the execution would fail, on the other hand, if a larger sleep value is provided and the page loads fast, the execution would be unnecessarily blocked, making the template run slower than it should.

Example template structure:
```yaml
- args:
    by: x
    xpath: //input[@id='password-field']
    timeout: 5 # this parameter should be optional
  action: waitvisible
```

Nuclei action definitions:
- `/nuclei/v2/pkg/protocols/headless/engine/action.go`
- `/nuclei/v2/pkg/protocols/headless/engine/page_actions.go`

Rod method to be exposed: `rod/element.go`
`func (el *Element) WaitVisible() error`
