### ISSUE TITLE
Custom header problem

### ISSUE THREAD

**Issue by zhihuba** [projectdiscovery/nuclei#1098]
**Describe the bug**
When using configuration files or command line parameters to add header, the scanner will ignore the header configuration in the template

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 
Current Version: 2.5.2

**Screenshot of the error or bug**
```bash
nuclei -t technologies/shiro-detect.yaml -header="Cookie: JSESSIONID=C46E3C3AC1EDF646E113FFEFBD464064" -list urls.txt -debug -markdown-export md
```
![image](https://user-images.githubusercontent.com/22538559/136581791-089c5e7c-4d57-4bbc-8dc5-5bcc54d3807f.png)
```bash
nuclei -t technologies/shiro-detect.yaml -list urls.txt -debug -markdown-export md
```
![image](https://user-images.githubusercontent.com/22538559/136582079-a2e3fe8d-78dd-4ac7-8746-3d26a1a71803.png)
**what should I do**

**Comment by zhihuba** [comment]
hi by looking up historical issues. Found a way to add cookies. But doing so requires modification to each template. Is there a more convenient way?
### this tamper
```yaml
id: shiro-detect

info:
  name: Detect Shiro Framework
  author: AresX
  severity: info
  tags: tech,shiro

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
    headers:
      Cookie: '{{TOKEN}};rememberMe=123'

    matchers:
      - type: word
        words:
          - 'rememberMe=deleteMe'
        part: header
```
### run
```bash
nuclei -t technologies/shiro-detect.yaml -var TOKEN=D255C2895E83EEE8168755CB3841A20F -list urls.txt -debug
```
![image](https://user-images.githubusercontent.com/22538559/136641240-8b605edc-951f-4a12-a6b9-236930ce031d.png)
