### ISSUE TITLE
Reporting to Github issues fails if the issue-label field is not set

### ISSUE THREAD

**Issue by 0xcrypto** [projectdiscovery/nuclei#1122]
**Describe the bug**
For the following reporting configuration, nuclei fails to report with error `422 Validation Failed [{Resource:Label Field:name Code:missing_field Message:}]`

```yaml
allow-list:
    severity: info, low, medium, high, critical
github: 
    username: "0xcrypto"
    owner: "bb-research"
    token: "REDACTED"
    project-name: "hackberry_xyz"
```

**Nuclei version**
v2.5.2

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/6683856/137379877-93ddb54d-d527-4bf5-ad48-60011dee5c83.png)
