### ISSUE TITLE
Adding simple value-sharing mechanism between templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1162]
### Please describe your feature request:
A mechanism to define and share values between other templates during scan time using extractors, the idea is is to have information saved and accessible globally during the scan time regardless of the type of templates, which enabled to write complex workflows using a combination of multi-type templates, i.e read values from DNS template to be used in HTTP or network.

### Describe the use case of this feature:
- Write a template to "login into the website" and store the session in a global variable and reuse the same session to run multiple other authenticated templates.
- Run DNS template, get some values to use with other HTTP templates or Network templates.

Example templates:-

<details>
<summary> Login Template </summary>

```yaml
id: wordpress-login
​
info:
  name: Test RAW Template
  author: pdteam
  severity: info
​
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
​
      - |
        POST /wp-login.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        
        log=wordpress&pwd=Hacker%40321&rememberme=forever&wp-submit=Log+In
​
    matchers-condition: and
    matchers:
      - type: word
        name: wordpress-login
        part: header
        words:
          - "/wp-admin/"
​
    extractors:
      - type: regex
        name: session
        internal: true
        part: header
        regex:
          - "wordpress_[a-z0-9]+=([A-Za-z0-9%]+)"
```
</details>

<details>
<summary> Authenthicated Template </summary>

```yaml
id: admin
​
info:
  name: Test RAW Template
  author: pdteam
  severity: info
​
requests:
  - raw:
      - |
        GET /wp-admin/ HTTP/1.1
        Host: {{Hostname}}
        Cookie: {{kb_get("wordpress-login:session", Input)}}
​
    matchers:
      - type: word
        name: admin-dashboard
        words:
          - "Dashboard"
```
</details>
