### ISSUE TITLE
Redirects support matching on final response only

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1173]
### Nuclei version:
v2.5.3

### Current Behavior:
If `redirects: true` is used, the matcher/extractor is checked against the final response only.

### Expected Behavior:
matcher/extractor is expected to be matched against all the responses in the redirect chain.

### Steps To Reproduce:

<details>
<summary> test template </summary>

```yaml
id: shiro-detect

info:
  name: Detect Shiro Framework
  author: AresX
  severity: info
  tags: tech,shiro

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
    headers:
      Cookie: JSESSIONID={{randstr}};rememberMe=123;

    redirects: true
    max-redirects: 2
    matchers:
      - type: word
        part: header
        words:
          - "rememberMe=deleteMe"
```

</details>

```
nuclei -u http://47.242.94.216 -t test.yaml
```

### Anything else:
This is partially handled here - https://github.com/projectdiscovery/nuclei/issues/652 by introducing `part: redirect-chain`, instead we can make this behavior as default and deprecate `part: redirect-chain`
