### ISSUE TITLE
Ability to send notification on template match

### ISSUE THREAD

**Issue by fyoorer** [projectdiscovery/nuclei#118]
Hi team

How about adding a new flag in the template yaml such that if something like `notification: true` is set within the template and user supplies for example `--send-notifications` flag to nuclie command, a notification is sent to the user when that template matches.

So template will look something like:

```yaml
id: basic-http-test

info:
  name: Test File
  author: pdteam
  severity: info

requests:
...whatever
...
notifications: true
```

and command to execute:

`nuclie -t /path/to/template.yaml --send-notification --slack-token foobar ....`

I'd have loved to contribute it myself but I don't know much about Go programming. Let me know what do u think.
