### ISSUE TITLE
Adding stop-at-first-match for DNS templates

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1188]
### Please describe your feature request:

Adding stop-at-first-match to prevent sending unnecessary requests and to allow first-match logic in templates

### Describe the use case of this feature:
The DMARC result for a domain is the result for `_dmarc.{{FQDN}}` or for `_dmarc.{{RDN}}`
```
id: dmarc-detect

info:
  name: dmarc-detect
  author: brenocss
  severity: info
  tags: dns,dmarc

dns:
  - name: _dmarc.{{FQDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tTXT\t(.+)"
  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"

    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tTXT\t(.+)"
 ```

**Comment by ehsandeep** [comment]
@brenocss this is now supported in the dev branch.

```yaml
id: dmarc-detect

info:
  name: dmarc-detect
  author: brenocss
  severity: info
  tags: dns,dmarc

stop-at-first-match: true
dns:
  - name: _dmarc.{{FQDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"

  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
```
