### ISSUE TITLE
Adding req-condition for DNS templates

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1189]
### Please describe your feature request:
Adding req-condition for DNS templates Its important to allow the and(&&) logic with multiple requests

### Describe the use case of this feature:
When DMARC is not present in the _dmarc.{{FQDN}} neither in _dmarc.{{RDN}}, then dmarc is missing
```
id: spoofable-mail-missingdmarc

info:
  name: spoofable-mail-missingdmarc
  author: brenocss
  severity: medium
  tags: dns,dmarc

dns:
  - name: _dmarc.{{FQDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        negative: true
  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        negative: true
 ```

**Comment by Mzack9999** [comment]
DNS internal structure needs to be reworked to allow value sharing between different requests - A solution could be built on top of https://github.com/projectdiscovery/nuclei/pull/1047

**Comment by parrasajad** [comment]
@brenocss We can achieve cross request `or`, `and` logic by using the `id` field in requests and then simply use the values from one request in other. Here is an example of how we can handle the use-case presented:
```yaml
id: spoofable-mail-missingdmarc

info:
  name: spoofable-mail-missingdmarc
  author: brenocss
  severity: medium
  tags: dns,dmarc

dns:
  - name: _dmarc.{{FQDN}}
    id: fqdn
    type: TXT
    class: inet
    recursion: true
    retries: 3

  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
      
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        part: fqdn_answer
        negative: true

      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        part: answer
        negative: true
```
