### ISSUE TITLE
Matcher syntax check 

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#1198]
\

### Nuclei version:
``2.5.3 ``
### Current Behavior:
If you create a template using this:

```
    matchers:
      - type: word
        word:
          - 'ErrorPages'

```
The template doesn't work because it has `word:` instead of `words:` . But no syntax error is either displayed. 

### Expected Behavior:
Give an error due to wrong syntax used on matcher description. 

### Steps To Reproduce:

1. Use any template for which you have confirmed positive results and uses the word matcher. 
2. Change the 'words' for 'word' -> no results or errors will show.
