### ISSUE TITLE
HTTP pipeline crash - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1202]
### Nuclei version:
v2.5.3

### Steps To Reproduce:

```yaml
id: pipeline-testing

info:
  name: pipeline testing
  author: pdteam
  severity: info

requests:

  - raw:
      - |
        GET /test HTTP/1.1
        Host: {{Hostname}}

    pipeline: true
```

```console
nuclei -t test.yaml -u https://example.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.5.3 (latest)
[INF] Using Nuclei Templates 8.6.1 (latest)
[INF] Using Interactsh Server https://interactsh.com
[INF] Templates added in last update: 0
[INF] Templates loaded for scan: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x104d71538]

goroutine 58 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0x140003dc420, {0x140000c0150, 0x13}, 0x140009d2180, 0x140000abf50, 0x0, 0x140000abf80, 0x0)
	/Users/sandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:389 +0xef8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP.func1(0x140000d6e20, 0x140003dc420, 0x140000a89e0, 0x140000abf50, 0x140000abf80, 0x140000c27a0, 0x140000a89f0, 0x140009d2180)
	/Users/sandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:180 +0x84
created by github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP
	/Users/sandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:177 +0x3d4
```
