### ISSUE TITLE
allow all extractors to be used as dynamic variable

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1222]
### Please describe your feature request:
Currently, `extractors` with `internal: true` attribute is only considered as dynamic variables, allowing to be resued in the requests, the problem with this is we can not use the same extractor to be used as dynamic variable + display the extractor in CLI output at the same time.

Wanted behaviour:

```[tasklist]
### Tasks
- [ ] make extractors to be used as a dynamic variable as default, as of now it can be using `internal` attribute.
- [ ] `internal` attribute in extractors should be only used to enable/disable printing extracted value to cli / result.
```
### Describe the use case of this feature:

<details>
<summary>Template with Current Support</summary>

```yaml
http:
  - raw:
      - |
        GET /go/add-on/business-continuity/api/cipher.aes HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /config HTTP/1.1
        Host: {{Hostname}}
        Key: {{cipher}}

    extractors:
      - type: regex
        name: cipher
        internal: true
        regex:
          - "([a-z0-9]+)"

      - type: regex
        name: cipher
        regex:
          - "([a-z0-9]+)"
```
</details>

<details>
<summary>Template after requested change</summary>

```yaml
http:
  - raw:
      - |
        GET /go/add-on/business-continuity/api/cipher.aes HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /config HTTP/1.1
        Host: {{Hostname}}
        Key: {{cipher}}

    extractors:
      - type: regex
        name: cipher
        regex:
          - "([a-z0-9]+)"
```
</details>

Related issue:
- https://github.com/projectdiscovery/nuclei/issues/2547

> [!CAUTION]
> This could be a little but critical modification to the core engine, as such we need to ensure change related to this issue doesn't break any existing behavior.
