### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jhhd88** [projectdiscovery/nuclei#1227]
### Nuclei version:
v2.5.3

### Current Behavior:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x104d47ffc]

goroutine 44 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*generatedRequest).URL(...)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/build_request.go:44
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0x140000fe580, {0x0, 0x0}, 0x1400081a180, 0x1400081a1b0, 0x1400081a210)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:226 +0x27c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0x140002b95a0, {0x0, 0x0})
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/common/executer/executer.go:52 +0x188
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processSelfContainedTemplates(0x140003923c0, 0x140000fe420)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/internal/runner/processor.go:12 +0x38
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration.func1(0x140002b9a60, 0x14000132a50, 0x140003923c0, 0x140000fe420)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/internal/runner/runner.go:542 +0x134
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/internal/runner/runner.go:538 +0x21a8
```

### Steps To Reproduce:

<details>
<summary>test template</summary>

```yaml
id: api-nownodes

info:
  name: Nownodes API Test
  author: daffainfo
  severity: info
  reference:
    - https://nownodes.io/
    - https://github.com/daffainfo/all-about-apikey/blob/main/Blockchain/Nownodes.md
  tags: token-spray,nownodes

self-contained: true
requests:
  - raw:
      - |
        GET /api HTTP/1.1
        Host: bsc-blockbook.nownodes.io
        api-key: {{token}}
        Content-Type: application/json

    matchers:
      - type: word
        part: body
        words:
          - '"coin":'
          - '"host":'
          - '"version":'
        condition: and
```
</details>

`nuclei -t test.yaml`
