### ISSUE TITLE
Unsafe request are not working with base template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1243]
### Nuclei version:
dev

### Current Behavior:

Currently, when using `unsafe: true` with the base template, additional headers are included as part of the request.

```yaml
GET / HTTP/1.1
Host: 0.0.0.0:57283
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```
### Expected Behavior:
```yaml
GET / HTTP/1.1
Host: 0.0.0.0:57283
```
### Steps To Reproduce:

**Unsafe Template:**

```yaml
id: basic-unsafe-request

info:
  name: Test Base Unsafe Request Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    unsafe: true
```
</details>

```
echo http://0.0.0.0:57283 | nuclei -t test.yaml -debug-req
```

Expected behavior can be also replicated with RAW template

```yaml
id: basic-raw-unsafe-request

info:
  name: Test RAW Unsafe Request Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```
