### ISSUE TITLE
Optional field update for DNS template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1244]
### Please describe your feature request:

Currently, DNS block contains `name`,`type`,`class`,`recursion`,`retries` as mandatory fields to include in the template, where 
 only the `type` is subject to change most of times, as such we can make last three fields optional with use of sane default values. 

Current default:-

```yaml
dns:
  - name: "{{FQDN}}"
    type: NS
    class: inet
    recursion: true
    retries: 3
```

After update default:

```yaml
dns:
  - name: "{{FQDN}}"
    type: NS
```
