### ISSUE TITLE
Can't use charset in helper functions

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#1261]
### Nuclei version:
v2.5.3

### Current Behavior:
Currently, the DSL helper functions do not work with the charset they should. In particular all functions that have a charset input, like:
- rand_char
- rand_text_alpha, and
- rand_text_numeric

### Expected Behavior:
`{{rand_char(2, "a")}}` should be produced `aa`.
`{{rand_text_numeric(2, "1")}}` should be produced `11`.
`{{rand_char(3, "A")}}` should be produced `AAA`.

**Comment by dwisiswant0** [comment]
While exploring the codes _(to make sure which helper functions are similar)_, only `rand_base` that works.

Although this is not included in the documentation, but I'm still confused.
![Screenshot_2021-11-17_01-47-37](https://user-images.githubusercontent.com/25837540/142046912-8dfe6905-a395-40b3-abfc-fb9f9870fd0b.png)

Inconsistent positioning of `charset` and `badchars` in the documentation, resulting in different in the engine. Which should work fine with `charset` in the 3rd position argument, while `badchars` is placed 2nd.

**Comment by pradkrish** [comment]
I am a C++ developer but new to `Go` and `Nuclei`. May I have a go at it with some guidance?

**Comment by forgedhallpass** [comment]
Hello @pradkrish,

I am doing some refactorings around the DSL functions, but can guide you after I've finished.

The fix for this should be very easy.

**Comment by forgedhallpass** [comment]
Hello again @pradkrish,
I've finished with #1295 
Let me know what kind of guidance do you need to start. 
You can also DM me on Discord.

**Comment by forgedhallpass** [comment]
Related documentation ticket: https://github.com/projectdiscovery/nuclei-docs/issues/27

**Comment by forgedhallpass** [comment]
Hello @dwisiswant0,

The bugs around the methods have been fixed.
I've also added two new ones: `repeat` and `remove_bad_chars`
The user experience of the DSL functions has been improved in #1295 

```yaml
id: helper-functions-examples

info:
  name: Template with Helper Functions
  author: forgedhallpass
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: dsl
        condition: and
        dsl:
          - "print_debug(rand_char())"                 # randomly choose 1 character from numbers + lowercase + uppercase letters
          - "print_debug(rand_char('abc'))"            # randomly choose 1 character from the input
          - "print_debug(rand_char('a'))"              # same, but since the input consists of 1 char only, there is no other choice
          - "print_debug(rand_base(10, 'abc'))"        # randomly choose 1 character from the input, 10 times
          - "print_debug(rand_base(5, 'a'))"           # same, but since the input consists of 1 char only, there is no other choice
          - "print_debug(repeat('a', 5))"              # repeats the "a" character 5 times
          - "print_debug(repeat('../', 5))"            # if the input consists of multiple characters, it maintains the order while repeating
          - "print_debug(repeat(rand_char('abc'), 5))" # repeat 1 randomly chosen character from the input 5 times
```

![image](https://user-images.githubusercontent.com/13679401/146194835-04b76a47-cb30-46d3-a83d-8726aedaf47f.png)

Documentation:
https://nuclei.projectdiscovery.io/templating-guide/helper-functions/
https://nuclei.projectdiscovery.io/template-examples/helper-functions/
