### ISSUE TITLE
Support to use multiple hosts from same template

### ISSUE THREAD

**Issue by appsec-airito** [projectdiscovery/nuclei#1289]
example template:

```
requests:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: python-requests/2.24.0
        Accept: */*
        Connection: close

      - |
        POST /random/okta-token-validation  HTTP/1.1
        Host: okta.com
        Connection: close
        Content-Length: 1067
        User-Agent: Mozilla/5.0 
        Content-Type: application/x-www-form-urlencoded
        Accept: */*
        Connection: close

        token={{randkey}}

    extractors:
      - type: regex
        name: randkey
        internal: true
        regex:
          - "([a-zA-Z0-9/+]+\\.[a-zA-Z0-9/+]+\\.[a-zA-Z0-9/+]+)"

      - type: regex
        name: token2
        regex:
          - "(?m).*"

```

In this template the second raw request should goto okta.com but it goes to {{Hostname}} ignoring the value in "Host".
The randkey is also not used as expected in dynamic variables

**Comment by ehsandeep** [comment]
thanks for flagging this @appsec-airito, upon further review, I can confirm the template defined `Host` header is respected but I guess you wanted to control the requesting URL as well in your case use?

To confirm the same, run the same template with `debug-req` flag.

```console
[INF] [basic-raw-example] Dumped HTTP request for https://example.com

GET / HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
Connection: close
Origin: https://example.com
Accept-Encoding: gzip

[INF] [basic-raw-example] Dumped HTTP request for https://example.com

GET /random/okta-token-validation HTTP/1.1
Host: okta.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36
Connection: close
Accept-Encoding: gzip
```

**Comment by appsec-airito** [comment]
Validated the above with debug-req in "dev" branch.

The problem I have raised here is related to 2nd request below:
```
[INF] [basic-raw-example] Dumped HTTP request for https://example.com

GET /random/okta-token-validation HTTP/1.1
Host: okta.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36
Connection: close
Accept-Encoding: gzip
```

The request is going to `https://example.com` whereas it should have gone to `https://example.com`.  2 reasons for it:
1) Not changing it limits the raw http header - because of which
- we can't make calls to different domains from a template
- it complicates how we can do a simple validation test after identifying a possible secret

2) The nuclei "Base HTTP" acts as requested in this PR and the "raw http" doesn't- which makes it confusing when using one product

**Comment by ehsandeep** [comment]
Yes, you are right @appsec-airito it doesn’t work similar to Base HTTP, as in Base HTTP template include the complete URL information vs in Raw HTTP request where it only includes request header and not the URL and the possible solution would be to include URL information in raw format similarly added recently for the **[self-contained](https://github.com/projectdiscovery/nuclei/pull/1121)** templates only, here is how the template will look like after the change to achieve expected behavior.

```yaml
requests:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: python-requests/2.24.0
        Accept: */*
        Connection: close

      - |
        POST https://okta.com/random/okta-token-validation  HTTP/1.1
        Host: okta.com
        Connection: close
        Content-Length: 1067
        User-Agent: Mozilla/5.0 

        token=§randkey§
```

**Comment by appsec-airito** [comment]
`self-contained` was made for entire template instead of per request and hence when we have multiple raw request like below:

```
self-contained: true
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: python-requests/2.24.0
        Accept: */*
        Connection: close

      - |
        POST https://okta.com/random/okta-token-validation  HTTP/1.1
        Host: okta.com
        Connection: close
        Content-Length: 1067
        User-Agent: Mozilla/5.0 

        token=§ randkey§
```
it breaks. With a template like above when I called nuclei like:
`./nuclei_test -t 2api-okta_dev.yaml -u http://localhost/okta_token.txt -vv -debug-req`

it made only one http call and the rawRequest.FullURL parameter's value read as:
`:///`

**Comment by ehsandeep** [comment]
@appsec-airito `self-contained` template was just an example of how the URL support can be added into raw template, in its current form it can not be used to achieve the above use case.

**Comment by appsec-airito** [comment]
@ehsandeep - since only `raw request` template supports dynamic variables in case someone wants to validate some information extracted from 1 request- it will be needed to have a per request based `self-contained` parameter. Is there a technical reason why we don't want to do it?

**Comment by ehsandeep** [comment]
> since only raw request template supports dynamic variables in case someone wants to validate some information extracted from 1 request

Base HTTP does support dynamic variables as well.

> it will be needed to have a per request based self-contained parameter.

Not sure if I understand this completely, if possible let's jump over [discord](https://discord.gg/projectdiscovery).

**Comment by appsec-airito** [comment]
We noticed that dynamic variables work but only if it is the same method. Eg:

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{RootURL}}/{{Path}}/{{map}}.js.map"
      
    extractors:
      - type: regex
        internal: true
        name: map
        group: 1
        regex:
          - "sourceMappingURL=([a-z-~0-9.]+).js.map"
```

**Comment by Mzack9999** [comment]
@appsec-airito, you can send an http request to other hosts by putting the entire HTTP URL in the first request line as follows:

```yaml
id: test

info:
  name: Test
  author: test
  severity: info
  description: test
  tags: none

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: python-requests/2.24.0
        Accept: */*
        Connection: close

      - |
        POST https://okta.com/random/okta-token-validation  HTTP/1.1
        Connection: close
        Content-Length: 1067
        User-Agent: Mozilla/5.0 
        Content-Type: application/x-www-form-urlencoded
        Accept: */*
        Connection: close

        token={{randkey}}

    extractors:
      - type: regex
        name: randkey
        internal: true
        regex:
          - "([a-zA-Z0-9/+]+\\.[a-zA-Z0-9/+]+\\.[a-zA-Z0-9/+]+)"

      - type: regex
        name: token2
        regex:
          - "(?m).*"
```

The second request will be sent to `okta.com`
