### ISSUE TITLE
Improve DSL function UX

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1295]
Proposed features:
- [x] Show meaningful error message, when a user provides an nonexistent DSL function name
- [x] Show meaningful error message, when a user give an incorrect number of arguments for a specific DSL function
- [x] Provide option to show all DSL methods and their signatures

**Comment by forgedhallpass** [comment]
Template test cases:
```yaml
id: test-dsl

info:
  name: DSL test
  author: forgedhallpass
  severity: info

file:
  - extensions:
    - txt

    matchers:
      - type: dsl
        dsl:
#          - print_debu()               # invalid DSL function. Display available options
#          - 'to_lower("a", "b", "c")'  # invalid method signature. Display correct one
#          - 'to_lower("a")'            # DSL expression should return a boolean
#          - 'to_lower("a") == "a"'     # positive test case
#          - 'tolower("a") == "a"'      # positive test case, backwards compatible
```

Case 1: `pint_debu()` invalid DSL function
![image](https://user-images.githubusercontent.com/13679401/145072544-f747bc54-9fde-4e82-a8aa-15f143c24fd2.png)

Case 2:  `to_lower("a", "b", "c")`
![image](https://user-images.githubusercontent.com/13679401/145070579-a258cb40-939c-4631-9ced-1980d7b62bfd.png)

Case 3: `to_lower("a")`
![image](https://user-images.githubusercontent.com/13679401/145072139-41ac611c-2280-40c7-b5c6-6107fb5c944f.png)
