### ISSUE TITLE
Support to use specific matcher in workflow in case multiple matcher is used 

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#133]
Is it possible to accept values other than `bool` under `logic` conditions? Since there has been a `tech-detect` template that fingerprinting the framework.

### Use cases

```yaml
variables:
  tech-detect: technologies/tech-detect.yaml
  php-fusion-cve: cve/cve-1-1.yaml

logic:
  |
    if tech-detect == "php-fusion" {
        php-fusion-cve
    }
```

Regards.

**Comment by bauthard** [comment]
This should be the correct logic format @Mzack9999 

```yaml
variables:
  tech-detect: technologies/tech-detect.yaml
  php-fusion-cve: cve/cve-1-1.yaml

logic:
  |
    if tech-detect() == "php-fusion" {
        php-fusion-cve()
    }
```

@Mzack9999 I'm not sure if we can support this format in logic, but as we return data in the following format in case multiple templates are in use:- 

```
[tech-detect:bootstrap] [http] https://cartops-staging.uber.com/
[tech-detect:wordpress] [http] https://eng.uber.com/
[tech-detect:google-font-api] [http] https://z.uber.com/
[tech-detect:react] [http] https://ladyeng.uber.com/
[tech-detect:react] [http] https://help.uber.com/
[tech-detect:contentful] [http] https://marketplace.uber.com/
[tech-detect:react] [http] https://receipts.uber.com/
```

the following logic will be simpler to use, only if it is supported in logic. 

```yaml
variables:
  tech-detect: technologies/tech-detect.yaml
  wp-cve: cve/cve-1-1.yaml

logic:
  |
    if tech-detect:wordpress() {
        wp-cve()
    }
```
