### ISSUE TITLE
Stop-at-first-match does not work with interactsh matchers

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1361]
### Nuclei version:
2.5.4

### Current Behavior:

<details>
<summary>test interactsh template</summary>

```yaml
id: test-interactsh

info:
  name: interactsh test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

    stop-at-first-match: true
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"
```
</details>

```console
echo https://geonet.shodan.io | nuclei -t test.yaml 

[test-interactsh] [http] [info] https://geonet.shodan.io/api/geoping/c6r03sdmmud3vov68sjgcg5ydhon5yn3k.interactsh.com
[test-interactsh] [http] [info] https://geonet.shodan.io/api/geoping/c6r03sdmmud3vov68sjgcg5yd7on5yn3c.interactsh.com
[test-interactsh] [http] [info] https://geonet.shodan.io/api/geoping/c6r03sdmmud3vov68sjgcg5yd7on5yn3c.interactsh.com
```

### Expected Behavior:
```console
echo https://geonet.shodan.io | nuclei -t test.yaml 

[test-interactsh] [http] [info] https://geonet.shodan.io/api/geoping/c6r03sdmmud3vov68sjgcg5ydhon5yn3k.interactsh.com
```
### Steps To Reproduce:

Run `echo https://geonet.shodan.io | nuclei -t test.yaml`
