### ISSUE TITLE
Allow Extraction of IPs involved in interactsh interactions

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#1391]
In some cases it may be useful to extract IPs involved in OOB interactions.
Currently only the request, response and protocol are available

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei/blob/ed309e446ab6284b74b7e4a58091e4628d140251/v2/pkg/protocols/common/interactsh/interactsh.go#L167

This can be achieved by exposing `interaction.RemoteAddress` to `interactsh_ip` which later can be accessed by users.

 ```go
 data.Event.InternalEvent["interactsh_ip"] = interaction.RemoteAddress
 ```
 
 
```yaml
    extractors:
      - type: kval
        part: header
        kval:
          - interactsh_ip
```

Also to note, `interaction.RemoteAddress` is already available and part of JSON output with key `remote-address`
