### ISSUE TITLE
Incorrect Stats Output for some templates

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#1402]
### Nuclei version:
2.5.7-dev

### Current Behavior:
Stats is broken for the following template
```yaml
id: stats-test-template

info:
  author: meme-lord
  name: stats-test-template
  severity: info

requests:
  - method: POST
    path:
      - "{{BaseURL}}"

    headers:
      Content-Type: application/x-www-form-urlencoded

    body: "{{body}}"

    payloads:
      body:
        - 'postdata=1'
        - 'postdata=2'
        - 'postdata=3'
        - 'postdata=4'
        - 'postdata=5'

    redirects: true
    max-redirects: 3
    matchers:
      - type: word
        part: body
        words:
          - "doesntmatter"
```

```bash
nuclei -si 1 -t test.yaml -u https://google.com -stats

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.7-dev

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: Version string empty
[INF] Using Nuclei Engine 2.5.7-dev
[INF] Using Nuclei Templates 
[INF] Using Interactsh Server https://interact.sh
[INF] Templates added in last update: 487
[INF] Templates loaded for scan: 1
[0:00:01] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 0/0 (0%)
[0:00:02] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 1/0 (0%)
[0:00:03] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 2/0 (0%)
[0:00:04] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 3/0 (0%)
[0:00:05] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 4/0 (0%)
[0:00:06] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 5/0 (0%)
[INF] No results found. Better luck next time!
```

### Expected Behavior:

```bash
[0:00:01] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 0/5 (0%)
[0:00:02] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 1/5 (20%)
[0:00:03] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 2/5 (40%)
[0:00:04] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 3/5 (60%)
[0:00:05] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 4/5 (80%)
[0:00:06] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 5/5 (100%)
```
