### ISSUE TITLE
Expose dsl key-value map of Interactsh variables

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1455]
### Please describe your feature request:
Expose interactsh variables to responseToDSLMap

https://github.com/projectdiscovery/nuclei/blob/88bb6cb0464855a5ab8ea4256bbcc93054ccd299/v2/pkg/protocols/http/operators.go#L103

### Describe the use case of this feature:
This will allow using interactsh related matchers / extrators with DSL matchers

Example:- 
```yaml
      - type: dsl
        dsl:
          - 'contains(interactsh_protocol, "dns")'
```
