### ISSUE TITLE
PTR Query does not work

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1464]
### Nuclei version:
dev

### Steps To Reproduce:

```yaml
id: ptr-fingerprint

info:
  name: PTR Fingerprint
  author: pdteam
  severity: info
  tags: dns,ptr

dns:
  - name: "{{FQDN}}"
    type: PTR

    matchers:
      - type: word
        words:
          - "IN\tPTR"

    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tPTR\t(.+)"
```

```
echo 46.84.0.173 | nuclei -t ptr.yaml -debug
```

### Current Behavior:
```console
[INF] [ptr-fingerprint] Dumped DNS request for 46.84.0.173 domain=46.84.0.173
;; opcode: QUERY, status: NOERROR, id: 49548
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;46.84.0.173.	IN	 PTR

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
[DBG] [ptr-fingerprint] Dumped DNS response for 46.84.0.173

;; opcode: QUERY, status: NXDOMAIN, id: 49548
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; QUESTION SECTION:
;46.84.0.173.	IN	 PTR

;; AUTHORITY SECTION:
.	86397	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022010600 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 512
[INF] No results found. Better luck next time!
```

### Expected Behavior:

```console
[INF] [ptr-fingerprint] Dumped DNS request for 46.84.0.173 domain=46.84.0.173.in-addr.arpa
;; opcode: QUERY, status: NOERROR, id: 38109
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;46.84.0.173.in-addr.arpa.	IN	 PTR

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
[DBG] [ptr-fingerprint] Dumped DNS response for 46.84.0.173.in-addr.arpa

;; opcode: QUERY, status: NOERROR, id: 38109
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;46.84.0.173.in-addr.arpa.	IN	 PTR

;; ANSWER SECTION:
46.84.0.173.in-addr.arpa.	300	IN	PTR	slc-a-origin-t.paypal.com.
46.84.0.173.in-addr.arpa.	300	IN	PTR	origin-t.paypal.com.

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 1232
[ptr-fingerprint:word-1] [dns] [info] 46.84.0.173 [slc-a-origin-t.paypal.com.,origin-t.paypal.com.]
```
