### ISSUE TITLE
New variable for xssprobe, new dsl function for xsscheck

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1507]
### Please describe your feature request:

A new variable and a new dsl function to use in all nuclei templates that is cheking for xss/html injection.
- Why
Will help and encourage template creators to use these functions, so the templates will be more concise and readable. Additionally, in this way, the scan results will be more accurate as they will not be blocked by Wafs.

- Template example 
https://github.com/projectdiscovery/nuclei-templates/blob/2165418c5900444855af0e1a923657b2f2e91ec5/vulnerabilities/generic/basic-xss-prober.yaml
- Reference
https://github.com/tomnomnom/hacks/tree/master/kxss
```
{{XSSProbe}}=smallrandstr>"'<
```

### Describe the use case of this feature:

```yaml
requests:
  - raw:
      - |
        GET /?param={{XSSProbe}} HTTP/1.1
        Host: {{Hostname}}
   matchers:
      - type: dsl
        name: xssprobe
        dsl:
            - xsscheck(body)
```
