### ISSUE TITLE
Introduce possibility to re-use matchers and extractors across multiple templates

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1510]
The same matchers and extractors used for identifying API tokens could be reused in multiple protocols. Without this functionality, these regular expressions have to be duplicated multiple times, for every relevant protocol, which is harder to maintain.

Example content [credentials-disclosure.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/0ff3afe771bed4f08165c286b52a7488474ceae7/exposures/tokens/generic/credentials-disclosure.yaml)

**Comment by forgedhallpass** [comment]
Another useful option/alternative would be if the extractors and matchers would accept `payload` data. Combined with support for transforming payloads, it would greatly improve situations like the above.

Examples:
```yaml
...
payloads:
  baseTokenPatterns:
    - access[_-]?token
    - account[_-]?sid
    - admin[_-]?email
    - adzerk[_-]?api[_-]?key
    - algolia[_-]?admin[_-]?key[_-]?1
    # ...
    # larger payloads lists could be loaded from file

transform:
  - baseTokenPatterns: 
    dsl:
      - {{map(baseTokenPatterns, concat("(?i)[\"']?", baseTokenPattern, "[\"']?[^\\S\r\n]*[=:][^\\S\r\n]*[\"']?[\\w-]+[\"']?"))}}

extractors:
  type: regex
  regex:
    - {{baseTokenPatterns}}
```

Or

```yaml
...
payloads:
  baseTokenPatterns:
    - access[_-]?token
    - account[_-]?sid
    - admin[_-]?email
    - adzerk[_-]?api[_-]?key
    - algolia[_-]?admin[_-]?key[_-]?1
    # ...
    # larger payloads lists could be loaded from file

extractors:
  type: dsl
  dsl:
    - {{matchRegex(map(baseTokenPatterns, concat("(?i)[\"']?", baseTokenPattern, "[\"']?[^\\S\r\n]*[=:][^\\S\r\n]*[\"']?[\\w-]+[\"']?")))}}
```
