### ISSUE TITLE
Altered request header

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1518]
It seems that nuclei alters the casing of certain headers.

Example:
The `http.server` module in Python 3 returns the `Content-type` header with a lower case `t`.

Writing a matcher for this, won't work because nuclei transforms the header. This is how it appears when the response is dumped as well.

Original response from `curl` and `burpsuite`:
```
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.9.9
Date: Wed, 19 Jan 2022 16:37:46 GMT
Content-type: text/html; charset=utf-8
Content-Length: 1638
```

Nuclei's response:
![image](https://user-images.githubusercontent.com/13679401/150175221-5edb76eb-7be7-4847-83d9-12e9276b0e29.png)

Example (generated) template:
```yaml
id: template-id
info:
  author: forgedhallpass
  name: Template Name
  severity: info
requests:
- matchers-condition: and
  matchers:
  - part: header
    type: word
    words:
    - 'Content-type:'
  - part: header
    status:
    - 200
    type: status
  raw:
  - |+
    GET / HTTP/1.1
    Host: localhost
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate
    Pragma: no-cache
    Cache-Control: no-cache
```
