### ISSUE TITLE
Strings literals between "{{" and "}}" are considered unresolved variables

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#1539]
### Nuclei version:
Dev

### Current Behavior:
`{{1+1}}` is detected as unresolved variable

### Expected Behavior:
`{{1+1}}` should be considered a string literal

### Steps To Reproduce:
```go
func TestUnresolvedVariablesCheck(t *testing.T) {
	tests := []struct {
		data string
		err  error
	}{
		{"{{1+1}}", nil},
	}
	for _, test := range tests {
		err := ContainsUnresolvedVariables(test.data)
		require.Equal(t, test.err, err, "could not get unresolved variables")
	}
}
```

### Anything else:
Probably a lexical analyzer should be considered (similar to https://github.com/projectdiscovery/nuclei/pull/1516)

**Comment by ehsandeep** [comment]
@Mzack9999 this turned out to be expected behaviour, anything under `{{ }}` marked as variable, to disable this check or to include literal string in template, `skip-variables-check: true` can be used with `issue-1497-lexer` branch.

```yaml
id: basic-raw-example
info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Test: {{1+1}}

    skip-variables-check: true
    matchers:
      - type: word
        words:
          - "Test is test matcher text"
```
