### ISSUE TITLE
Helper function randomization improvements

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1543]
### Please describe your feature request:

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        rand_base-1: {{rand_base(10)}}
        rand_base-2: {{rand_base(10)}}
        rand_char-1: {{rand_char()}}
        rand_char-2: {{rand_char()}}
        rand_int-1: {{rand_int(10)}}
        rand_int-2: {{rand_int(10)}}
        rand_text_alpha-1: {{rand_text_alpha(10)}}
        rand_text_alpha-2: {{rand_text_alpha(10)}}
        rand_text_alphanumeric-1: {{rand_text_alphanumeric(10)}}
        rand_text_alphanumeric-2: {{rand_text_alphanumeric(10)}}
        rand_text_numeric-1: {{rand_text_numeric(10)}}
        rand_text_numeric-2: {{rand_text_numeric(10)}}
```

Template shared above result into following HTTP requests containing similar random values that can be improved further.

```html
GET / HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Connection: close
rand_base-1: Cej434eyBK
rand_base-2: Cej434eyBK
rand_char-1: v
rand_char-2: v
rand_int-1: 208158958
rand_int-2: 208158958
rand_text_alpha-1: ZlifIwaGTZ
rand_text_alpha-2: ZlifIwaGTZ
rand_text_alphanumeric-1: SO49rmhwlm
rand_text_alphanumeric-2: SO49rmhwlm
rand_text_numeric-1: 4030448575
rand_text_numeric-2: 4030448575
Accept-Encoding: gzip
```
