### ISSUE TITLE
stop-at-first-match bug with extractors

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1546]
### Nuclei version:
2.5.9

### Current Behavior:
`stop-at-first-match: true`  extractor part gets counted as first match.

```
[sfm-bug] [http] [info] https://example.com/ [ECS (sab/56F2)]
```

### Expected Behavior:
Just use matchers for first match.  Especially with internal extractors.

```
[sfm-bug] [http] [info] https://example.com/ [ECS (sab/56F2)]
[sfm-bug] [http] [info] https://example.com/ [ECS (sab/56F2)]
```

Example template:

```yaml
id: sfm-bug

info:
  name: Stop at first match bug
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    stop-at-first-match: true
    extractors:
      - type: kval
        part: header
        kval:
          - "server"
```
