### ISSUE TITLE
Interactsh matcher issue with non interactsh matcher in OR condition

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1553]
### Nuclei version:
latest, dev

### Steps To Reproduce:
<details>
<summary>1. Test template</summary>

```yaml
id: test-interactsh

info:
  name: interactsh test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: or
    matchers:
      - type: word
        name: test1
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"

      - type: word
        name: test2
        words:
          - "GeoNet"
```
</details>

2. `echo https://geonet.shodan.io | nuclei -t test.yaml`

### Current Behavior:
```console
[test-interactsh:test1] [http] [info] https://geonet.shodan.io/api/geoping/c7q59cdmmud6hk3bbs50c84fjcedxydzc.oast.site
```
### Expected Behavior:
```console
[test-interactsh:test1] [http] [info] https://geonet.shodan.io/api/geoping/c7q59cdmmud6hk3bbs50c84fjcedxydzc.oast.site
[test-interactsh:test2] [http] [info] https://geonet.shodan.io/
```
