### ISSUE TITLE
Add support to traverse compressed archives for file templates

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#1578]
### Please describe your feature request:
Templates processing files should be able to unpack and analyze files within the archives automatically

### Describe the use case of this feature:
Process compressed archives without unpacking

```yaml
id: file-protocol-with-zip

info:
  name: File protocol support to process ZIP file
  author: pdteam
  severity: info

file:
  - extensions:
      - all

    archive: true
    matchers:
      - type: word
        words:
          - "Secret Text"

```
