### ISSUE TITLE
Bug in reading unsafe response data

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1613]
### Nuclei version:
latest & dev

### Current Behavior:
unsafe engine discard additional response outside of defined content length sent by server

### Expected Behavior:
real all the responses regardless of returned content length by sever
### Steps To Reproduce:

```console
HTTP/1.1 200 OK
content-type: image/png
content-length: 2383
last-modified: Mon, 24 Oct 2011 10:21:56 GMT
sap-dms: KW
ms-author-via: DAV
cache-control: max-age=3600
x-content-type-options: nosniff
sap-server: true
date: Thu, 17 Feb 2022 15:25:29 GMT
connection: Keep-Alive

PNG


IHDRB!m4}tEXtSoftwareAdobe ImageReadyqÉe<"iTXtXML:com.adobe.xmp<?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.0-c060 61.134777, 2010/02/12-17:32:00        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#" xmp:CreatorTool="Adobe Photoshop CS5 Macintosh" xmpMM:InstanceID="xmp.iid:3BC28BC733CE11E0A16DAC392E144EAE" xmpMM:DocumentID="xmp.did:3BC28BC833CE11E0A16DAC392E144EAE"> <xmpMM:DerivedFrom stRef:instanceID="xmp.iid:3BC28BC533CE11E0A16DAC392E144EAE" stRef:documentID="xmp.did:3BC28BC633CE11E0A16DAC392E144EAE"/> </rdf:Description> </rdf:RDF> </x:xmpmeta> <?xpacket end="r"?>ú.fXÃIDATxÚìYLG;kl øàGìF@!Å@Û¤AQLÚ4@RÅJ_ZõÁ¶´úÐF */í UUOP5©*YÀK«ô¡5j¥¦ª8/4j.HCÃi;@±;3íÝõÁÈHã]ÏÎüóÏ7ÿüóÏà§§wèg~C0ÁIÅ
¼>jË"Lð¶Æ¯¸Ýè)ÜrB¼Eûÿ"ó[Ó;èà¢­Cx¿/F B
äb!è÷ÈAW,uº%Ç:îËÐ\yüû¦8ûj{3TR«¼ùêiô%¨¯YDÝ]n/tÏþ¬cs«XÂéb|Ù5K$J*Àx8ÁØ\r/Í]#Ðr}<P¦ ÿT1gýö»N0üñ(¤¬©*dÅ<Ûä<4\²¹w2NK@»Ã2Qn¢`<ÐË ­6?fõlÍjïÏxù¶PRäEo\ãQIàW­èËÅ#B  òEª
oäÅmi)0ßw0YÊº½iÁa«®¾ÅsmÇ ÉKÅ½^|\AGGÉ¾ý92KØ`s¹¡Ã:ø_4P·á¢
u¶ø¿©d	;<Q(ö£Ë< ,¶É¹\I÷RXþuEvûèXÀRÉ(:¤LáüX~þ6¸æ<¬r½:Tr	XíÓ¡¥GíP»[òá²\Õm÷ïj4
%hBc?
ÖÛëåÐ´?&>¤P¸d²\ÉX£$JÎrûÍhº4RëáAÆôX -ÏÒmµOÁÙ®'l!³t[iæ×è¸6Y·Ç>³Ë3¡ÿ£J0Ö¾ê¬¤kÌ´­{&Ø&äFõá}ÄZCø´*.Og<ÐyoßÁ¡ÁÕÈ[CÿWÀxl'ãðLe2¸ðãÉ4tÜf«·'#sObÚò
0H6mtQë!Y&øì ½çK
8g`ÐéöëÃ 9;òÖ¥@}U.ÉÍÙ 	e¹f'{Ûì¸6>'·£«ÈëP/¦×w§2UÚt'rX@¿ÀqÂÕ+@@:fñáBvÆö6QR!Fíî¾; 2ß×Ì<z¶4#ÔiîIÎ¼ °üh©ÉãWWø`Ó2üÔÕçnå¡36§ é+³AÇÏúx
l³D.QÃºðL¯4À:¶ÿcg|Â×«À5Â¶K¯d"´{3@÷j¨sSxOqmç±ÙZ8¸c
døÏæ;£`ø±ÐrdÕuúO4m èRÁxrpcàþmµåÊÔRF?×ÌzÈEõü	Z®	Ä ôûrÁ|{tÊx´]óS1A³ªÖkËVÚç`_¯}[C¯¥TNJÈþÔ
ÂTh{¯Íün8{ÙFXc66ýÆºÂu¹àÀ,§	þ;ÆïjéµÖÊx!aÚî5Ö
ºüÿ7,q;Q«£×£;*,h
RE¬©£ÂÜ=ê<iØ_@E )±ðÐÇ	çÑëÅ)¨	ÛãWÌÝÃÐðsç7u¾n}r0~À¨u@â¿º¨LUsÌÖèÞ{fïebÔÑ5ã2ÎlämÇ±ñrø~}!0wê·ÀUñI"bÖ]ìë£I9;hÒâur«ÀK$jÀDä Køá8ý,\#ñ&¼oFÞ¢}1Fø¹º{s&áYv(|asØ
ÄAðØòóÓÿzR¤®ÁIEND®B`HTTP/1.0 400 Bad Request
date: Thu, 17 Feb 2022 15:25:29 GMT
pragma: no-cache
connection: close
content-length: 9654   
content-type: text/html
```

```yaml
id: template-id

info:
  name: Template Name
  author: geekboy
  severity: info
  description: description
  tags: tags

requests:
- raw:
  - |+
    GET /sap/public/bc/ur/Login/assets/corbu/sap_logo.png HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Onapsis' ICM CVE-2022-22536 assess tool
    Content-Length: 82646
    Connection: keep-alive

    {{repeat("A", 82642)}}

    GET / HTTP/1.1
    Host: {{Hostname}}


  unsafe: true
  matchers:
  - type: word
    part: body
    words:
    - This error page was generated by ICM
```

### Reference
- https://github.com/Onapsis/onapsis_icmad_scanner
