### ISSUE TITLE
[issue] Debug mode does not include POST body in the request 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#162]
Template used:- 

```yaml
id: test-template

info:
  name: test-template
  author: pdteam
  severity: info


requests:
  - raw:
      - |
        POST /test HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

        body=testing
```
Output:- 

```bash
echo https://e2hgie9hs7ekv8mhi5v6o3vaj1psdh.burpcollaborator.net | nuclei -t test.yaml -debug

POST /test HTTP/1.1
Host: e2hgie9hs7ekv8mhi5v6o3vaj1psdh.burpcollaborator.net
Connection: close
Connection: close
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

[INF] Dumped HTTP response for https://e2hgie9hs7ekv8mhi5v6o3vaj1psdh.burpcollaborator.net (test-template)

HTTP/1.1 200 OK
Content-Length: 53
Content-Type: text/html
Server: Burp Collaborator https://burpcollaborator.net/
X-Collaborator-Version: 4

<html><body>u8qjvbie59gj1og5tlpzzgzjjgz</body></html>
[INF] No results found for the template. Happy hacking!
```
