### ISSUE TITLE
[feature] Negative condition support for all matcher type

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#163]
To allow more flexibility to conditions, we can add negative support to all types of the matcher, for now only possible in `dsl` type with native support. 

`negative` supports two inputs, `true`, `false`, default, `negative` set to `false` if not used, and works with both HTTP and DNS templates. 

Example:- 

```yml
matchers:
  - type: word
    words:
      - "PHPSESSID"
    negative: true
```

```yml
matchers:
  - type: word
    name: cakePHP
    words:
      - "PHPSESSID"
    negative: true

  - type: word
    name: CF
    words:
      - "Cloudflare"
```

```yml
matchers:
  - type: status
    status:
      - 401
      - 403
      - 401
      - 500
    negative: true
```

```yml
matchers:
  - type: word
    words:
      - "X-Powered-By: PHP"
      - "PHPSESSID"
    negative: true
```

```yml
matchers:
  - type: size
    size:
      - 170
    negative: true
```

same goes with other matcher types as well.
