### ISSUE TITLE
Raw requests aren't routed correctly when a port is specified for a target

### ISSUE THREAD

**Issue by manuelbua** [projectdiscovery/nuclei#165]
When raw requests are defined there is no way for a rule to specify the port at the `Host` header line: this has the effect to route requests at the wrong port even if the input URL specifies one.

Sample rule:
```yaml
id: test-template

info:
  name: test-template
  author: pdteam
  severity: info


requests:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

        body=testing
```

Result:
```
echo 'http://localhost:9999' | ./nuclei -debug -v -t test.yaml

[INF] Dumped HTTP request for http://localhost:9999 (test-template)

POST / HTTP/1.1
Host: localhost
Connection: close
Connection: close
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

[WRN] Could not do request: POST http://localhost/ giving up after 2 attempts: Post "http://localhost/": dial tcp 127.0.0.1:80: connect: connection refused
[http-request] Sent HTTP request to http://localhost:9999
[INF] No results found for the template. Happy hacking!
```
