### ISSUE TITLE
Numeric matcher

### ISSUE THREAD

**Issue by bananabr** [projectdiscovery/nuclei#1650]
### Please describe your feature request:
* Provide a helper function to convert a dynamic variable into an integer value.
* Provide a matcher to match numeric comparison conditions like ```>,<,=,>=,<=```.

Helper functions to add:

```
to_number()
to_string()
```

### Describe the use case of this feature:
Sometimes all it takes to confirm a vulnerability is to check if a timestamp/version tag/build number is less than or equal to some reference value.

**Comment by ehsandeep** [comment]
Example Template:

```yaml
id: dsl-compare

info:
  name: example DSL compare template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/contact-form-7/readme.txt"

    matchers:
      - type: dsl
        dsl:
          - '{{to_string(version)}} < 5.3.2'

    extractors:
      - type: regex
        name: version
        group: 1
        regex:
          - "Stable tag: ([0-9.]+)"
```
