### ISSUE TITLE
Print extractor URL's only when it has expected value. 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#167]
Test template:- 

```yaml
id: pd-test
info:
  name: pd-test
  author: pd-test
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: kval
        kval:
          - server
```

CMD:-

```
$ chaos -silent -d hackerone.com -bbq -http-url | ./nuclei -t test.yaml -silent
```

Output:- 

```
[pd-test] [http] https://mta-sts.hackerone.com [GitHub.com]
[pd-test] [http] https://mta-sts.forwarding.hackerone.com [GitHub.com]
[pd-test] [http] https://mta-sts.managed.hackerone.com [GitHub.com]
[pd-test] [http] https://docs.hackerone.com [GitHub.com]
[pd-test] [http] https://support.hackerone.com [cloudflare]
[pd-test] [http] https://www.hackerone.com [cloudflare]
[pd-test] [http] https://api.hackerone.com [cloudflare]
[pd-test] [http] https://resources.hackerone.com
```

Expected output:- 

```
[pd-test] [http] https://mta-sts.hackerone.com [GitHub.com]
[pd-test] [http] https://mta-sts.forwarding.hackerone.com [GitHub.com]
[pd-test] [http] https://mta-sts.managed.hackerone.com [GitHub.com]
[pd-test] [http] https://docs.hackerone.com [GitHub.com]
[pd-test] [http] https://support.hackerone.com [cloudflare]
[pd-test] [http] https://www.hackerone.com [cloudflare]
[pd-test] [http] https://api.hackerone.com [cloudflare]
```

i.e return URL's for matched extractor only.
