### ISSUE TITLE
interactsh variable use to work with multiple placeholders

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1698]
### Please describe your feature request:

continuation of https://github.com/projectdiscovery/nuclei/issues/1360

Template with single `{{interactsh-url}}` placeholder works

`nuclei -t test.yaml -u https://geonet.shodan.io`

```yaml
id: test-interactsh

info:
  name: interactsh test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

    extractors:
      - type: kval
        kval:
          - interactsh-id
```

Template with multiple `{{interactsh-url}}` placeholder does not work. 

`nuclei -t test.yaml -u https://geonet.shodan.io`

```yaml
id: test-interactsh

info:
  name: interactsh test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
        Test: {{interactsh-url}}

    extractors:
      - type: kval
        kval:
          - interactsh-id
```
