### ISSUE TITLE
Implement Rule Engine

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#17]
Proposal of adding a rule engine so that for example the following matchers taken from the docs:

```
matcher:
  # match the body word
  - type: word
   # some words we want to match
   words: 
     - "[core]"
     - "[config]"
   # both words must be found in the response body
   condition: and
   #  we want to match request body (default)
   part: body
matcher:
  # match the status codes
  - type: status
    # some status codes we want to match
    status:
      - 200
      - 302
```

could be expressed as:

```
matcher: ('core', 'config') in response.body or response.status_code in (200, 302)
```
