### ISSUE TITLE
Configurable tech to tags mapping for automatic scan

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1749]
### Please describe your feature request:
The ability to map the wappalyzer tech to tags, which is currently [automated](https://github.com/projectdiscovery/nuclei/blob/7b13c663c3d8a177f15c976fa27477557575171e/v2/pkg/protocols/common/automaticscan/doc.go#L10) with no user control and may miss more relevant tags to execute when the technology name from wappalyzer is not the same as available tags in nuclei as [pointed here](https://twitter.com/0xw2w/status/1506167880160886784).

To improve this, an additional config file can be added under `.config/nuclei/` to intake custom tech to tags mapping which can be utilized by nuclei on the top of automated mapping.

```yaml
# This is an example tech to tags mapping config
# Value can be provided in `key:value` (tech:tags) format 

node.js : nodejs
atlassican: jira,confluence
```

This will help to cover all the cases missing in automated mapping.
