### ISSUE TITLE
Unable to use DSL functions on extractor that returns an array (multiple results)

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1763]
### Nuclei version:

2.6.5
### Current Behavior:

DSL functions only work when the extractor only has a single result. 
```yaml
id: testextractors

info:
  name: test extractors
  author: brenocss
  severity: critical
  description: test
  tags: test

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    extractors:
         - part: body
           name: extractorvariable
           internal: true
           type: regex
           regex:
             - "(?mi)extracthere\\d"

    matchers:
        - type: dsl
          dsl:
            - "print_debug(extractorvariable)"
            #- "contains(body, 'extracthere')"
          condition: or
```
```bash
echo 'http://localhost/only1result' | nuclei -t teste.yaml -debug-resp -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] Could not fetch latest releases: could not do request: Get "https://version-check.nuclei.sh/versions?v=2.6.5": context deadline exceeded
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[INF] print_debug value: [extracthere1]
[DBG] [testextractors] Dumped HTTP response (Truncated) http://localhost/only1result

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Content-Type: text/html
Date: Thu, 24 Mar 2022 16:08:26 GMT
Vary: Accept-Encoding

<script>
extracthere1
</script>
[2022-03-24 13:08:26] [testextractors:dsl-1] [http] [critical] http://localhost/only1result
```
```bash
 echo 'https://localhost/morethan1result' | nuclei -t teste.yaml -debug-resp -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[WRN] No parameter 'extractorvariable' found.
[DBG] [testextractors] Dumped HTTP response (Truncated) https://localhost/morethan1result

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Thu, 24 Mar 2022 16:10:36 GMT
Vary: Accept-Encoding

<script>
extracthere1
extracthere2
extracthere3
</script>
[INF] No results found. Better luck next time!
```
if we comment out the flag internal true and uncomment the second DSL we will notice that the extractor returns a kind of array and I believe that's why it's not possible to use print_debug or any other DSL
```bash
echo 'http://localhost/morethan1result' | nuclei -t teste.yaml -debug-resp -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[WRN] No parameter 'extractorvariable' found.
[DBG] [testextractors] Dumped HTTP response (Truncated) http://localhost/morethan1result

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Thu, 24 Mar 2022 16:13:21 GMT
Vary: Accept-Encoding

<script>
extracthere1
extracthere2
extracthere3
</script>
[2022-03-24 13:13:22] [testextractors:dsl-1] [http] [critical] http://localhost/morethan1result [extracthere1,extracthere2,extracthere3]
```

### Anything else:

It would be nice to have a way to choose specific indexes or even iterate through all the values
```golang
print_debug(variable[0])
print_debug(variable[...]) || print_debug(variable)
```
