### ISSUE TITLE
Add print() DSL Function

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1769]
### Please describe your feature request:

Very similar to print_debug() function, But with the same behavior of an extractor
### Describe the use case of this feature:

It would be useful if some extractors are only shown together with their matchers
```yaml
id: jsf-detection

info:
  name: JavaServer Faces Detection
  author: brenocss,Moritz Nentwig
  severity: info
  description: Searches for JavaServer Faces content on a URL.
  tags: jsf,tech,primefaces,richfaces

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 3
    cookie-reuse: true
    extractors:
      - type: regex
        name: primefaces-version 
        internal: true
        group: 1
        regex:
          - "(?mi)primefaces.*v=([0-9.]+)"
    matchers:
      - type: dsl
        name: primefaces
        dsl:
          - 'contains(body, "ln=primefaces")'
          - 'contains(body, "PrimeFaces.cw(") || contains(body, "PrimeFaces.ab(")'
          - 'contains(body, "window.PrimeFaces")'
          - 'print("Version:",primefaces-version)' ## NEW DSL FUNCTION 
        condition: or
      - type: dsl
        name: javafaces
        dsl:
          - 'contains(body, "javax.faces.resource") || contains(body, "javax.faces.ViewState")'
          - 'regex("JSF/(([0-9._-]+))",all_headers)'
          - 'contains(body,"ln=javax.faces")'
        condition: or
```
```zsh
echo 'http://redacted/login.jsf' | nuclei -t teste.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[VER] [jsf-detection] Sent HTTP request to http://redacted/login.jsf
[2022-03-25 14:54:19] [jsf-detection:primefaces] [http] [info] http://redacted/login.jsf [Version: 5.1]
[2022-03-25 14:54:19] [jsf-detection:javafaces] [http] [info] http://redacted/login.jsf

**Comment by ehsandeep** [comment]
@brenocss this is already possible with dsl extractor, for example:

```yaml
    extractors:
      - type: dsl
        dsl:
          - '"Server => "+ server'
```

```console
[basic-raw-example] [http] [info] https://geonet.shodan.io/ [Server => cloudflare]
```
