### ISSUE TITLE
Payload variable does not match with helpers

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1770]
Initial issue: https://github.com/projectdiscovery/nuclei/issues/555 

### Nuclei version:
dev

### Steps To Reproduce:

```yaml
id: payloads-matching

info:
  name: payload matcher test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST /search.php?test=query HTTP/1.1
        Host: {{Hostname}}
        Origin: http://testphp.vulnweb.com
        Content-Type: application/x-www-form-urlencoded
  
        searchFor={{fff}}&goButton=go

    payloads:
      fff:
        - "{{rand_base(5)}}"
        - "test"

    matchers:
      - type: word
        words:
          - "{{fff}}"
```

```
echo http://testphp.vulnweb.com | nuclei -t test.yaml
```

### Current Behavior:

```diff
echo http://testphp.vulnweb.com | nuclei -t ff.yaml -p http://127.0.0.1:8080

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[payload-matcher] [http] [info] http://testphp.vulnweb.com/search.php?test=query [fff=test]
```

### Expected Behavior:

```diff
echo http://testphp.vulnweb.com | nuclei -t ff.yaml -p http://127.0.0.1:8080

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
+[payload-matcher] [http] [info] http://testphp.vulnweb.com/search.php?test=query [fff=LocVq]
[payload-matcher] [http] [info] http://testphp.vulnweb.com/search.php?test=query [fff=test]
```
