### ISSUE TITLE
Adding variables support to templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1771]
### Please describe your feature request:

Variables will be usable globally within templates, allowing us to define an arbitrary variable name and assign a value to it, mostly using helper functions and existing global variables/DSLs, which can then be used anywhere as part of requests/matchers/extractors.

An example template with defined variables:  

```yaml
id: variables

info:
  name: variable example
  author: pdteam
  severity: info

variables:
  a1: {{rand_base(5)}}
  a2: {{md5(a1)}}
  a3: this_is_random_text
  a4: {{date("%Y-%M-%D")}}
  a5: {{rev(hostname)}}

requests:
  - raw:
      - |
        POST /search.php?test=query&date={{a4}} HTTP/1.1
        Host: {{Hostname}}
        Origin: http://testphp.vulnweb.com
        Content-Type: application/x-www-form-urlencoded

        searchFor={{a1}}&goButton=go

    matchers:
      - type: word
        words:
          - "{{a2}}"
          - "{{a2}}"
          - "{{a3}}"
          - "{{a4}}"
        condition: or
```

Support for variables will be protocol agnostic and can be used with any type of template.

### Describe the use case of this feature:

More flexibility to write complex + clean templates
