### ISSUE TITLE
A request is made for each payload even if the variable is not used in that request

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1772]
### Nuclei version:

2.6.5
### Current Behavior:

A request is made for each payload even if the variable is not used in that request

```yaml
id: BugMultipleRequest

info:
  name: Bug Multiple Request
  author: brenocss
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
    payloads:
      teste:
        - '1'
        - '2'
        - '3'
    matchers:
      - type: word
        words:
          - '1'
        condition: or
```
```zsh
nuclei -t teste1.yaml -u 'https://google.com' -duc -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[INF] [BugMultipleRequest] Dumped HTTP request for https://google.com

GET / HTTP/1.1
Host: google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Connection: close
Accept-Encoding: gzip

[2022-03-27 18:39:00] [BugMultipleRequest] [http] [info] https://google.com/ [teste=1]
[INF] [BugMultipleRequest] Dumped HTTP request for https://google.com

GET / HTTP/1.1
Host: google.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36
Connection: close
Accept-Encoding: gzip

[2022-03-27 18:39:00] [BugMultipleRequest] [http] [info] https://google.com/ [teste=2]
[INF] [BugMultipleRequest] Dumped HTTP request for https://google.com

GET / HTTP/1.1
Host: google.com
User-Agent: Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36
Connection: close
Accept-Encoding: gzip

[2022-03-27 18:39:00] [BugMultipleRequest] [http] [info] https://google.com/ [teste=3]
```
### Expected Behavior:
```zsh
nuclei -t teste1.yaml -u 'https://google.com' -duc -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.5 (latest)
[INF] Using Nuclei Templates 8.9.1 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[INF] [BugMultipleRequest] Dumped HTTP request for https://google.com

GET / HTTP/1.1
Host: google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Connection: close
Accept-Encoding: gzip
```

**Comment by brenocss** [comment]
nuclei -t teste1.yaml -u https://google.com -duc -debug-req
`Current Version: 2.6.6`
```yaml
id: BugMultipleRequest

info:
  name: Bug Multiple Request
  author: brenocss
  severity: info

requests:
  - raw:
      - |
        GET /usedonlyonce HTTP/1.1
      - |
        GET /{{teste}} HTTP/1.1
    payloads:
      teste:
        - '1'
        - '2'
        - '3'
    matchers:
      - type: word
        words:
          - '1'
        condition: or
   ```
   the first request should only have been executed once
