### ISSUE TITLE
openrdap panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1816]
### Nuclei version:
latest

### Current Behavior:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104e56bb8]

goroutine 62 [running]:
github.com/openrdap/rdap/bootstrap.(*Client).Lookup(0x140008e9e30, 0x140006c8150)
	/Users/geekboy/go/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/bootstrap/client.go:340 +0x578
github.com/openrdap/rdap.(*Client).Do(0x140008e92f0, 0x1400055e960)
	/Users/geekboy/go/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/client.go:150 +0x4f0
github.com/projectdiscovery/nuclei/v2/pkg/protocols/whois.(*Request).ExecuteWithResults(0x14000718750, {0x140008ea990, 0x9}, 0x140006c8000, 0x140006c8030, 0x140006c8060)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/whois/whois.go:89 +0xb4
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0x1400044c960, {0x140008ea990, 0x9})
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1c4
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x140000112b8, 0x140008efae0, 0x9, 0x140000e6160, 0x140008b9340, 0x140008ea8f8, 0x8, 0x0, {0x140008ea990, 0x9})
	/Users/geekboy/Github/nuclei/v2/pkg/core/execute.go:142 +0xd8
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	/Users/geekboy/Github/nuclei/v2/pkg/core/execute.go:129 +0x5f0
```

Example Template:

```yaml
id: whois-test

info:
  name: Whois Test
  author: test
  severity: info
  tags: whois

whois:
  - query: "{{Host}}"

    extractors:
      - type: json
        json:
          - '.Data["Expiration Date"][0]'
```
