### ISSUE TITLE
Issue with printing matched results with env variables in use

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1882]
### Nuclei version:
latest,dev

### Current Behavior:
All the env variables are printed as metadata of the results.

### Steps To Reproduce:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

self-contained: true
requests:
  - raw:
    - |
      GET https://example.com/{{PATH}} HTTP/1.1
      Host: example.com

    matchers:
      - type: status
        status:
          - 404
```

```
nuclei -t test.yaml -u https://example.com -ev
```
