### ISSUE TITLE
How variable reference

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#1899]
How to use the matched data as a variable for reference in the following situation?
```
action: screenshot
args: 
  to: /root/test/{{var1}}
  fullpage: true
```
