### ISSUE TITLE
Optional Matched line number display in file template with extractors

### ISSUE THREAD

**Issue by ayadim** [projectdiscovery/nuclei#1937]
hi, guys.
 thank u for this great tool. I have a little suggestion: I wish you add a flag to disable the printing line number. you can see the problem in my case: [https://i.imgur.com/x0Ma1Co.png](https://t.co/wBIO6YzYGY) 

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/8293321/166902626-dedb7a0e-1c49-4384-a61d-247b45ea6f3e.png">

I suggest that you limit the numbers or give the choice to the user to disable them.

:( all I need is a confirmation that some parameters exist in the -target file. 
my regards.

**Comment by ehsandeep** [comment]
@ayadim, thanks for reporting this. Could you confirm if you are using **matchers** or **extractors** in your custom template?

**Comment by ehsandeep** [comment]
For the time being, you can use matchers instead of extractors as `extractors` has default behavior to print line number.

```yaml
    matchers:
      - type: regex
        regex:
          - "(\\?|\\&|\\/)(pg|Lmage|open|callback|checkout|continue|data|dest|destination|dir|domain|feed|file|folder|forward)((_|-){0,})((url|to|uri|link|page|path|name|pg){0,1})(=)"
          - "(\\?|\\&|\\/)(r|from|go|host|html|image|img|load|login|redirect|logout|navigation|next|out|page|path)((_|-){0,})((url|to|uri|link|page|path|name|pg){0,1})(=)"
          - "(\\?|\\&|\\/)(to|link|port|redir|redirect|ref|reference|return|rt|show|site|target|to|uri|url|val|validate|view|window|back|redirect.cgi)((_|-){0,})((url|to|uri|link|page|path|name|pg){0,1})(=)"
          - "(\\?|\\&|\\/)([a-z0-9]+)((_|-){0,})((url|to|uri|link|page|path|name|pg){1,1})(=)"
```
