### ISSUE TITLE
TLS SNI overwrite in templates using request annotation

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1943]
### Please describe your feature request:
Since we have added the http request annotation feature (https://github.com/projectdiscovery/nuclei/pull/1805) to overwrite some HTTP information, it would be useful if we used this syntax to override TLS-SNI at the template level as well. 

### Describe the use case of this feature:
For the cases where TLS SNI is validated based on host header value, it would be useful to customize the TLS SNI value either using the [CLI flag](https://github.com/projectdiscovery/nuclei/issues/1883) or in the template as shared below:

```yaml
  - raw:
      - |
        @tls-sni: {{interactsh-url}}
        POST / HTTP/1.1
        Host: {{interactsh-url}}
  ```
