### ISSUE TITLE
Issue with query params as URL input if not encoded

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1956]
### Nuclei version:
latest

### Steps To Reproduce:

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET  HTTP/1.1
        Host: {{Hostname}}
```

```
nuclei -t test.yaml -debug-req -u http://google.com/test/?a=b
```

will result in as follows where everything after `?` gets discarded:

```console
[INF] [basic-raw-example] Dumped HTTP request for http://google.com/test/?a=b

GET /test/ HTTP/1.1
Host: google.com
```

Works as expected if `?` is urlencoded in the input:

```
nuclei -t test.yaml -debug-req -u http://google.com/test/%3fa=b
```

```console
[INF] [basic-raw-example] Dumped HTTP request for http://google.com/test/%3fa=b

GET /test/?a=b HTTP/1.1
```

Similar behavior can also be reproduced with `self-contained` templates.
