### ISSUE TITLE
Status 101 is not supported

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1993]
### Discussed in https://github.com/projectdiscovery/nuclei-templates/discussions/4299

<div type='discussions-op-text'>

<sup>Originally posted by **Sim4n6** May  4, 2022</sup>
It seems that no HTTP response is recorded in debug mode with the status code `101 Switching Protocols` in case of a request with the following headers: 

```
Connection: Upgrade
Sec-WebSocket-Key: U2NqiNSUA==
Sec-WebSocket-Version: 13
Upgrade: websocket
```
So, I was wondering is there a way to catch (extract or match) a **101** status code using nuclei scanner, please.

</div>

Example response:

```
HTTP/1.1 101 Switching Protocols
Server: SBS
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 5eDZZbOR6sddfLJc+jA8+DMLXS8=
Sec-WebSocket-Version: 13
```

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: status
        status:
          - 101
```
