### ISSUE TITLE
Disable printing defined template variables in the output

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1994]
### Nuclei version:
latest

### Current Behavior:
```
[basic-example] [http] [info] https://example.com [c=test3,a=test,b=test2]
```

### Expected Behavior:
```
[basic-example] [http] [info] https://example.com
```

### Steps To Reproduce:
```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info


variables:
  a: test
  b: test2
  c: test3

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: status
        status:
          - 200
```

```
echo https://example.com | nuclei -t test.yaml
```
