### ISSUE TITLE
File templates with multiple matchers not working

### ISSUE THREAD

**Issue by diego95root** [projectdiscovery/nuclei#2009]
### Nuclei version:

2.7.0

### Current Behavior:

File templates seem to not work right with multiple matching conditions. When using`matchers-condition: and` none of the matchers match anything but if swapped by an `or` then the different conditions get matched independently.

### Expected Behavior:

Properly match based on multiple conditions.

### Steps To Reproduce:

- Create `test.yaml`:

```yaml
id: passive-two-strings

info:
  name: Detect two strings
  author: test
  severity: medium

file:
  - extensions:
      - all
    
    matchers-condition: and
    matchers:
      - type: word
        part: all
        words:
          - 'STRING1'
      - type: word
        part: all
        words:
          - 'STRING2'
```

- Create `test.txt`:

```
STRING1
STRING2
```

- Run `nuclei -duc -t test.yaml -target test.txt`. You'll see that there are no matches. Now change `matchers-condition: and` by `matchers-condition: or`. You'll see that the two lines get matched independently now.
