### ISSUE TITLE
Consider the template Path when clustering

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2010]
Consider the template path when doing the clustering instead of defaulting to `BaseURL`.

Example:
```
http://example.com/one
http://example.com/two
http://example.com/three
```

Template: 

```yaml
id: test-example

info:
  name: test example
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{RootURL}}"
```

It would be expected that only one request would be made against `example.com`, instead of 3.

The `-debug` message should also be updated:

![image](https://user-images.githubusercontent.com/13679401/168826739-7794bc17-e3ea-477c-81f7-0a5f3a735cf9.png)
