### ISSUE TITLE
Validate flag does not consider passed in template

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2011]
Nuclei should validate the `faulty.yaml` template, instead of the public templates directory.

Use-cases:
* [x] `-t template.yaml`: validate `template.yaml`
* [x] `-t .`: validate all templates within the given (current) directory
* [x] without `-t`: validate all public templates

```sh
nuclei -t faulty.yaml -u http://example.com -validate   


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] All templates validated successfully
```

```yaml
id: http-missing-security-headers

info:
  name: HTTP Missing Security Headers
  author: socketz,geeknik,G4L1T0,convisoappsec,kurohost,dawid-czarnecki
  severity: info
  description: It searches for missing security headers, but obviously, could be so less generic and could be useless for Bug Bounty.
  tags: misconfig,generic

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 3
    matchers-condition: or
    matchers:
      - type: dsl
        name: strict-transport-security
        dsl:
          - "regex('(?i)strict-transport-security')"
        negative: true
        part: header
```
