### ISSUE TITLE
Warning messages are not showing by default

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2012]
Error message stating the incorrect usage of an existing DSL function is not shown without the `-debug` flag.

Execution without `-debug`:
```sh
nuclei -t faulty.yaml -u http://example.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.0 (latest)
[INF] Using Nuclei Templates 9.0.1 (latest)
[INF] Templates added in last update: 23
[INF] Templates loaded for scan: 1
[INF] No results found. Better luck next time!
```

Execution with `-debug`:
```sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.0 (latest)
[INF] Using Nuclei Templates 9.0.1 (latest)
[INF] Templates added in last update: 23
[INF] Templates loaded for scan: 1
[INF] [http-missing-security-headers] Dumped HTTP request for http://example.com

GET / HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[WRN] invalid DSL function signature. correct method signature "regex(arg1, arg2 interface{}) interface{}"
[DBG] [http-missing-security-headers] Dumped HTTP response http://example.com
```

```yaml
id: faulty

info:
  name: HTTP Missing Security Headers
  author: fhp
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 3
    matchers-condition: or
    matchers:
      - type: dsl
        name: strict-transport-security
        dsl:
          - "regex('(?i)strict-transport-security')"       
```

Related:
* #1295 
* #1166
