### ISSUE TITLE
Improve support or add validation for matcher types and supported matcher attributes

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2013]
All existing matcher attributes should apply to all existing matcher types. Where adding support is not possible for a well defined reason, validation should be added.

Example: the below templates should do the same:
```yaml
matchers:
      - type: dsl
        name: strict-transport-security
        dsl:
          - "regex('(?i)strict-transport-security', all_headers)"
        negative: true
```

```yaml
matchers:
      - type: dsl
        name: strict-transport-security
        dsl:
          - "regex('(?i)strict-transport-security', all_headers)"
        negative: true
        part: header
```
