### ISSUE TITLE
Variables support in headless protocol to support global variable/dsl mapping

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2021]
### Nuclei version:
latest

### Steps To Reproduce:

1. Save the below nuclei template
<details>
<summary>2. screenshot.yaml</summary>

```yaml
id: screenshot

info:
  name: Headless Screenshotter
  author: V0idC0de
  severity: info
  description: Takes a screenshot of the specified URLS.
  tags: headless,screenshot

variables:
  file: "{{Host}}"

headless:
  - steps:
      - action: setheader
        args:
          part: request
          key: "User-Agent"
          value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

      - action: navigate
        args:
          url: "{{BaseURL}}"

      - action: waitload
      - action: screenshot
        args:
          fullpage: true
          to: "{{file}}"
```
</details>

3. Run `echo https://example.com | nuclei -t screenshot.yaml -headless`

### Current Behavior:
A screenshot file gets created named `{{Host}}.png`

### Expected Behavior:
An output file named `example.com.png`

Similar to **HTTP / DNS / TCP** protocol, it is expected for [variables](https://nuclei.projectdiscovery.io/templating-guide/variables/) in headless protocol to support available global variable/dsl mapping to write more customizable templates.
