### ISSUE TITLE
Support for Timeout in the template

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#2024]
### Please describe your feature request:
In a few cases, the exploit requires more time to execute, so in those cases, it would be useful to explicitly include the wait-time or timeout in the template, as the default nuclei timeout is just five seconds.

### Describe the use case of this feature:
In order to match this template, I had to run it with a timeout of 25 seconds else it would result in a false negative.
https://github.com/projectdiscovery/nuclei-templates/pull/4434/files

**Comment by Mzack9999** [comment]
This can be implemented with request annotation:
```yaml
- raw:
      - |
        @timeout:5s
        POST /conf_mail.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        mail_address=%3B{{cmd}}%3B&button=%83%81%81%5B%83%8B%91%97%90M
```
