### ISSUE TITLE
Network templates error message is misleading when port is closed

### ISSUE THREAD

**Issue by wgill-tetra** [projectdiscovery/nuclei#2069]
### Nuclei version:
2.7.1

### Current Behavior:
```yaml
id: tcp-template

info:
  name: test
  author: test
  severity: info

network:
  - inputs:
      - data: "00000034320001010101010100010001000100010100203238005c7065726c2e65786500202d6573797374656d282777686f616d69272900" # whoami
        type: hex

    host:
      - "{{Host}}:5555"
```

```console
echo example.com | nuclei -t test.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.1 (latest)
[INF] Using Nuclei Templates 9.0.2 (latest)
[INF] Templates added in last update: 24
[INF] Templates loaded for scan: 1
[WRN] Could not make network request for example.com:5555: could not connect to server request: no address found for host
[INF] No results found. Better luck next time!
```

`Could not make network request for example.com:5555: could not connect to server request: no address found for host` This is misleading as

- Network request is sent out
- The address is found for the host

### Expected Behavior:
Error message "Network request for example.com:5555 timed out."

### Steps To Reproduce:
```
nuclei -u example.com -t test.yaml -v -debug
```

if you run `netstat -tan | grep 5555` while nuclei is running you can see the hostname was resolved and some request is being made to port 5555

### Anything else:
When the network request times out, the dump of the network request is not logged even though -debug is on.  

- [x] Display correct error in verbose mode
- [x] ~~Display outgoing TCP request in debug mode~~
