### ISSUE TITLE
Payload support for specific request

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2083]
### Please describe your feature request:

By default, payload applies on all the requests defined under the request block and executed sequentially, currently, there is no way to specify if we wanted to apply the payload rule on a specific request for the use cases like those shared in the below template that needs to be supported, possibly we can make us of request annotation to mark/identify the request where payload rule will be applicable.

```yaml
id: multiple-request-payload

info:
  name: Multiple Request Payload
  author: brenocss
  severity: info

requests:
  - raw:
      - | # Request 1
        @once
        GET /login HTTP/1.1
        Host: {{Hostname}}

      - | # Request 2 ( Request to Fuzz)
        POST /login_request HTTP/1.1
        Host: {{Hostname}}

        user=admin&password={{pass}}&csrf_token={{token}}

    cookie-reuse: true
    payloads:
      pass:
        - pass_1
        - pass_2
        - pass_3

    extractors:
      - type: regex
        name: csrf_token
        internal: true
        regex:
          - 'value="(.*?)">'

    matchers:
      - type: word
        words:
          - 'Welcome Admin'
```

### Describe the use case of this feature:

Fetch token from initial request to fuzz subsequent requests.
