### ISSUE TITLE
Request condition numbering issue when using with payloads

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2093]
When using `req-condition: true` with payloads, number counters are mapped to the actual request number and not based on the defined template request number that is expected, otherwise, counters can't be used.

```yaml
id: login-dome

info:
  name: Login-dome
  author: dome
  severity: high

requests:
  - raw:
      - |
        GET /login.php HTTP/1.1
        Host: {{Hostname}}

      - |
        POST /login.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        username={{usernames}}&password={{passwords}}

    attack: clusterbomb
    payloads:
      usernames:
        - "user"
        - "root"

      passwords:
        - "123456"
        - "111111"

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - status_code_8 == 404
```

```console
echo http://0.0.0.0:58704 | nuclei -t test.yaml -stats

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.1 (latest)
[INF] Using Nuclei Templates 9.0.4 (latest)
[INF] Templates added in last update: 10
[INF] Templates loaded for scan: 1
[login-dome] [http] [high] http://0.0.0.0:58704/login.php [usernames=root,passwords=111111]
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 58 | Matched: 1 | Errors: 0 | Requests: 8/8 (100%)
```
