### ISSUE TITLE
BUG - Nuclei doesn't follow redirect like HTTP 301/302

### ISSUE THREAD

**Issue by swisskyrepo** [projectdiscovery/nuclei#21]
Hello,

Is there any way to force nuclei to follow redirect? I came across the following cases recently where a nuclei template didn't trigger because nuclei stopped at the redirect. 

* 301 Moved Permanently
* 302 Found

You will find below a simple example of these kind of redirect:

```powershell
GET / HTTP/1.1
> Host: www.useless.domain
> User-Agent: curl/7.68.0
> Accept: */*

< HTTP/1.1 301 Moved Permanently
< Date: Mon, 13 Apr 2020 12:58:41 GMT
< Content-Type: text/html
< Location: https://interesting.host.domain/some/where
< Set-Cookie: some=cookie; path=/; HttpOnly; Secure
[...]
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html
```

The only mention of a redirect I found in the source code is the following https://github.com/projectdiscovery/nuclei/blob/481a7c0f549bcda5cb3de45754c91dbc1eae2571/internal/runner/runner.go#L56
https://github.com/projectdiscovery/nuclei/blob/481a7c0f549bcda5cb3de45754c91dbc1eae2571/internal/runner/runner.go#L57

> ErrUseLastResponse can be returned by Client.CheckRedirect hooks to control how redirects are processed. If returned, the next request is not sent and the most recent response is returned with its body unclosed. - https://golang.org/pkg/net/http/

Based on the docs, the redirected request is not sent.

This "feature" could be a great addition. Furthermore this request can be linked to https://github.com/projectdiscovery/nuclei/issues/10 (Added conditional redirects following or not following based on template config)

Thank you

**Comment by Ice3man543** [comment]
Hey @swisskyrepo, this feature was recently added to nuclei. Could you download the master and check if it suits your need?

It can be specified in the template request itself like this - 

```yaml
id: redirects-test

info:
  name: Redirects Test
  author: Ice3man
  severity: medium

requests:
  - method: GET
    # redirects specifies whether to follow redirects or not.
    redirects: true
    # max-redirects is max number of redirects to follow. Can be blank.
    max-redirects: 5
    path:
      - "{{BaseURL}}/"
    matchers:
      - type: status
        status: [301]
```

**Comment by swisskyrepo** [comment]
Hello, it seems to be working correctly using the following setup:

```powershell
./server/bin/nuclei -l /tmp/urls -t "server/wordlists/templates_nuclei/redirect-test.yaml" 

                       __     _ 
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ / 
   / / / / /_/ / /__/ /  __/ /  
  /_/ /_/\__,_/\___/_/\___/_/   v1                                                                        

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] [redirects-test] Loaded template Redirects Test (@Ice3man) [medium]
[redirects-test] https://REDACTED/SUB/index.html/ [AIzaSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxI]
```

```yaml
requests:
  - method: GET
    redirects: true
    max-redirects: 5
    path:
      - "{{BaseURL}}/"
    matchers:
      - type: regex
        part: body
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
    extractors:
      - type: regex
        part: body
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
```

Thank you for the great work ! :+1:
