### ISSUE TITLE
Support to access specific index from the array element

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2106]
### Note: confirm if accessing a specific index from the array element is possible. if yes, update the docs, if not we can look into adding support for it.
----

* [ ] Update existing templates
* [ ] Update the documentation

```yaml
id: testextractors

info:
  name: test extractors
  author: brenocss
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        name: multiple
        regex:
          - 'script src="(.*?)">'
        internal: true

      - type: regex
        name: single
        regex:
          - 'UA-49905813-1'
        internal: true

    matchers:
      - type: dsl
        dsl:
          - "print_debug(multiple)"
          - "print_debug(multiple0)"
          - "contains(multiple, 'test')"
        condition: and
```

- https://github.com/projectdiscovery/nuclei/issues/1763
- https://github.com/projectdiscovery/nuclei/discussions/3766
