### ISSUE TITLE
Template `variables` are not resolved when used with the `pipeline` and `threads` attributes

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2110]
```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
  test: abc

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{test}}"

    pipeline: true
```

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
  test: abc

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{test}}"

    threads: 2
```

```console
echo http://0.0.0.0:55823 | nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.1 (latest)
[INF] Using Nuclei Templates 9.0.6 (latest)
[INF] Templates added in last update: 0
[INF] Templates loaded for scan: 1
[WRN] [basic-example] Could not make http request for http://0.0.0.0:55823: unresolved variables found: test
[WRN] [basic-example] Could not execute request for http://0.0.0.0:55823: stop execution due to unresolved variables
```
