### ISSUE TITLE
The include-templates flag is not taken into account

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2124]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/1748

<div type='discussions-op-text'>

<sup>Originally posted by **Techbrunch** March 22, 2022</sup>
The contents of my `~/.config/nuclei/.nuclei-ignore` file:

```yaml
# ==| Nuclei Templates Ignore list |==
# ====================================
#
# This is default list of tags and files to excluded from default nuclei scan.$
# More details - https://nuclei.projectdiscovery.io/nuclei/get-started$

# tags is a list of tags to ignore execution for
# unless asked for by the user.

tags:
  - "fuzz"
  - "dos"

# files is a list of files to ignore template execution
# unless asked for by the user.

files:
  - cves/2020/CVE-2020-35489.yaml
```

I have the following entry in `.config/nuclei/config.yaml`:

```yaml
# templates to be executed even if they are excluded either by default$
include-templates:
  - fuzzing/iis-shortname.yaml
```

but when I run nuclei the template is not executed so it looks like that the template is not run because of the fuzz tag being ignored but the comment in the config says it should.</div>
