### ISSUE TITLE
Combine Wappalyzer with tech detection templates

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#2132]
### Please describe your feature request:

For now, we use nuclei tech detection templates as the only way to scan technologies on a target. However we could detect more technologies if we run wappalyzer as well and print out results like a nuclei template response.  Another approach would be, to automate a update on nuclei templates based on wappalyzer ( Suggested by @ehsandeep ). 

### Describe the use case of this feature:

Improve tech-detection templates

**Comment by brenocss** [comment]
Here i think would be a nice idea to implement 
 - [cdncheck](https://github.com/projectdiscovery/cdncheck) as a dsl_function 
  - [wappalyzergo](https://github.com/projectdiscovery/wappalyzergo) as a dsl_function 
  ```yaml
  id: dummy-example
info:
  name: usage of cdncheck and wappalyzergo
  author: mzack9999
  severity: none
  description: Checks if CNAME and A record is returned.

dns:
  - name: "{{FQDN}}"
    type: A
    class: inet
    recursion: true
    retries: 3

    matchers:
        - type: dsl
          dsl:
            - "print_debug(cdn_check(extractorvariable))"
   ```
