### ISSUE TITLE
Validate should give a warning when regex matcher uses words and words matcher uses regex

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#2154]
### Nuclei version:
2.7.2

### Current Behavior:
If when writing a template someone switches between word and regex matchers (or copy pastes a lot) they may make a mistake like this:
```
    matchers:
      - type: regex
        name: test
        part: body
        words:
          - "this wont match"
```
This passes validation but will never match.
The same applies to
```
    matchers:
      - type: word
        name: test
        part: body
        regex:
          - "this wont match"
```

### Expected Behavior:
A warning or something to alert the user of the error.
Perhaps another option is to avoid having two types "words" and regex" when the "type" of matcher should be what determines how they are used.
