### ISSUE TITLE
[feature] Handling ports input when conflicts with template

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#216]
**Is your feature request related to a problem? Please describe.**

The problem is, the port can be defined in a template or can be passed with input list as well, a problem arises when the port is submitted in both ways, at that time request get fails and that is expected as per current flow, but this can be handled by detecting port in the input list.
 
**Describe the solution you'd like**

This can be solved by prioritizing the input list. When the user input list contains `:port` values, then `:port` values in the template will be ignored. 

For example for the given template, if the user input is `echo https://x.x.x.x:7001 | nuclei -t example.yaml` 

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}:7001/console/login/LoginForm.jsp"
      - "{{BaseURL}}/console/login/LoginForm.jsp"
```

The expected probe/request will look like, as it will simply ignore the port values in the template prioritizing with user-submitted port value as input. 

```
https://x.x.x.x:7001/console/login/LoginForm.jsp
https://x.x.x.x:7001/console/login/LoginForm.jsp
```

The current implementation will probe like this:- 

```
https://x.x.x.x:7001:7001/console/login/LoginForm.jsp
https://x.x.x.x:7001/console/login/LoginForm.jsp
```
