### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by parrasajad** [projectdiscovery/nuclei#2163]
### Nuclei version:
dev latest

### Current Behavior:
```bash
echo https://example.com | ./nuclei -t test1.yaml,test2.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.2

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.2 (latest)
[INF] Using Nuclei Templates 9.0.6 (latest)
[INF] Templates added in last update: 0
[INF] Templates loaded for scan: 2
[INF] Templates clustered: 2 (Reduced 1 HTTP Requests)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10281ea18]

goroutine 66 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).Execute(0x0, 0x140005aa360, 0x140005a4bf0, 0x140005a4be0, 0x0)
        /Users/sajad/nuclei/v2/pkg/operators/operators.go:188 +0x38
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*Executer).Execute.func1(0x140005aa390)
        /Users/sajad/nuclei/v2/pkg/templates/cluster.go:183 +0xe8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0x140005aa390)
        /Users/sajad/nuclei/v2/pkg/protocols/http/request.go:285 +0x29c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0x140001d5080, {0x14000038708, 0x13}, 0x140001ef220, 0x0?, 0x0, 0x140005a5a68, 0x0?)
        /Users/sajad/nuclei/v2/pkg/protocols/http/request.go:604 +0x1dc4
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0x1400031cd20, 0xb}, 0x0, 0x140009fc780)
        /Users/sajad/nuclei/v2/pkg/protocols/http/request.go:270 +0x41c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0x140001d5080, {0x14000038708, 0x13}, 0x140009fc780, 0x140009fc750, 0x140001c49d8)
        /Users/sajad/nuclei/v2/pkg/protocols/http/request.go:322 +0x1b4
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*Executer).Execute(0x140009fc600, {0x14000038708, 0x13})
        /Users/sajad/nuclei/v2/pkg/templates/cluster.go:181 +0xc4
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0?, 0x0?, {0x14000038708?, 0x1400088e0e0?})
        /Users/sajad/nuclei/v2/pkg/core/execute.go:142 +0xf4
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        /Users/sajad/nuclei/v2/pkg/core/execute.go:129 +0x598
```

### Steps To Reproduce:
<details>
<summary>test templates</summary>

test1.yaml:

```yaml
id: test-template-1

info:
  name: test template 1
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{RootURL}}"
```

test2.yaml:

```yaml
id: test-template-2

info:
  name: test template 2
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{RootURL}}"
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
```
