### ISSUE TITLE
Interactsh-url doesn't work when using variables

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#2169]
### Current Behavior: 

The `interactsh-url` does not work when using under variables. For example:

```
variables:
  data: "{{interactsh-url}}"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?url=//{{data}}"
```

![Screenshot 2022-06-15 at 2 43 38 PM](https://user-images.githubusercontent.com/16654365/173790709-a52777b0-e994-4c17-a57d-18af194a7493.png)

### Expected Behavior:

`{{interactsh-url}}` should work as usual even when defined as a variable

### Notes
Use case at https://github.com/projectdiscovery/nuclei-templates/pull/4588
