### ISSUE TITLE
Payloads are not working with digest auth

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#2229]
### Current Behavior:
The payloads variables are not working with digest authentication

### Expected Behavior:
The payloads should work as usual even when defined as digest username/password.

### Steps To Reproduce:

```
requests:
  - raw:
      - |
        GET /admin HTTP/1.1
        Host: {{Hostname}}

    digest-username: "{{username}}"
    digest-password: "{{password}}"

    payloads:
      username:
        - admin
      password:
        - admin
```
