### ISSUE TITLE
Unsafe: true giving read i/o timeout error

### ISSUE THREAD

**Issue by tarunkant** [projectdiscovery/nuclei#2234]
Hello, I was trying to create a nuclei template which uses `unsafe: true`. On running the template I am getting `Could not execute request for https://[REDACTED].com: ReadStatusLine: read tcp XX.XX.XX.XX:62594->XX.XX.XX.XX:443: i/o timeout`

### Nuclei version:
2.7.3

### Current Behavior:
Error: `Could not execute request for https://[REDACTED].com: ReadStatusLine: read tcp 192.168.XXX.XXX:62594->XX.XX.XX.XX:443: i/o timeout`

### Expected Behavior:
The template should run without error

### Steps To Reproduce:
I created this template:

```
id: testing

info:
  name: testing
  author: XXX
  severity: info
  tags: vulnerability

requests:
  - raw:
      - |
        GET / HTTP/1.1
        {{hex_decode('1d')}}Host: facebook.com
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en-US;q=0.9,en;q=0.8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
        Connection: close
        
    unsafe: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'example'

      - type: status
        status:
          - 200
```

**Command 1:**

```
nuclei -u "https://google.com" -t ./testing.yaml -vv -debug
```

**Output:**

```
[WRN] [testing] Could not execute request for https://google.com: ReadStatusLine: read tcp [2409:4043:4b8d:f769:a0be:b769:2574:bbd2]:62743->[2404:6800:4009:809::200e]:443: i/o timeout
```

**Command 2:**
Here, if you try with example.com, it will work but it will break if you use `-proxy` flag

```
nuclei -u "https://example.com" -t ./testing.yaml -vv -debug -proxy "http://127.0.0.1:8080"
```

**Output:**

```
[WRN] [testing] Could not execute request for https://example.com: ReadStatusLine: read tcp 127.0.0.1:62782->127.0.0.1:8080: i/o timeout
```

**Comment by ehsandeep** [comment]
@tarunkant it's a syntax issue within template, see the additional `+` in line three, and also shown in the examples here for the templates using `unsafe` - https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#unsafe-http-requests

```yaml
requests:
  - raw:
      - |+
        GET / HTTP/1.1
        {{hex_decode('1d')}}Host: facebook.com
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en-US;q=0.9,en;q=0.8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
        Connection: close
```
