### ISSUE TITLE
[issue] raw request adds extra  headers

### ISSUE THREAD

**Issue by un-fmunozs** [projectdiscovery/nuclei#224]
**Describe the bug**
RAW request should just have what is included on the template, currently there are two extra "Connection: close" headers and UserAgent added.

**Nuclei version**
[INF] Current Version: 2.1.0

**Screenshot of the error or bug**
```
$ echo https://beford.org | /home/buggie/go/bin/nuclei -t new.yaml -H "Host: xxx" -debug

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] [test] Loaded template  (@)
[INF] Dumped HTTP request for https://beford.org (test)

GET / HTTP/1.1
Host: google.com
Connection: close
Connection: close
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)

[INF] Dumped HTTP response for https://beford.org (test)

HTTP/1.1 301 Moved Permanently
Connection: close
Content-Length: 220
Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: public, max-age=2592000
Content-Type: text/html; charset=UTF-8
Date: Wed, 12 Aug 2020 09:47:11 GMT
Expires: Fri, 11 Sep 2020 09:47:11 GMT
Location: https://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>

[INF] No results found. Happy hacking!


```

Template:
```
id: test

requests:
  - raw:
      - |
          GET / HTTP/1.1
          Host: google.com

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 206
      - type: word
        words:
          - Test
        part: all

```

Expected behaviour: No connection or User-Agent headers on the HTTP Request.
