### ISSUE TITLE
Can't hit rule after declaring more templates

### ISSUE THREAD

**Issue by LubinLew** [projectdiscovery/nuclei#2242]
**ENV**
CentOS 7 x64
Nuclei Engine `2.7.3`
Nuclei Templates `9.0.8`

**TEST**

Target : `misconfiguration/unauthenticated-nacos-access.yaml`

```yaml
# config1
templates:
  - misconfiguration/

exclude-tags: network

exclude-templates:
  - misconfiguration/xss-deprecated-header.yaml
  - misconfiguration/http-missing-security-headers.yaml
```
Hit `misconfiguration/unauthenticated-nacos-access.yaml`

```bash
nuclei -ni -config conf.yml -u http://124.204.76.213:12185/

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.3 (latest)
[INF] Using Nuclei Templates 9.0.8 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 195
[INF] Templates clustered: 26 (Reduced 23 HTTP Requests)
[2022-06-29 15:06:32] [unauthenticated-nacos-access] [http] [critical] http://124.204.76.213:12185/nacos/v1/auth/users?pageNo=1&pageSize=9
```
---

If I add more templates, got `No results found`.

```yaml
# config2
templates:
  - misconfiguration/
  - cves/
  - cnvd/
  - vulnerabilities/

exclude-tags: network

exclude-templates:
  - misconfiguration/xss-deprecated-header.yaml
  - misconfiguration/http-missing-security-headers.yaml
```

```bash
nuclei -ni -config conf.yml -u http://124.204.76.213:12185/

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.3 (latest)
[INF] Using Nuclei Templates 9.0.8 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 1879
[INF] Templates clustered: 51 (Reduced 39 HTTP Requests)
[INF] No results found. Better luck next time!
```
