### ISSUE TITLE
Fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2257]
### Steps To Reproduce:
```sh
docker run -it -v /root:/root --rm projectdiscovery/nuclei -t /root/test.yaml -l input_urls.txt -stats
```

test.yaml
```yaml
id: test

info:
  name: test
  author: tester

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
```

This ticket was created based on `p1734543`'s [message on Discord](https://discord.com/channels/695645237418131507/700092442661355602/993337143105683468).

[full_stack_trace.txt](https://github.com/projectdiscovery/nuclei/files/9047462/full_stack_trace.txt)
[input_urls.txt](https://github.com/projectdiscovery/nuclei/files/9038499/input_urls.txt)
