### ISSUE TITLE
[issue] Connection header update and duplicate issue 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#226]
**Describe the bug**

Run this template, 
```yaml
id: testing-http

requests:
  - raw:
      - |
          GET / HTTP/1.1
          Host: {{Hostname}}
          Connection: keep-alive
```

`Connection: keep-alive` will be updated with `Connection: close` in the request. 

```
GET / HTTP/1.1
Host: franhem6qjrzkyfje9qic0a6ux0ood.burpcollaborator.net
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
Connection: close
```

and with BaseURL HTTP request:- 

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    headers:
      Connection: keep-alive
``` 
It adds another header along with having a default one. 

```
GET / HTTP/1.1
Host: franhem6qjrzkyfje9qic0a6ux0ood.burpcollaborator.net
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
Connection: close
Accept: */*
Accept-Language: en
Connection: keep-alive
Accept-Encoding: gzip
```
**Nuclei version**
2.1.0

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
