### ISSUE TITLE
Implement Option to allow enriched/modified templates

### ISSUE THREAD

**Issue by c-f** [projectdiscovery/nuclei#2265]
### Please describe your feature request:

Option to allow enriched/modified templates to be processed by nuclei. 
Currently it is not possible to use a template - even if nuclei do not require the field to be running .

### Describe the use case of this feature: 

Since Oct 2021 it is no longer possible to use customized/enriched templates (https://github.com/projectdiscovery/nuclei/commit/0cabce518f8f97204c0b406376b9c95209a54129#diff-7375be6a2fb2f554533f4e370078c9ba80c03634a026f357336471e7e59d672fR126). 

For internal usage and other options it would be great if enriched templates would not be declined completely by nuclei. 

The following minimal template - cannot be run by nuclei - thus all required fields are available, since the field `custom` is not defined in the template.Template. 
```yaml
# modified from https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/generic/oob-param-based-interaction.yaml
# minimal example
---
id: oob-param-based-interaction
info:
  name: Parameter Based Generic OOB Interaction
  author: pdteam
  severity: info
requests:
- path: ["{{BaseURL}}/lel?u={{interact-sh}}"]
  matchers:
  - type: word
    part: interactsh_protocol
    name: http
    words: [http]
custom:
 internal-reference: "superlel"
 reviewed: "2022-04-04"
```

When validate nuclei will log the following error - even though name, author is available. The reason for this is the method 
`yaml.UnmarshalStrict`, which do not populate the template if other fields were found. 

```bash
nuclei -validate -t ./52384a97-d0b7-471f-b731-bba05f593cb8.yaml -sc     

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[ERR] Syntax warnings for template <location>/52384a97-d0b7-471f-b731-bba05f593cb8.yaml: yaml: unmarshal errors:
  line 20: field <custom> not found in type templates.Alias
[ERR] Error occurred loading template <location>/52384a97-d0b7-471f-b731-bba05f593cb8.yaml: mandatory 'name' field is missing, mandatory 'author' field is missing, mandatory 'id' field is missing
[FTL] Could not validate templates: errors occured during template validation

```
<details>
<summary> If 'custom' field is removed - template works as intended (click to see) </summary>
 
```bash 
yq  'del(.custom)' 52384a97-d0b7-471f-b731-bba05f593cb8.yaml > no_custom.yaml; nuclei -validate -t ./no_custom.yaml -sc


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] All templates validated successfully
```
</details>

**Comment by ehsandeep** [comment]
@c-f we can fix the issue to actually update the error details, but we have a dedicated field named `metadata` to include/enrich **arbitrary** fields/information in the template, for example:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  metadata:
    internal-reference: "superlel"
    reviewed: "2022-04-04"

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "This is test matcher text"
```

**Comment by c-f** [comment]
Thanks for the hint. But this only works in a limited way. 

Complex types cannot be representable (since only strings are allowed). Furthermore we use metadata for ID references and do not want to pollute our internal information within responses.

**Comment by ehsandeep** [comment]
@c-f do you have types of examples to share that can not be achieved with metadata? please have a look at https://github.com/projectdiscovery/nuclei/pull/1649 which enhanced the metadata attribute to support all possible types.

Also the idea of metadata attribute that allows arbitrary fields to **NOT** have arbitrary attribute in the template which does not help with various [automation](https://github.com/projectdiscovery/nuclei/blob/master/nuclei-jsonschema.json) and pre-defined checks we can have.

**Comment by c-f** [comment]
Ah i did not notice #1649 -  my bad -  it would indeed allow arbitrary structs in the field. Unfortunately i think this is still the wrong field for our use cases.

### Integration and Processes 
One problem we have with metadata is, that metadata is not exclusively used by us, but also defined by any other authors. This means metadata requires to be merged and trusted (if used in a automated ways). 

This results in several challenges: 
- Harder diffing. If new changes are made (by projectdiscovery or any other), we need to diff and check whether we accept the changes or not. 
- Variable pollution. It is no longer possible to easily verify who the author was. Especially when the variables used for internal tooling - input requires to be trusted or verified. 
- Output pollution. Currently we use metadata to include autogenerated  reference IDs, which will also be included in the output of nuclei. Information of tooling would should pollute the output and is not wanted. 

### Stability & loosely coupled compontents
It's easier to maintain a separate field (e.g. for a separate tool) than to integrate in the current structure. If the structure changes or requires additional syntax are enforced (e.g. "shodan-query" must be a string ) than the tool must be changed too. 

Of course you can always use "higher structures" . However then you need to always convert myconfig into a nuclei-template and this is annoying. 

```yaml
myconfig:
 nuclei: 
  <nuclei-template>:
 crawler:
   <crawler-specifc-config>
  osint: 
    <other-config>
```

### Semantics 
Some attributes do not fit (in my opinion) in the metadata, since they are not related to the vulnerability but to the template and/or the product in general:

```yaml
  uuid: <uuid>
  origin:
    repo: https://github.com/projectdiscovery/nuclei-templates
    hash: d23bfa04623ac22a67b9b27e12d91f7809ea2016
    path: cves/2018/CVE-2018-9845.yaml
    id: "CVE-2018-9845"
 
 opsec_explotiation: 
  - < :) > 
  - < :D >
 detection: 
  iocs: 
   - query:  <>
    ref: <>   
  http: 
     query: <query-
     requires: <scheme-ref>
   app_log: 
   
```
