### ISSUE TITLE
Error handling update with validation

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2269]
### Nuclei version:
dev,latest

### Current Behavior:
Misleading error details while validating the template.

### Expected Behavior:
Correct error detail

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matcherss:
      - type: word
        words:
          - "This is test matcher text"
```

In above template, I've used `matcherss` instead of `matchers`

### Steps To Reproduce:

```console
nuclei -t test.yaml -validate

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.

[ERR] Syntax warnings for template /Users/geekboy/Github/nuclei-templates/test.yaml: yaml: unmarshal errors:
  line 13: field matcherss not found in type http.Request
[ERR] Error occurred loading template  /Users/geekboy/Github/nuclei-templates/test.yaml: mandatory 'name' field is missing, mandatory 'author' field is missing, mandatory 'id' field is missing
[FTL] Could not validate templates: errors occured during template validation
```

See the error line indicating:

>  `mandatory 'name' field is missing, mandatory 'author' field is missing, mandatory 'id' field is missing` as error.
