### ISSUE TITLE
Helper function for IP Formats

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2271]
### Please describe your feature request:
Helper function to support https://github.com/projectdiscovery/mapcidr#ip-formats

### Describe the use case of this feature:
To write templates including IP in various formats to fuzz/bypass multiple IP-based protection.

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        X-IP: {{ips}}
        Origin: {{BaseURL}}

    payloads:
      ips:
        - "{{ip_format("127.0.1.0", 3)}}"
        - "{{ip_format("169.254.169.254", 4)}}"
        - "{{ip_format(ip, 4)}}"
```
