### ISSUE TITLE
[Feature] Create a matcher for the response time

### ISSUE THREAD

**Issue by Nadino92** [projectdiscovery/nuclei#230]
I'd like to have a matcher for the response time, for instance to catch timeouts

**Comment by Mzack9999** [comment]
Now available using DSL matcher as `duration` (integer). It's highly susceptible to false positives therefore it should be used for specific scenarios where the response time is a crucial metric.

**Comment by bauthard** [comment]
@Nadino92 FYI, this has been added into master code using DSL matcher, example template:- 

```yaml
id: time-test

info:
  name: DSL duration
  severity: none

requests:
  - raw:
      - |
        GET /slow HTTP/1.1

    matchers:
      - type: dsl
        # int64 - so 1 => one second
        dsl:
          - 'duration>=1'
```
