### ISSUE TITLE
 uniq and sort helper function

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2305]
### Please describe your feature request:
New helper functions:

- [x] sort
- [x] uniq

Helper example:

```yaml
{{sort(list)}}
{{uniq(list)}}
```

The list is an array of data in a variable.

Exampel template:

```yaml
requests:
  - method: GET
    path:
      - "{{RootURL}}"
      - "{{RootURL}}{{uniq(endpoint)}}/phpinfo.php"

    extractors:
      - type: regex
        name: endpoint
        group: 1
        regex:
          - '(/([a-z0-9A-Z-_.]+/)*([a-z0-9A-Z-_]+)/)'
        internal: true

    iterate-all: true
    redirects: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "phpinfo()"
```
