### ISSUE TITLE
TestDslExpressions Invalid token: ';'

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2317]
@ehsandeep 
test code:
```
`"contains(body,\"if($('return_123);alert(/testvul/);//'\")"`:                               true,
```
### Result
```
=== RUN   TestDslExpressions/"contains(body,\"if($('return_123);alert(/testvul/);//'\")"
    dsl_test.go:344: 
        	Error Trace:	dsl_test.go:344
        	            				dsl_test.go:272
        	Error:      	Received unexpected error:
        	            	Invalid token: ';'
        	Test:       	TestDslExpressions/"contains(body,\"if($('return_123);alert(/testvul/);//'\")"
        	Messages:   	Error while compiling the "\"contains(body,\\\"if($('return_123);alert(/testvul/);//'\\\")\"" expression
    --- FAIL: TestDslExpressions/"contains(body,\"if($('return_123);alert(/testvul/);//'\")" (0.00s)


```

**Comment by Mzack9999** [comment]
You need to use single quotes to wrap strings, and escape correctly single quotes within a string, for example:
```yaml
id: application-yaml

info:
  name: test
  author: test
  severity: info
  description: test
  tags: misconfig

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers:
      - type: dsl
        dsl:
          - "contains(body,'if($(\\'return_123);alert(/testvul/);//\\'')"
  ```
