### ISSUE TITLE
Notify users if the passed in template will not be executed

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2320]
The user is not notified that the template will not be executed. We should let them know that headless templates require the `-headless` flag.

```sh
nuclei -t headless.yaml -u https://www.instagram.com/jerkingmad -v
```

```yaml
id: template-id
info:
  name: Template Name
  author: forgedhallpass
  severity: info
  description: description
  reference:
    - https://
  tags: tags

headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload
      
    matchers:
      - type: word
        part: body
        words:
          - "Sorry, this page isn't available."
```

![image](https://user-images.githubusercontent.com/13679401/179970286-d7c69422-1487-45ce-9b45-e828b06fbdd5.png)
