### ISSUE TITLE
The debug flags do not work correctly with headless templates

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2328]
Request and response headers are not shown when the `-debug`, `-debug-req`, `-debug-resp` flags are provided.

The headless action execution messages should be formatted (e.g. by adding `[DBG]` prefix) and some context should also be given (e.g. "Executing headless action: waitload").

It would also be nice to show the actual URL, instead of `{{BaseURL}}`.

```sh
nuclei -t headless.yaml -u https://twitter.com -headless -debug
```

```yaml
id: headless
info:
    name: Headless Example
    severity: info
    author: forgedhallpass

headless:
  - steps:
      - action: navigate      
        args:
          url: "{{BaseURL}}"
      - action: waitload
```

![image](https://user-images.githubusercontent.com/13679401/180225308-ac6423bf-d51f-4d99-94e4-a405b0430bce.png)
