### ISSUE TITLE
resolve / resolve_all helper functions

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2341]
New helpers for DNS resolution enable writing more complex nuclei templates.

- [x] resolve

Helper example:

```yaml
{{resolve ("hackerone.com")}} # Resolve hackerone.com, returns single IPv4 A record (IPv4 is being default option here)
{{resolve ("hackerone.com", 6)}} # Resolve hackerone.com, returns single IPv6 A record
{{resolve ("hackerone.com", 4,6)}} # Resolve hackerone.com and returns array of signle IP v4/v6 A record for each
```

Example template using `resolve` helper:

```yaml
id: test

info:
  name: test template
  author: 0xAwali
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        X-Forwards-For: {{resolve(Host)}}
```

```yaml
id: test

info:
  name: test template
  author: 0xAwali
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{resolve(Host, 6)}}
```
