### ISSUE TITLE
Make extracted values available both as a variable and as a result

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2364]
Currently if someone would like to use an extracted value as a variable, and both display it in the results, they need to duplicate the extractor (e.g. https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/csrfguard-detect.yaml#L63). Besides not being elegant, it's also harder to write and maintain.

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{browser}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{browser}} HTTP/1.1
        Host: {{Hostname}}

    redirects: true
    extractors:
      - type: regex
        name: browser
        part: header
        internal: true
        group: 1
        regex:
          - "Server: ([a-zA-z]+)"

      - type: kval
        kval:
          - browser
```

Test against `python -m http.server`

**Comment by forgedhallpass** [comment]
It seems that in certain cases it work though, when there are some matchers referencing indexed values, and the `req-condition` is set to `true`.

Example:

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

    redirects: true
    req-condition: true
    matchers:
      - type: dsl
        name: timer
        dsl:
          - "print_debug(concat('first:', duration_1))"
          - "print_debug(concat('second:', duration_2))"
          - "print_debug(concat('third:', duration_3))"
          - duration_3 < 1
        condition: and

    extractors:
      - type: regex
        name: srvr
        part: header
        internal: true
        group: 1
        regex:
          - "Server: ([a-zA-z]+)"

      - type: kval
        kval:
          - srvr
```

![image](https://user-images.githubusercontent.com/13679401/181747786-afa04bf2-6295-4cac-88a3-44f4c7afdf23.png)
