### ISSUE TITLE
Ambiguous variable resolution

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2367]
There is some ambiguity in the variable resolution, when a user declares an extractor with a name that is reserved.
e.g. If a user defines a variable called `server`, that is also a reserved word, the internal evaluation in the request uses the user defined extracted value, but the result displays the value of the reserved word.

An error clear error message should notify about the ambiguity, and preferably all "reserved" word should be displayed, like in case of the DSL method signatures (see:  #1295)

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

    redirects: true
    matchers:
      - type: dsl
        name: timer
        dsl:
          - true # required because of a bug: https://github.com/projectdiscovery/nuclei/issues/2364#issuecomment-1199159688

    extractors:
      - type: regex
        name: srvr
        part: header
        internal: true
        group: 1
        regex:
          - "Server: ([a-zA-z]+)"

      - type: kval
        kval:
          - srvr
```

![image](https://user-images.githubusercontent.com/13679401/181748720-ad368e47-333b-40c9-9084-c3d8515c88ce.png)

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{server}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{server}} HTTP/1.1
        Host: {{Hostname}}

    redirects: true
    matchers:
      - type: dsl
        name: timer
        dsl:
          - true # # required because of a bug: https://github.com/projectdiscovery/nuclei/issues/2364#issuecomment-1199159688

    extractors:
      - type: regex
        name: server
        part: header
        internal: true
        group: 1
        regex:
          - "Server: ([a-zA-z]+)"

      - type: kval
        kval:
          - server
```

![image](https://user-images.githubusercontent.com/13679401/181748995-2606f5ea-e45b-47a3-af36-651c9a9b184d.png)

Related: https://github.com/projectdiscovery/nuclei/issues/2364#issuecomment-1199159688
