### ISSUE TITLE
Rate limit per minute doesn't work in some cases in v2.7.5

### ISSUE THREAD

**Issue by brincowale** [projectdiscovery/nuclei#2375]
Since version 2.7.5 sometimes I'm getting an error, other times it's frozen after the first request. The error is not reproducible in version 2.7.4. The error occurs with `-rlm 10` but not with `-rlm 20`

**Log**:
```
PS C:\templates\example> nuclei -t example.yaml -rlm 10 -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.5 (latest)
[INF] Using Nuclei Templates 9.1.3 (latest)
[INF] Templates added in last update: 40
[INF] Templates loaded for scan: 1
[VER] [example] Sent HTTP request to https://example.com/test1
[WRN] [example] Could not execute request for : context deadline exceeded
[INF] No results found. Better luck next time!
PS C:\templates\example> 
```

**Minimal example**:
```yaml
id: example

info:
  name: example
  author: brincowale

self-contained: true
requests:
  - raw:
      - |
        GET https://example.com/{{test}} HTTP/1.1

    attack: batteringram
    payloads:
      test: 
        - test1
        - test2
        - test3
        - test4
        - test5
```
