### ISSUE TITLE
Trailing slash after file name with raw http template format

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2377]
### Nuclei version:
dev,master

### Current Behavior:
```console
echo https://example.com/test.html | nuclei -t rr.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.5 (latest)
[INF] Using Nuclei Templates 9.1.3 (latest)
[INF] Templates added in last update: 40
[INF] Templates loaded for scan: 1
[INF] [test] Dumped HTTP request for https://example.com/test.html/

GET /test.html/ HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2919.83 Safari/537.36
Connection: close
Accept-Encoding: gzip

[INF] No results found. Better luck next time!
```

### Expected Behavior:

```console
GET /test.html HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2919.83 Safari/537.36
Connection: close
Accept-Encoding: gzip
````

### Steps To Reproduce:
```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
```

```
echo https://example.com/test.html | nuclei -t rr.yaml -debug-req
```

**Comment by Ice3man543** [comment]
@ehsandeep the same behaviour occurs when using base http format.

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

requests:
  - path: 
      - "{{BaseURL}}/"
```

We need to fix this for the http module as a whole as it's not specific to raw http format
