### ISSUE TITLE
Request condition issue with base http template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2394]
### Nuclei version:
dev,latest

### Current Behavior:
multiple base http request can not be used with request condition.

### Expected Behavior:
request condition using with base http template. 

### Steps To Reproduce:

<details>
<summary>base-template.yaml</summary>

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

  - method: GET
    path:
      - "{{BaseURL}}/test"

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200
          - status_code_2 == 404
        condition: and
```
</details>

<details>
<summary>raw-template.yaml</summary>

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /test HTTP/1.1
        Host: {{Hostname}}

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200
          - status_code_2 == 404
        condition: and
```
</details>

```console
echo https://example.com | nuclei -t raw-template.yaml

[basic-example] [http] [info] https://example.com/test
```

```console
echo https://example.com | nuclei -t base-template.yaml

[INF] No results found. Better luck next time!
```
