### ISSUE TITLE
tls: no renegotiation (sni) issue with unsafe template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2395]
### Nuclei version:
dev,master

Test template:

```yaml
id: aws-ssrf
info:
  name: AWS SSRF
  author: test
  severity: critical

requests:
  - raw:
      - |+
        GET http://169.254.169.254/ HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
    matchers:
      - type: word
        part: body
        words:
          - "latest"
```

### Current Behavior:
```console
echo https://redacted | nuclei -t test.yaml -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.5 (latest)
[INF] Using Nuclei Templates 9.1.3 (latest)
[INF] Templates added in last update: 40
[INF] Templates loaded for scan: 1
[INF] [aws-ssrf] Dumped HTTP request for https://redacted

GET http://169.254.169.254/ HTTP/1.1
Host: redacted

[WRN] [aws-ssrf] Could not execute request for https://redacted: ReadStatusLine: local error: tls: no renegotiation
```

### Note:
Above template works when setting up `-sni` value manually, i.e `echo https://redacted | nuclei -t test.yaml -sni redacted`
