### ISSUE TITLE
Add resursive option for processing payloads

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2398]
Example word list:
```
version
version.txt
api
lib
v1
```

Example input root URL of a web application: `redacted.com/a-web-application`

Current approach would test only the following:
```
redacted.com/a-web-application/version
redacted.com/a-web-application/version.txt
redacted.com/a-web-application/api
redacted.com/a-web-application/lib
redacted.com/a-web-application/v1
```

It is not possible to hard-code the path in the template, because custom deployments can modify the root path of the applications. The preferred solution would be to enable recursive path fuzzing.

Let's assume two valid paths are:
```
redacted.com/a-web-application/api/v1/version.txt
redacted.com/lib/version.txt
```

and the intermediate paths would all return 200 OK:
```
redacted.com/a-web-application/api
redacted.com/a-web-application/api/v1
redacted.com/lib
```

In this case the recursive option, combined with a `status_code==200` matcher, the template should find the valid paths.

## Scenario 2
That being said, there might be cases when the intermediate paths would respond with 404. Adding a new attribute , something like `permute: true`, could be used to try all possible permutations and look for a specific status code.

Example template:
```yaml
requests:
  - raw:
      - |
        GET /{{payload}} HTTP/1.1
        Host: {{Hostname}}

    recurse: true # <---
    permute: true # <---
    payloads:
      payload:
        - admin

    iterate-all: true
    matchers:
      - type: status
        status:
          - 200

    extractors:
      - type: kval
         kval:
           - payload
```
