### ISSUE TITLE
[feature] supporting multiple extractor (same like matchers) 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#241]
**Is your feature request related to a problem? Please describe.**

As extractor and matchers can be used independently, it's useful to support multiple features to extractor as well. 

**Describe the solution you'd like**

example template:- 

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    extractors:
      - type: regex
        name: ex1
        regex:
          - Collaborator-Version

      - type: regex
        name: ex2
        regex:
          - <html>
```

expected output:- 

```
[template-name:ex1] [http] http://etb0968645x0py1efi1ycfpzoquhi6.burpcollaborator.net
[template-name:ex2] [http] http:/etb0968645x0py1efi1ycfpzoquhi6.burpcollaborator.net
```

basically porting all features of multiple matchers to multiple extractors
