### ISSUE TITLE
Double 'Connection' header in POST request

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#2424]
### Nuclei version:
[INF] Using Nuclei Engine 2.7.5 (latest)

### Current Behavior:
When trying to give a custom 'Connection' value in a POST request, nuclei accepts it but add it's own connection header in the request. It doesn't show when using the -debug flag (it shows only one header).

But if you try with your own server or burp collab, when you see it you receive 2 Connection headers.

### Steps To Reproduce:

```
requests:
  - raw:
      - |
        POST  HTTP/1.1
        Host: {{Hostname}}
        Connection: keep-alive
        Content-Length: 35
```

debug request:

```
POST / HTTP/1.1
Host: 4w1epaumf6ycxaug7pnwka8mndt3hs.oastify.com
User-Agent: Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
Content-Length: 41
Connection: keep-alive
Accept-Encoding: gzip
```

server request of burp collab:

```
POST / HTTP/1.1
Host: 4w1epaumf6ycxaug7pnwka8mndt3hs.oastify.com
User-Agent: Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
Content-Length: 41
Connection: keep-alive
Accept-Encoding: gzip
Connection: close
```

Which includes both `Connection: keep-alive` and `Connection: close` in the same request.
