### ISSUE TITLE
Unsafe POST request adds new line

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#2425]
### Nuclei version:

[INF] Using Nuclei Engine 2.7.5 (latest)

### Current Behavior:
So the issue is simple, nuclei adds a new line to POST unsafe requests (might so the same in normal requests, lets hope so, but didn't test).

## template

```
requests:
  - raw:
      - |+
        POST / HTTP/1.1
        Host: {{Hostname}}
        Connection: keep-alive
        Content-Length: 40

        blablabla
```

command

`echo https://burpcollaborator | nuclei -t template`

received response like this:

```
POST / HTTP/1.1
Host: rwre86hjst71dn7ykrq9czcbo2usih.oastify.com
Connection: keep-alive
Content-Length: 40

blablabla

```

with a extra new line in the body of the POST request (shouldn't include one).

**Comment by ehsandeep** [comment]
Line break can be controlled from template as shared below, closing as this is not an issue.

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |+
        POST / HTTP/1.1
        Host: {{Hostname}}

        blablabla=blabla
    unsafe: true
```

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |+
        POST / HTTP/1.1
        Host: {{Hostname}}

        blablabla=blabla

    unsafe: true
```
