### ISSUE TITLE
The `duration` variable doesn't return the elapsed time required for all requests

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2447]
When `req-condition: true` the `duration` is equal to the last suffixable duration. 
E.g. in case of 3 requests, `duration == duration_3`, whereas it should rather be equal to the total (`duration_1 + duration_2 + duration_3`)

Test template:
```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /{{srvr}} HTTP/1.1
        Host: {{Hostname}}

    redirects: true
    req-condition: true
    matchers:
      - type: dsl
        name: timer
        dsl:
          - "print_debug(concat('first: ', duration_1))"
          - "print_debug(concat('second: ', duration_2))"
          - "print_debug(concat('third: ', duration_3))"
          - "print_debug(concat('duration: ', duration))"
          - "print_debug(concat('total: ', to_string(to_number(duration_1) + to_number(duration_2) + to_number(duration_3))))"
        condition: and

    extractors:
      - type: regex
        name: srvr
        part: header
        internal: true
        group: 1
        regex:
          - "Server: ([a-zA-z]+)"

      - type: kval
        kval:
          - srvr
```

Current output:
![image](https://user-images.githubusercontent.com/13679401/185074329-2e565fd9-0a4a-47e4-bd6e-90e524f93a2c.png)
