### ISSUE TITLE
Show method signatures if an invalid DSL function is referenced in case of extractors

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2481]
Original enhancement: https://github.com/projectdiscovery/nuclei/issues/1295

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET /etag.txt HTTP/1.1
        Host: {{Hostname}}

    # matchers:          <- is working for matchers
    # - type: dsl
    #    dsl:
    #      - print_de()

    extractors:
      - type: dsl
        dsl:
          - "print_debu()"
```

Actual:
![image](https://user-images.githubusercontent.com/13679401/186135665-fb978396-fb2c-4f6d-88ef-5cbc6fe09db4.png)

Expected:
![image](https://user-images.githubusercontent.com/13679401/186136400-aa3325bc-81b0-4e99-a384-1cd5053f75aa.png)
