### ISSUE TITLE
Blank Request-URI issue with unsafe templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2503]
### Nuclei version:
latest

### Steps To Reproduce:

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |+
        GET ?a=b HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    unsafe: true
```

```console
echo https://example.com/test.js | nuclei -t test.yaml
```

### Current Behavior:
The request gets sent to `https://example.com?a=b`

### Expected Behavior:
The request gets sent to `https://example.com/test.js?a=b`

### Fix

- [ ] Fix for blank URI with unsafe template
- [ ] Integration test for blank URI for safe + unsafe template 

### Anything else:
- https://github.com/projectdiscovery/nuclei/pull/2414 (related to)
