### ISSUE TITLE
Conditional named matchers in workflows

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2521]
I have written multiple fingerprint templates
I want to execute a vulnerability scan when I execute a workflow template that satisfies any one of the features of this set of fingerprints.
But as it stands, I have to write multiple fingerprints side by side, **which generates a lot of extra requests**

Current template situation

```yaml
id: finger-scan

info:
  name: finger-scan
  author: capiton

workflows:
  - template: technologies/tech-detect.yaml
    matchers:
      - name: spring-boot
        subtemplates:
          - tags: springboot
          - tags: spring

      - name: spring
        subtemplates:
          - tags: springboot
          - tags: spring
          
      - name: spring-framework
        subtemplates:
          - tags: spring
```
What I want to achieve

```yaml
workflows:
  - template: technologies/tech-detect.yaml
    matchers:
      - names:
          - spring-boot
          - spring
          - spring-framework
        condition: or
        subtemplates:
          - tags: springboot
          - tags: spring
```
