### ISSUE TITLE
Adding mathematical operations to dsl functions

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2526]
### Please describe your feature request:

When probing for command execution vulnerabilities
mathematical operations are required to reduce false positives
For example

linux:
```
variables:
    re1: "{{rand_int(1000000, 2000000)}}"
    re2: "{{rand_int(2000000, 3000000)}}"
 
payloads:
    Cmd: expr {{re1}} + {{re2}}
```

windows:
```
variables:
    re1: "{{rand_int(1000000, 2000000)}}"
    re2: "{{rand_int(2000000, 3000000)}}"
 
payloads:
     Cmd: set /A {{re1}} + {{re2}}
```

Desired additions:
```
variables:
    re1: "{{rand_int(1000000, 2000000)}}"
    re2: "{{rand_int(2000000, 3000000)}}"
    re3: '{{math(re1 + re2)}}'

variables:
    re1: "{{rand_int(1000000, 2000000)}}"
    re2: "{{rand_int(2000000, 3000000)}}"
    re3: '{{math(re1 * re2)}}'

  matchers:
    - type: word
      part: body
      words:
        - {{re3}}
```

**Comment by forgedhallpass** [comment]
@capiton0 This can be achieved. Try this:

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

variables:
  a: '{{rand_int(1, 10)}}'
  b: '{{rand_int(2, 10)}}'
  c: '{{to_number(a) + to_number(b)}}'

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - "print_debug(concat(a, ' + ', b, ' = ',c))"
```

Result:
```sh
...
[INF] print_debug value: [2 + 5 = 7]
...
```
