### ISSUE TITLE
Issue with printing result in case of match from multiple protocol

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2533]
Currently, if multiple protocol outputs from the same template return true, only one is displayed or ignored, this behaviour can be updated / fixed as running multipe protocol from same template is required to further allow protocol based conditional matching.

### Nuclei version:
latest

**Nuclei Template:**

```yaml
id: basic-template

info:
  name: basic template
  author: pdteam
  severity: info


dns:
  - name: "{{FQDN}}"
    type: CNAME

    matchers:
      - type: word
        words:
          - "IN\tCNAME"

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
```

### Current Behavior:

```console
$ nuclei -u https://docs.hackerone.com -t test.yaml -silent

[basic-template] [dns] [info] https://docs.hackerone.com
```

### Expected Behavior:

```console
$ nuclei -u https://docs.hackerone.com -t test.yaml -silent

[basic-template] [dns] [info] https://docs.hackerone.com
[basic-template] [http] [info] https://docs.hackerone.com
```
### Steps To Reproduce:

```console
$ nuclei -u https://docs.hackerone.com -t test.yaml -silent
```
