### ISSUE TITLE
conditional request execution support with flow

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2534]
Here is an example nuclei template with flow execution conditions.

**Details:**

```yaml
id: zendesk-takeover
info:
  name: Zendesk takeover detection
  author: pdteam
  severity: info

# flow decides execution flow
# result will return true when both executions return true.

flow: dns() && http()

dns:
  - name: "{{FQDN}}"
    type: CNAME

    matchers:
      - type: word
        words:
          - "zendesk.com"

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "zendesk not found"
```

**Related discussion:**
- https://github.com/projectdiscovery/nuclei/discussions/2016
- https://github.com/projectdiscovery/nuclei/discussions/2936

This support allows us to do:

- Conditional request execution with implicit cross-protocol support.
