### ISSUE TITLE
Variables loose their data types

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2543]
```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

variables:
  a: '{{rand_int(1, 10)}}'   # <-- returns an int
  b: '{{rand_int(2, 10)}}'
  c: '{{to_number(a) + to_number(b)}}'  # <-- if to_number is not used, it will concatenate the two numbers instead of adding them

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - "print_debug(concat(a, '  +  ', b, ' = ', c))" # <-- even though `c` is clearly a number, adding a number to it will result again in string concatenation instead of the result of the arithmetic operation
```
