### ISSUE TITLE
DSL expression evaluation invoked too many times

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2546]
Making a mistake in the variable declaration will show the debug message 4 times. Messing up both variables will double the number of evaluations.

```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

variables:
  before: '{{to_unix_time("2019-13-10")}}' # <-- making a mistake here in the date format
  after: '{{to_unix_time("2019-12-13")}}'

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - print_debug((to_number(before) < hex_to_dec("5df16a63")) && (hex_to_dec("5df16a63") < to_number(after)))
```

```console
nuclei -u example.com -t test.yaml -svd -debug-req
```
p.s. the related logic for the `to_unix_time` and `hex_to_dec` functions is in #2544
