### ISSUE TITLE
Extracted value not accessible within a DSL context

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2547]
```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET /etag.txt HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
           - true

    extractors:
      - type: regex
        part: body
        group: 1
        name: snippet
        internal: true
        regex:
          - 'ETag: \"[0-9a-fA-F]{4}([0-9a-fA-F]{8})\"'

      - type: dsl
        dsl:
          - "print_debug(snippet)"
```

Example file with `ETag` header:
```
Date: Thu, 18 Aug 2022 17:07:29 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 11749
Connection: keep-alive
ETag: "7e645df16a63"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
```

In the result there isn't even an indication that the `snippet` internal variable does not exist or is inaccessible.
