### ISSUE TITLE
Implement an option to force  use of HTTP/2

### ISSUE THREAD

**Issue by darshanpjpt** [projectdiscovery/nuclei#2584]
Hello Team,

When I was testing a target, all the request was resulting in 403. By further checking, I found that the site is returning 403 if HTTP/2 is not used.

I think that there should be an option that force nuclei to use HTTP/2 for all the outgoing request. It should also include the ones that has specified HTTP/1.1 in raw format in template.

**Comment by forgedhallpass** [comment]
Confirmed. The connection upgrade does not happen, and even the explicit HTTP2 request via the raw requests are being ignored. Temporary solution until this gets fixed is to proxy through BurpSuite, because it automatically upgrades the requests.

![image](https://user-images.githubusercontent.com/13679401/189481281-a6e8a127-7ac6-48ec-947a-cda372837530.png)

Without proxy:
![image](https://user-images.githubusercontent.com/13679401/189481323-ef330210-3aaa-4964-af04-b89cb21da601.png)

Template with HTTP/2 raw request:
```yaml
id: http2-test

info:
  name: test
  author: forgedhallpass
  severity: info
  description: HTTP2 test

requests:
  - raw:
      - |
        GET / HTTP/2.0           # <--- note this. HTTP/2 doesn't work either
        Host: {{Hostname}}
    
    matchers:
      - type: dsl
        dsl:
          - true
```

![image](https://user-images.githubusercontent.com/13679401/189481436-fa703164-831a-47f9-96ae-4eb3a90f7861.png)

**Comment by jimen0** [comment]
@forgedhallpass - note `httputil` package prints HTTP/1.1-like requests, it doesn't print HTTP/2 requests:

> HTTP/2 requests are dumped in HTTP/1.x form, not in their original binary representations.

Source: https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/net/http/httputil/dump.go;l=208-209

Make sure you've verified the HTTP1.0 protocol is being used with something like tcpdump or wireshark.

**Comment by forgedhallpass** [comment]
> @forgedhallpass - note `httputil` package prints HTTP/1.1-like requests, it doesn't print HTTP/2 requests:
> 
> > HTTP/2 requests are dumped in HTTP/1.x form, not in their original binary representations.
> 
> Source: https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/net/http/httputil/dump.go;l=208-209
> 
> Make sure you've verified the HTTP1.0 protocol is being used with something like tcpdump or wireshark.

That's true, because HTTP2 is binary, but still the text representation should show HTTP2 if the request was made using HTTP2. Furthermore the functionality was tested against a host that does not respond to HTTP1.x requests. You can see the differences in the first two screenshots.

**Comment by Mzack9999** [comment]
Possible implementations:
- `ForceAttemptHTTP2` Transport Option:
```go
http.Transport = &http.Transport{ForceAttemptHTTP2: true}
```
- Using pure http2 client:
```go
import `golang.org/x/net/http2`
...
transport := &http2.Transport{}
```

**Comment by Mzack9999** [comment]
related: https://github.com/projectdiscovery/team-backlogs/issues/157

**Comment by hateshape** [comment]
Hey there folks, first off y'all are the best! I have reached out on Twitter previously asking how to sponsor you / donate. This needs to be an option! I and so many others would!

With regards to this issue I also see this behavior. HTTP/2 is one part to this, but I would also be interested in being able to send a request with an HTTP version that doesn't exist as well. 
```
id: bla-test

info:
  name: test
  author: forgedhallpass
  severity: info
  description: BLA-test-E-test

requests:
  - raw:
      - |
        GET / BLA/1.0           # <--- note this. BLA/1.0 doesn't work either. Expected. based on current issue
        Host: {{Hostname}}
    
    matchers:
      - type: dsl
        dsl:
          - true
```
![bla-1 0](https://user-images.githubusercontent.com/31131951/203088529-3cb19a6b-8b6e-49f4-83b3-329da0496ee6.png)

**Comment by ehsandeep** [comment]
@hateshape thank you, we appreciate your kindness; sharing feedback and bugs is what donation mean to us, we don't accept monetary donations as the community already did a lot to let us do this [full time](https://blog.projectdiscovery.io/we-are-going-full-time/). 

You can pass any malformed request/header if you need to add `unsafe: true` into your template. for example -

```yaml
id: bla-test

info:
  name: test
  author: pdteam
  severity: info
  description: BLA-test-E-test

requests:
  - raw:
      - |
        GET / BLA/1.0
        Host: {{Hostname}}


    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - true
```

```console
echo https://example.com | nuclei -t test.yaml -debug-req

[INF] Using Nuclei Engine 2.7.8 (outdated)
[INF] Using Nuclei Templates 9.2.9 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] [bla-test] Dumped HTTP request for https://example.com/

GET / BLA/1.0
Host: example.com
[2022-11-21 21:37:54] [bla-test] [http] [info] https://example.com
```

Check out the documentation for more details - https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#unsafe-http-requests, also feel free to join the [discord server](https://discord.gg/projectdiscovery) if you any additional questions/feedback.
