### ISSUE TITLE
Multiple n matcher for dsl duration matcher

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/nuclei#2587]
Hi Team,

Hope All are going well !!

At present, only one `dsl duration condition` can be used against overall requests in template and cannot be used as `duration_n` matcher

<details>
<summary>time-based-template.yaml</summary>

```yaml
id: time-based
info:
  name: Time Based
  author: zy9ard3
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{fuzz}}"
      - "{{BaseURL}}"

    attack: clusterbomb
    payloads:
      fuzz:
      - "';SLEEP(12)"

    matchers:
      - type: dsl
        dsl:
          - 'duration_1 >= 10'
          - 'duration_2 < 10'
        condition: and
```
</details>

![duration_n not available](https://user-images.githubusercontent.com/67743789/189523262-5ec88214-395d-462f-98be-3729a076166e.png)

But I would like to suggest a feature of considering Adding n matcher for `dsl duration matcher` ( i.e : `duration_1`, `duration_2`, etc... ) just like other dsl n matchers ( i.e : `status_code_1`, `body_1`, etc... ) which can be helpful in detecting & confirming issues on time based and also to avoid false positives

*Kindly please let me know if anything I missed out, I'm glad to assist with pleasure on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by forgedhallpass** [comment]
Hello @zy9ard3 

This is already supported, you just need to add `req-condition: true`.

Related:
https://github.com/projectdiscovery/nuclei/issues/2362#issuecomment-1198366756
https://github.com/projectdiscovery/nuclei/issues/2393

**Comment by zy9ard3** [comment]
Hi @forgedhallpass 

Thanks for the Kind Response and Detailed Clarifications !!

I'm able to successfully execute as you said, but there seems to be problem on output as I receiving double results when using multiple duration matchers

<details>
<summary>time-based-template.yaml</summary>

```yaml
id: time-based
info:
  name: Time Based
  author: zy9ard3
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{fuzz}}"
      - "{{BaseURL}}"

    req-condition: true
    attack: clusterbomb
    payloads:
      fuzz:
      - 1+AND+(SELECT+*+FROM+(SELECT(SLEEP(12)))nQIP)

    matchers:
      - type: dsl
        dsl:
          - 'duration_1 >= 10'
          - 'duration_2 < 10'
        condition: and
```
</details>

![double results](https://user-images.githubusercontent.com/67743789/190894506-dafae6d6-30df-4abf-8b32-0938c734f6cb.png)

And for the reason, I tried to create template as raw based but the issue on raw also seems to be the query parameters are getting stripped from the request and also I'm not able to find a global variable for avoid stripping query parameter from request

Is there any solution for the above two things or either any one of the thing !!

*Kindly please let me know if anything I missed out, I'm glad to assist with pleasure on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by ehsandeep** [comment]
@zy9ard3 following raw template should work, if it doesn't feel free to dm on discord (`pd-team`)

```yaml
id: time-based
info:
  name: Time Based
  author: zy9ard3
  severity: high

requests:
  - raw:
      - |
        GET {{fuzz}} HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

      - |
        GET  HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    req-condition: true
    attack: clusterbomb
    payloads:
      fuzz:
      - 1+AND+(SELECT+*+FROM+(SELECT(SLEEP(12)))nQIP)

    matchers:
      - type: dsl
        dsl:
          - 'duration_1 >= 10'
          - 'duration_2 < 10'
        condition: and
```
