### ISSUE TITLE
suspected bug,could not compile DSL expression

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2598]
nuclei -duc -validate -t  x.yaml  
```
[ERR] Error occurred parsing template x.yaml: could not compile request: could not compile operators: could not compile matcher: could not compile DSL expression: regex("if\\('1' == '0' \\|\\| '([\\S]*)' == '([\\S]*)'",body_1). Cannot transition token types from STRING [if\(] to NUMERIC [1]
```
$ cat x.yaml 
```
id: ASUS_RT_N16-error_page-info

info:
  name: xxx
  author:
  - Jim2g

requests:
  - raw:
      - |
        GET /error_page.htm HTTP/1.1
        Host: {{Hostname}}

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - status_code_1==200
          - regex("if\\('1' == '0' \\|\\| '([\\S]*)' == '([\\S]*)'",body_1)
        condition: and
```

test.go
```
package main

import (
	"log"
	"regexp"
)

func main() {

	r, err := regexp.Compile("if\\('1' == '0' \\|\\| '([\\S]*)' == '([\\S]*)'")
	if nil != err {
		log.Println(err)
		return
	}
	if nil != r {
		log.Println("Ok: ", r)
	}
}

```
go run test.go
2022/09/13 15:32:33 Ok:  if\('1' == '0' \|\| '([\S]*)' == '([\S]*)'

**Comment by forgedhallpass** [comment]
Try

```yaml
 matchers:
      - type: dsl
        dsl:
          - regex("if\s*\(\'1\'\s*==\s*\'0\'\s*\|\|\s*\'([\S]+)\'\s*==\s*\'([\S]+)\'\s*\).*", body_1)
```

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/13679401/190134389-a7b74ccd-4493-4ea3-b327-0654002b65d3.png">
