### ISSUE TITLE
when use -rc, lost results

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2603]
@ehsandeep 
1、create web server
like 
router.POST("/:id/_doc", lib.SaveRsult)
2、nuclei -rc
set ReportingConfig

3、now found lost resut
<img width="889" alt="image" src="https://user-images.githubusercontent.com/18223385/190171109-ed45ad39-6aeb-4ba0-8cee-352f1f7c8b02.png">
not found the result

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18223385/190171296-7efd8bae-8eec-4aca-8522-5fcbc51b89a3.png">

I have observed that my configuration is correct as only a small number of results are missing, not sure if I can investigate

other is ok
<img width="830" alt="image" src="https://user-images.githubusercontent.com/18223385/190171945-51d14c47-8b33-4f33-a668-5f1be4830ad1.png">

**Comment by hktalent** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/18223385/190178319-76aebe9c-c645-43a9-8f2e-141a8bf1bf6d.png">
leveldb: closed

**Comment by hktalent** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/18223385/190180525-5709cc00-0765-4a46-bda1-c5eff6728330.png">

**Comment by hktalent** [comment]
@ehsandeep
-rc can not work,
nuclei -v      
2.7.9

cmd
```
 nuclei -rate-limit 300  -bulk-size 64 -concurrency 64   -rc  $PWD/config/nuclei_esConfig.yaml -duc -t $PWD/config/nuclei-templates/network/detection/weblogic-iiop-detect.yaml  -tags weblogic -u test.com -vv -debug

cat $PWD/config/nuclei_esConfig.yaml 
```
config
```
elasticsearch:
  # IP for elasticsearch instance
  ip: 127.0.0.1
  # Port is the port of elasticsearch instance
  port: 8081
  # IndexName is the name of the elasticsearch index
  index-name: nuclei_index
  # SSL enables ssl for elasticsearch connection
  ssl: true
  # SSLVerification disables SSL verification for elasticsearch
  ssl-verification: false
  # Username for the elasticsearch instance
  username: elastic
  # Password is the password for elasticsearch instance
  password: testnmanp                                      
```

curl https://127.0.0.1:8081/
is http2
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< accept-ranges: bytes
< content-type: text/html; charset=utf-8
< last-modified: Sat, 26 Nov 2022 07:43:29 GMT
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< content-length: 3548
< date: Fri, 02 Dec 2022 08:03:38 GMT
```
router.POST("/:type/_doc/:id", util1.AuthHandler, lib.SaveRsult)
