### ISSUE TITLE
Issue with variable value parsing with dsl function

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2636]
### Nuclei version:
dev

### Steps To Reproduce:

```yaml
id: test

info:
  name: test
  author: test
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?a={{base64(test)}}&b={{test}}"

    payloads:
      test:
        - "{{DN}}.xxx"
        - "{{RDN}}.yyy"
        - "{{RDN}}.xxx"
```

```console
echo https://example.com | nuclei -t test.yaml
```

```console
[VER] [test] Sent HTTP request to https://example.com/?a=e3tETn19&b=example
```

### Current Behavior:
with `base64` dsl, `test` is being replaced with `{{DN}}`

### Expected Behavior:
with `base64` dsl, `test` is being replaced with `example`

**Comment by forgedhallpass** [comment]
Related: https://github.com/projectdiscovery/nuclei/issues/2601

**Comment by ehsandeep** [comment]
Depends on https://github.com/projectdiscovery/nuclei/pull/2679

**Comment by Mzack9999** [comment]
As stated in https://github.com/projectdiscovery/nuclei/issues/2601#issuecomment-1261300997 I think the syntax should be simple enough. The previous case can be trivially covered by refactoring as follows:

```yaml
id: test

info:
  name: test
  author: test
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?a={{base64(DN+test)}}&b={{DN+test}}"
      - "{{BaseURL}}/?a={{base64(RDN+test)}}&b={{RDN+test}}" 
      
    payloads:
      test:
        - ".xxx"
        - ".yyy"
```
