### ISSUE TITLE
extractors add variable support

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2647]
### Please describe your feature request:

This is the json data returned from the target site:
```
{
 "subdomain": ["www","m","mail"]
}
```
This is the `extractors` syntax I use:
```
    extractors:
      - type: json
        part: body
        name: subdomain
        json:
          - '.subdomain[]'
```
The final output:
```
[test:status-1] [http] [info] https://test.com/subdomains [www,m,mail]
```
### Describe the use case of this feature:

I want to add variables to the output
```
variables:
 domain: "xxx.com"

     extractors:
      - type: json
        part: body
        name: subdomain
        json:
          - '"\(.subdomain[]).{{domain}}"'
```
or
```
nuclei -var domain=xxx.com
     extractors:
      - type: json
        part: body
        name: subdomain
        json:
          - '"\(.subdomain[]).{{domain}}"'
```
Let the final output look like this:
```
[test:status-1] [http] [info] https://test.com/subdomains [www.xxx.com,m.xxx.com,mail.xxx.com]
```
