### ISSUE TITLE
workflows load template id

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2648]
### Please describe your feature request:

This is the syntax when the template is currently loaded:
```
workflows:
  - template: tech/workflow1.yaml
    subtemplates:
      - template: tech/workflow2.yaml
        subtemplates:
          - template: tech/workflow3.yaml

```
I hope it is possible to load the template id directly:
```
workflows:
  - template-id: workflow1
    subtemplates:
      - template-id: workflow2
        subtemplates:
          - template-id: workflow3
```
Because if the `tech` folder is changed, or the file name is changed, the corresponding workflow must also be changed
This is to prepare for the future naming of template files, template classification standardization
