### ISSUE TITLE
workflows add stop option

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2649]
### Please describe your feature request:

I want to use workflows to detect the presence of waf in the target first.
If the target has a waf, then stop all subsequent requests
Otherwise, continue the scanning behavior
```
  - template: technologies/waf-detect.yaml
    stop-at-first-match: true
    
    subtemplates:        
      - template: cves/
```
