### ISSUE TITLE
CLI option specify attack type

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2666]
### Describe the use case of this feature:
While writing a fuzzing template attack type can be defined in the template using `attack:` attribute, and can not be updated externally when required, to make this possible to update the attack type without editing the template file each time, this can be supported via CLI option, when specified will update/overwrite template option.

### Please describe your feature request:

Example Template:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?username={{user}}&password={{pass}}"

    attack: clusterbomb
    payloads:
      user: users.txt
      pass: pass.txt

    matchers:
      - type: word
        words:
          - "This is test matcher text"
```

CLI Option:

```console
   -at, -attack-type          type of payload combinations to perform (batteringram,pitchfork,clusterbomb)
 ```
