### ISSUE TITLE
Nuclei doesn't encode query parameters by default when sending HTTP request

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#2698]

**Comment by tarunKoyalwar** [comment]
@Ice3man543  @ehsandeep 

Some more insights are required here .  If we always url encode parameters it might cause problems with `sql` and `xss` since results are different when payloads are url encoded .  

Here are some testcases how nuclei behaves now

```yaml
id: test-parameters

info:
  name: Test Param
  author: tarunKoyalwar
  severity: medium
  description: xxx

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?param=val1'"
    extractors:
      - type: regex
        part: body
        regex:
          - "request uri is .*"
  
  - method: GET
    path:
      - "{{BaseURL}}/?param=val2' OR 1=1 --"
    extractors:
      - type: regex
        part: body
        regex:
          - "request uri is .*"
  
  - method: GET
    path:
      - "{{BaseURL}}/?param=val3'()][|"
    extractors:
      - type: regex
        part: body
        regex:
          - "request uri is .*"
  
  - raw:
      - |
        GET /?param=raw''][{}' val-ue HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Connection: close
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Language: en-US,en;q=0.9
    extractors:
      - type: regex
        part: body
        regex:
          - "request uri is .*"

```

## Example HTTP server at port 9000

```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Printf("requestURI is %v\n", r.RequestURI)
		fmt.Printf("encoded querystring is %v\n", r.URL.Query().Encode())
		w.WriteHeader(200)
		rstring := fmt.Sprintf("request uri is %v\n", r.RequestURI)
		w.Write([]byte(rstring))
	})

	if err := http.ListenAndServe(":9000", nil); err != nil {
		log.Fatal(err)
	}
}
```

Try running

1. ` echo http://localhost:9000 | nuclei -t query.yaml`
2.  `echo http://localhost:9000/?key=value. | nuclei -t query.yaml `

~~~sh
echo "http://localhost:9000" | nuclei -t query.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.1

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.1 (latest)
[INF] Using Nuclei Templates 9.3.0 (latest)
[INF] Templates added in last update: 70
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[test-parameters] [http] [medium] http://localhost:9000/?param=val1' [request uri is /?param=val1']
[test-parameters] [http] [medium] http://localhost:9000/?param=val3'()][| [request uri is /?param=val3'()][|]
[test-parameters] [http] [medium] http://localhost:9000/?param=raw''][{}' [request uri is /?param=raw''][{}']
~~~
