### ISSUE TITLE
URL parsing issue in raw template with ports

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2700]
### Nuclei version:
`dev` | `master`

### Steps To Reproduce:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST /xmlrpc HTTP/1.1
        Host: {{Host}}:7272
```

```
nuclei -t test.yaml -u https://example.com
```

### Current Behavior:
Request sent out to `https://example.com/xmlrpc`

### Expected Behavior:
Request sent out to `https://example.com:7272/xmlrpc`

### Anything else:
- Add / update test to include this behavior.

**Comment by brenocss** [comment]
I think that is corret and intended. host header should the only thing to be changed. This way, if the input is https://example.com:7272 the template will work as expected.  
```sh
echo https://google.com | nuclei -t teste.yaml -duc -v -debug-req
[INF] [basic-example] Dumped HTTP request for https://google.com/xmlrpc

POST /xmlrpc HTTP/1.1
Host: google.com:7272
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36
Connection: close
Content-Length: 0
Accept-Encoding: gzip
```

```sh
echo https://localhost:7272 | nuclei -t teste.yaml -duc -v -debug-req
[INF] [basic-example] Dumped HTTP request for https://localhost:7272/xmlrpc

POST /xmlrpc HTTP/1.1
Host: localhost:7272
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Connection: close
Content-Length: 0
Accept-Encoding: gzip
```
if we want to change the port should be done in request annotation like `@host`, would be nice to create new annotations like `@port:7272`. `@scheme:https`, etc.
```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        @port:7272
        POST /xmlrpc HTTP/1.1
        Host: {{Host}}:7272
```
other option would be to make this possible
```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        @host:{{Host}}:7272
        POST /xmlrpc HTTP/1.1
        Host: {{Host}}:7272
  ```
