### ISSUE TITLE
Allow to define matchers, payloads and other features globally for all requests.

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#2711]
### Please describe your feature request:

For now the only way to create a matcher or payload or configure the requests for a given request is to create a subfield of -raw. But this makes the templates very repetitive unnecessarily.
 ```yaml
 id: teste

info:
  name: teste
  author: brenocss
  severity: critical

requests:
  - raw:
      - | # Request 2 Only 1 for http_ext
        GET /teste{{http_ext}}? HTTP/1.1
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    attack: clusterbomb
    payloads:
        http_ext:
        - '.js'
        - '.php'
    matchers:
      - type: dsl
        dsl:
          - 'status_code==404'  
  - raw:
      - | # Request 3 Only 1 for version and http_ext
        GET /test{{version}}.{{version_ext}}{{http_ext}} HTTP/1.1

    redirects: true
    max-redirects: 3
    cookie-reuse: true
    attack: clusterbomb
    payloads:
      version:
        - '10.3.2'
        - '10.3.1'     
      version_ext:
        - 'final'
        - 'beta'      
      http_ext:
        - '.js'
        - '.php'
    matchers:
      - type: dsl
        dsl:
          - 'status_code==404'
   ```
It would be nice, if it were possible, in addition to creating the subfields of -raw, that the request itself could have these same subfields that were set for all -raw. making the templates prettier and more syntactically correct

```yaml
id: teste

info:
  name: teste
  author: brenocss
  severity: critical

requests:
  - raw:
      - | # Request 2 Only 1 for http_ext
        GET /teste{{http_ext}}? HTTP/1.1
  - raw:
      - | # Request 3 Only 1 for version and http_ext
        GET /test{{version}}.{{version_ext}}{{http_ext}} HTTP/1.1
  - configs:
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    attack: clusterbomb
    payloads:
      version:
        - '10.3.2'
        - '10.3.1'     
      version_ext:
        - 'final'
        - 'beta'      
      http_ext:
        - '.js'
        - '.php'
    matchers:
      - type: dsl
        dsl:
          - 'status_code==404'
```

### Describe the use case of this feature:

Share the results and settings of matcher, extractor, and other fields for all requests
