### ISSUE TITLE
`@Host` annotation to support dynamic variable

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2766]
@Host: {{myHost}} unresolved variables found: myHost

code
```
id: oss
info:
  name: OSS bucket object checke
  author: 51pwn
  severity: critical
  reference:
    - https://github.com/hktalent/nuclei-templates
    - https://51pwn.com
  tags: oss

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Pragma:no-cache
        Content-type: application/xml
extractors:
      - type: regex
        name: myHost
        group: 1
        regex:
          - '<HostId>([^<]+)<'
```

**Comment by Mzack9999** [comment]
It's only an indentation issue. This works for me:

```yaml
id: oss
info:
  name: OSS bucket object checke
  author: 51pwn
  severity: critical
  reference:
    - https://github.com/hktalent/nuclei-templates
    - https://51pwn.com
  tags: oss

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Pragma:no-cache
        Content-type: application/xml

    extractors:
      - type: regex
        name: myHost
        group: 1
        regex:
          - '<HostId>([^<]+)<'
```
