### ISSUE TITLE
Exposing tlsx scan_mode setting in the template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2779]
### Please describe your feature request:
Exposing tlsx [scan_mode](https://github.com/projectdiscovery/nuclei/blob/85eda65d3128308fde83d5e586962c58b30c4320/v2/pkg/protocols/ssl/ssl.go#L85) setting in the template.

```yaml
id: expired-ssl

info:
  name: Test Template
  author: pdteam
  severity: info

ssl:
  - address: "{{Host}}:{{Port}}"

    min_version: tls11
    max_version: tls12
    scan_mode:  ztls

    matchers:
      - type: word
        words:
          - "test"
```

### Describe the use case of this feature:
control over scan mode with the template for using specific modes.
