### ISSUE TITLE
Exposing raw tls handshake to dsl in supported protocol

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2780]
### Describe the use case of this feature:
To write a more complex template and match/extract data from raw tls handshake.

Example Template for SSL / HTTP

```yaml
ssl:
  - address: "{{Host}}:{{Port}}"

    matchers:
      - type: dsl
        dsl:
          - contains(tls_handshake, "XXX")
```

```yaml
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        
    matchers:
      - type: dsl
        dsl:
          - contains(tls_handshake, "XXX")
```

#### Supported in protocols:

- [x] SSL
- [ ] HTTP
- [ ] TCP
