### ISSUE TITLE
Cannot use pre-processor values in DSL context

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2835]
```yaml
id: template-id

info:
  name: Template Name
  author: forgedhallpass
  severity: info

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
     
    redirects: true
    matchers:
      - type: dsl
         dsl:
           - "print_debug(interactsh-url)"     # none of these work
           - print_debug(interactsh-url)
           - "print_debug({{interactsh-url}})"
           - print_debug({{interactsh-url}})
```

Workaround:
```yaml
variables:
  interact: "{{interactsh-url}}"
   # ...
   - print_debug(interact)
```

Related: https://github.com/projectdiscovery/nuclei/issues/2601

**Comment by ehsandeep** [comment]
@forgedhallpass working example for the above -

```yaml
requests:
  - raw:
      - |+
        GET /?a={{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
     
    matchers:
      - type: dsl
        dsl:
          - print_debug("{{interactsh-url}}")
```
