### ISSUE TITLE
Variables not accessible within the file protocol

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2836]
```yaml
id: test-dsl

info:
  name: DSL test
  author: fhp
  severity: info

variables:
  interact: "{{interactsh-url}}"

file:
  - extensions:
    - txt

    matchers:
      - type: dsl
        dsl:
          - "print_debug(interact)"
 ```

The same works with HTTP.

Related: #2835
