### ISSUE TITLE
AWS Templates with wrong signature

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2840]
### Nuclei version:
2.7.9

### Current Behavior:
Amazon endpoint rejects signed AWS request due to missing/wrong info

### Expected Behavior:
Amazon accepting AWS signature

### Steps To Reproduce:
AWS signed template:
```yaml
id: sts-get-caller-identity
info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info

self-contained: true
signature: aws

requests:
  - raw:
      - |
        POST https://sts.us-east-1.amazonaws.com/ HTTP/1.1
        Host: sts.us-east-1.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.1.28 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off command/sts.get-caller-identity
        Content-Length: 43

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200
```

Run the following command:

```console
$ go run . -V "aws-id=xxx" -V "aws-secret=yyyy" -V "service=zzzz" -V "region=pppp"
```
