### ISSUE TITLE
Matcher Name based condition check cannot match normally

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2848]
### Nuclei version:

Nuclei Engine 2.7.9

### Current Behavior:

Here are two templates:
1.workflow: basic-workflow.yaml
```yaml
id: basic-workflow

info:
  name: Test HTTP Template
  author: capiton

workflows:
  - template: basic-template.yaml
    matchers:
      - name:
          - PHP
        condition: and

        subtemplates:
          - tags: cve

```
2.basic-template.yaml
```yaml
id: basic-template

info:
  name: basic-template
  author: capiton
  severity: info

requests:
  - method: GET
    path:
      - "{{RootURL}}"

    matchers:
      - type: word
        name: PHP
        condition: and
        words:
          - php
```

The template was successfully executed when I first used `basic-template.yaml`

```yaml
nuclei -t basic-template.yaml -u http://127.0.0.1:8000

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Templates added in last update: 51
[INF] Templates loaded for scan: 1
[basic-template] basic-template (@capiton) [info]
[basic-template:PHP] [http] [info] http://127.0.0.1:8000
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 276 | Matched: 1 | Errors: 0 | Requests: 1/1 (100%)
```

However, when I execute the workflow template, the conditional match is not executed successfully, and `tag:cve` is not executed
```yaml
 nuclei -w basic-workflow.yaml -u http://127.0.0.1:8000

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Workflows loaded for scan: 1
[basic-workflow] Test HTTP Template (@capiton) []
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 235 | Matched: 0 | Errors: 0 | Requests: 1/1 (100%)
[INF] No results found. Better luck next time!
```

### Expected Behavior:

The `tags:cve` in workflows should be executed successfully

### Reason:

After several rounds of testing, I found that the reason for this is the `name: PHP` in `basic-template.yaml`, `PHP` cannot be capitalized:
```yaml
    matchers:
      - type: word
        name: PHP 
```

Also the `name: PHP` in `basic-workflow.yaml`, `PHP` cannot be capitalized:
```yaml
    matchers:
      - name:
          - PHP
        condition: and
```
After several rounds of testing, I found that in `name: XXX`, the letter cannot be capitalized, otherwise it will trigger the problem that workflow cannot match.

So here are the results of my tests using `name:php`,`name:pHP`,`name:PhP`,`name:Php`:

Executed successfully using  `name:php`
```yaml
    matchers:
      - type: word
        name: php
        condition: and
        words:
          - php
```

```yaml
workflows:
  - template: 0.local/basic-template.yaml
    matchers:
      - name:
          - php
        condition: and
```

```yaml
nuclei -w 0.local/basic-workflow.yaml -u http://127.0.0.1:8000


[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Workflows loaded for scan: 1
[basic-workflow] Test HTTP Template (@capiton) []
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 1388 | Matched: 0 | Errors: 0 | Requests: 123/123 (100%)
```

Failed to execute with   `name:pHP`
```yaml
    matchers:
      - type: word
        name: pHP
        condition: and
        words:
          - php
```

```yaml
workflows:
  - template: 0.local/basic-template.yaml
    matchers:
      - name:
          - pHP
        condition: and
```

```yaml
nuclei -w 0.local/basic-workflow.yaml -u http://127.0.0.1:8000


[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Workflows loaded for scan: 1
[basic-workflow] Test HTTP Template (@capiton) []
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 18 | Matched: 0 | Errors: 0 | Requests: 1/1 (100%)
```

Failed to execute with  `name:PhP`
```yaml
    matchers:
      - type: word
        name: PhP
        condition: and
        words:
          - php
```

```yaml
workflows:
  - template: 0.local/basic-template.yaml
    matchers:
      - name:
          - PhP
        condition: and
```

```yaml
nuclei -w 0.local/basic-workflow.yaml -u http://127.0.0.1:8000


[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Workflows loaded for scan: 1
[basic-workflow] Test HTTP Template (@capiton) []
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 18 | Matched: 0 | Errors: 0 | Requests: 1/1 (100%)
```

Failed to execute with  `name:Php`
```yaml
    matchers:
      - type: word
        name: pHP
        condition: and
        words:
          - php
```

```yaml
workflows:
  - template: 0.local/basic-template.yaml
    matchers:
      - name:
          - Php
        condition: and
```

```yaml
nuclei -w 0.local/basic-workflow.yaml -u http://127.0.0.1:8000


[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.8 (latest)
[INF] Workflows loaded for scan: 1
[basic-workflow] Test HTTP Template (@capiton) []
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 18 | Matched: 0 | Errors: 0 | Requests: 1/1 (100%)
```
