### ISSUE TITLE
Incorrect results for templates with interactsh matchers and AND condition

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2870]
### Nuclei version:
`main` and `dev`

### Current Behavior:
Templates using  `matchers-condition: and` with matchers referring to `interactsh_protocol` as part don't work

```yaml
id: test-interactsh

info:
  name: interactsh test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /api/geoping/{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"

      - type: dsl
        dsl:
          - "status_code_2 == 200"
```

```console
echo https://geonet.shodan.io | nuclei -t test.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.9.2-dev (development)
[INF] Using Nuclei Templates 9.4.2 (latest)
[INF] Templates added in last update: 78
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Using Interactsh Server: oast.pro
[INF] No results found. Better luck next time!
```

### Expected Behavior:
Correct matching on vulnerable targets

### Steps To Reproduce:
Ref: https://github.com/projectdiscovery/nuclei-templates/pull/6080

**Comment by dwisiswant0** [comment]
Can you elaborate on the current behavior further? I mean, will combining `interactsh_protocol` with `matcher-condition` as **AND** ignore other types? And only fits into Interactsh pingback? Or what?

**Comment by Mzack9999** [comment]
For some reason (I've still to investigate in detail) the word matcher on the body works, but the interactsh matcher (altough retrieved correctly internally) doesn't trigger when used with "AND" condition:
``
 matchers-condition: and
    matchers:
      - type: word # This matches
        part: body
        words:
          - "RUN_BUILD_RPM_TASK"
          - "shared:iapp:build-package:buildrpmtaskstate"
      
      - type: word # This doesn't match even if the interactions are retrieved
        part: interactsh_protocol
        words:
          - "dns"
          - "http"
``
Changing the condition to OR make both matchers work

**Comment by ehsandeep** [comment]
@Mzack9999 @dwisiswant0 I've investigated this issue, and this behavior/bug can be replicated only when using a dynamic extractor.

**Comment by Mzack9999** [comment]
On Hold - interactsh urls can actually be matched only in the corresponding request where they are used. More edge cases needs to be documented.

**Comment by ehsandeep** [comment]
> On Hold - interactsh urls can actually be matched only in the corresponding request where they are used. More edge cases needs to be documented.

This doesn't work for single request as well.

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?x={{interactsh-url}}"

    matchers-condition: and
    matchers:
      - type: word # This matches
        part: body
        words:
          - "XXXXXXX"
        negative: true
      
      - type: word # This doesn't match even if the interactions are retrieved
        part: interactsh_protocol
        words:
          - "dns"
        negative: true
```
