### ISSUE TITLE
Ability to match content from the rendered HTML in headless templates

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2960]
Even in cases of headless templates, matchers only work on HTTP responses, but there are sites that generate the DOM using JavaScript logic. It would be nice to save the rendered HTML into a variable and make it accessible for matching through the `part` attribute.

Example:

```yaml
id: twitter

info:
    name: Nonexistent Twitter user
    severity: info
    author: forgedhallpass

headless:
  - steps:
      - action: navigate      
        args:
          url: "{{BaseURL}}"
      - action: waitload

    matchers:
      - type: word
        words:
          - "This account doesn't exist"
```

```console
./nuclei -t twitter.yaml -u https://twitter.com/gaergef -headless

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.0

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.0 (outdated)
[INF] Using Nuclei Templates 9.3.0 (latest)
[INF] Templates added in last update: 70
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
```

Note:
> *This further needs to be investigated if this supposed to be supported with `history` implemented in https://github.com/projectdiscovery/nuclei/pull/1432, if not this support can be implemented*

Potential concurrency issues need to be considered (e.g. the page is not loaded when the matcher is executed etc.)

**Comment by ehsandeep** [comment]
@forgedhallpass this is fixed in the `dev` branch with https://github.com/projectdiscovery/nuclei/issues/2885

```bash
echo https://discord.com/invite/asdasdasdas | ./nuclei -t discord.yaml -headless -silent

[2022-12-04 18:53:46] [discord] [headless] [info] https://discord.com/invite/asdasdasdas
```

**Comment by forgedhallpass** [comment]
The fix you've linked doesn't do what this ticket is asking for. The change seems to affect the `waitload` method, but doesn't change the target of the matchers.

```yaml
id: twitter
info:
    name: Nonexistent Twitter user
    severity: info
    author: forgedhallpass

headless:
  - steps:
      - action: navigate      
        args:
          url: "{{BaseURL}}"
      - action: waitload

    matchers:
      - type: word
        words:
          - "This account doesn't exist"
```

```sh
./nuclei -t twitter.yaml -u https://twitter.com/gaergef -headless
```
