### ISSUE TITLE
Implement shell protocol or integrate 3rd party tools into nuclei

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#2964]
### Please describe your feature request:

currently, nuclei has various protocols (headless , HTTP , DNS , SSL etc) that are used to create/run templates .  Implementing new protocol `shell` will allow integration of other (3rd party) tools to be integrated with nuclei 

### Describe the use case of this feature:

Nuclei has many features which make it possible to create template for almost every security check but it might be too complex or not possible to implement certain security checks due to various reasons . for example use cases like SQL injection exploitation (sqlmap) , IDOR testing , JWT attacks , oauth checks etc  . Or any another custom script/tool . Such tools can be integrated with nuclei using `shell` protocol .

Example template

```yaml
id: exploit-sql
...
shell:
  - timeout: 120
    cmd:
      - "sqlmap  -u  {{BaseURL}}  --dbs"
    matchers:
      - type: word
        words:
          - "fetching database names"
```

This is just a simple example which might be implemented by Nuclei in future but implementing IDOR testing which requires different logic might not be possible . If `shell` protocol is implemented all existing open source tools can be integrated with nuclei and fully leverage features of nuclei like scaling , automation,cloud etc .and use `nuclei` as pivot instead of using nuclei as library and writing bash scripts

Note: Since operators / matchers/variables etc are already available implementing `shell` will be easy .
