### ISSUE TITLE
Add support for nested variables in Variables block.

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#2984]
### Please describe your feature request:
In the latest nuclei version a new feature was added:  nesting variables, ie: 

```
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
  test: "{{interactsh-url}}"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{base64('{{test}}')}}"
```
But the `nesting` only works on the **request** block (as in the template above)  but it doesn't work in the `variables` block. 

This example doesn't work:

```
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
  url: "{{interactsh-url}}"
  cmd: "{{hex_encode({{url)}}"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{cmd}}"
```

The variable `cmd` has the value  `7b7b696e74657261637473682d75726c7d7d`  which is the result of hex_encoding  the value `'{{interactsh-url}}'`, so, the variable is resolved as its literal value and not the assignment. 

### Describe the use case of this feature:

The most relevant use case is to allow the use of interarctsh in cases where the url itself needs to be modified (in this case encoding it), also improves readability.

**Comment by forgedhallpass** [comment]
Try it without the nested curly braces, because you are already in a DSL context.

e.g.
```yaml
cmd: "{{hex_encode(url)}}"
# or
- "{{BaseURL}}/{{base64(url)}}"
```

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/13679401/206024813-8d7c0726-9873-4925-9725-75707700c165.png">

**Comment by Mzack9999** [comment]
Variables nesting is not necessary here. The same result can be obtained as follows:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
  test: "{{interactsh-url}}"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{hex_encode(test)}}"
 ```

Adding recursive support for nested variables would potentially increasingly make the syntax more complex and confusing.
