### ISSUE TITLE
stop-at-first-match field in headless mode

### ISSUE THREAD

**Issue by theamanrawat** [projectdiscovery/nuclei#2991]
### Current Behavior:

While running headless template which has `stop-at-first-match: true`, It is giving an error: - 

```
yaml: unmarshal errors:
  line : field stop-at-first-match not found in type headless.Request
```

### Expected Behavior:

It should run the template and stop at first match as expected.

**Comment by tarunKoyalwar** [comment]
@theamanrawat  , `stop-at-first-match` has only been implemented for `HTTP Requests` which was also specified in v2.5.0 release 

> Stop At First Match
stop-at-first-match is now supported in the template for HTTP requests. What this means is, if there are multiple requests, nuclei will stop sending requests as soon as it gets a match. This is useful in cases like brute-forcing, etc., where you want to stop after finding the first match. Previously, it was supported by a CLI flag that applied to all templates, and now it can be defined within a template, allowing it to be used in particular cases.


Can you provide any usecase ?? so we can consider implementing this .

**Comment by theamanrawat** [comment]
Hi @tarunKoyalwar,

Here is the use case (Run the given template on http://www.evil.com/ ): - 

```yaml
id: test

info:
  name: Use case for stop-at-first-match
  author: theamanrawat
  severity: low
  description: Use case for stop-at-first-match in headless.


headless:
  - steps:
      - args:
         url: '{{BaseURL}}/{{path}}'
        action: navigate
      - action: waitload

    payloads:
      path:

        - '/'
        - '/projectX.htm'

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "evil.com"
          - "We get it...Daily."
        condition: and
```

In headless template, If we wants to stop at first match then this won't work and gives us two match.
