### ISSUE TITLE
Annotations prepending {{Path}} from target URL in raw requests

### ISSUE THREAD

**Issue by ricardomaia** [projectdiscovery/nuclei#2998]
### Nuclei version: v2.8.1

I'm creating a template that will use annotations, but when informing the destination URL as a parameter to Nuclei, the path is included at the beginning of the raw request.

Below is a template to help reproduce the error.

```yaml
id: annotations-bug

info:
  name: Annotations Bug
  author: ricardomaia
  severity: info
  tags: bug

requests:
  - raw:
      - |
        @Host: https://github.com:443
        GET /ricardomaia HTTP/1.1
        Host: github.com

    extractors:
      - type: regex
        name: name_internal
        internal: true
        part: body
        regex:
          - "(?i)Ricardo.Maia"

      - type: regex
        name: name
        part: body
        regex:
          - "(?i)Ricardo.Maia"

    matchers-condition: or

    matchers:
      - type: regex
        regex:
          - "(?i)Ricardo.Maia"
```

### Current Behavior:

As you can see in the request dump, the path "foo/bar" is appended to the request.

```
[annotations-bug] Dumped HTTP request for https://github.com:443/foo/bar/ricardomaia


GET /foo/bar/ricardomaia HTTP/1.1
Host: github.com
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36
Connection: close
Accept-Encoding: gzip


[annotations-bug] Dumped HTTP response https://github.com:443/foo/bar/ricardomaia

HTTP/1.1 404 Not Found
```

### Expected Behavior:

I expected the result of the request to be like below, without appending the target path informed in the `-u` parameter.

```
[annotations-bug] Dumped HTTP request for https://github.com:443/ricardomaia


GET /ricardomaia HTTP/1.1
Host: github.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2919.83 Safari/537.36
Connection: close
Accept-Encoding: gzip


[annotations-bug] Dumped HTTP response https://github.com:443/ricardomaia

HTTP/1.1 200 OK
```

![image](https://user-images.githubusercontent.com/1353811/206366566-b757ed06-fc52-4fa7-917a-2c567efde209.png)

### Steps To Reproduce:

1. Run `nuclei -t annotation-bug.yaml -u https://github.com/foo/bar`
2. Receive a dump of the request as described in "Current Behavior".
