### ISSUE TITLE
Matcher with binary rule capability

### ISSUE THREAD

**Issue by toufik-airane** [projectdiscovery/nuclei#30]
Note that this issue is following the PR https://github.com/projectdiscovery/nuclei/pull/31.

# Context

I thought that a matcher with binary rule capability could be interesting like Yara rules.
It's useful to match binary files such as archives.
In fact, the need to develop a dedicated matcher comes from the native utf-8 encoding from Golang.
I wanted to bypass the issue that I can't match characters such a: `\x8a` because Golang automatically handles it as `\xc2\x8a`.

So finally, after contribution #31, you can now invoke a binary matcher to handle hexadecimal rules.

## usage
```
matchers:
      - type: binary
        binary:
        - "504B0304" # zip
        - "425A68" # bz2
        condition: or
        part: body
```
