### ISSUE TITLE
Add noise level to configure fuzzing payload count at runtime based on user preference

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#3005]
### Please describe your feature request:
Currently there's no way to specify how much noise we want to generate during fuzzing. As an example - https://github.com/projectdiscovery/fuzzing-templates/blob/main/crlf/crlf-injection.yaml - this template sends 30 payloads by default.

Somehow we should make it configurable and use a low count of payloads by default. Usually this is done by having a command line flag like `-noise <low/medium/high>` and using the provided value to configure payload sets.

A potential example of how this would look like - 

```yaml
payloads:
  escape:
     low:
        - "%00"
        - "%0a"
        - "%0a%20"
        - "%0d"
     medium:
        - "%0d%09"
        - "%0d%0a"
        - "%0d%0a%09"
        - "%0d%0a%20"
        - "%0d%20"
        - "%20"
        - "%20%0a"
        - "%20%0d"
        - "%20%0d%0a"
        - "%23%0a"
        - "%23%0a%20"
        - "%23%0d"
        - "%23%0d%0a"
        - "%23%oa"
        - "%25%30"
        - "%25%30%61"
      high:
        - "%2e%2e%2f%0d%0a"
        - "%2f%2e%2e%0d%0a"
        - "%2f..%0d%0a"
        - "%3f"
        - "%3f%0a"
        - "%3f%0d"
        - "%3f%0d%0a"
        - "%e5%98%8a%e5%98%8d"
        - "%e5%98%8a%e5%98%8d%0a"
        - "%e5%98%8a%e5%98%8d%0d"
        - "%e5%98%8a%e5%98%8d%0d%0a"
        - "%e5%98%8a%e5%98%8d%e5%98%8a%e5%98%8d"
        - "%u0000"
        - "%u000a"
        - "%u000d"
        - "\r"
        - "\r%20"
        - "\r\n"
        - "\r\n%20"
        - "\r\n\t"
        - "\r\t"
```

Other suggestions on how to achieve this are welcomed.

### Describe the use case of this feature:

Allow user configurable fuzzing scans with configurable aggression.
