### ISSUE TITLE
Auto merge parameters and paths

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3013]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/1392

<div type='discussions-op-text'>

<sup>Originally posted by **wdahlenburg** December 17, 2021</sup>
I find that I'm usually working with a lot of urls that have mixed endings. Some end in paths, others in endpoints, and some with URI parameters.

One thing that I think would go a long ways towards sending better requests would be auto merging parameters and paths.

Currently if I send `https://server.com/search?s=foobar` through the following template I will get a request made for `https://server.com/search?s=foobar/services/foo`

```
requests:
  - method: GET
    path:
      - '{{BaseURL}}/services/foo'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Foo</title>'
      - type: status
        status:
          - 200
```

Manually I'd expect the path to be merged and the parameter to be set in the correct location. I'd expect the request to go to `https://server.com/search/services/foo?s=foobar` instead.

Similarly if I send the same url through a template that defines additional parameters I'd expect the parameters are joined where possible.

Take a variation of https://github.com/projectdiscovery/nuclei-templates/blob/master/fuzzing/linux-lfi-fuzzing.yaml for example

```
- "{{BaseURL}}?name=..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd"
```

With this, I'll see a request for 
```
https://server.com?s=foobar?name=..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd
```

Manually I'd want this to be 
```
https://server.com?s=foobar&name=..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd
```

For parameters where the param already exists, I think there could be discussion about what the default case should be. Is it fine to replace the predefined parameter? Should both values be submitted? Should the value of the parameter in the template be appended to the url defined value?

A safe default could be to replace it the existing parameter value.

</div>
