### ISSUE TITLE
Support for reading keys from environment variables in report config file

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3015]
### Please describe your feature request:
Allow reading reporting config values from as env variable to avoid storing sensitive keys/credentials as plain text in a reporting and flag config file.

```yaml
github:
  username: $GITHUB_USER
  owner: $GITHUB_OWNER
  token: $GITHUB_TOKEN
  project-name: $GITHUB_PROJECT
  issue-label: $ISSUE_LABEL
  severity-as-label: false
```

### Describe the use case of this feature:

Example implementation in cloudlist - https://github.com/projectdiscovery/cloudlist/pull/257
