### ISSUE TITLE
Template protocol attribute name update

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3055]
### Please describe your feature request:

Template attribute name of the protocol that needs to be updated -

1. `requests` needs to be updated with `http`
2. `network` needs to be updated with `tcp`

> **Note**:
- *these changes will be reflected for `./nuclei -h pt` and `./nuclei -h ept` option as well.*
- *`requests` and `network` will be still supported in templates for backward compatibility and will be removed in the future.* 

#### Examples:

Current:

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/ui/"
```

Updated:

```yaml
http:
  - method: GET
    path:
      - "{{BaseURL}}/ui/"
```

### Describe the use case of this feature:
- self-explanatory protocol attribute names.
- a clear distinction between different types of protocol nuclei supports.
