### ISSUE TITLE
Support for curly brackets in payloads and etc.

### ISSUE THREAD

**Issue by cryonayes** [projectdiscovery/nuclei#3071]
I made a template to see if I can automate my SSTI exploits but unfortunately curly brackets in the payload doesn't work.
I'm sure nuclei processing them as a variable or something but I couldn't find a way to escape the curly brackets.

Here is an example template:

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    payloads:
      SSTI: 
        - "{{7*7}}"
    stop-at-first-match: true
    fuzzing:
      - part: query
        type: replace
        mode: single
        fuzz:
          - "{{SSTI}}"
    matchers:
      - type: word
        part: body
        words:
          - "49"
```
If there is a work around for this please let me know.
