### ISSUE TITLE
[issue]  Extractors don't select match groups in regex output

### ISSUE THREAD

**Issue by allwin101** [projectdiscovery/nuclei#311]
**Describe the bug**
There is no way for extractors to select match groups in a regex output. There are scenarios where a full match is not always possible due to the placement of data. That becomes a road blocker to proceed further in the flow

The root cause of the issue is related to using FindAllString in the extractor whereas FindAllStringSubmatch can return the match group.

Line 57 -> extractor.go as:

	for _, regex := range e.regexCompiled {
		matches := regex.FindAllStringSubmatch(corpus, -1)
		for _, match := range matches {
			results[match[1]] = struct{}{}
		}
	}

This code change helps to identify match group 1 of the regex output

**Nuclei version**
Version 2.1.0 

**Screenshot of the error or bug**
It would be highly helpful to use at least the first match group along with a full match. 

Credits goes to  @CasperGN in finding the root cause.

**Comment by bauthard** [comment]
Hey @allwin101, 

Thank you for creating this issue, for regex groups support, we have open PR here https://github.com/projectdiscovery/nuclei/pull/231 that will be added in the next release.

**Comment by bauthard** [comment]
@allwin101 

This support has been added here https://github.com/projectdiscovery/nuclei/commit/57fa83ca355eab8c1e39dc458bf8d7597892bc7b, if you are on master code, the following should work for your case.

```yaml
    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '"form_key" type="hidden" value="(.*)" \/> <div id="au'
```

```sh
echo https://stage51-a.cricut.com | ./nuclei -t test.yaml -silent
[basic-example] [http] https://stage51-a.cricut.com/ [5ElrnaQ6sSi0HDRG]
```

@CasperGN FYI, thank you for debugging this.

**Comment by allwin101** [comment]
Can you please send me the test yaml for the same. When I try without a proxy, I get empty results. But with proxy " -proxy-URL http://localhost:8080" I get the desired result. I have no changes made in the proxy or in the host file.

![image](https://user-images.githubusercontent.com/2221330/93456970-09516e00-f8fc-11ea-9360-0e36a7d2783d.png)

![image](https://user-images.githubusercontent.com/2221330/93457601-d2c82300-f8fc-11ea-9777-240ad0a44157.png)

**Comment by bauthard** [comment]
```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '"form_key" type="hidden" value="(.*)" \/> <div id="au'
```

```
echo https://stage51-a.cricut.com | ./nuclei -t test.yaml -silent
```
