### ISSUE TITLE
Issue with trailing slash (raw request) in latest version of nuclei

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3126]
### Nuclei version:
v2.8.4

Test template -

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /test/..;/..;/ HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
```

### Current Behavior:
nuclei make request to `https://example.com/test/..;/..;`

### Expected Behavior:
nuclei make request to `https://example.com/test/..;/..;/`

### Steps To Reproduce:
`echo https://example.com | ./nuclei -t test.yaml -debug-req`

### Anything else:
- [x] Include tests
