### ISSUE TITLE
Request condition support for network protocol

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#3141]
### Please describe your feature request:
It would be helpful to have the ability to specify a request condition based on network protocols, similar to how it is currently possible with HTTP templates.

### Describe the use case of this feature:

```yaml
network:
  - inputs:
      - data: "USER letmein:)\r\nPASS please\r\n"
    host:
      - "{{Host}}:21"

  - inputs:
      - data: "id\n"
    host:      
      - "{{Host}}:6200"  

    matchers-condition: and
    matchers:
      - type: word
        part: data_1
        words:
          - "vsFTPd 2.3.4"

      - type: word
        part: data_2
        words:
          - "uid="
          - "gid="
        condition: or
```
