### ISSUE TITLE
Target variables should be evaluated (too) in `variables` object, not just in `requests`

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#3161]
### Please describe your feature request:

As stated in the title, the target variable should be evaluated in the `variables` object of the template.

Target variables:

<img src="https://user-images.githubusercontent.com/25837540/211038565-9586b117-1de0-482b-b089-898f6b20ca28.png" height="250px">

### Describe the use case of this feature:

Real case: https://github.com/projectdiscovery/nuclei-templates/pull/6479

**Comment by dwisiswant0** [comment]
As you can see in the real case mentioned. Snippet:

```yaml
# ...
variables:
  json: |
    {
      "name": "admin",
      "nickName": "Administrator",
      "email": "admin@{{Host}}",
      "language": "en-EN",
      "resourcePermissions": {},
      "isAdministrator": true,
      "mfa": {
        "enable": false,
        "secret": "",
        "approved": false
      },
      "iat": {{unix_time()}},
      "exp": {{to_unix_time("2032-12-30T16:30:10+00:00")}}
    }
# ...
```

In the `variables` above, the helper functions (`unix_time` & `to_unix_time`) can be evaluated properly. But not with the target variable used, which is the `Host`.
