### ISSUE TITLE
issue with template (rawhttp)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3175]
### Nuclei version:
`main` | `dev` < 2.8.4

Test template:

```yaml
requests:
  - raw:
      - |+
        GET /%20test%0a HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

### Current Behavior:
```console
[INF] [test-injection] Dumped HTTP request for https://redacted/%20test%0a

GET / test
 HTTP/1.1
Host: redacted
```

### Expected Behavior:
```console
[INF] [test-injection] Dumped HTTP request for https://redacted/%20test%0a

GET /%20test%0a HTTP/1.1
Host: redacted
```
