### ISSUE TITLE
AWS Templates Variable issue

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#3202]
### Nuclei version:
2.8.7

### Current Behavior:
The engine is not picking up variables from the templates with the AWS signature.

### Expected Behavior:

The intended functionality should be to work without requiring manual input of the region and service name from cli `nuclei -t templates/sts-get-caller-identity.yaml.` However, it is currently only working when the region and service are manually provided using the flags `-V "service=sts" -V "region=us-east-1"`

```yaml
id: sts-get-caller-identity
info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info

self-contained: true
signature: aws

variables:
  service: sts
  region: us-east-1

requests:
  - raw:
      - |
        POST https://sts.us-east-1.amazonaws.com HTTP/1.1
        Host: sts.us-east-1.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.1.28 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off command/sts.get-caller-identity
        Content-Length: 43

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200
```
