### ISSUE TITLE
issue with template (rawhttp)

### ISSUE THREAD

**Issue by tess-ss** [projectdiscovery/nuclei#3207]
Nuclei version: Latest

Test template:

```yaml
requests:
  - raw:
      - |+
        GET /%20test%0a HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
```

Current Behavior:
```yaml
[INF] [test-injection] Dumped HTTP request for https://redacted/%20test%0a

GET / test
 HTTP/1.1
Host: redacted
```
Expected Behavior:

```yaml
[INF] [test-injection] Dumped HTTP request for https://redacted/%20test%0a

GET /%20test%0a HTTP/1.1
Host: redacted
```
