### ISSUE TITLE
Helper function support for date comparision

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#3225]
to write aws template and other cases where it is required to compare the data between current with response data information, we need to add new helper function that can be used to compare with the current date.

Add support for date comparison between extracted date and `{{date_time("%Y-%M-%D")}}`

For example:

```yaml
    matchers:
      - type: dsl
        dsl:
          - date > {{date_time("%Y-%M-%D")}}

    extractors:
      - type: regex
        part: body
        name: date
        group: 1
        regex:
          - '/(\d{4}-\d{2}-\d{1,2}).*/'
```
