### ISSUE TITLE
add template option to create new directory if not exists

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3246]
### Please describe your feature request:

- add template option (in headless protocol and maybe others) `allow-mkdir` or `allow-newdir`  to allow nuclei in creating new directory if path does not exists

### Describe the use case of this feature:

```yaml
id: httpscreenshot

info:
  name: Headless Http Screenshot
  author: tarunKoyalwar
  severity: info
  description: Capture screenshots of URLs
  tags: headless,screenshot

variables:
  suffix: "{{Host}}"
  dir: "screenshots"

headless:
  - steps:
      - action: setheader
        args:
          part: request
          key: "User-Agent"
          value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

      - action: navigate
        args:
          url: "{{BaseURL}}"

      - action: waitload
      - action: screenshot
        args:
          fullpage: true
          to: "{{dir}}/{{suffix}}"
```

- currently this template fails because nuclei does not create `screenshots` directory
