### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by purple-WL** [projectdiscovery/nuclei#3253]
Version: macos amd 2.8.8
Executed command：

```
./nuclei -l URL.txt -s low,medium,high,critical -o gg.txt
```

The following errors were found after running:

```console

fatal error: concurrent map writes

goroutine 688338 [running]:
github.com/antchfx/xpath.(*descendantQuery).Select.func1()
	github.com/antchfx/xpath@v1.2.2/query.go:281 +0x128
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0062ebfc0, {0x3499820, 0xc0044c7f20})
	github.com/antchfx/xpath@v1.2.2/query.go:289 +0x150
github.com/antchfx/xpath.(*filterQuery).Select(0xc00379b560, {0x3499820, 0xc0044c7f20})
	github.com/antchfx/xpath@v1.2.2/query.go:589 +0x8c
github.com/antchfx/xpath.(*NodeIterator).MoveNext(0xc0044c7f20)
	github.com/antchfx/xpath@v1.2.2/xpath.go:86 +0x38
github.com/antchfx/htmlquery.QuerySelectorAll(0xc002f247e0, 0xc004828220)
	github.com/antchfx/htmlquery@v1.2.6/query.go:83 +0x125
github.com/antchfx/htmlquery.QueryAll(0x349e080?, {0xc003f10440?, 0x1f84c45?})
	github.com/antchfx/htmlquery@v1.2.6/query.go:54 +0x52
github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors.(*Extractor).ExtractHTML(0xc0066a4fc0, {0xc0088c1c00, 0x23e})
	github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors/extract.go:79 +0x10d
github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors.(*Extractor).ExtractXPath(0x60?, {0xc0088c1c00?, 0x23e?})
	github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors/extract.go:67 +0x5d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).Extract(0x58?, 0x2b1cb40?, 0xc0066a4fc0)
	github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/operators.go:71 +0x115
github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).Execute(0xc0050f6a80, 0xc0097aa390, 0xc0059bca50, 0xc0059bca38, 0x0)
```

**Comment by ehsandeep** [comment]
### To reproduce:

### payload file -

```
seq 1000 > test.txt
```

### template -

```yaml
id: test

info:
    name: test
    author: test
    severity: info

requests:
  - raw:
      - |
        GET /?{{param}}=1 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /?{{param}}=2 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /?{{param}}=3 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /?{{param}}=4 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /?{{param}}=5 HTTP/1.1
        Host: {{Hostname}}

    threads: 5
    attack: batteringram
    payloads:
        param: test.txt

    matchers:
        - type: word
          words:
              - 'aaaaaaaaaaa'
```

```
nuclei -t template.yaml -u http://0.0.0.0:61178/
```
