### ISSUE TITLE
double url encoding issue in non-unsafe templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3292]
### Nuclei version:

dev | main

### Current Behavior:

```yaml
requests:
  - raw:
    - |+
        GET {{Path}}%0D%0ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
        Connection: close
```
Nuclei while running this template double encodes the payload and dumps below http request

```console
[INF] [crlf-injection] Dumped HTTP request for https://example.com/foo/%0D%0ASet-Cookie:crlfinjection=crlfinjection

GET /foo/%250D%250ASet-Cookie:crlfinjection=crlfinjection HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```

### Expected Behavior:

- If possible nuclei should avoid double url encoding special characters 

### Anything else:

- cause https://github.com/projectdiscovery/utils/blob/main/url/README.md
