### ISSUE TITLE
Raw Request Bug [Slash is added with UnSafe=true]

### ISSUE THREAD

**Issue by Impact-I** [projectdiscovery/nuclei#3326]
### Nuclei version:
[INF] Current Version: 2.8.9

### Current Behavior:
When sending a raw request, a '/' is added.

### Expected Behavior:
Raw request to be sent as described in the yaml.

### Steps To Reproduce:
**Template:**
```yaml
id: C

info:
  name: C
  author: C
  description: C
 
requests:
  - raw:
      - |+
        GET 1337 HTTP/1.1
        Host: google.com

    unsafe: true
```
**Command:**
```bash
./nuclei -debug -t temple.yaml -u http://google.com
```

2. Notice that instead of a GET 1337 is sent, actually GET /1337 is sent.

OS: Windows 10, Ubuntu 18.04
