### ISSUE TITLE
Request generation failure when url contains %u encoded patterns

### ISSUE THREAD

**Issue by denizcevik** [projectdiscovery/nuclei#3334]
Here is tested environment version details

```
Nuclei Engine 2.8.9 (latest)
Nuclei Templates 9.3.7 (latest)
```

Sample template portion:

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/%u002e/WEB-INF/web.xml"
```

When defined test pattern is like above, nuclei is generating request as below.

```
GET /https://hostname/%25u002e/WEB-INF/web.xml HTTP/1.1
Host: hostname
User-Agent: Go-http-client/1.1
```

It seems there is a problem when %u encoded patterns are used.
