### ISSUE TITLE
`No results found error` when match found with `self-contained` template

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei#3338]
### Nuclei version:
v2.8.9

### Current Behavior:
```yaml
[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 1
[sherlock-username:7cups] [http] [info] https://www.7cups.com/@blue
[INF] No results found. Better luck next time!
```

### Expected Behavior:
```
[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 1
[sherlock-username:7cups] [http] [info] https://www.7cups.com/@blue
```
### Steps To Reproduce:

```yamll
id: sherlock-username

info:
  name: Sherlock Username Enumeration
  author: DhiyaneshDk
  severity: info
  description: Hunt down social media accounts by username across social networks
  reference:
    - https://github.com/sherlock-project/sherlock
    - https://sherlock-project.github.io/
  tags: token-spray,sherlock,enum,osint

self-contained: true

requests:
  - method: GET
    path:
      - "https://www.7cups.com/@{{username}}"

    matchers:
      - type: word
        part: body
        name: 7cups
        words:
          - 'screenName:'
          - 'userType:'
          - 'userIDe:'
        condition: and
```

```bash
nuclei -var username=blue -t test.yaml
```
-->
