### ISSUE TITLE
Support for URL Fuzzing in headless protocol

### ISSUE THREAD

**Issue by theamanrawat** [projectdiscovery/nuclei#3339]
Currently, nuclei does not support for headless in fuzzing-templates. It would be great if you can add a support for this. 

This feature would be great to create fuzzing templates for vulnerability which needs to be run on headless browser i:e., DOM XSS.

```yaml
id: headless-query-fuzzing

info:
  name: Example Query Fuzzing
  author: pdteam
  severity: info

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"
      - action: waitload

    payloads:
      redirect:
        - "evil.com"

    fuzzing:
      - part: query
        mode: single
        fuzz:
          - "https://{{redirect}}"

    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?:\/\/|\/\/|\/\\\\|\/\\)?(?:[a-zA-Z0-9\-_\.@]*)evil\.com\/?(\/|[^.].*)?$' # https://regex101.com/r/ZDYhFh/1
```

### Anything else?

https://github.com/projectdiscovery/nuclei-templates/issues/7240
