### ISSUE TITLE
support for http request with list of hosts from `ssl_subject_an` and `ssl_subject_cn` as Host header

### ISSUE THREAD

**Issue by venom26** [projectdiscovery/nuclei#3349]
Hey team,
Opening this feature request to integrate TLSx with nuclei

### Please describe your feature request:
When I pass IP address as input to nuclei, I want an option to use domains mentioned in that ip's SSL certificate as a host header.

### Describe the use case of this feature:
Sometimes, there are some IP addresses that we can not access directly, we need to provide a valid host to them. Or even sometimes changing the host header for different hosts gives different outputs. So integrating TLSx will be helpful in this case. 

### How TLSx can be used:
Once an IP address or IP addresses are passed to nuclei for scanning there should be an option that will enable to use TLSx. Now TLSx will extract domains from that particular IP address SSL certificate and will use it as the host header. If multiple domains are mentioned in SSL certificate of an IP address, then nuclei should make multiple requests to that IP address by changing the appropriate host header which was found from TLSx output.

**Comment by ehsandeep** [comment]
@venom26 this is now possible with latest release of nuclei.

```yaml
id: ssl-vhost

info:
  name: Flow + Iteration
  author: pdteam
  severity: info

flow:
  ssl();
  for (let vhost of iterate(template["ssl_domains"])) {
    set("vhost", vhost);
    http();
  }

ssl:
  - address: "{{Host}}:{{Port}}"

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    headers:
      Host: "{{vhost}}"

    extractors:
      - type: dsl
        dsl:
          - '"HOST: " + vhost + " | STATUS: "+ status_code + " | SIZE: " + content_length'
```
