### ISSUE TITLE
bug: default matcher-condition 'or' cannot work

### ISSUE THREAD

**Issue by Bisstocuz** [projectdiscovery/nuclei#3350]
### Nuclei version:

nuclei v2.8.9
nuclei-templates v9.3.7

### Current Behavior:
> 	// description: |
	//   MatchersCondition is the condition between the matchers. Default is OR.
	// values:
	//   - "and"
	//   - "or"

Default `matcher-condition` value is `or`, and `or` condition cannot work properly. 
```yaml
requests:
  - raw:
      - |
        GET /?paytm_action=curltest&url={{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "http"

      - type: word
        part: body
        words:
          - "paytm-payments.css"

      - type: status
        status:
          - 200
```
Status code 200 matched but no successful result.
![image](https://user-images.githubusercontent.com/42398278/220310567-0c06b2ea-65e9-4aa4-888a-b6673209cf49.png)

### Expected Behavior:

The template's match should be successful.

### Steps To Reproduce:
1. Use template: https://github.com/projectdiscovery/nuclei-templates/blob/main/cves/2022/CVE-2022-45362.yaml
2. Request to any web service that always return status code 200
