### ISSUE TITLE
Payload handling issue in `self-contained` template in base format

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3361]
### Nuclei version:
latest/dev

`var_test.yaml`

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

self-contained: true
requests:
  - method: GET
    path:
      - "https://example.com/{{test}}"
```

`number.txt`

```console
1
2
```

### Current Behavior:
```console
[WRN] [basic-example] Could not make http request for https://example.com/{{test}}: unresolved variables found: test
```

### Expected Behavior:
```console
[VER] [basic-example] Sent HTTP request to https://example.com/1
[VER] [basic-example] Sent HTTP request to https://example.com/2
```

### Steps To Reproduce:
```console
nuclei -t var_test.yaml -var test=number.txt -v
```

### Anything else:
This is only an issue with `self-contained` in the template in base format, raw format or non `self-contained` base format works as expected.

### Affected template

- [token-spray](https://github.com/projectdiscovery/nuclei-templates/tree/main/token-spray) templates (in base format) used with file input for tokens
- [OSINT templates](https://github.com/projectdiscovery/nuclei-templates/pull/6776) with file input for usernames.
