### ISSUE TITLE
[issue] condition between matcher and extractor

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#340]
**Describe the bug**
If a matcher and extractor are used in the same template, the default condition between both is OR, that set the wrong impressions while using the template, in cases where both `matcher` and `extractor` is used, in most cases it is expected, the extractor will be used on the matched result, but listed PR as a reference, even matcher is not matcher, the extractor returns true. 

**Nuclei version**
2.1.1

Below example will return FALSE. 

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers:
      - type: word
        words:
          - Exporter # Exporters have "Exporter" in the page title (e.g, Node Exporter, Bind Exporter and so on)
          - /metrics
        condition: and
```

the same example used with `extractors` will return true. 

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    matchers:
      - type: word
        words:
          - Exporter # Exporters have "Exporter" in the page title (e.g, Node Exporter, Bind Exporter and so on)
          - /metrics
        condition: and
    extractors: # Extract exporter name
      - type: regex
        part: body
        name: exporter_name
        group: 1
        regex:
          - "<title>(.*?)</title>"
```

This is because nuclei is default to OR when multiple matchers is used which is expected and that's doesn't go well in combination with `extractors`. 

Possible solutions:- 

When `matchers` and `extractors` both are used, we can default (implicit) to set ` matchers-condition: and`?

**Reference**
https://github.com/projectdiscovery/nuclei-templates/pull/537
