### ISSUE TITLE
Support for dynamic extractors in dns protocol 

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3409]
### Please describe your feature request:
This support will extend dns protocol to write multi-step dns based detections.
### Describe the use case of this feature:

```yaml
id: dns-template

info:
  name: basic dns template
  author: pdteam
  severity: info

dns:
  - name: "{{FQDN}}"
    type: NS

  - name: "{{ns}}"
    type: A

    extractors:
      - type: regex
        name: ns
        group: 1
        regex:
          - "IN\tNS\t(.+)"
        internal: true

    matchers:
      - type: word
        part: status_code_2
        words:
          - 'refused'
          - 'servfail'
        condition: or
```

```console
echo gslink.hackerone.com | nuclei -t ns-dns-status.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9

    projectdiscovery.io

[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.9 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[VER] [dns-template] Sent DNS request to gslink.hackerone.com.
[VER] [dns-template] Sent DNS request to ns-1171.awsdns-18.org.
[VER] [dns-template] Sent DNS request to ns-1832.awsdns-37.co.uk..
[VER] [dns-template] Sent DNS request to ns-481.awsdns-60.com.
[VER] [dns-template] Sent DNS request to ns-733.awsdns-27.net.
[INF] No results found. Better luck next time!
```

### Reference
- https://github.com/projectdiscovery/nuclei/discussions/2934
