### ISSUE TITLE
expose dns reponse fields as key value pairs

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3411]
### Please describe your feature request:
To ease the writing of dns template to match / extractor dns field values, similar to SSL protocol (tlsx) response, dns responses fields can be made available as key-value pairs.

```yaml
id: dns-template

info:
  name: basic dns template
  author: pdteam
  severity: info

dns:
  - name: "{{FQDN}}"
    type: CNAME

    matchers:
      - type: word
        part: rcode
        words:
          - 'noerror'

    extractors:
      - type: dsl
          - rcode
          - cname
          - a
          - aaaa
```

### Describe the use case of this feature:
- would help write [complex dns templates](https://github.com/projectdiscovery/nuclei/issues/3409).
