### ISSUE TITLE
payloads support in dns protocol

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3412]
### Please describe your feature request:

```yaml
id: dns-brute

info:
  name: basic dns template
  author: pdteam
  severity: info

dns:
  - name: "{{subdomain_wordlist}}.{{FQDN}}"
    type: A

    attack: batteringram
    payloads:
      subdomain_wordlist: '{{wordlist}}'

    matchers:
      - type: word
        words:
          - "NOERROR"
```
### Describe the use case of this feature:

```console
nuclei -t dns-brute.yaml -list domains.txt -var wordlist=/usr/local/dns_wordlist.txt -r resolvers.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9

    projectdiscovery.io

[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.9 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 18
[INF] Targets loaded for scan: 21
[INF] Templates clustered: 12 (Reduced 168 Requests)
[dns-brute] [dns] [info] www.hackerone.com
[dns-brute] [dns] [info] support.hackerone.com
[dns-brute] [dns] [info] gslink.hackerone.com
```
