### ISSUE TITLE
Global / Dynamic variables to support in template context  (multi protocol execution)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3413]
### Please describe your feature request:
From discord -

> Is there a way to use extracted values from requests in the dns section? I have extracted a value after making a web request; however, it doesn't seem available from the subsequent dns section.

### Current behavior:

Extracted variables are only available within the same request context.

### Desired behavior

Extracted variables should be accessible within the template context to any or all protocols.

### Dynamic extractor to use with multi-protocol template

```yaml
id: dns-http-template

info:
  name: dns + http takeover template
  author: pdteam
  severity: info

dns:
  - name: "{{FQDN}}" # DNS Request
    type: cname

    extractors:
      - type: dsl
        name: cname
        dsl:
          - cname
        internal: true

http:
  - method: GET # http request
    path:
      - "{{BaseURL}}"

    matchers:
      - type: dsl
        dsl:
          - contains(body,'Domain not found') # check for http string
          - contains(cname, 'github.io') # check for cname (extracted information from dns response)
        condition: and
```

### Global protocol variables with multi-protocol template

```yaml
id: nuclei-multi-protocol

info:
  name: multi protocol support
  author: pdteam
  severity: info

dns:
  - name: "{{FQDN}}" # dns request 
    type: cname

ssl:
  - address: "{{Hostname}}" # ssl request

http:
  - method: GET
    path:
      - "{{BaseURL}}" # http request

    headers:
      Host: "{{ssl_subject_cn}}" # host extracted from ssl request

    matchers:
      - type: dsl
        dsl:
          - contains(http_body,'Domain not found') # check for http string
          - contains(dns_cname, 'github.io') # check for cname
        condition: and
```
