### ISSUE TITLE
error when i create template

### ISSUE THREAD

**Issue by deep1chil** [projectdiscovery/nuclei#3418]
```console
nuclei -u http://testphp.vulnweb.com/ -t myxss.yaml            

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.3

                projectdiscovery.io

[WRN] Found 1 templates with syntax error (use -validate flag for further examination)
[INF] Using Nuclei Engine 2.8.3 (outdated)
[INF] Using Nuclei Templates 9.3.9 (latest)
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found
```                                                                                                       

my template

```yaml
id: Reflected XSS

info:
  name: Reflected Cross-Site Scripting (XSS)
  author: daffainfo
  severity: medium

requests:
  - method: GET
    path:
      - '{{BaseURL}}/search?q=%22%3E%3Cscript%3Ealert%28123%29%3C/script%3E'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<script>alert(123)</script>"
        part: body

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
