### ISSUE TITLE
Utility to calculate / write max request counter for nuclei templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3443]
### Description:
Currently, there is no way to determine the maximum number of requests that can be generated using a Nuclei template. It would be useful to have a utility that can calculate this value and store it in the metadata section of the template.

### Proposal:
Create a new utility that can calculate the maximum number of requests that can be generated using a given Nuclei template. The utility can analyze the template's structure and estimate the number of unique inputs and their combinations. The estimated value can be written in the metadata section of the input template in the following format:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  metadata:
    max_request: 2

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}"

    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 200
```

The new utility can calculate that this template can generate a maximum of 2 requests. This value can be added to the metadata section as follows:

```yaml
  metadata:
    max-request: 2
```

Here is another example:

<details><summary>template</summary>
<p>

```yaml
id: akamai-s3-cache-poisoning

info:
  name: Akamai/Amazon S3 - Cache Poisoning
  author: DhiyaneshDk
  severity: medium
  metadata:
    max_request: 209

variables:
  rand: "{{rand_base(5)}}"

requests:
  - raw:
      - |+
        GET /nuclei.svg?{{rand}}=x HTTP/1.1
        Host: {{Hostname}}
        {{escape}}Host: {{bucket}}

      - |+
        GET /nuclei.svg?{{rand}}=x HTTP/1.1
        Host: {{Hostname}}

    attack: clusterbomb
    payloads:
      escape:
        - "\x0b"
        - "\x0c"
        - "\x1c"
        - "\x1d"
        - "\x1e"
        - "\x1f"

      bucket:
        - "nuclei-ap-northeast-1"
        - "nuclei-ap-northeast-2"
        - "nuclei-ap-northeast-3"
        - "nuclei-ap-south-1"
        - "nuclei-ap-southeast-1"
        - "nuclei-ap-southeast-2"
        - "nuclei-ca-central-1"
        - "nuclei-eu-central-1"
        - "nuclei-eu-north-1"
        - "nuclei-eu-west-1"
        - "nuclei-eu-west-2"
        - "nuclei-eu-west-3"
        - "nuclei-sa-east-1"
        - "nuclei-us-east-1"
        - "nuclei-us-east-2"
        - "nuclei-us-west-1"
        - "nuclei-us-west-2"

    stop-at-first-match: true
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_2, "alert(document.domain)")'
          - 'status_code_2 == 200'
        condition: and
```

</p>
</details> 

### Use Case
- This feature would be very useful for users who want to estimate the scope and impact of running a particular Nuclei template in their security testing efforts.
- Run template based on max request counter with `-template-condition` filter, for ex: `nuclei -tc 'max_request <= 10'`

This utility will be added in the [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates) project's CI workflow to populate max request information for all the existing and new templates.
