### ISSUE TITLE
Extractor Support to write  network templates

### ISSUE THREAD

**Issue by pussycat0x** [projectdiscovery/nuclei#3465]
### Please describe your feature request:

Need support to export variables through extractor in network templates.

### Describe the use case of this feature:

Example template
```
network:

  - inputs:
      - data: 00156e00050007499c4141414141414041414141414141
        type: hex
        read: 1024
      - data: {{support}}}
        read: 1024
    host:
      - "{{Hostname}}:9100"

    extractors:
      - type: regex
        name: support
        internal: true
        regex:
         - '.*'
 ```
