### ISSUE TITLE
[feature] Injection marker rework for fuzzing

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#347]
**Is your feature request related to a problem? Please describe.**
As of now, when doing fuzzing, we define payload variables and call it using variable name wishing requests which sometimes get confusing.

Current flow:- 

```yaml
- payloads:
      test: wordlist.txt

    attack: sniper

    raw:
      - |
        GET /test HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
        Accept: application/json, text/plain, */*
        Accept-Language: en-US,en;q=0.5
        Referer: {{BaseURL}}
```

**Describe the solution you'd like**

Add unique marker when using the variable name in the request, some like `§variable_name§`

```yaml
- payloads:
      test: wordlist.txt

    attack: sniper

    raw:
      - |
        GET /§test§ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
        Accept: application/json, text/plain, */*
        Accept-Language: en-US,en;q=0.5
        Referer: {{BaseURL}}
```
