### ISSUE TITLE
Weird behaviour when handling paths in rawhttp defined requests

### ISSUE THREAD

**Issue by SecGus** [projectdiscovery/nuclei#3475]
I have the following template which I am running through nuclei:
```
requests:
  - raw:
      - |+
        GET  HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Accept-Language: en-GB,en;q=0.5
        Accept-Encoding: gzip, deflate
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0


      
      - |+
        GET {{md5(headers)}}=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0



    unsafe: true
    matchers:
      - type: dsl
        dsl:
         - "status_code_1 == 200"
    redirects: false
    req-condition: false
 ```
 
 When running the following command, it sends the following request:
 `echo "https://example.com/" | nuclei -t cpdos.yaml -dreq`

```
GET  HTTP/1.1
Host: example.com
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
```

Notice the lack of a path. When I saw this, I guessed I should manually add {{Path}} as I am using rawhttp. However, when the URL naturally includes a path, such as /testing, and there is something already defined where the path would go, such as a parameter (notice in the rawhttp request the question mark), the following happens:
`echo "https://example.com/testing/" | nuclei -t cpdos.yaml -dreq`
```
requests:
  - raw:
      - |+
        GET ? HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Accept-Language: en-GB,en;q=0.5
        Accept-Encoding: gzip, deflate
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
```

```
GET /testing/ HTTP/1.1
Host: example.com
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
```

Notice the URL has been appended.

To summarise, this means that when piping standard input to the nuclei template, when a URL ends only in `/`, and not {{Path}} variable is defined in the template, it will not work, as the path in the HTTP Request is sent as blank. Whereas, if you include the {{Path}} variable in the rawHTTP request, and then pipe a URL that already has a path on it to it, the path is included twice.

This ultimately leads to there being no viable rawhttp request definition that can be applied to situations where both a path, and no path is being passed to the template.
