### ISSUE TITLE
Cannot set Hostname in parameter

### ISSUE THREAD

**Issue by td4b** [projectdiscovery/nuclei#3479]
### Please describe your feature request:
At the moment you cannot set {{Hostname}} or any other variable in payload parameters within templates so they can be interpolated.

```yaml
 payloads:
      username:
        - jon.doe@{{Hostname}}
      password:
        - dsabkuasbdaobfdugkh
```

### Describe the use case of this feature:
This would allow you to write exploit checks for cloud services. As an example I posted a description of the template implementation here for attacking Autodiscovery on Exchange.
https://github.com/projectdiscovery/nuclei-templates/issues/6977

In summary the overall template would look something like this:

```yaml
id: autodiscover-login
info:
  name: Auto Discover Information Disclosure
  author: td4b
  severity: medium
  tags: exchange,misconfig
requests:
  - method: GET
    path:
      - "https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml"
    headers:
      Authorization: Basic {{base64(username + ':' + password)}}
    attack: pitchfork
    payloads:
      username:
        - jon.doe@{{Hostname}}
      password:
        - dsabkuasbdaobfdugkh
    matchers-condition: and
    matchers:
      - type: word
        part: all_headers
        words:
          - "X-Autodiscovery-Error: LiveIdBasicAuth:InvalidCreds"
          - "<LogonFailed-BadPassword>"
        condition: and
      - type: word
        part: body
        words:
          - "<Response>"
          - "<Message>Invalid Request</Message>"
        condition: and

      - type: status
        status:
          - 401
```

Where the attack can be performed via:

```bash
nuclei -t template.yaml -u https://targetdomain.com
```

The -u parameter is used essentially to append to username to check if basic auth is enabled or blocked on the auto-discovery service.

I'm not sure if there are other cloud services where something similar can be explored but figured i would put this out there. 

Thanks!
