### ISSUE TITLE
Add support for LLM via helper function/matcher/extractor

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3480]
### Please describe your feature request:
It would be interesting to explore usages of LLM as helper functions, for example:

```yaml
requests:
  - raw:
      - |
        GET / HTTP/1.1
      - |
        POST / HTTP/1.1
        blabla: blabla

        {{llm_prompt("write a random json object using values from " + body_1)}}
```

Or as DSL matcher/extractors:

```yaml
    extractors:
      - type: dsl
        dsl:
          - 'llm_prompt("what tech this server is using? return idk if you dont know" + header)'
```
