### ISSUE TITLE
Support nested key variables

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#3525]
### Please describe your feature request:
I'm having trouble accessing nested data structures in my templates using the current syntax for declaring variables. It would be helpful if the template language could support nested key variables.

Thus, I would like to be able to define nested variables using YAML syntax in my templates, see the example template provided below.

### Describe the use case of this feature:

Here's an example of how I'd like to define and use nested variables in my templates:
```yaml
variables:
  data: '{name: "dw1"}'
  json: json_parse(data) # func json_parse(...) interface{}

{{json.name}} # Output: dw1

# or

variables:
  data:
    name: dw1

{{data.name}} # Output: dw1
```

or

```yaml
variables:
  data:
    first_name: "John"
    last_name: "Doe"
    full_name: {{concat(first_name, " ", last_name)}}
    age: 30
    address:
      street: "123 Main St"
      city: "Anytown"
      state: "CA"
      zip: "12345"

{{data.first_name}} # Output: John
{{data.address.city}}, {{data.address.state}} {{data.address.zip}} # Output: Anytown, CA 12345
```

That would allow me to work with more complex data structures and reference properties within those structures using dot notation.

I believe that adding support for nested key variables would greatly improve the flexibility and readability of templates. It would also make it easier to work with structured data and reduce the need for custom helper functions or manual parsing of JSON strings.
