### ISSUE TITLE
severity not marked as required attribute  

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3528]
### Nuclei version:
dev | main

### Current Behavior:
nuclei process templates without severity attribute.

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
#  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
```

```console
nuclei -t test.yaml -validate

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.1

		projectdiscovery.io

[INF] All templates validated successfully
```

### Expected Behavior:
```console
nuclei -t test.yaml -validate

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.1

		projectdiscovery.io

[ERR] Error occurred loading template /Users/geekboy/Github/test.yaml: mandatory 'severity' field is missing
[FTL] Could not validate templates: errors occured during template validation
```

### Anything else:

> **Info** : `severity` is optional for workflows.
