### ISSUE TITLE
[issue] fuzzing issue with multiple request

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#354]
**Describe the bug**

<details><summary> test fuzzing template</summary>

```yaml
id: multiple-raw-example
info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:

# HTTP Intruder fuzzing wordlist based payload support. 

  - payloads:
      username:
        - 'test1'
        - 'test2'

      password:
        - 'test3'
        - 'test4'

    attack: clusterbomb

    # Available types: sniper, pitchfork and clusterbomb

    raw:
      - |
        GET /§username§ HTTP/1.1
        Host: {{Hostname}}

      - |
        POST / HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
        Host: {{Hostname}}
        Accept: §password§

    matchers:
      - type: word
        words:
          - "Test is test matcher text"
```

</details>

This template will make 5 requests in total, 1 base request, 4 based on the number of payloads.

Bug:-  All 4 requests get sent to 1st request defined in the block. 

**Note:-** This bug also exists in the last stable release. 

**Nuclei version**
master version

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
