### ISSUE TITLE
Semicolon in GET requests Removed

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei#3574]
### Nuclei version:
v2.9.2

### Current Behavior:

Semi Colon Get's Removed 

```
GET /ctc/servlet/ConfigServlet?param=com.sap.ctc.util.FileSystemConfigEXECUTE_CMDCMDLINE=tasklist HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```

### Expected Behavior:

```
GET /ctc/servlet/ConfigServlet?param=com.sap.ctc.util.FileSystemConfig;EXECUTE_CMD;CMDLINE=tasklist HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```

### Steps To Reproduce:

`nuclei -t test.yaml -u example.com -debug-req`

```yaml
id: semi-colon-breakage

info:
  name: Semi Colon Breakage
  author: dhiyaneshDk
  severity: unknown
  tags: etc

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ctc/servlet/ConfigServlet?param=com.sap.ctc.util.FileSystemConfig;EXECUTE_CMD;CMDLINE=tasklist"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Test'

        part: body
      - type: status
        status:
          - 200
```
