### ISSUE TITLE
`template-condition` update to support selecting key/values under classification

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3575]
### Please describe your feature request:
```yaml
id: CVE-2023-28432
info:
  name: Minio Cluster Deployment - Information Disclosure
  author: Mr-xn
  severity: high
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2023-28432
    cwe-id: CWE-200
    cpe: cpe:2.3:a:minio:minio:*:*:*:*:*:*:*:*
    epss-score: 0.01489
  metadata:
    fofa-query: app="Minio"
    shodan-query: title:"Minio Console"
    verified: true
    max-request: 10
  tags: cve,cve2023,minio,console,exposure
```
Currently, this is possible for the metadata section but not for classification.

Current working example with metadata section.

```
nuclei -tc 'verified == "true"'
```

### Describe the use case of this feature:
- Load all the templates where `cpe == "XXX"`
- Load all the templates where `cpe` **contains** `"XXX"`
- Load all the templates where `cvss-score == 7.5`
- Load all the templates where `cvss-score => 5.0`
- Load all the templates where `cvss-metrics == "XXX"`
- Load all the templates where `cvss-metrics` **contains** `"PR:N"`
- Load all the templates where `max_request <= 10`

Examples:

```
nuclei -tc 'cpe == "cpe:2.3:a:minio:minio:*:*:*:*:*:*:*:*"'
nuclei -tc 'contains(cpe, "cpe:2.3:a:minio:minio:*:*:*:*:*:*:*:*")'
nuclei -tc 'cvss_score == 7.5'
nuclei -tc 'cvss_score => 5.0'
nuclei -tc 'cvss_metrics == "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N")'
nuclei -tc 'contains_any(cvss_metrics, "AC:L", "AV:N")'
nuclei -tc 'max_request <= 10'
```
