### ISSUE TITLE
The value of the variable once calculated does not change.

### ISSUE THREAD

**Issue by atlassion** [projectdiscovery/nuclei#3580]
"Variables can be used to declare some values which remain constant throughout the template. The value of the variable once calculated does not change. "

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

variables:
 a1: "{{to_lower(rand_base(5))}}"


requests:
  - method: GET
    path:
      - "{{BaseURL}}/?x={{a1}}"
      - "{{BaseURL}}/?x={{a1}}"

    extractors:
      - type: dsl
        dsl:
          - a1
```

Current:

```console
echo https://example.com | nuclei -t test.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: v9.4.2 (latest)
[INF] New templates added in latest release: 78
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[basic-example] [http] [info] https://example.com/?x=s0lon [s0lon]
[basic-example] [http] [info] https://example.com/?x=ljxy2 [ljxy2]
```

Expected:

```console
echo https://example.com | nuclei -t test.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: v9.4.2 (latest)
[INF] New templates added in latest release: 78
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[basic-example] [http] [info] https://example.com/?x=s0lon [s0lon]
[basic-example] [http] [info] https://example.com/?x=s0lon [s0lon]
```
