### ISSUE TITLE
Add negative: true for Conditional Workflows

### ISSUE THREAD

**Issue by hazanasec** [projectdiscovery/nuclei#3582]
Currently workflows only allow templates based condition check in which a workflow will execute subtemplates when base template gets matched.

### Please describe your feature request:
Include a negative check to only execute a template if template x was not matched. For example we can execute fuzzers only if WAF template does not detect the use of a WAF.  This will help avoid sending uncessary requests and being blocked.

### Describe the use case of this feature:
```
workflows:
  - template: technologies/jenkins-detect.yaml
    subtemplates:
      - template: technologies/waf-detect.yaml
         negative: true
       subtemplates:
          - fuzzing/custom-jenkins-fuzzer.yaml
```
