### ISSUE TITLE
X-Amz-Content-SHA256 header missing when using AWS signature

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#3597]
### Current Behavior:
When running a self-contained AWS signature template, the X-Amz-Content-SHA256 header is not being added. This results in authentication errors and prevents the successful execution of the template.

### Steps To Reproduce:
- Try running `aws s3api create-bucket --bucket randombucketname3233`

```yaml
id: create-s3-bucket
info:
  name: Create S3 Bucket
  author: princechaddha
  severity: info
  description: |
    Creadted s3 bucket in you amazon account
  reference:
    - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcs.html
    - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFlowLogs.html
  remediation: Enabling VPC Flow Logs
  tags: cloud,devops,aws,amazon,cloudtrail,s3

self-contained: true
signature: aws
variables:
  service: s3
  region: us-east-1
  bucketname: randombucketname3233

requests:
  - raw:
      - |
        PUT https://{{bucketname}}.{{region}}.amazonaws.com/ HTTP/1.1
        Host: {{bucketname}}.s3.{{region}}.amazonaws.com
        User-Agent: aws-cli/2.9.15 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off command/s3api.create-bucket

    iterate-all: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '</LoggingEnabled>'
```
