### ISSUE TITLE
URL parameters duplication issue in self-contained template in raw http format

### ISSUE THREAD

**Issue by vallelianc** [projectdiscovery/nuclei#3604]
### Nuclei version:
Nuclei v.2.9.2

### Current Behavior:
```yaml
id: test

info:
  name: test
  author: test

self-contained: true
requests:
  - raw:
    - |
      GET http://example.com/user?param=value HTTP/1.1
      Host: example.com

  - method: GET
    path:
      - "http://example.com/user?param=value"
```

The issue is similar to #3208, but with URL parameters:

```
nuclei -t test.yaml -v 
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[VER] [test] Sent HTTP request to http://example.com/user?param=value&param=value
[VER] [test] Sent HTTP request to http://example.com/user?param=value
[INF] No results found. Better luck next time!
```


### Expected Behavior:
```
$ nuclei -t test.yaml -v                                                                                                                                                                                                                                   
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[VER] [test] Sent HTTP request to http://example.com/user?param=value
[VER] [test] Sent HTTP request to http://example.com/user?param=value
[INF] No results found. Better luck next time!
```
### Steps To Reproduce:
```
nuclei -t test.yaml -v 
```
