### ISSUE TITLE
duplicated parameters in self contained templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3610]
### Nuclei version:

dev | main

### Current Behavior:

- if self-contained template contains parameters . those are duplicated in actual outgoing http request

### Steps To Reproduce:

```yaml
id: example-self-contained-input

info:
  name: example-self-contained
  author: pd-team
  severity: info

self-contained: true
requests:
  - raw:
      - |
        GET http://127.0.0.1:5431/?something=here&key=value HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: word
        words:
          - This is self-contained response%                                                               
```

```console
$ nuclei -t self-contained-with-params.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

		projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] [example-self-contained-input] Dumped HTTP request for http://127.0.0.1:5431/?key=value&key=value&something=here&something=here

GET /?key=value&key=value&something=here&something=here HTTP/1.1
Host: 127.0.0.1:5431
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2919.83 Safari/537.36
Connection: close
Accept-Encoding: gzip

[WRN] [example-self-contained-input] Could not execute request for : GET http://127.0.0.1:5431/?key=value&key=value&something=here&something=here giving up after 2 attempts: Get "http://127.0.0.1:5431/?key=value&key=value&something=here&something=here": could not connect to any address found for host
[INF] No results found. Better luck next time!
```

### Anything else:

cc: @DhiyaneshGeek
