### ISSUE TITLE
option to save extractors data to file

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3611]
### Please describe your feature request:

- similar to headless requests where it is possible to save screenshot to file. it should be possible to save results of `extractors` to a file
cc: @DhiyaneshGeek 

- example
```yaml
    extractors:
      - type: regex
        part: body
        regex:
          - '[0-9]+'
        to: output.txt
```

## Possible use cases

-  saving secrets/keys/emails found in js files to file (something like custom fields in katana) and other similar use cases
