### ISSUE TITLE
ANY query support in dns protocol

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3643]
### Please describe your feature request:
```yaml
id: any-fingerprinting

info:
  name: ANY Fingerprint
  author: pdteam
  severity: info

dns:
  - name: "{{FQDN}}"
    type: ANY

    extractors:
      - type: dsl
        dsl:
          - a
          - aaaa
          - came
```

### Describe the use case of this feature:

```
echo google.com | ./nuclei -t any.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[any-fingerprinting] [dns] [info] google.com [142.250.193.206,2404:6800:4002:81c::200e]
```
