### ISSUE TITLE
self-contained template support for dns protocol

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3661]
### Please describe your feature request:
Support for `self-contained` template in dns protocol to run more specific dns based cloud checks.

### Describe the use case of this feature:

```yaml
id: cloud-enum-azure-vm

info:
  name: Cloud Enumeration - Azure Virtual Machines
  author: initstring
  severity: info
  description: Searches for Azure virtual machines via their registered DNS names
  reference: tba
  tags: cloud,azure

self-contained: true
variables:
  baseDNS: "cloudapp.azure.com"


dns:
  - name: "{{keyword}}.{{regionName}}.{{baseDNS}}"
    type: A

    attack: batteringram
    payloads:
      regionName:
        - eastasia
        - southeastasia
        - centralus
        - eastus
        - eastus2
        - westus
        - northcentralus
        - southcentralus
        - northeurope
        - westeurope
        - japanwest
        - japaneast
```

```console
nuclei -t dns.yaml -var keyword=list.txt
```

## Anything else

https://github.com/projectdiscovery/nuclei-templates/pull/6865
