### ISSUE TITLE
Special string URL encoding problem   

### ISSUE THREAD

**Issue by ltfafei** [projectdiscovery/nuclei#3695]
I found:
```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/v1/docs//..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\..\\\/windows/win.ini"
```

can't Pass detection. 

I want string \\ escape \, Resplice /，but nuclei Impossible to achieve

I don't want it to URL encode. but I found method: GET or raw request, They're URL encoded
