### ISSUE TITLE
Add support for constants

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3696]
### Please describe your feature request:
In some cases it's necessary to define constants scalar values that will never change during template execution regardless of runtime dynamic values and CLI override.

### Describe the use case of this feature:
```yaml
variables:
  a: test
constants:
  c: test
```
