### ISSUE TITLE
[feature] Implement requests-condition: and for templates with multiple requests

### ISSUE THREAD

**Issue by harisec** [projectdiscovery/nuclei#370]
**Is your feature request related to a problem? Please describe.**
When we have a template with multiple requests they are evaluated by default using **OR**: the template is alerted when one request is successful OR another request is successful.

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/?test=1"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/?test=2"
    matchers:
      - type: status
        status:
          - 302
```

**Describe the solution you'd like**
I would like to have the option to make templates where request 1 is successful AND request 2 is successful. 

For example, with one request you make a change to the server (you create a file via PUT) and with the second request you verify if the file was created.

Something like this maybe:

```yaml
requests-condition: and
requests:
  - method: PUT
    path:
      - "{{BaseURL}}/?test=1"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/?test=2"
    matchers:
      - type: status
        status:
          - 200
```

**Comment by bauthard** [comment]
Hey @harisec, 

We have added support for this as you requested, this can be used with DSL matcher, we extended DSL matcher to write conditions for each request, for example,  `status_code_1`, `status_code_2`, `body_1` up to 20 requests, here is an example making use of this feature. 

```yaml

id: multi-request-test
info:
  name: multi-request-test
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/random_path_1"
      - "{{BaseURL}}/"

    matchers:
      - type: dsl
        name: multi-req
        dsl:
          - "status_code_1==404 && status_code_2 == 200 && contains((body_2), 'Hacker-Powered Security')"
```

```sh
echo https://www.hackerone.com | ./nuclei -t test.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [multi-request-test] multi-request-test (@pdteam) [info]
[INF] Using 1 rules (1 templates, 0 workflows)

[multi-request-test] [http] [info] https://www.hackerone.com/
```
