### ISSUE TITLE
False positives and excessive requests with iterate-all and variable list

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#3700]
A new bug has been introduced in the Nuclei engine. When using the `iterate-all` and providing a list of variables, it results in a high number of requests being sent and produces false positive results.

### Steps To Reproduce:

Run the following template: `nuclei -t ~/Documents/GitHub/nuclei-templates/ -id vpc-logging-not-enabled -proxy http://127.0.0.1:8080 -var "region=region.txt"`

#### regions.txt

```txt
us-west-1
us-east-1
```

```yaml
id: vpc-logging-not-enabled
info:
  name: VPC flow logging Not enabled
  author: princechaddha
  severity: low
  description: |
    Checks if the Amazon CloudWatch alarmed is enabled for Sign In without MFA
  reference:
    - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcs.html
    - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFlowLogs.html
  remediation: Enabling VPC Flow Logs
  tags: cloud,devops,aws,amazon,vpc,ec2,logging

self-contained: true
signature: aws
variables:
  service: ec2
  region: us-east-1

http:
  - raw:
      - |
        POST https://{{service}}.{{region}}.amazonaws.com/ HTTP/1.1
        Host: {{service}}.{{region}}.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.9.15 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off command/ec2.describe-vpcs

        Action=DescribeVpcs&Version=2016-11-15
      - |
        POST https://{{service}}.{{region}}.amazonaws.com/ HTTP/1.1
        Host: {{service}}.{{region}}.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.9.15 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off command/ec2.describe-flow-logs

        Action=DescribeFlowLogs&Version=2016-11-15&Filter.1.Name=resource-id&Filter.1.Value.1={{vpcId}}

    iterate-all: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "</DescribeFlowLogsResponse>"

      - type: word
        words:
          - "<flowLogId>"
        negative: true

    extractors:
      - type: regex
        name: vpcId
        part: body
        internal: true
        group: 1
        regex:
          - '<vpcId>([a-z-0-9]+)<\/vpcId>'

      - type: dsl
        dsl:
          - '"VPC flow logging is not enabled for " + vpcId + " in " + region + " region"'
```

### Output:

```yaml
[vpc-logging-not-enabled] [http] [low] https://ec2.us-west-1.amazonaws.com/ [VPC flow logging is not enabled for vpc-0a7b0a4148d2b5c14 in us-west-1 region] [region="us-west-1"]
[vpc-logging-not-enabled] [http] [low] https://ec2.us-east-1.amazonaws.com/ [VPC flow logging is not enabled for vpc-0cc801e39bf787771 in us-east-1 region] [region="us-east-1"]
[vpc-logging-not-enabled] [http] [low] https://ec2.us-east-1.amazonaws.com/ [VPC flow logging is not enabled for vpc-072e8d17809966803 in us-east-1 region] [region="us-east-1"]
[vpc-logging-not-enabled] [http] [low] https://ec2.us-east-1.amazonaws.com/ [VPC flow logging is not enabled for vpc-0a7b0a4148d2b5c14 in us-east-1 region] [region="us-east-1"]
```

There is no `vpc-0a7b0a4148d2b5c14` in `us-east-1` region (DM for test creds)
