### ISSUE TITLE
Matching content from headers in `headless` mode is not working

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#3715]
### Nuclei version:
`v2.9.4`

### Current Behavior:
Nuclei doesn't match content from the headers when used in headless mode.

### Expected Behavior:
The execution of the below template should produce a match.

### Steps To Reproduce:
Command to use:
```sh
nuclei -t headless_test.yaml -u https://projectdiscovery.io -headless
```

`headless_test.yaml`:
```yaml
id: headless-header-test

info:
  name: Testing headless matchers
  author: forgedhallpass
  severity: critical
  tags: headless

headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
```

Related:
* #2960
