### ISSUE TITLE
Enable network template to be configured with min/max tls version

### ISSUE THREAD

**Issue by pussycat0x** [projectdiscovery/nuclei#3759]
### Please describe your feature request:

Enable network template to be configured with min/max tls version and using tls://

```
  tcp:
    - input:
         - data: "{{concat(hb_1 + hb_2)}}"  
            read: 1024  
    host:
      - "tls://{{Hostname}}"
          min_version: tls11
          max_version: tls11
      
```
