### ISSUE TITLE
cve-annotate is not working

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3782]
### cve-annotate version:
latest

### Current Behavior:
`cve-annotate` failed to annotate cve templates.

### Expected Behavior:
Populating cves related information to cve templates.

### Steps To Reproduce:

```yaml
id: CVE-2023-0968

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}"
```

```
cve-annotate -i test.yaml
```

### Note:
- Currently, only `max-request` is being populated.
- Currently, `cve-annotate` uses [nvd](https://github.com/projectdiscovery/nvd) lib to populate cve-related information instead now it can be replaced with templateman's [enhance api](https://github.com/projectdiscovery/templateman/blob/main/templateman-rest-api/README.md#enhance-api).
