### ISSUE TITLE
Automatic path merge to preserve query order

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3801]
### Nuclei version:
latest, dev

### Current Behavior:
Automatic query merge behavior forms new queries sorted in alphabetic order, for the cases where query parameter does matter, this behavior becomes an issue.

### Expected Behavior:
Automatic query merge behavior should form urls similarly to how the path is getting merged, i.e., prefixed with cli input path + template path; the same behavior should also be followed for query parameters.

### Steps To Reproduce:

Template:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}/template/input?a=b"
```

```console
echo https://example.com/cli/input/?c=d | nuclei -t test.yaml -v
```

Current:

```console
[VER] [basic-example] Sent HTTP request to https://example.com/cli/input/template/input?a=b&c=d
```

Expected:

```console
[VER] [basic-example] Sent HTTP request to https://example.com/cli/input/template/input?c=d&a=b
```
