### ISSUE TITLE
Wordlist input using CLI variable is not working

### ISSUE THREAD

**Issue by secureITmania** [projectdiscovery/nuclei#3826]
I am creating a template that uses the payloads wordlist via variable. But I am getting an error while executing the template.

![image](https://github.com/projectdiscovery/nuclei/assets/67820809/43cc828e-3fe3-43a4-83ee-7c46a79865a1)

![image](https://github.com/projectdiscovery/nuclei/assets/67820809/9c6e3849-fd75-4ac3-90e0-4fb685dd67c1)

Is the problem with the template or the nuclei engine?

**Comment by MetzinAround** [comment]
It seems to be an issue with the template. The error: `yaml: invalid map key:` is what's causing it to be invalid, so we I'm going to explore that error. Be back soon.

**Comment by MetzinAround** [comment]
This might not be it but is there a space after `{{pp}}`? 

https://stackoverflow.com/a/74644186

**Comment by ehsandeep** [comment]
@secureITmania please include a text version of your template.

**Comment by secureITmania** [comment]
Please have look at the text version of the template

```
id: snyk-vul-scan

info:
  name: snyk-vul-scan
  author: secureitmania
  severity: info
  description: description
  reference: https://
  tags: tag

self-contained: true
http:
 - raw:
   - |
     GET https://api.snyk.io/v1/vuln/npm/{{component}}?org= HTTP/1.1
     Host: api.snyk.io
     User-Agent: Needle/3.0.0 (Node.js v16.16.0; win32 x64)
     Accept: application/json
     Authorization: token {{redacted}}
     X-Is-Ci: false
     X-Snyk-Cli-Version: 1.1142.0
     Accept-Encoding: gzip
   
   payloads:
     component: {{pp}}

   extractors:
   - type: json
     part: body
     name: test
     json:
       - '.vulnerabilities[] | {title, description, moduleName, identifiers}'
```

**Comment by Mzack9999** [comment]
@secureITmania unfortunately the core doesn't implement yet a recursive unbalanced expression engine (discarded in https://github.com/projectdiscovery/nuclei/pull/3066), therefore the payload expression can only be resolved up to one nesting level and futher manually added edge cases. For the time being you can obtain the wanted result by placing the payload within the variable section as follows:

```yaml
id: snyk-vul-scan

info:
  name: snyk-vul-scan
  author: secureitmania
  severity: info
  description: description
  reference: https://
  tags: tag

variables:
  component: "{{pp}}"

self-contained: true
http:
  - raw:
      - |
        GET https://api.snyk.io/v1/vuln/npm/{{component}}?org= HTTP/1.1
        Host: api.snyk.io
        User-Agent: Needle/3.0.0 (Node.js v16.16.0; win32 x64)
        Accept: application/json
        Authorization: token {{redacted}}
        X-Is-Ci: false
        X-Snyk-Cli-Version: 1.1142.0
        Accept-Encoding: gzip

    extractors:
      - type: json
        part: body
        name: test
        json:
          - ".vulnerabilities[] | {title, description, moduleName, identifiers}"

```

Not sure if you are aware but you can directly reference the variable `pp` within the template, simplyfing it to:
```yaml
id: snyk-vul-scan

info:
  name: snyk-vul-scan
  author: secureitmania
  severity: info
  description: description
  reference: https://
  tags: tag

self-contained: true
http:
  - raw:
      - |
        GET https://api.snyk.io/v1/vuln/npm/{{pp}}?org= HTTP/1.1
        Host: api.snyk.io
        User-Agent: Needle/3.0.0 (Node.js v16.16.0; win32 x64)
        Accept: application/json
        Authorization: token {{redacted}}
        X-Is-Ci: false
        X-Snyk-Cli-Version: 1.1142.0
        Accept-Encoding: gzip

    extractors:
      - type: json
        part: body
        name: test
        json:
          - ".vulnerabilities[] | {title, description, moduleName, identifiers}"

```
