### ISSUE TITLE
Issue with printing matched urls in unsafe mode

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3834]
### Nuclei version:
latest/dev

### Current Behavior:
```console
echo https://example.com/test?a=b | nuclei -t test.yaml -silent
[basic-example] [http] [info] https://example.com
```

### Expected Behavior:
```console
echo https://example.com/test?a=b | nuclei -t test.yaml -silent
[basic-example] [http] [info] https://example.com/test/?a=b
```

### Steps To Reproduce:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - true
```

```
echo https://example.com/test?a=b | nuclei -t test.yaml
```
