### ISSUE TITLE
support for `disable-path-automerge` in unsafe mode

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3848]
Follow up for https://github.com/projectdiscovery/nuclei/pull/3799

This support can be extended in `unsafe` mode in raw format.

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

http:
  - raw:
      - |+
        GET /api/v1/id=123 HTTP/1.1
        Host: {{Hostname}}

    disable-path-automerge: true
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - true
```
