### ISSUE TITLE
enable cookie reuse / data sharing as default in template / workflows

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3894]
### Please describe your feature request:
With the addition of https://github.com/projectdiscovery/nuclei/pull/2576, it made it possible to share data between templates when using with workflows, enabled writing workflows that require authentication before running templates, since it's commonly required behavior it would be much more useful to enable it as default and optionally disable it when required, which will unblock template authors of the need of explicitly adding `cookie-reuse` in each template that needs to be used within workflows.

Template attribute to disable this specific behavior:

`disable-cookie: true`

### Describe the use case of this feature:

Write authenticated workflows with ease without manually updating each underlying template with `cookie-reuse: true`

```yaml
id: test-workflow

info:
  name: Test Workflow
  author: pdteam

workflows:
  - template: http/default-login/xxx.yaml
    subtemplates:
      - template: http/x/template1.yaml
      - template: http/x/template2.yaml
```

Note:
> - `cookie-reuse` can be marked as deprecated and to be removed later.
