### ISSUE TITLE
[feature] Allow easier workflow building with YAML native language itself

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#390]
A feature can be adopted which would allow workflows to be created using plain YAML language for users who do not prefer the scripting language capability.

```yaml
workflows:
  - path: path-to-template-a.yaml
    condition-and:
       - path: path-to-template-2.yaml
       - path: path-to-template-2.yaml
```

This is the gist of the idea, more language conditions can be defined to support all sort of operations!

**Comment by Ice3man543** [comment]
Looking at workflows examples, there are some fixed types of variations in workflows but the overall logic remains almost always the same. Some common workflow use cases are given below - 

- Run a template (Stores it's result in a varable with same name)
- Run a template based on condition of previous template (Comes under the run template)
- Run a template based on condition of previous template result (Comes under the run template)

A simple workflow.

```yaml
workflows:
  - template: /root/jira-detect.yaml
    subtemplates:
      - template: /root/jira-exploit-1.yaml
      - template: /root/jira-exploit-1.yaml
```

A template with multiple chained conditions.

```yaml
workflows:
  - template: /root/atlassian-detect.yaml
    subtemplates:
      - template: /root/jira-detect.yaml
        subtemplates:
          - template: /root/jira-exploit-1.yaml
          - template: /root/jira-exploit-2.yaml
      - template: /root/confluence-detect.yaml
        subtemplates:
          - template: /root/confluence-exploit-1.yaml
          - template: /root/confluence-exploit-2.yaml
```

A match on the template value.

```yaml
workflows:
  - template: /root/tech-detect.yaml
    match:
      - value: vbulletin
        subtemplates:
          - template: /root/vbulletin-exp1.yaml
          - template: /root/vbulletin-exp2.yaml
      - value: jboss
        subtemplates:
          - template: /root/jboss-exp1.yaml
          - template: /root/jboss-exp2.yaml
```

The last example is something similar to a switch condition on the results of the root template and `case` conditions are specified in `match` blocks.

**Comment by Ice3man543** [comment]
The idea is to convert the workflow block to tengo code at runtime dynamically which will then be executed by the engine allowing us to accomplish this feature with ease.

**Comment by bauthard** [comment]
This looks useful and useful for writing workflows in existing YAML format @Ice3man543, small naming suggestion in case looking for sub matchers:-  

```yaml
workflows:
  - template: /root/tech-detect.yaml
    matchers:
      - name: vbulletin
        subtemplates:
          - template: /root/vbulletin-exp1.yaml
          - template: /root/vbulletin-exp2.yaml
      - name: jboss
        subtemplates:
          - template: /root/jboss-exp1.yaml
          - template: /root/jboss-exp2.yaml
```
