### ISSUE TITLE
Input handling for network templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3902]
### Please describe your feature request:

Current Template:
 
```yaml
tcp:
  - inputs:
      - data: "Docker:\nVersion:\n"

    host:
      - "{{Host}}:2375"
      - "{{Hostname}}"
```

```
echo http://127.0.0.1 | nuclei -t test.yaml

[VER] Sent TCP request to example.com:2375
[VER] Sent TCP request to example.com:80
```

Expected Template:

```yaml
tcp:
  - inputs:
      - data: "Docker:\nVersion:\n"

    host:
      - "{{Hostname}}:2375"
```

```console
echo http://127.0.0.1 | nuclei -t test.yaml

[VER] Sent TCP request to example.com:2375
```

```console
echo http://127.0.0.1:8080 | nuclei -t test.yaml

[VER] Sent TCP request to example.com:8080
```

Current format:
- both `{{Host}}` and `{{Hostname}}` is specified to support both pre-defined port + as other port with user input.
- keeping both format result into increased scan time, as one request from both is going to be timed out.

After update:

- As default ports will be hard coded into the network template, which will be used as the default
- Input with the port will overwrite the hardcoded port from the template 

### Describe the use case of this feature:
- This will avoid needing to define `host` with port and `hostname` to ensure hardcoded port and user-defined input is getting respected.
- This will reduce scan time (network templates) as, for now, one request will always result in a timeout.
