### ISSUE TITLE
[feature] Adding directory / path schema for offline processing

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#391]
**Is your feature request related to a problem? Please describe.**

This issue is a result of one of the features requested on our discord server where we can use nuclei to process offline data using a local path or directory.

Use cases:- 

- Secret scanning in source codes
- Processing passive HTTP based templates. 

**Describe the solution you'd like**

```yaml
id: basic-offline-template

info:
  name: Test File Template
  author: pdteam
  severity: info

file:
    path:
      - "/recon/http-data/"
      - "/github-projects/bugbounty/"

    matchers:
      - type: word
        words:
          - "This is a secret test"
        recursive: true
```

```bash
nuclei -t basic-offline-template.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.x.x

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.

[basic-offline-template] [file] /recon/http-data/example.txt
[basic-offline-template] [file] /github-projects/bugbounty/secret.txt
```
