### ISSUE TITLE
Query automerge not supported in headless mode

### ISSUE THREAD

**Issue by iambouali** [projectdiscovery/nuclei#3919]
When scanning the provided URL, it appears that query automerge is not supported in headless mode. This limitation affects the ability to automatically determine whether to append an XSS payload using an ampersand (&) or a question mark (?) when dealing with URLs like `https://host.com/test/` and `https://host.com/test/?param=1`.

## Context

Query automerge is a crucial feature that determines the appropriate delimiter to use when appending an XSS payload to URLs. The presence or absence of existing query parameters should influence the choice between & and ? as the delimiter.

## Expected Behavior

In headless mode, the scanning process should support query automerge and correctly determine the appropriate delimiter to use based on the presence or absence of existing query parameters.

## Steps to Reproduce

- Access the URL: https://xxxxxx.oastify.com/?test=1 in headless mode.

- Observe that query automerge is not supported and the delimiter for appending an XSS payload is not determined correctly.

<img width="950" alt="Captura_de_pantalla_2023-07-08_a_las_19 05 33" src="https://github.com/projectdiscovery/nuclei/assets/74378500/f526c8b8-679f-4ec7-95d4-45480bdec26a">

## Template example

```yaml
id: poc

info:
  name: poc
  author: poc
  severity: medium
  tags: poc

headless:
  - steps:
      - args:
          url: '{{BaseURL}}/?{{aa}}="><pwnd>'
        action: navigate
      - action: waitload

    payloads:
      aa:
        - xss
```

```console
echo https://example.com/testing?a=b | nuclei -t aa.yaml -headless -p http://127.0.0.1:8080 -v
```

Results into:

```
https://example.com/testing?a=b/?xss=%22%3E%3Cpwnd%3E
```

Expected:

```
https://example.com/testing?a=b&xss=%22%3E%3Cpwnd%3E
```
