### ISSUE TITLE
issue with headless response

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3923]
### Nuclei version:
latest, dev

### Current Behavior:
headless response with encoded html tags

<img width="816" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/c4bd9326-bf4e-4ce1-87bd-931e766946ee">

### Expected Behavior:

same as actual dom

<img width="437" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/8bfaccfa-0e12-45b0-956f-377c1e8d89e1">

### Steps To Reproduce:
```
echo "http://pdteam.amanrawat.in/xss.html?q=test" | ./nuclei -t dom-xss.yaml -headless -debug
```

```yaml
id: dom-xss

info:
  name: DOM Cross Site Scripting
  author: theamanrawat
  severity: medium
  tags: xss,dom,dast

variables:
  first: "{{rand_int(10000, 99999)}}"

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"
      - action: waitload

    payloads:
       reflection:
        - "'\"><{{first}}"

    fuzzing:
      - part: query
        type: postfix
        mode: single
        fuzz:
          - "{{reflection}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "{{reflection}}"

      - type: word
        part: header
        words:
          - "text/html"
```

**Comment by ehsandeep** [comment]
Another example is where the actual response is HTML encoded and nuclei see it as unencoded.

<details>
<summary>test2.yaml</summary>

```yaml
id: reflected-xss

info:
  name: test
  author: test
  severity: info

headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload

    fuzzing:
      - part: query
        type: postfix
        mode: single
        fuzz:
          - '"><pwnd>'

    matchers:
      - type: word
        part: body
        words:
          - "><pwnd>"
```
</details>

```console
nuclei -t test2.yaml -u 'https://activities.marriott.com/berlin-p/things-to-do?query=ID%3A0PG28IPO005H4"><pwnd>' -headless
```

Original response:

<img width="547" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/669d61c9-9504-49ff-9068-9f06361425c2">

Nuclei headless in debug mode:

<img width="549" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/6f6eb0f5-e2b5-46ad-b4d1-7920f4aa9ce9">
