### ISSUE TITLE
 Missing DSL Support on File Protocol

### ISSUE THREAD

**Issue by pussycat0x** [projectdiscovery/nuclei#4012]
### Please describe your feature request:

Support DSL on File Protocol, and it will help us to write templates for malware detection.
### Describe the use case of this feature:

```
file:
  - extensions:
      - all

    matchers:
      - type: dsl
        dsl:
          - "sha256(file) == '00014d16d21d21d00042d41d00041df1e57cd0b3bf64d18696fb4fce056610'"
          ```
