### ISSUE TITLE
Nuclei Beta v3 multi protocol issues if the regex extract many result 

### ISSUE THREAD

**Issue by 00xSayDoo** [projectdiscovery/nuclei#4058]
### Issue description:

In nuclei Beta v3 version 3.0.0, if a multi-protocol is used to search for Firebase links (#4322) inside and then pass it to the insecure Firebase check, the templates will only check the last Firebase link if the file contains multiple Firebase links. This issue still exists even if stop at first match is used.

Note: The same issue will occur even if the scan is performed from Nuclei in the full folder and there are two Firebase links in different locations, such as one in /home/firebase1.link and the other in /home/test/firebase2.link.

### Anything else:

```yaml
id: insecure-firebase-database-Beta-v3

info:
  name: Insecure Firebase Database
  author: rafaelwdornelas
  severity: high
  description: If the owner of the app have set the security rules as true for both "read" & "write" an attacker can probably dump database and write his own data to firebase database.
  reference:
    - https://blog.securitybreached.org/2020/02/04/exploiting-insecure-firebase-database-bugbounty
  metadata:
    verified: true
  tags: firebase,google,misconfig

file:
  - extensions:
      - all

    extractors:
      - type: regex
        name: token
        internal: true
        regex:
          - "[a-z0-9.-]+\\.firebaseio\\.com"
          - "[a-z0-9.-]+\\.firebaseapp\\.com"

http:
  - method: GET
    path:
      -  "https://{{token}}/{{randstr}}.json"
    # stop-at-first-match: true
    # iterate-all: true
    # req-condition: true

    matchers-condition: and
    matchers:

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
```

    The first case where the last link in the file is returned 404 is described here.

![image](https://github.com/projectdiscovery/nuclei-templates/assets/108477129/06757454-5ae4-4aca-aa65-25d4d1e4c64b)

    The second case where the last link in the file is returned 200 is described here.

![image](https://github.com/projectdiscovery/nuclei-templates/assets/108477129/c7029eca-59c2-4ea1-ba19-03c287b8c253)

sample of the link was used 

```
https://banlek-28e05.firebaseio.com/nuclei.json
https://byclean-1525737949784.firebaseio.com/nuclei.json
https://byclean-152573794978d.firebaseio.com/nuclei.json
```
