### ISSUE TITLE
for request annotation support in http protocol

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4081]
### Please describe your feature request:

As suggested by @Mzack9999 in previous discussions for goto / simple use cases where flow might be an overkill . we should add a for request annotation for iterating over a slice/value .

Example

```yaml
    raw:
      - |
        for @vpcId in @myVpcs
        POST https://{{service}}.{{region}}.amazonaws.com/ HTTP/1.1
        Host: {{service}}.{{region}}.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.9.15 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off command/ec2.describe-flow-logs

        Action=DescribeFlowLogs&Version=2016-11-15&Filter.1.Name=resource-id&Filter.1.Value.1={{vpcId}}
```

### Describe the use case of this feature:

- drop in replacement for `iterate-all`
