### ISSUE TITLE
When using conditional workflows, only subtemplate shows in output

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#4128]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/2683

<div type='discussions-op-text'>

<sup>Originally posted by **tryeng** September  5, 2022</sup>
Workflow:
```
id: test

info:
  name: test workflow
  author: t
  description: Simple workflow running templates

workflows:
  - template: mydevice.yaml 
    subtemplates:
        - template: mydevice-default-password-check.yaml 
```
Output:
```
$ ./nuclei -w nuclei-templates/workflows/test.yaml -l input.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.7

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.1.8 (latest)
[INF] Workflows loaded for scan: 1
[2022-09-05 15:50:24] [mydevice-default-password-check] [http] [info] http://localhost:10001/
```

I would expect this to also show matches on the `mydevice` template. Currently this can be done by running `mydevice` twice, but that will take twice the number of requests and more cluttered workflow files.</div>

**Comment by k3mlol** [comment]
hope awesome nuclei team will fix this!

**Comment by k3mlol** [comment]
Hi, may I ask this bug have any plan to fix?

**Comment by k3mlol** [comment]
Hi, may I ask this bug have any plan to fix?

**Comment by ehsandeep** [comment]
@k3mlol this is by design, here is workaround to get the expected result.

```yaml
id: test

info:
  name: test workflow
  author: t
  description: Simple workflow running templates

workflows:
  - template: mydevice.yaml 
    subtemplates:
        - template: mydevice.yaml 
        - template: mydevice-default-password-check.yaml 
```

**Comment by Mzack9999** [comment]
Closing as it seems the design is not going to be changed - Summarizing for whom may incur into this behavior: it's necessary to execute again the condition template within subtemplates in order to have it among results

**Comment by dkasak** [comment]
This seems like a self-inflicted and unnecessary wound. Why throw away perfectly good results which you then have to recover by issuing the same requests all over again?

I think the mismatch here is that there are two ways in which you could use conditional templates / subtemplates:

1. As a logical AND. If *both* the parent template matches *and* the subtemplate matches, only then do you want a result to be emitted. This is the behaviour we have today.
2. As refinement: the parent template produces some results but I then run some subtemplates on those results to potentially produce more results.

An example of the latter is a workflow like:

a. Given an input domain
b. Discover a list of related hosts / URLs, all of which are interesting on their own
c. Issue some additional requests to those discovered hosts / URLs, for example to detect CVEs

It seems like this behaviour could be added with a very small and localised change, for example by adding an `emit` key on the `workflows` spec, with possible values `emit: matching`  (which would be the current behaviour and the default) and `emit: all` (which would make nuclei emit all matches for the parent template, in addition to and regardless of any matches by the subtemplates)

In pseudocode:

```yaml
workflows:
  - template: discover-related-services.yaml
    emit: all  # emit all discovered services, regardless of whether they have CVEs 
    subtemplates:
       - template: cves/
```

@ehsandeep What do you think?
