### ISSUE TITLE
[issue] Issue with collab DSL matcher in case of multiple input

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#417]
**Describe the bug**
Collab DSL matcher flag same matcher results for all input.

<details>
<summary> Collab template</summary>

```yaml
id: collab-automation
info:
  name: Collab automation with nuclei
  author: pdteam
  description: Burp Collaborator Test
  severity: info

 # echo http://api.reqbin.com | nuclei -t burp.yaml -burp-collaborator-biid xxxxx

requests:
  - raw:
      - |
        POST /api/v1/requests HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        Content-Length: 549
        Accept: */*
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
        Content-Type: application/json
        Origin: https://reqbin.com
        Sec-Fetch-Site: same-site
        Sec-Fetch-Mode: cors
        Sec-Fetch-Dest: empty
        Referer: https://reqbin.com/
        Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
        
        {"id":"0","name":"","errors":"","json":"{\"method\":\"GET\",\"url\":\"http://easygzsg2ik0r1c6zj1nc5ns8jea2z.burpcollaborator.net\",\"apiNode\":\"US\",\"contentType\":\"\",\"content\":\"\",\"headers\":\"\",\"errors\":\"\",\"curlCmd\":\"\",\"auth\":{\"auth\":\"noAuth\",\"bearerToken\":\"\",\"basicUsername\":\"\",\"basicPassword\":\"\",\"customHeader\":\"\",\"encrypted\":\"\"},\"compare\":false,\"idnUrl\":\"http://4jo7pqdvj5kyw0sj16nxfn19107uvj.burpcollaborator.net/\"}","deviceId":"4e9c318b-a3c8-41cd-8ce2-bade04a85398R","sessionId":1606129662009}

    matchers:
      - type: dsl
        dsl:
          - "waitfor(6) && collab('')"
```
</details>

To reproduce this, run the same template with multiple URLs. 

**Nuclei version**
2.2.0

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
