### ISSUE TITLE
bug:{{Path}} has repeat

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#4194]
@Mzack9999 
Current nuclei version: v2.9.15 
bug:{{Path}} has repeat

if url end with "/"

$ nuclei -duc -t $HOME/xxx.yaml -u http://127.0.0.1:9000/myapp/ -debug
```
id: xxx

info:
  name: xxx
  author: 51pwn
  severity: critical
  description: |
    xxx
    

# Host: localhost
http:
  - raw:
    - |+
      POST {{Path}} HTTP/1.1
      Host: {{Hostname}}
      Content-Length: 454
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

    
```
debug out
```
POST /myapp/myapp HTTP/1.1
Host: 127.0.0.1:9000
```
you can see:/myapp/myapp

if 
$ nuclei -duc -t $HOME/xxx.yaml -u http://127.0.0.1:9000/myapp -debug

debug out
```
POST /myapp/ HTTP/1.1
Host: 127.0.0.1:9000
```

if use
POST {{RootURL}} HTTP/1.1

debug out
POST /myapp/http://127.0.0.1:9000 HTTP/1.1

**Comment by hktalent** [comment]
@ehsandeep 
Sorry for bothering you all the time
Also, I have a question
When sending -raw:, on macos or linux system, there is no such content in the edited yaml.
\r, then do we need to force joining? Or will the program help us join it by default?

**Comment by ehsandeep** [comment]
@hktalent this is not a bug, as default `{{BaseURL}}` is used and you added `{{Path}}` on the top of it.

so if the input is `http://127.0.0.1:9000/myapp/`

`BaseURL`: `http://127.0.0.1:9000/myapp/`
`Path`: `/myapp/`

So, the final request will be `http://127.0.0.1:9000/myapp/myapp`, so this is expected, if you wish to use RootURL as default, you can use `disable-path-automerge: true` in your template. ([Reference](https://github.com/projectdiscovery/nuclei/blob/main/SYNTAX-REFERENCE.md))

```yaml
id: xxx

info:
  name: xxx
  author: 51pwn
  severity: critical
  description: |
    xxx
    
http:
  - raw:
    - |+
      POST {{Path}} HTTP/1.1
      Host: {{Hostname}}
      Content-Length: 454
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

    disable-path-automerge: true
```

For your comment, it's unclear to me, can you please create a separate discussion instead of an issue with examples?
