### ISSUE TITLE
The content-length of the raw request was removed

### ISSUE THREAD

**Issue by Chestnuts4** [projectdiscovery/nuclei#4227]
### Nuclei version:

v2.9.14
### Current Behavior:

custom  header `Content-Length` has removed
### Expected Behavior:

in request, `Content-Length` equal the value in template.yml
### Steps To Reproduce:

there was the template I use
```yml
id: id

info:
  name: name
  author: author
  severity: medium
  description: desc
  tags: tags

http:
  - raw:
    - |
        GET /index.php HTTP/1.1
        Host: {{Hostname}}
        Content-Length: aaa
```
 when I use `nuclei -l urls.txt -t template.yaml -p http://192.168.32.1:8083 -o result.txt -pi` run nuclei rule, in burpsuite, I see
```http
GET /index.php HTTP/1.1
Host: host
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36
Connection: close
Accept-Encoding: gzip, deflate


```

### Anything else:

and when I use normal HTTP, `Content-Length` header will be removed but `Content-Type` header not
```yml
http:
  - method: GET
    path:
      - "{{RootURL}}/index.php"
    headers:
      Content-Length: "asdf"
      Content-Type: application/x-www-form-urlencoded
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    matchers:
      - type: status
        status:
          - 413


```

**Comment by ehsandeep** [comment]
@Chestnuts4 for the malformed request you need to use `unsafe: true` to make use of https://github.com/projectdiscovery/rawhttp library instead of default net/http by go, which will normalize the request.

Here is an example template: 

```yaml
id: id

info:
  name: name
  author: author
  severity: medium
  description: desc
  tags: tags

http:
  - raw:
    - |+
        GET /index.php HTTP/1.1
        Host: {{Hostname}}
        Content-Length: aaa

    unsafe: true
```

Note: don't miss the `+` sign used in template with `unsafe: true`

```console
echo https://scanme.sh | nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

		projectdiscovery.io

[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] [id] Dumped HTTP request for https://scanme.sh/index.php

GET /index.php HTTP/1.1
Host: scanme.sh
Content-Length: aaa

[INF] No results found. Better luck next time!
```
