### ISSUE TITLE
nuclei 3.0 could not resolve variables like "randstr"

### ISSUE THREAD

**Issue by qianbenhyu** [projectdiscovery/nuclei#4259]
Test Template:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}?x={{randstr}}"
```

```console
[WRN] [basic-example] Could not make http request for https://example.com: unresolved variables found: randstr
```

![image](https://github.com/projectdiscovery/nuclei/assets/32768810/6376bcf7-be5a-4081-bc21-63dffa1f3381)
![image](https://github.com/projectdiscovery/nuclei/assets/32768810/5358c5c9-1631-4720-ae6e-f84d8087367d)
