### ISSUE TITLE
Reference already existing templates within a template

### ISSUE THREAD

**Issue by iamnoooob** [projectdiscovery/nuclei#4287]
### Please describe your feature request:
There should be a feature to reuse existing templates by referencing them inside a nuclei template instead of re-writing the already existing config/rule (similar to workflows).

### Describe the use case of this feature:

Taking this template as an example from [here](https://docs.nuclei.sh/template-guide/flow#request-execution-orchestration) :

```yaml
id: wordpress-bruteforce

info:
  name: WordPress Login Bruteforce
  author: pdteam
  severity: high

flow: http(1) && http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-login.php"

    matchers:
        - type: word
            words:
            - "WordPress"

  - method: POST
    path:
      - "{{BaseURL}}/wp-login.php"

    body: |
        log={{username}}&pwd={{password}}&wp-submit=Log+In

    attack: clusterbomb 
    payloads:
      users: helpers/wordlists/wp-users.txt
      passwords: helpers/wordlists/wp-passwords.txt

    matchers:
      - type: dsl
        dsl:
          - status_code == 302
          - contains_all(header, "/wp-admin","wordpress_logged_in")
        condition: and

```
Here, there is a detection step in the first http request of the flow involved which is kind of repetitive as detection for wordpress pre-exists as a separate template. It would be much more easier and remove any kind of redudancy while writing templates if we could just add a reference to the pre-existing templates. Something like:

```yaml
...
http:
    template: http/technologies/wordpress-detect.yaml

  - method: POST
    path:
      - "{{BaseURL}}/wp-login.php"
...
```
