### ISSUE TITLE
Unable to get response package content

### ISSUE THREAD

**Issue by HuTa0kj** [projectdiscovery/nuclei#4317]
### Current Behavior:

The Web response package I examined contained an extra blank line that prevented me from matching the content of the response package.

### Steps To Reproduce:

I can't match the status code and string for response package 2.

example:
`nuclei -t test.yaml -u http://127.0.0.1:8088 -debug`
yaml:
```
matchers-condition: and
matchers:
  - type: word
    part: body_1
    words:
      - "uploads_chat"
  
  - type: status
    part: header_1
    status:
      - 302

  - type: word
    part: body_2
    words:
      - "{{match_str}}"

  - type: status
    part: header_2
    status:
      - 200
```
resp:
```
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
Date: Tue, 31 Oct 2023 08:40:09 GMT
Server: Apache/2.4.39 (Win64) OpenSSL/1.1.1b mod_fcgid/2.3.9a mod_log_rotate/1.02
X-Powered-By: PHP/7.2.9

Content-Type: image/jpeg

13075ec1d408e612c02b27966a6bfdab
[INF] No results found. Better luck next time!
```

I tried to grab the original packet.There is a blank line in the response package.
![image](https://github.com/projectdiscovery/nuclei/assets/67937284/01613b40-e63f-4e83-b15e-aa17e2cd223e)

But when I changed the matcher to dsl, it worked fine.
```
matchers:
  - type: dsl
    dsl:
      - "status_code_1 == 302 && status_code_2 == 200"
      - "contains(body_1, 'uploads_chat') && contains(body_2, '{{match_str}}')"
    condition: and
```
