### ISSUE TITLE
javascript protocol not working in flow

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4318]
### Nuclei version:

main | dev

### Current Behavior:

- javascript protocol is not available or working in flow templates
- when there are multiple http requests without any matcher then matcher status is false 

### Steps To Reproduce:

```yaml
id: js_test

info:
  name: Testing JS 
  author: rahulmaini
  severity: info
  
flow: http(1) && javascript() && http(2)

# custom helper function using javascript
javascript:
  - code: |
      // custom helper function
      function stringToHex(str) {
          var hex = '';
          for (var i = 0; i < str.length; i++) {
              hex += str.charCodeAt(i).toString(16);
          }
          return hex;
      }
      // invoke helper
      stringToHex(Body)

    args:
      Body: "{{http_1_body}}"

http:
  - method: GET # http request
    path:
      - "{{BaseURL}}"

  - raw:
    - |
      GET /{{javascript_response}} HTTP/1.1
      Host: {{Hostname}}

    matchers:
      - type: status
        status:
          - 200
```

```console
$ nuclei -u scanme.sh -t ~/Codebase/nuclei/jshelper.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] No results found. Better luck next time!
```
