### ISSUE TITLE
Can't args be a variable for the code pattern of template?

### ISSUE THREAD

**Issue by Greatbug333** [projectdiscovery/nuclei#4321]
I want to execute my python script with some variables as parameters. But I don't know how to do that.
nuclei version：3.0.2
Such as：
code:
  - engine:
    - C:\Python27\python.exe
    source: C:\Users\test.py
    args:
    - {{BaseURL}}

    matchers:
      - type: word
        words:
          - "match words"

**Comment by MetzinAround** [comment]
I think you just need to declare the variable as equal to the baseurl. 
 `variable_name = {{BaseURL}}`

**Comment by tarunKoyalwar** [comment]
@Greatbug333 , args argument in code protocol is used to pass flags to engine example
```yaml
engine:
      - powershell
      - powershell.exe
    args:
      - -ExecutionPolicy
      - Bypass
      - -File
```

and all declared variables are passed as env variable regardless of engine used . so let's say you want to use BaseURL in python you can do it following way

```yaml
id: py-code-snippet

info:
  name: py-code-snippet
  author: pdteam
  severity: info
  tags: code
  description: |
    py-code-snippet

variables:
  URL: "{{BaseURL}}"

code:
  - engine:
      - py
      - python3
    source: |
      import sys,os
      print(os.getenv('URL'))
    
    extractors:
      - type: dsl
        dsl:
          - "response"
```

```console
./nuclei -u https://scanme.sh -t integration_tests/protocols/code/py-env-var.yaml       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.3

		projectdiscovery.io

[INF] Current nuclei version: v3.0.3 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 24
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from tarun
[INF] Targets loaded for current scan: 1
[py-code-snippet] [code] [info] https://scanme.sh [https://scanme.sh]
````
