### ISSUE TITLE
Executing flow template prints multiple results when using matchers

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4323]
### Current Behavior:

```yaml
id: flow-hide-matcher

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  description: In flow matcher output of previous step is hidden and only last event matcher output is shown

flow: http(1) && http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - ok

  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "Failed event"
```

```console
$  nuclei -u scanme.sh -t integration_tests/flow/flow-hide-matcher.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[flow-hide-matcher] [http] [info] https://scanme.sh
[INF] No results found. Better luck next time!
```
We get above result when we run a flow template which has matchers . as we can see it say `No results Found` but also prints ` a result  this happens because 1st matcher was successful and second wasn't  but this is a confusing behaviour for users. 

### Expected Behavior:

- only print result if template executed successfully and got a result. after fixing this nuclei should not show any result as target was not vulnerable/ matched

```console
$ ./nuclei -u scanme.sh -t integration_tests/flow/flow-hide-matcher.yaml                   130 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[INF] Current nuclei version: v3.0.2 (latest)
[INF] Current nuclei-templates version: v9.6.8 (latest)
[INF] New templates added in latest release: 79
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] No results found. Better luck next time!
```

### Anything else:

https://discord.com/channels/695645237418131507/700096242226692236/1167389841789550633
