### ISSUE TITLE
Missing DNS Type: RRSIG and DNSKEY

### ISSUE THREAD

**Issue by kor-condignum** [projectdiscovery/nuclei#4358]
### Nuclei version:
Nuclei Engine Version: v3.0.3

### Current Behavior:
The template fails to load currently because DNSKEY and RRSIG aren't considered valid DNS query types. DNSKEY and RRSIG are used for the DNSSEC configuration of a domain zone.

### Expected Behavior:
I expect no validation error and that the template loads successfully.

### Steps To Reproduce:
First create this template (dns-rrsig-detect.yaml):
```yaml
id: dns-rrsig-detect

info:
  name: DNS RRSIG Detect
  author: kor
  severity: info
  description: |
    Checks if the Domain has a RRSIG record
  metadata:
    max-request: 1

dns:
  - name: "{{FQDN}}"
    type: RRSIG

    matchers:
      - type: regex
        part: answer
        regex:
          - "IN\tRRSIG\\t(.+)$"
```
And run the validate command:
nuclei -t dns-rrsig-detect.yaml -target example.com -validate

### Anything else:
[ERR] Error occurred loading template /xxx/nuclei-templates/dns-rrsig-detect.yaml: Could not load template /xxx/nuclei-templates/dns-rrsig-detect.yaml: Invalid DNS request type: RRSIG
