### ISSUE TITLE
[issue] yaml: control characters are not allowed

### ISSUE THREAD

**Issue by Smismi11** [projectdiscovery/nuclei#437]
Hi,

while playing around with the raw HTTP requests I got the error yaml: control characters are not allowed.

I copied a HTTP request from burp and used a fuzzer to modify it. I used the output to create a nuclei template with a raw HTTP request. When I tried to use the template with nuclei I get an error. 

Here is the (redacted) template with all necessary informations in it.

[yaml-error.zip](https://github.com/projectdiscovery/nuclei/files/5653822/yaml-error.zip)

**Comment by bauthard** [comment]
Example template:- 

```yaml
requests:
  - raw:
    - |
       GET / HTTP/1.1
       Host: {{Host}}
       Connection: close
       Accept: application/json, text/plain, */*
       Accept-Encoding: gzip, deflate
       Accept-Language: en-US,en;q=0.9
       Cookie: test=kLWNvcmUiLCá Jjb20ua36iNjU5MTIwó OGEtMWIzYy01MWUtNzl;
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - "status_code != 400"
```

Error:- 

```
echo http://test.com | nuclei -t test.yaml 

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.2.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[ERR] Could not parse file '/Users/bauthard/Github/test.yaml': yaml: control characters are not allowed
[FTL] Error, no templates were found.
```
