### ISSUE TITLE
Headless ignores relative paths in templates

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#4370]
### Nuclei version:
`main|dev`

### Current Behavior:
Headless templates ignore relative path and navigate only to `{{BaseURL}}`

### Expected Behavior:
The navigation should happen as per the template `{{BaseURL}}/relative/path`

### Steps To Reproduce:
```yaml
id: test

info:
  name: test
  author: test
  description: test

headless:
  - steps:
    - action: navigate
      args:
        url: "{{BaseURL}}/test"
    - action: waitload
```
Execute with:
```console
nuclei -u https://docs.projectdiscovery.io -duc -v -show-browser -headless -t template.yaml
```

Ref: https://github.com/projectdiscovery/nuclei/issues/4288
