### ISSUE TITLE
Make the SSH client used in javascript templates able to execute custom commands

### ISSUE THREAD

**Issue by 5amu** [projectdiscovery/nuclei#4406]
### Please describe your feature request:
As I was reading about the Javascript protocol, I noticed that there was no way to run custom code using the SSHClient, so I implemented it and will be shortly attach the PR to this issue. Overall I think is a small change that gives an higher degree of freedom and customization for the users.

Using the javascript protocol in a custom template, I'd like to be able to execute one (or more) custom commands:

```yaml
id: ssh-test-cmd

info:
  name: test
  author: 5amu
  severity: info

javascript:
  - args:
      Host: "{{Host}}"
      Port: "22"
    code: |
      var m = require("nuclei/ssh");
      var c = m.SSHClient();
      c.Connect(Host, Port, template.Username, template.Password)
      c.Run("echo lolz > /tmp/lolz");
      var response = c.Run("cat /tmp/lolz");
      to_json(response);
```

### Describe the use case of this feature:
In some scenarios it would be useful to make a vulnerability scan on a target system without dropping the whole nuclei binary (+ templates) in it, or maybe there are many machines possibly having the same vulnerability that require 2-3 commands to confirm.
