### ISSUE TITLE
Static text output on templates

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#4418]
### Please describe your feature request:

As was clear from Discord chat from @ehsandeep , Nuclei still can't display  static outputs. 

So we need option to make output on template with static script. like in case we parse file name

```
    extractors:
      - type: regex
        name: file
        part: body_1
        internal: true
        group: 1
        regex:
          - '(.*?)\|\|\|\|'

```
then need to display it like:

` 'host + "/attachment/file_uploads/" + file'
`
So we need that static text part

### Describe the use case of this feature:
In cases when RFU templates displays uploaded file name, we need to parse the path and then to display full path we need to add static text in it. Because outputting just extractor doesn't make sense.

**Comment by ehsandeep** [comment]
@mastercho static text print is supported and possibe.

```yaml
    extractors:
      - type: dsl
        dsl:
          - '"This is Vulnerable"'
```

What you shared is here is known bug related to printing dynamic variable https://github.com/projectdiscovery/nuclei/issues/1222 and being worked on https://github.com/projectdiscovery/nuclei/pull/4471

Closing this as we already have GH issue to track this.
