### ISSUE TITLE
add method for ldap module to list kerberoastable users

### ISSUE THREAD

**Issue by 5amu** [projectdiscovery/nuclei#4419]
### Please describe your feature request:
The Kerberos module already performs an enumeration to find users without Kerberos pre-authentication required attribute (DONT_REQ_PREAUTH). It'd be very useful to have the LDAP module expose a method to list all kerberoastable users as well. I already implemented it and I'll shortly attach the PR to this issue.

### Describe the use case of this feature:
It would be useful to incorporate some more AD checks into an activity without "leaving" the nuclei environment. For example, using a template like this:

```yaml
id: ldap-list-kerberoastable-users-test

info:
  name: test
  author: 5amu
  severity: info

javascript:
  - args:
      DomainController: "{{Host}}"
    code: |
      ldap = require("nuclei/ldap");
      client = ldap.LdapClient();
      users = client.GetKerberoastableUsers(template.Domain, DomainController, template.Username, template.Password);
      to_json(users);
    extractors:
      - type: json
        json:
          - '.[]'
```
