### ISSUE TITLE
Make smtp module able to send mail

### ISSUE THREAD

**Issue by Marcuccio** [projectdiscovery/nuclei#4444]
### Please describe your feature request:
As I was reading about the Javascript protocol, I noticed that there was no way to properly test the smtp service. A concrete example is sending email to test/exploit open relay with the smtpClient object, so I implemented it and will be shortly attach the PR to this issue. 

Using the javascript protocol in a custom template, I'd like to be able to send email and properly check smtp sevices.

```yaml
id: smtp-open-relay

info:
  name: SMTP open relay - Exploit
  author: abut0n
  severity: High
  description: |
    Mail relaying allows any spammer or phisher to abuse the smtp service and send unsolicited mails, thus flooding network bandwidth or enabling [spear-]phishing attacks.
  reference:
    - https://nmap.org/nsedoc/scripts/smtp-open-relay.html
  tags: network,js,smtp,mail
javascript:
  - code: |
      var m = require("nuclei/smtp");
      var c = m.SMTPClient();
      var response = c.IsOpenRelay(Host, Port, template.From, template.To, Subj, Msg);
      to_json(response);
```

### Describe the use case of this feature:
Testing open relays can be cumbersome because of rules administrators choose to enforce. To properly confirm the presence of this vulnerability is necessary to send an email and verify that was properly received.
