### ISSUE TITLE
Read and Name attributes of network.Input() not working

### ISSUE THREAD

**Issue by UnaPibaGeek** [projectdiscovery/nuclei#4454]
Hello! 

I've been playing with some network templates and discovered that all of them using the `read` attribute in `network.Input()` are currently failing. Only the `read-size` attribute in `network.Request()` is working properly.

Example: [ftp-anonymous-login.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/network/default-login/ftp-anonymous-login.yaml) (that uses `read` instead of `read-size`).

<img width="1090" alt="template-fails" src="https://github.com/projectdiscovery/nuclei/assets/15347928/6d351e5a-9b46-436e-8c1a-31f1bc737cdf">

The timeout error is misleading.  

<img width="854" alt="network-capture" src="https://github.com/projectdiscovery/nuclei/assets/15347928/47e159f7-688d-4677-b246-550bdf70b594">
  
Modifying the code to use `read-size` instead resolves the issue:  

<img width="459" alt="code-modified" src="https://github.com/projectdiscovery/nuclei/assets/15347928/28b41d3b-ce06-40b9-bfd9-c546ac29d80a">  
  
  
<img width="895" alt="it-works" src="https://github.com/projectdiscovery/nuclei/assets/15347928/dcfa9a7f-dca8-42a5-8e7f-e730e3d34014">  
  
This problem occurs whenever `read` is used, so there are many network templates failing due to this issue.

Besides that, I've noticed that adding the `name` attribute to an input request doesn't work. According to the documentation, the following code should work:

```
  - inputs:
      - data: "blahblah" 
        name: prefix
        read: 1024
      - data: "other data"
        name: other
        read: 1024

  matchers:
      - type: word
        part: prefix
        words:
          - "string-to-match in the prefix part"

```
However, it doesn't seem to be the case. 
Please let me know if you have any questions. Thank you!
