### ISSUE TITLE
Fuzzing mode incompatible with self-contained option

### ISSUE THREAD

**Issue by k-poppe** [projectdiscovery/nuclei#4509]
### Nuclei version: 
3.1.1, 3.1.2

### Current Behavior:

When using `self-contained: true` with `fuzzing:`, you get `could not execute rule: [urlutil:RUNTIME] failed to parse url got empty input` as the fuzzing engine expects you to provide target(s) either with -u or from stdin.

### Expected Behavior:

Fuzzing should be compatible with self-contained and should treat the hardcoded URL(s) as its targets.

### Steps To Reproduce:

```yml
id: fuzzing-temp
info:
  name: Fuzzing Template
  author: custom
  severity: low

self-contained: true

http:
  - method: GET
    path:
      - "https://example.com/?param_name=123"
      
    payloads:
      payload_set1:
        - "1"
        - "2"
    attack: clusterbomb
    fuzzing:
      - part: query
        type: replace
        mode: single
        keys:
          - "param_name"
        fuzz:
          - "{{payload_set1}}"
    matchers:
      - type: status
        status:
          - 200

```
