### ISSUE TITLE
different behavior with extracted value between single / multi protocol

### ISSUE THREAD

**Issue by xxxxxxxxyyyy** [projectdiscovery/nuclei#4547]
In HTTP nuclei, the first request uses payloads and extractors are used to extract the value from the response as the path to the second request. If the first request does not match the extractors rule on the first payload, the nuclei will abort. No further payloads will be executed.
So I want to use Flow to ensure that the subsequent payload detection continues if the previous payload is not detected, but after using Flow, I find that the value that the extractors successfully matched on the first request is converted from a string to an array on the second request. For example, if the path to the first request is /123, then the path to the second request will become [/123], so how to extract the required /123 from [/123]?

**Comment by ehsandeep** [comment]
Related - https://github.com/projectdiscovery/nuclei/discussions/4449

**Comment by ehsandeep** [comment]
Example:

1. Multi request in same http block passes extracted value as string
2. Multi request in same http block passes extracted value as array


```yaml
id: extracted_value

info:
  name: Extracted value does not work in flow
  author: pascal-sun
  severity: info

#flow: http(1) && http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/{{test}}"

    extractors: 
      - type: regex
        name: test
        group: 1
        regex:
          - 'This (domain) is for use in illustrative examples in documents.'
        internal: true

    matchers:
      - type: status
        status:
          - 200
 
#  - method: GET
#    path:
#      - "https://example.org/{{test}}"
#    matchers:
#      - type: status
#        status:
#          - 200
```
