### ISSUE TITLE
Global passive matchers / extractors for nuclei scan

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4549]
### Please describe your feature request:

Nuclei runs multiple templates that makes active HTTP request, generally matchers are defined to detect specific issue / detection / tech for specific templates, instead global matcher will make use of existing response data passed through nuclei i.e no additional active requests and allow users to write matchers / extractors to detect interesting behavior / errors / secret etc.

### Describe the use case of this feature:
- Passive response based detections
- Passive response based fingerprinting.
- Error / WAF / Interesting behavior detection
- Secret Detection

Example Template:

```yaml
id: global-matcher-example

info:
  name: Test Global Matcher Template
  author: pdteam
  severity: info

  - global-matchers: true # enables global matching and applies them globally to all events from other templates
    matchers-condition: and
    matchers:
      - type: word
        words:
          - This is test matcher text

      - type: word
        words:
          - This is test matcher text 2

    extractors:
      - type: regex
        group: 1
        regex:
          - '<title>(.*)<\/title>'
```
