### ISSUE TITLE
Save to file (extractors) doesn't respect default file system restriction

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4564]
### Nuclei version:
latest / dev

### Current Behavior:

```yaml
    extractors:
      - type: json
        json:
          - '.data'
        to: "/tmp/test.txt"
```

As of now above extractor can write arbitrary content to arbitrary location on the file system.

### Expected Behavior:
above extractor should failed to write and should work only when `-lfa` option is used.

### Anything else:
https://github.com/projectdiscovery/nuclei/pull/3608
