### ISSUE TITLE
[Feature] Edge cases that are not supported by rawhttp

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#457]
**Is your feature request related to a problem? Please describe.**

- [x] Arbitrary HTTP server version is not allowed.

Test template:- 

```yaml
requests:
  - raw:
      - |
        GET / http/0.9
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: close

    unsafe: true
```

```curl
echo https://example.com | nuclei -t test.yaml -debug -silent
```

Request generated by nuclei:-

```http
GET / HTTP/1.1
Connection: close
Host:example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
```

Expected request generated by nuclei:-

```http
GET / http/0.9
Connection: close
Host:example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
```

- [x] Arbitrary Request format is not supported.

```yaml
requests:
  - raw:
      - |
        GET /
        GET /
        HTTP/1.1
        
    unsafe: true
```

Error:- **[WRN] [] Could not execute step: malformed request supplied**

**Comment by bauthard** [comment]
@geeknik if you have more cases to share you can update this list in the comment section.

**Comment by geeknik** [comment]
@bauthard 

RFC 7230, specifically [section 3.2.2](https://tools.ietf.org/html/rfc7230#section-3.2.2) allows for the passing of multiple values for the same request header via comma-separated list. However, we currently are not allowed to do so:

```
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host:{{Hostname}},127.0.0.1,localhost
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: keep-alive

    unsafe: true
    disable-automatic-host-header: true
```

Actual request sent by nuclei 2.2.1-dev:
```
GET / HTTP/1.1
Connection: keep-alive
Host:hackerone.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
```

Expected request:
```
GET / HTTP/1.1
Connection: keep-alive
Host:hackerone.com,127.0.0.1,localhost
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
```
