### ISSUE TITLE
Support for Internal Matchers using `internal: true`

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4580]
### Please describe your feature request:

- follow up was https://github.com/projectdiscovery/nuclei/pull/4015#issuecomment-1676009780
While writing multi-protocol templates or flow templates when matchers are used duplicated or multiple events are printed , to avoid this similar to `extractors` , `internal: true` can be added to matcher to make it internal which  is not printed in terminal output

### Example template

```yaml
id: dns-ns-probe

info:
  name: Nuclei flow dns ns probe
  author: pdteam
  severity: info
  description: Description of the Template
  reference: https://example-reference-link

flow: |
  dns("fetch-ns");
  for(let ns of template["nameservers"]) {
    set("nameserver",ns);
    dns("probe-ns");
  };

dns:
  - id: "fetch-ns"
    name: "{{FQDN}}"
    type: NS
    matchers:
      - type: word
        words:
          - "IN\tNS"
        internal: true
    extractors:
      - type: regex
        internal: true
        name: "nameservers"
        group: 1
        regex:
          - "IN\tNS\t(.+)"

  - id: "probe-ns"
    name: "{{nameserver}}"
    type: A
    class: inet
    retries: 3
    recursion: true
    extractors:
      - type: dsl
        dsl:
          - "a"
```

### Without `internal: true` 

```console
$ ./nuclei -u oast.fun -t integration_tests/flow/dns-ns-probe.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.4-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.1.4-dev (development)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[dns-ns-probe] [dns] [info] oast.fun
[dns-ns-probe] [dns] [info] ns1.oast.fun [206.189.156.69]
[dns-ns-probe] [dns] [info] ns2.oast.fun [206.189.156.69]
```

## With `internal: true`

```console
$ ./nuclei -u oast.fun -t integration_tests/flow/dns-ns-probe.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.4-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.1.4-dev (development)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[dns-ns-probe] [dns] [info] ns1.oast.fun [206.189.156.69]
[dns-ns-probe] [dns] [info] ns2.oast.fun [206.189.156.69]
```

>[!NOTE]
> This was implicitly done in < v3.1.4 but it was design issue and broke templates when using for loop (see: #4581 ) . Hence with this feature same behaviour can be enabled/disabled with `internal: true`
