### ISSUE TITLE
Missing results when iterating over protocol in `flow`

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4581]
### Nuclei version:

main | latest

### Example Template

```yaml
id: public-s3-buckets
info:
  name: Public S3 Bucket
  author: princechaddha
  severity: critical
  description: |
    This templates creates s3 bucket in your AWS account
  reference:
    - https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html
    - https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html
  tags: cloud,devops,aws,amazon,s3

flow: |
  code(1)
  for(let bucketName of template.buckets){
    set("bucket", bucketName)
    code(2)
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      aws s3api list-buckets --query 'Buckets[*].Name'

    extractors:
      - type: json # type of the extractor
        internal: true
        name: buckets
        json:
          - '.[]'

  - engine:
      - sh
      - bash
    source: |
      aws s3api get-bucket-acl --bucket $bucket --query 'Grants[?(Grantee.URI=="http://acs.amazonaws.com/groups/global/AllUsers")]'

    matchers:
      - type: word
        words:
          - "FULL_CONTROL"

    extractors:
     - type: dsl
       dsl:
         - '"The S3 bucket " + bucket +" is publicly accessible"'
# digest: 4b0a00483046022100b5f1cdb52d588a7bc9144535a40a29b5e0ca8ed15d74373b35b5a9b09d053fd40221009983156d083ff792290dd4186634b82d97bb5832a2f82a53496f9a8b7c9fbd77:73812c4e0e52692225979bd2d5f05a3c
```

### Current Behavior:

```console
$  nuclei -t bucket.yaml -code         

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.3

		projectdiscovery.io

[INF] Current nuclei version: v3.1.3 (latest)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from tarun
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket6> is publicly accessible]
```

### Expected Behavior:

```console
$ ./nuclei -t bucket.yaml -code 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.4-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.1.4-dev (development)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from tarun
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket1> is publicly accessible]
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket2> is publicly accessible]
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket3> is publicly accessible]
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket4> is publicly accessible]
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket5> is publicly accessible]
[public-s3-buckets] [code] [critical]  [The S3 bucket <bucket6> is publicly accessible]
```

### Anything else:

cc: @princechaddha
