### ISSUE TITLE
Issue while using redirects: true while unsafe: true

### ISSUE THREAD

**Issue by exploit40** [projectdiscovery/nuclei#4616]
```yaml
http:
  - raw:
    - |+
      GET / HTTP/1.1
      Host: {{Hostname}}
          Host: evil.com

    redirects: true
    max-redirects: 3
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(header, "Set-Cookie")' 
```

while using unsafe: true redirects: true giving error in sending request "_[WRN] [HostHeaderOptimizedUnsafe] Could not execute request for https://example.com: remote error: tls: user canceled_   "

**BUT**
while removing redirects: true like below .template works fine. **Please tell me how to use redirects here**

```yaml
http:
  - raw:
    - |+
      GET / HTTP/1.1
      Host: {{Hostname}}
          Host: evil.com

    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(header, "Set-Cookie")' 
```

**Comment by tarunKoyalwar** [comment]
@exploit40 , `remote error: tls: user cancelled` is error related to tls handshake when you are proxying your traffic through burpsuite which is most likely the issue here . 

i found 
no error when tested in both unsafe and normal mode with redirection

### example template

```yaml
id: basic-example

info:
  name: Basic GET Request
  author: pdteam
  severity: info

http:
  - raw:
    - |+
      GET /redirect-to?url=https://scanme.sh HTTP/1.1
      Host: {{Hostname}}

    redirects: true
    max-redirects: 3
    unsafe: true

    matchers:
      - type: status
        status:
          - 200
```

```console
$  ./nuclei -t a.yaml -debug -u https://httpbin.org/ 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.5

		projectdiscovery.io

[INF] Current nuclei version: v3.1.5 (latest)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] [basic-example] Dumped HTTP request for https://httpbin.org/redirect-to?url=https://scanme.sh

GET /redirect-to?url=https://scanme.sh HTTP/1.1
Host: httpbin.org

[DBG] [basic-example] Dumped HTTP response https://httpbin.org/redirect-to?url=https://scanme.sh

HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Thu, 11 Jan 2024 21:01:23 GMT

ok
[basic-example:status-1] [http] [info] https://httpbin.org/redirect-to?url=https://scanme.sh
```
