### ISSUE TITLE
extractors regex internal get extra data []

### ISSUE THREAD

**Issue by passwa11** [projectdiscovery/nuclei#4617]
### Nuclei version:

v3.1.5
### Current Behavior:

flow: http(1)&&http(2)
extractors in http(1)
timestrp used in http(2)
```
extractors:
      - type: regex # type of the extractor
        part: body  # part of the response (header,body,all)
        name: timestrp
        internal: true
        group: 1
        regex:
          - '\d{6}\\(\d+)\.'
```
strings : `\somgstr\202401\2024011010161234.jpg` but the nuclei debug info 
```
[2024011010161234]
```
get extra data [ ] !! if not use  flow: http(1)&&http(2) the extractors work well.
### Expected Behavior:

only 2024011112143362
