### ISSUE TITLE
When sending a request using the following template, the "?" at the end of the URL will be lost 

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/nuclei#4622]
When sending a request using the following template, the "?" at the end of the URL will be lost abnormally. I was wondering how to retain this "?"

```yaml
http:
  - raw:
      - |+
        POST /general/appbuilder/web/portal/gateway/? HTTP/1.1
        Host: {{Hostname}}`
```

The following request was actually sent:

```http
POST /general/appbuilder/web/portal/gateway/ HTTP/1.1
Host: x.x.x.x
```

_Originally posted by @Chi11-H in https://github.com/projectdiscovery/nuclei/discussions/4282_

**Comment by olearycrew** [comment]
Example template:

```yaml
id: test-question-mark

info:
  name: Test Question Mark
  author: olearycrew
  severity: info

http:
  - raw:
    - |+
      POST /general/appbuilder/web/portal/gateway/? HTTP/1.1
      Host: {{Hostname}}
```

Run with:

`nuclei -t /home/kali/test/testquestion.yaml -u https://olearycrew.requestcatcher.com/`

This does NOT send the actual `?` on the POST:

```
[test-question-mark] Dumped HTTP request for https://olearycrew.requestcatcher.com/general/appbuilder/web/portal/gateway


POST /general/appbuilder/web/portal/gateway HTTP/1.1
Host: olearycrew.requestcatcher.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2762.73 Safari/537.36
Connection: close
Content-Length: 0
Accept-Encoding: gzip


[test-question-mark] Dumped HTTP response https://olearycrew.requestcatcher.com/general/appbuilder/web/portal/gateway

HTTP/1.1 200 OK
Connection: close
Content-Length: 14
Content-Type: text/plain; charset=utf-8
Date: Thu, 11 Jan 2024 18:39:29 GMT

request caught
```

![CleanShot 2024-01-11 at 13 38 53](https://github.com/projectdiscovery/nuclei/assets/6044920/b8d46a04-1796-4712-9b8d-c3712ed53ced)
