### ISSUE TITLE
[Feature] Introducing nuclei config file

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#472]
**Is your feature request related to a problem? Please describe.**

Many times, we wanted to execute customized scans with additional flags, and I need to make sure to use those flags every nuclei scan, to name a few:- 

- Custom user-agent with `-H` flag
- Custom header with `-H` flag
- Running templates with a specific severity
- Excluding a few templates from each scan

**Describe the solution you'd like**

With a config file, a user can define all the above needs in the config file for once which will be followed on every run. 

**Suggested flag:-**

`config`, as default config file will be saved/read from the default location, will be used, custom config can be provided using `-config` flag.

**Notes:-**

As a default, execution will be based on the config file, if the CLI flag is provided, the CLI flag will take precedence over the config file options.

**Comment by bauthard** [comment]
Linking https://github.com/projectdiscovery/nuclei/issues/471 here, as config file might be a better way to handle exclusion of templates.

**Comment by bauthard** [comment]
Here is an example of config file:- 

```yaml
# Templates to scan (same as t flag)
templates:
    - cves/
    - exposures/
    - explosed-tokens/

# Templates to exclude from scans (same as exclude flag)
exclude:
    - technologies/
    - exposed-panels/
    - miscellaneous/wp-xmlrpc.yaml

# Templates to run based on severity
severity:
    - critical
    - high
    - medium
    - low

# Custom headers to send with HTTP requests (same as H flag)
headers:
    - X-Bounty-Hunter: h1/geekboy
    - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)

# Rate limit related configs
rate-limit: 500
bulk-size: 50
c: 30

# Nuclei CLI flags
no-meta: false
json: false
include-rr: false
silent: true
update-templates: false
update-directory: $HOME/
retries: 1
timeout: 10
```
