### ISSUE TITLE
Regex Fails to Compile for a specific pattern

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#4734]
### Nuclei version:
v3.1.10

### Current Behavior:
```
[ERR] Error occurred parsing template /tmp/example.yaml: could not compile request: could not compile operators: could not compile matcher: could not compile regex: [x- ]
```
For when running -validate for this template:
```yaml
id: testtemp

info:
  name: testtemp
  author: meme-lord
  severity: info
  tags: test

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: regex
        part: body
        regex:
          - "[x- ]"

    extractors:
      - type: regex
        part: body
        regex:
          - "[x- ]"
```

### Expected Behavior:
The template to validate successfully

### Steps To Reproduce:
```sh
nuclei -t example.yaml -validate
```

### Workaround
My workaround for this currently is to just rearrange the elements in the group eg `[x -]` but hacks like this shouldn't be needed.
