### ISSUE TITLE
`stop-at-first-match` + payloads doesn't work with flow

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4744]
### Nuclei version:
latest | dev

### Current Behavior:
`stop-at-first-match` with `payloads` doesn't work with flow.

### Expected Behavior:
`stop-at-first-match` works as expected with flow.

### Steps To Reproduce:
```yaml
id: flow-spm-bug

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

flow: http(1) && http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}/{{randstr}}"

    matchers:
      - type: status
        status:
          - 404
        internal: true

  - method: GET
    path:
      - "{{BaseURL}}/{{paths}}"

    payloads:
      paths:
        - gg
        - gg
        - gg

    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 404
```

```
echo https://example.com | nuclei -t test.yaml

[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
```

Expected:

```
echo https://example.com | nuclei -t test.yaml

[flow-spm-bug] [http] [info] https://example.com/gg [paths="gg"]
```

### Anything else:
it works as expected when used without payloads, so it has something to do when flow is used with payloads combination.
