### ISSUE TITLE
Issue with self contained + request annotation in flow

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4788]
### Nuclei version:

main | dev

### Template

```yaml
id: stripe-secret-key

info:
  name: Stripe Secret Key
  author: DhiyaneshDk
  severity: high
  tags: exposure,token,stripe

flow: http(1) && http(2)

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    extractors:
      - type: regex
        part: body
        name: token
        regex:
          - 'sk_(?:live|test)_[0-9a-zA-Z]{24}'
        internal: true

  - raw:
      - |
        @Host: https://api.stripe.com:443
        GET /v1/charges?limit=1 HTTP/1.1
        Host: api.stripe.com
        Authorization: Bearer {{token}}

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "billing_details")'
        condition: and
```

### Nuclei

```console
$ nuclei -u https://gist.githubusercontent.com/DhiyaneshGeek/a440sdf/test.txt -t test.yaml -vv -debug
```

- [ ] Parsing Issue with request annotation
- [ ] self-contained template not working with flow

### Anything else:

- reach out to @DhiyaneshGeek for more info
