### ISSUE TITLE
Issue with Lua script execution in redis js module

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4790]
### Please describe your feature request:

```yaml
id: redis-lua-script

info:
  name: Redis RunLuaScript - Detect
  author: DhiyaneshDK
  severity: info

javascript:
  - code: |
      const redis = require('nuclei/redis');
      const result = redis.RunLuaScript('Host', 'Port', 'Password', 'return redis.call("get", KEYS[1])');
      log(to_json(result));

    args:
      Host: "131.72.44.54"
      Port: "6379"
      Password: ""

    matchers:
      - type: dsl
        dsl:
          - "success == true"
```

### Anything else:

>is this possible to use redis lua in redis module without this? return redis.call('INFO')

reach out to @DhiyaneshGeek  or @pussycat0x  for more info
