### ISSUE TITLE
Add a generic sql

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4791]
### Please describe your feature request:

we currently have seperate modules for mysql,postgres and other sql databases instead of having a single sql module .because this is how db's are used in golang . This is causing lot of duplication in code . instead we can just export sql module and internally add drivers . 

go sql drivers => https://go.dev/wiki/SQLDrivers

we should only add drivers that are required instead of adding all databases . current focus of templates team is on 
>  mysql,mssql, postgress, mongodb and redis

```yaml
id: all-databases-example

info:
  name: Example Databases
  author: DhiyaneshDk
  severity: high
  metadata:
    shodan-query: port:3306
  tags: js,mssql,network

javascript:
  - code: |
      const sql = require('nuclei/sql');
      let db = sql.Connect(Driver,Host,Port,User,Pass)
      db.Exec(query)

    args:
      Driver: "mysql"
      Host: "{{Host}}"
      Port: "3306"
      User: "root"
      Pass: "root"
      Query: "Show databases"

    matchers:
      - type: dsl
        dsl:
          # - "response == true"
          - "success == true"
        # condition: and
```

### Follow-up
- deprecate duplicated sql modules like mysql,postgres,mssql
