### ISSUE TITLE
File template update

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#481]
- [ ] File type template update

<details>
<summary> Current template </summary>

```yaml
id: test-file

info:
  name: File based test template
  author: ice3man
  severity: low

file:
    # extensions is the master level flag that ovverides allowlist and denylist.
    # use extension when the pattern to match is highly specific to a file type, for
    # example when you are writing checks to detect secrets in a language like php, etc.
  - extensions: [".go"]

    # allowlist removes an item from the denylist. both default and user provided 
    # denylist can be overwriten by using an allowlist value. For example, to allow .css
    # to be scanned along with all other extensions, which is in the default denylist can be done
    # by uncommenting the next line adding .css to the allowlist.
    #allowlist: [".css"] 
    
    # denylist adds an extension to the denylist which will not be scanned by nuclei. Nuclei
    # has a comprehensive denylist which can be extended as per user's choice.
    #denylist: [".go"]
    matchers:
      - type: word
        words:
          - "Workflows"
```
</details>
<details>
<summary> Updated template  </summary>

```yaml
id: File based template updates

info:
  name: File based test template
  author: ice3man
  severity: low

file:

    # As default, everything under given path will be scanned except extensions defined in the default denylist.
    # To allow scan on extensions that are added into denylist, specific or additional extension can be listed.
    # Example:- Running scans on all extensions including '.bin' that is part of denylist.
  - extensions:
        - '*'
      # - '.bin'
      # - .yaml
      # - .go

    # denylist adds an extension to the denylist which will not be scanned by nuclei. Nuclei
    # has a comprehensive denylist which can be extended as per the user's choice.
    # also denylist attribute can be used at runtime to add more extension at runtime as shown in the below example:-
    denylist:
        - '.log'
    max-size: 5 # Size in MB
    no-recursive: true # False as default.


    matchers:
      - type: word
        words:
          - "Workflows"
```
</details>

Note:- we can remove the `allowlist` as it will be handled under extensions.
