### ISSUE TITLE
Nuclei still shows the second output even though the second matcher doesnt match with the target

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei#4810]
Nuclei still showing us the second output even if the second matcher is wrong. For example, I have a nuclei template like this
```yaml
id: buggy-template

info:
  name: Testing Template
  author: daffainfo
  severity: info
  tags: test

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /impossible_to_match HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: or
    matchers:
      - type: dsl
        dsl:
          - "contains(body_1, '<title>Example Domain</title>')"
          - "status_code_1 == 200"
        condition: and

      - type: dsl
        dsl:
          - "contains(body_2, 'VERYVERYRANDOMSTRINGGGGGLOLL')"
          - "status_code_2 == 999"
        condition: and
```

And the command:
```bash
nuclei -u https://example.com -t buggy-template.yaml
```

Output:
```
[INF] Current nuclei version: v3.1.10 (latest)
[INF] Current nuclei-templates version: v9.7.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 49
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[buggy-template] [http] [info] https://example.com/
[buggy-template] [http] [info] https://example.com/impossible_to_match
```

Expected output:
```
[INF] Current nuclei version: v3.1.10 (latest)
[INF] Current nuclei-templates version: v9.7.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 49
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[buggy-template] [http] [info] https://example.com/
```

**Comment by daffainfo** [comment]
But, if you switch the request and also the matcher like this
```
id: buggy-template

info:
  name: Testing Template
  author: daffainfo
  severity: info
  tags: test

http:
  - raw:
      - |
        GET /impossible_to_match HTTP/1.1
        Host: {{Hostname}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: or
    matchers:
      - type: dsl
        dsl:
          - "contains(body_1, 'VERYVERYRANDOMSTRINGGGGGLOLL')"
          - "status_code_1 == 999"
        condition: and

      - type: dsl
        dsl:
          - "contains(body_2, '<title>Example Domain</title>')"
          - "status_code_2 == 200"
        condition: and
```

The output will be like this
```
[INF] Current nuclei version: v3.1.10 (latest)
[INF] Current nuclei-templates version: v9.7.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 49
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[buggy-template] [http] [info] https://example.com/
```

**Comment by dogancanbakir** [comment]
I've changed the templates slightly and named DSL matchers to make them more verbose. First case:

```console
$ go run . -u https://example.com -t buggy-template.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.0-dev

                projectdiscovery.io

[INF] Current nuclei version: v3.2.0-dev (development)
[INF] Current nuclei-templates version: v9.7.8 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 126
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[buggy-template:dsl_1] [http] [info] https://example.com/
[buggy-template:dsl_1] [http] [info] https://example.com/impossible_to_match
```

The reason we get `dsl_1` matched for both requests is because we’re matching against the first result. 
```yaml
- type: dsl
        dsl:
          - "contains(body_1, '<title>Example Domain</title>')"
          - "status_code_1 == 200"
        condition: and
```


Second case:

```console
$ go run . -u https://example.com -t buggy-template.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.0-dev

                projectdiscovery.io

[INF] Current nuclei version: v3.2.0-dev (development)
[INF] Current nuclei-templates version: v9.7.8 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 126
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[buggy-template:dsl_2] [http] [info] https://example.com/
```

And the reason you get `dsl_2` matched only for the second request is because we’re matching against the second result. 

```yaml
- type: dsl
        name: dsl_2
        dsl:
          - "contains(body_2, '<title>Example Domain</title>')"
          - "status_code_2 == 200"
        condition: and
```

Am I missing something here? @tarunKoyalwar

**Comment by daffainfo** [comment]
What is the diff between `dsl_1` and `dsl_2`? You put the same matcher btw

**Comment by dogancanbakir** [comment]
matchers from first template:
```yaml
    matchers-condition: or
    matchers:
      - type: dsl
        name: dsl_1
        dsl:
          - "contains(body_1, '<title>Example Domain</title>')"
          - "status_code_1 == 200"
        condition: and

      - type: dsl
        name: dsl_2
        dsl:
          - "contains(body_2, 'VERYVERYRANDOMSTRINGGGGGLOLL')"
          - "status_code_2 == 999"
        condition: and
```

matchers from second template:
```yaml
    matchers-condition: or
    matchers:
      - type: dsl
        name: dsl_1
        dsl:
          - "contains(body_1, 'VERYVERYRANDOMSTRINGGGGGLOLL')"
          - "status_code_1 == 999"
        condition: and

      - type: dsl
        name: dsl_2
        dsl:
          - "contains(body_2, '<title>Example Domain</title>')"
          - "status_code_2 == 200"
        condition: and
```

The difference between `dsl_1`(from first template) and `dsl_2`(from second template) is that, in `dsl_2` (from second template) you're matching against second request -`body_2`, `status_code_2` etc.
