### ISSUE TITLE
[issue] ongoing dev bugs

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#483]
- [x] Missing sub matcher name in `extractors`

`echo https://developer.uber.com | ./nuclei -t test.yaml`

<details>

```yaml
id: google-api-key

info:
  name: Google API Key
  author: Swissky
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        name: ext-name
        part: body
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
```
</details>

-------
- [x] Issue with dynamic extractor

`echo http://caqpvbbl1jckz9lfm5wybxr980eq2f.burpcollaborator.net | ./nuclei -t test.yaml --debug-req`

<details>

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /menu/neo HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Connection: close

      - |
        GET /menu/stc HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Connection: close
        burp: §server§

    extractors:
      - type: kval
        name: server
        part: body
        internal: true
        kval:
          - "server"
```
</details>

-------
</details>

- [x] Nil pointer dereference when running workflows to run directory

`echo http://caqpvbbl1jckz9lfm5wybxr980eq2f.burpcollaborator.net | ./nuclei -t test.yaml --debug-req`
`chaos -d uber.com -bbq -http-url | ./nuclei -t ~/nuclei-templates/workflows/wordpress-workflow.yaml`

<details>

```yaml
workflows:
  - template: exposed-tokens/

```
</details>

-------
- [x] `kval` extractor issue with `-` input

`echo http://caqpvbbl1jckz9lfm5wybxr980eq2f.burpcollaborator.net | ./nuclei -t test.yaml --debug-req`

<details>

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /menu/neo HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Connection: close

      - |
        GET /menu/stc HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Connection: close
        burp: §server§
        burp2: §gg§
        burp3: §gg2§

    extractors:
#      - type: kval
#        name: server
#        part: body
#        internal: false
#        kval:
#          - "server"
#
#      - type: kval
#        name: gg
#        part: body
#        internal: false
#        kval:
#          - "X-Collaborator-Versio"
#
      - type: regex
        name: gg2
        part: body
        internal: false
        regex:
          - "Content-Length"

```
</details>

-------
- [x] Output file to ignore debug data. 

`echo https://developer.uber.com | ./nuclei -t ~/nuclei-templates/workflows/wordpress-workflow.yaml -o output.txt`

------
- [x] Could not dump http response
```
echo https://contentmoments.aol.com | ./nuclei -t test.yaml --debug -v

[WRN] [bad-request] Could not execute step: could not handle http request: could not dump http response: http: ContentLength=4210 with Body length 9726
```

<details>

```yaml
requests:
  - raw:
      - |
        GET /  HTTP/1.1
        Host: {{Hostname}}
        Origin: %0dfoo%0aaaaaaa//
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: close

    unsafe: true
    redirects: true
    max-redirects: 10
```

**Comment by bauthard** [comment]
- [ ] `.nuclei-ignore` file getting ignored while downloading templates.

**Comment by ehsandeep** [comment]
- [ ] Panic error with passive templates

<details>

```
# ./nuclei -l output/ -t ~/nuclei-templates/ -passive

goroutine 94 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc002a9f1e0, 0x181b158, 0x10, 0xc0036e44e0, 0x0, 0xc0036e0b20, 0x30, 0x17b1a60)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/request.go:186 +0x150
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/clusterer.(*Executer).Execute(0xc0036994d0, 0x181b158, 0x10, 0x0, 0x0, 0x0)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/clusterer/executer.go:63 +0xc5
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList(0xc0000981c0, 0xc003629ce0, 0x0)
	/Users/geekboy/Github/nuclei/v2/internal/runner/processor.go:38 +0x1fc
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration.func1(0xc0036bdc00, 0xc0036b8cd0, 0xc0000981c0, 0xc003629ce0)
	/Users/geekboy/Github/nuclei/v2/internal/runner/runner.go:286 +0xb0
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration
	/Users/geekboy/Github/nuclei/v2/internal/runner/runner.go:280 +0xba5
```
</details>

**Comment by ehsandeep** [comment]
- [ ] Issue with Race condition template

`echo http://caqpvbbl1jckz9lfm5wybxr980eq2f.burpcollaborator.net | ./nuclei -t race.yaml --debug-req`

<details>

```yaml
id: race-condition-testing

info:
  name: Race condition testing
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        POST /coupons HTTP/1.1
        Host: {{Hostname}}
        Pragma: no-cache
        Cache-Control: no-cache, no-transform
        User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

        promo_code=20OFF        

    race: true
    race_count: 10

    matchers:
      - type: status
        part: header
        status:
          - 200
```
</details>

------

**Comment by ehsandeep** [comment]
- [ ] nil pointer crash with `unsafe: true`

<details>

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    unsafe: true
    redirects: true
    max-redirects: 10
```

</details>
