### ISSUE TITLE
Filter field in http protocol to select what requests to be fuzzed

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4846]
### Proposed Changes

- When writing fuzzing templates , there is a need to specify if this fuzzing templates should run or should not run on a given request and this is achieved by filters ( which is a similar to/ twin of matchers )

```yaml
http:
  - filters:
      - type: dsl
        dsl:
          - method != "GET"
          - method != "HEAD"
          - contains(content_type, "application/json")
        condition: and
```

Here, only those requests which don't have GET/HEAD request method and content type is application/json will be executed on this template and others will be excluded /skipped
