### ISSUE TITLE
Support KV Fuzzing in Fuzz rules

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4848]
### Proposed Changes

Currently fuzzing in nuclei is designed / logically seperated into key-value fields. 

```yaml
    fuzzing:
      - part: query
        type: replace
        mode: multiple
        values: 
          - "^[0-9]+$" # only if value is number
        fuzz:
          - '{{nums}}'
```

so fuzzing rule in above format will only fuzz every value of query params (map), and key cannot be fuzzed nor it was possible to pass both key and value ( ex: new query param pair altogether )  at once , but with kv this should be possible

In below fuzzing rule we are adding new headers altogether by specifying / passing kv combination in fuzz section

```yaml
    fuzzing:
      - part: headers
        type: replace
        mode: single
        fuzz:
          X-Forwarded-For: "{{domain}}"
          X-Forwarded-Host: "{{domain}}"
          Forwarded: "{{domain}}"
          X-Real-IP: "{{domain}}"
          X-Original-URL: "{{domain}}"
          X-Rewrite-URL: "{{domain}}"
          Host: "{{domain}}"
          # " Host": "{{domain}}" # space before host (not supported yet due to lack of unsafe mode)
```
