### ISSUE TITLE
[feature] Display redirect chain with debug flag

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#486]
**Is your feature request related to a problem? Please describe.**
Currently, we don't see a redirect chain when using the debug flag.

**Describe the solution you'd like**
Expose the redirect request/response data in debug mode for better template debugging.

Test template:- 

```yaml
id: basic-redirect

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
```

```
echo http://hackerone.com | ./nuclei -t redirect.yaml --debug
```
