### ISSUE TITLE
No Query Parameters in protocol variables

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4869]
### Nuclei version:

main | dev

### Current Behavior:

```yaml
id: post-based-xss

info:
  name: Post-based XSS
  author: mayurudiniya
  severity: high

variables:
  URL: "{{BaseURL}}"

code:
  - engine:
      - bash
    source: |
      read url
      query=$(echo $url | awk -F"?" '{print $2}')
      echo "${query}"

    extractors:
      - type: dsl
        dsl:
          - response
```

```console
 ./nuclei -t x.yaml -v  -u https://scanme.sh/\?lol\=syz -code -debug -v -svd

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.0-dev

        projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.0-dev (development)
[INF] Current nuclei-templates version: v9.7.8 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 126
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from tarun
[INF] Targets loaded for current scan: 1
[VER] [post-based-xss] Executed code on local machine https://scanme.sh/?lol=syz
[DBG] Code Protocol request variables: 
    1. BaseURL => https://scanme.sh/
    2. DN => scanme
    3. FQDN => scanme.sh
    4. File => /
    5. Host => scanme.sh
    6. Hostname => scanme.sh
    7. Input => https://scanme.sh/
    8. Path => /
    9. Port => 443
    10. RDN => scanme.sh
    11. RootURL => https://scanme.sh
    12. SD => 
    13. Scheme => https
    14. TLD => sh
    15. URL => https://scanme.sh/

[DBG] [post-based-xss] Dumped Executed Source Code for https://scanme.sh/?lol=syz

read url
query=$(echo $url | awk -F"?" '{print $2}')
echo "${query}"

[DBG] Code Protocol response variables: 
    1. input => https://scanme.sh/?lol=syz
    2. interactsh-server => 
    3. response => lol=syz
    4. template-id => post-based-xss
    5. template-info => {Post-based XSS mayurudin .... nil> {high} map[] <nil> }
    6. template-path => /Users/tarun/Codebase/nuclei/x.yaml
    7. type => code

[DBG] [post-based-xss] Dumped Code Execution for https://scanme.sh/?lol=syz

lol=syz

[post-based-xss] [code] [high] https://scanme.sh/?lol=syz [lol=syz]
```

- missing or incorrect `Input` variable in request variables ( these variables are common for all protocols ) so most likely a issue on all protocols, but the input in protocol response variables is correct
- should we add a new variable for query param `query` ?

### Anything else:

- consult @ehsandeep
