### ISSUE TITLE
Variables sharing between two req sections of protocol is not working

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4870]
### Nuclei version:

main | latest

### Current Behavior:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "This is test matcher text"
        negative: true

    extractors:
      - type: dsl
        name: ffff
        dsl:
          - status_code
        internal: true

  - method: GET
    path:
      - "{{BaseURL}}/{{ffff}}"
```

- This throws a unresolved variable error 

### Expected Behavior:

- no error
