### ISSUE TITLE
Missing variables in code protocol operators (matchers/extractors)

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4878]
### Nuclei version:

main | dev

### Current Behavior:

- In code protocol variables and other options given in input were not available in matchers or extractors resulting in incorrect behaviour

### Steps To Reproduce:

```yaml
id: rds-event-sub-enable
info:
  name: RDS Event Subscription Not Enabled
  author: princechaddha
  severity: high
  description: |
    Ensures Amazon RDS event notifications are enabled for database instance level events, allowing for real-time alerts on operational changes.
  impact: |
    Lack of event notifications may delay the response to critical RDS operational events, affecting database availability and performance.
  remediation: |
    Enable RDS event notification subscriptions for relevant database instance level events through the AWS Management Console or AWS CLI.
  reference:
    - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html
  tags: cloud,devops,aws,amazon,rds

variables:
  region: "ap-northeast-1"

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      aws rds describe-event-subscriptions --region $region --query "EventSubscriptionsList[?SourceType == 'db-instance'].CustSubscriptionId"

    matchers:
      - type: word
        words:
          - '[]'

    extractors:
      - type: dsl
        dsl:
          - '"There are no Amazon RDS event subscriptions created for instance level events in " + region + " AWS region"'
 ```

```console
$  nuclei -code -t a.yaml -v -ms

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.10

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.1.10 (latest)
[INF] Current nuclei-templates version: v9.7.8 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 126
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from tarun
[VER] [rds-event-sub-enable] Executed code on local machine 
[rds-event-sub-enable] [matched] [code] [high] 
```

> [!NOTE]
> here extractor value is empty because dsl extractor failed to evaluate(due to missing region var value) resulting in empty string
