### ISSUE TITLE
Fuzzing loses context of request condition

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#4891]
### Nuclei version:
`main|dev`

### Current Behavior:
Fuzzing uses a flat request iteration logic that loses context of ordering while fuzzing a particular element, namely request count is always zero at https://github.com/projectdiscovery/nuclei/blob/df67578d98df605d8a97d52b007d445dcc9c293e/pkg/protocols/http/request_fuzz.go#L195

### Expected Behavior:
Either erroring if matchers/dsl contains request condition logic or introduce the concept of fuzzing context, while fuzzing a particular item (for example a query parameter) initialize a counter until the attack type has finished for that particular element:
```yaml
matchers:
      - type: dsl
        dsl:
          - 'duration_1>18'
          - 'duration_2<7'
```
