### ISSUE TITLE
Incorrect result output from conditional workflows

### ISSUE THREAD

**Issue by tovask** [projectdiscovery/nuclei#4933]
I have some complex scenarios with workflows:
 - a child template is executed even if its parent template's condition does not match, if another _non-direct_ parent matches before its own one.
 - in other times, a match of a top level template (that does not have a child template) does not show up in the output if another top level template's child does not match.

(This may sounds complicated, so better to check out the example below :wink::arrow_down:)

### Nuclei version:
3.1.0 - 3.2.2

### Steps To Reproduce:
I created this simplified workflow to reproduce the issue:
```YAML
id: debug_workflow
info:
  name: Debug workflow
  author: Levente Kovats

workflows:
      - template: always_match1.yaml
        subtemplates:
          - template: never_match.yaml
            subtemplates:
              - template: always_match3.yaml
      - template: always_match2.yaml
```
`always_match1.yaml`:
```YAML
id: always_match1
info:
  name: Test
  author: Levente Kovats
  severity: info
  description: Test template for investigations
  reference:
   - https://docs.projectdiscovery.io/templates/workflows/overview

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: dsl
        name: always_true
        dsl:
          - true
```
Similarly, there're `always_match2.yaml`, `always_match3.yaml` and a `never_match.yaml` template (this last one has an _always\_false_ matcher of course).

### Current Behavior:
If `always_match2` finishes before `never_match`, then `always_match3` is executed, despite `never_match` did not match:
```
./nuclei -disable-update-check -target https://httpbin.org/user-agent -workflows debug_workflow.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.2 (outdated)
[INF] Current nuclei-templates version:  (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] Workflows loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [always_match1] Sent HTTP request to https://httpbin.org/user-agent
[VER] [always_match2] Sent HTTP request to https://httpbin.org/user-agent
[VER] [never_match] Sent HTTP request to https://httpbin.org/user-agent
[VER] [always_match3] Sent HTTP request to https://httpbin.org/user-agent
[always_match3:always_true] [http] [info] https://httpbin.org/user-agent
```
Or when the `always_match2` is slowler than `never_match`, then even the `always_match2` does not show up:
```
 ./nuclei -disable-update-check -target https://httpbin.org/user-agent -workflows debug_workflow.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.2 (outdated)
[INF] Current nuclei-templates version:  (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] Workflows loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [always_match1] Sent HTTP request to https://httpbin.org/user-agent
[VER] [never_match] Sent HTTP request to https://httpbin.org/user-agent
[VER] [always_match2] Sent HTTP request to https://httpbin.org/user-agent
[INF] No results found. Better luck next time!
```

### Expected Behavior:
Until version 3.0.4 it works as expected:
```
./nuclei -disable-update-check -target https://httpbin.org/user-agent -workflows debug_workflow.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.4

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.0.4 (outdated)
[INF] Current nuclei-templates version:  (latest)
[INF] Workflows loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [always_match1] Sent HTTP request to https://httpbin.org/user-agent
[VER] [always_match2] Sent HTTP request to https://httpbin.org/user-agent
[always_match2:always_true] [http] [info] https://httpbin.org/user-agent
[VER] [never_match] Sent HTTP request to https://httpbin.org/user-agent
```

So it seems like the results of the templates got mixed inside the workflow. Any guess or idea?
Using Matcher Name based conditions might be a workaround, but in my case it's not an option, as I have templates with `matchers-condition: and`, and couldn't get it work by referring a named matcher.
