### ISSUE TITLE
filter support to dast templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4935]
Follow up for https://github.com/projectdiscovery/nuclei/pull/4925

- [x] support for filters for old dast templates ( missing value of method variable )

```yaml
variables:
  first: "cookie_injection"

http:
  - filters:
      - type: dsl
        dsl:
          - 'method == "GET"'
        condition: and

    payloads:
      reflection:
        - "{{first}}"

    fuzzing:
      - part: query
        type: postfix
        fuzz:
          - "{{reflection}}"

    matchers:
      - type: regex
        part: header
        regex:
          - '(?m)(?i)(^set-cookie.*cookie_injection.*)'
 ```
 - [x] improve `-dast` (fuzz) option to load only dast based templates
