### ISSUE TITLE
Nuclei doesn't execute subtemplate if flow in parent template of a workflow

### ISSUE THREAD

**Issue by gpc1996** [projectdiscovery/nuclei#4945]
### Nuclei version:
v3.2.2

### Current Behavior:
When using a custom workflow with custom templates, should one of the templates use the flow engine, any subtemplate after it won't be executed, and an error is generated.

### Expected Behavior:
When using a custom workflow with custom templates, the subtemplates should be executed regardless if the parent template uses the flow engine or not.

### Steps To Reproduce:
1. Have a workflow with a template that uses the flow engine and a subtemplate.
```
workflows:
    - template: custom_template_flow.yaml
      subtemplates:
         - template: custom_subtemplate.yaml
```
   Mandatory content in the first template:
`flow: <protocol>`

2. Run `nuclei -u "url_path" -w "workflow_path"`

3. Get this error:
![image](https://github.com/projectdiscovery/nuclei/assets/63821151/0111d2bc-1217-4919-9a0e-4a6b45ceb914)
