### ISSUE TITLE
interactsh-url dependent variables are not lazy evaluated

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4946]
### Nuclei version:

main | latest

### Current Behavior:

```yaml
id: some-exploit

info:
  name: "Some Exploit"
  author: pdteam
  severity: critical
  description: this is a test description

variables:
  callback: "{{interactsh-url}}"
  cmd: "nslookup {{callback}}"
  payload: '{{base64(cmd)}}'

http:
  - raw:
      - |
        GET /{{payload}} HTTP/1.1
        Host: {{Hostname}}
    
    matchers:
      - type: status
        status:
          - 200

    extractors:
      - type: dsl
        dsl:
          - 'base64_decode(payload)'
```

```console
$ nuclei -u https://scanme.sh -t a.yaml       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.fun
[some-exploit] [http] [critical] https://scanme.sh/bnNsb29rdXAge3tpbnRlcmFjdHNoLXVybH19 [nslookup {{interactsh-url}}]
```

### Expected Behavior:

```console
$ ./nuclei -u https://scanme.sh -t a.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.online
[some-exploit] [http] [critical] https://scanme.sh/bnNsb29rdXAgY28xZGtmc280N21oOGNwOGg1MTA2ODRyb2NtNHE5dWd5Lm9hc3Qub25saW5l ["nslookup co1dkfso47mh8cp8h510684rocm4q9ugy.oast.online"]
```
