### ISSUE TITLE
When the request content after the = sign is empty, the = sign will be deleted and an error will occur.

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/nuclei#5005]
### Nuclei version:
```
nuclei -version
[INF] Nuclei Engine Version: v3.1.10
```

### Current Behavior:
The parameters passed by passwd are empty, but the request will delete the = sign  

YAML  
```
http:
  - raw:
      - |
        GET /cgi-bin/xxxx.cgi?user=aaaa&passwd=&cmd=111  HTTP/1.1
        Host: {{Hostname}}

```

Resp  
```
GET /cgi-bin/xxxx.cgi?user=aaaa&passwd&cmd=111 HTTP/1.1
Host: 1localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.19.27 (KHTML, like Gecko) Version/9.1.2 Safari/537.19.27
Connection: close
Accept-Encoding: gzip
```

### Expected Behavior:
Note that there is an = sign in the content behind passwd.    
```
GET /cgi-bin/xxxx.cgi?user=aaaa&passwd=&cmd=111 HTTP/1.1
Host: 1localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.19.27 (KHTML, like Gecko) Version/9.1.2 Safari/537.19.27
Connection: close
Accept-Encoding: gzip
```

### Steps To Reproduce:
```
nuclei -t xxxx.yaml -u http://localhost --debug  
```
