### ISSUE TITLE
Internal extractor unresolvable when used with payloads

### ISSUE THREAD

**Issue by mwulftange** [projectdiscovery/nuclei#5017]
Internal extractors appear to be unresolvable if used with `payloads`. This issue is related to #4865.

Consider the following template, that is a variant of the integration test `http-matcher-extractor-dy-extractor.yaml` added in #4868:

```yaml
id: http-matcher-extractor-dy-extractor-payloads
info:
  name: HTTP matcher and extractor & dynamic extractor with payloads
  description: >
    Edgecase to test for a combination of matchers, extractors and dynamic extractors with payloads
  author: anonymous
  severity: info

http:
  - raw:
      - |
        GET {{payloadPath}} HTTP/1.1
      - |
        GET {{absolutePath}} HTTP/1.1
    attack: clusterbomb
    payloads:
      payloadPath:
        - '{{BaseURL}}'
    req-condition: true
    extractors:
      - type: regex
        internal: true
        part: body_1
        name: absolutePath
        regex:
          - '<a href="(/domains)">'
        group: 1
      - type: regex
        internal: false
        part: body_2
        name: title
        regex:
          - '<title[^>]*>([^<]+)</title>'
        group: 1
    matchers:
      - type: regex
        part: body_2
        regex:
          - '<title[^>]*>([^<]+)</title>'
```

Instead of using `{{BaseURL}}` directly in the first request, a `payloads` with one payload is used:

```yaml
    attack: clusterbomb
    payloads:
      payloadPath:
        - '{{BaseURL}}'
```

### Nuclei version:

3.2.2

### Current Behavior:

```
[WRN] [http-matcher-extractor-dy-extractor-payloads] Could not make http request for https://www.iana.org/: unresolved variables found: absolutePath
[WRN] [http-matcher-extractor-dy-extractor-payloads] Could not execute request for https://www.iana.org/: stop execution due to unresolved variables
```

### Expected Behavior:

```
[http-matcher-extractor-dy-extractor-payloads:title] [http] [info] https://www.iana.org/domains [Domain Name Services]
```

This behavior can also be observed with **3.x up to and including 3.1.3**.

### Steps To Reproduce:

Run the aforementioned template with `-debug` against `https://www.iana.org/`:

```bash
nuclei -t http-matcher-extractor-dy-extractor-payloads.yaml -u https://www.iana.org/ -debug
```

### Anything else:

- #4865
