### ISSUE TITLE
In custom workflows, nuclei doesn't execute subtemplate if parent template uses flow

### ISSUE THREAD

**Issue by gpc1996** [projectdiscovery/nuclei#5024]
### Nuclei version:
3.2.4

### Current Behavior:
When using a custom workflow with custom templates, should one of the templates use the flow engine, any subtemplate after it won't be executed, and an error is generated.

### Expected Behavior:
When using a custom workflow with custom templates, the subtemplates should be executed regardless if the parent template uses the flow engine or not.

### Steps To Reproduce:

1. Have a workflow with a template that uses the flow engine and a subtemplate.
```
workflows:
    - template: custom_template.yaml
      subtemplates:
         - template: custom_subtemplate.yaml
```

2. Run `nuclei -u "url_path" -w "workflow_path"`

3. Get panic error:
![image](https://github.com/projectdiscovery/nuclei/assets/63821151/cf9c5d02-3b19-44ca-b521-64a4795d3c80)
