### ISSUE TITLE
skip-variables-check option not working in self-contained templates

### ISSUE THREAD

**Issue by vallelianc** [projectdiscovery/nuclei#5026]
### Nuclei version:
v3.2.4

### Current Behavior:
Self-contained templates do not take the `skip-variables-check` option into account. It is therefore not possible to perform requests containing "{{}}".

### Expected Behavior:
Self-contained templates should also verify the `skip-variables-check` option.

### Steps To Reproduce:
The following template (not self-contained) works properly and is able to send a request with `{{test}}` in the path without attempting to resolve the `test` variable (because of the `skip-variables-check` option).

```yaml
id: ginandjuiceshop_testSkipVariablesCheck

info:
  name: skip-variables-check
  description: ""
  severity: HIGH
  remediation: ""
  author: "test"

self-contained: false

http:
- raw:
  - |+
    GET /blog/?search={{test}} HTTP/2
    Host: ginandjuice.shop

  skip-variables-check: true
  redirects: true
  cookie-reuse: true
  matchers:
  - type: dsl
    dsl:
    - (contains(body, "{{test}}")) && (status_code==200)
  matchers-condition: and
```
Command;
```
nuclei -t skipVariablesCheck_1.yaml -u https://ginandjuice.shop
```

However, when performing the same in a self-contained template, Nuclei is trying to find the `test` variable even with the `skip-variables-check` property set.

```yaml
id: ginandjuiceshop_testSkipVariablesCheck

info:
  name: skip-variables-check
  description: ""
  severity: HIGH
  remediation: ""
  author: "test"

self-contained: true

http:
- raw:
  - |+
    GET https://ginandjuice.shop/blog/?search={{test}} HTTP/2
    Host: ginandjuice.shop
  skip-variables-check: true
  redirects: true
  cookie-reuse: true
  matchers:
  - type: dsl
    dsl:
    - (contains(body, "{{test}}")) && (status_code==200)
  matchers-condition: and
```

Command:
```
nuclei -t skipVariablesCheck_2.yaml  -verbose
```

Output:
```
[WRN] [ginandjuiceshop_testSkipVariablesCheck] Could not execute request for : unresolved variables `https://ginandjuice.shop/blog/?search={{test}}` found in request
```
