### ISSUE TITLE
[Function Request] ldap is supported

### ISSUE THREAD

**Issue by pwnhxl** [projectdiscovery/nuclei#5054]
```
    matchers:
      - type: dsl
        dsl:
          - contains(interactsh_protocol, 'ldap')
```
It doesn't seem to be working.

This matcher doesn't seem to work, but I think interactsh supports ldap？

@ehsandeep
