### ISSUE TITLE
Fuzzing with `multiple` mode not working

### ISSUE THREAD

**Issue by RamanaReddy0M** [projectdiscovery/nuclei#5081]
### Current Behavior:
Currently nuclei panic when using fuzzing in `multiple` mode.

### Expected Behavior:
Nuclei's multiple mode fuzzing should work without panic.

### Steps To Reproduce:
__test.yaml__
```yaml
id: log4j-header-injection

info:
  name: Log-4j Injection In Headers
  author: Nishantbhagat57
  severity: high
  description: Detects potential Out-of-Band Log-4j Injection vulnerabilities, blind testing using payloads in headers.
  reference:
    - https://www.acunetix.com/blog/web-security-zone/critical-alert-log4shell-cve-2021-44228-in-log4j-possibly-the-biggest-impact-vulnerability-ever/
  tags: cmdi, oast, dast, log4j

http:
  - payloads:
      inject:
        - aa

    fuzzing:
      - part: header
        type: replace
        mode: multiple
        fuzz:
          User-Agent: "{{inject}}"
          Referer: "{{inject}}"
          X-Client-IP: "{{inject}}"
          X-Forwarded-For: "{{inject}}"
          X-Api-Version: "{{inject}}"
          
    matchers-condition: or
    matchers:
      - type: word
        words:
          - "test"
```

```console


✗ nuclei -t test.yaml -u example.com -dast -proxy http://localhost:8080

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.4

                projectdiscovery.io

[VER] Using http://localhost:8080 as proxy server
[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.4 (latest)
[INF] Current nuclei-templates version: v9.8.5 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 142
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 118 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/fuzz/component.(*Header).Rebuild.func1({0x0, 0x0}, {0x1056a1660, 0x14002f19770})
        github.com/projectdiscovery/nuclei/v3/pkg/fuzz/component/headers.go:99 +0x1b8
github.com/projectdiscovery/nuclei/v3/pkg/fuzz/dataformat.(*KV).Iterate(0x14002f19650?, 0x140047c3388)
        github.com/projectdiscovery/nuclei/v3/pkg/fuzz/dataformat/kv.go:75 +0xbc
github.com/projectdiscovery/nuclei/v3/pkg/fuzz/component.(*Header).Rebuild(0x140057e4470)
        github.com/projectdiscovery/nuclei/v3/pkg/fuzz/component/headers.go:85 +0x6c
github.com/projectdiscovery/nuclei/v3/pkg/fuzz.(*Rule).executeRuleValues(0x140007670e0, 0x14000d0a3c0, {0x105b76b20, 0x140057e4470})
        github.com/projectdiscovery/nuclei/v3/pkg/fuzz/execute.go:214 +0xb8
github.com/projectdiscovery/nuclei/v3/pkg/fuzz.(*Rule).Execute(0x140007670e0, 0x14000d0a3c0)
        github.com/projectdiscovery/nuclei/v3/pkg/fuzz/execute.go:132 +0x9dc
```
