### ISSUE TITLE
workflow crash nuclei

### ISSUE THREAD

**Issue by k3mlol** [projectdiscovery/nuclei#5087]
Hi, I want to submit this workflow for you to debug
``` yaml
id: error
info:
  name: error workflow
  author: error
  description: error
stop-at-first-match: false
workflows:
- template: http/technologies/citrix-xenmobile-version.yaml
  subtemplates:
  - template: http/exposed-panels/tomcat/tomcat-exposed-docs.yaml
```
 nuclei -w error.yaml -u https://yahoo.com -duc

``` ini
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d0c7bb]

goroutine 65 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec.(*TemplateExecuter).ExecuteWithResults(0x44ece5?, 0xc000ff9e00?)
	github.com/projectdiscovery/nuclei/v3/pkg/tmplexec/exec.go:186 +0x1b
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).runWorkflowStep(0xc00106e480, 0xc000a6e7e0, 0xc0005a9c20, 0xc000f95f40, 0xc000ff0280, 0xc000a35240)
	github.com/projectdiscovery/nuclei/v3/pkg/core/workflow_execute.go:92 +0x615
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeWorkflow.func1(0xc000ff0280?, 0x3587478?, 0x4d242a0?, 0xa0?, 0x2980d40?, 0xc000a6e7e0)
	github.com/projectdiscovery/nuclei/v3/pkg/core/workflow_execute.go:43 +0x71
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeWorkflow(0x0?, 0xc0005a9c20, 0xc000a35240)
	github.com/projectdiscovery/nuclei/v3/pkg/core/workflow_execute.go:46 +0x1e6
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x22f5e87?, 0x0?, 0xc000fec3c0)
	github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:122 +0x1fb
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 32
	github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:108 +0x459
```
my nuclei version
Nuclei Engine Version: v3.2.2
