### ISSUE TITLE
Can the fuzz functionality provide fuzzing based on keys?

### ISSUE THREAD

**Issue by 666asd** [projectdiscovery/nuclei#5103]
### Please describe your feature request:

Can the fuzz functionality provide fuzzing based on keys?
### Describe the use case of this feature:

For example, CVE-2018-1273 is a vulnerability that occurs during the parsing of keys.
[http/cves/2018/CVE-2018-1273.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/fa711a55603c5401b80d0bcebbeab210bcca5de8/http/cves/2018/CVE-2018-1273.yaml#L2)
![image](https://github.com/projectdiscovery/nuclei/assets/16465586/4728c986-b8bb-4e70-ab1b-d8f792792251)

**Comment by GeorginaReeder** [comment]
Thanks so much for this feature request @666asd , we'll take a look into it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by Mzack9999** [comment]
Closing this as covered by existing DAST fuzzing.

`keys` / `keys-regex` select which parameters to fuzz. To put a payload in the parameter *name* (e.g. CVE-2018-1273-style), use map-form `fuzz:` so the key is set as a named field:

```yaml
fuzzing:
  - part: body
    type: replace
    mode: single
    fuzz:
      "name[#this.getClass().forName('java.lang.Runtime').getRuntime().exec('id')]": "{{randstr}}"
```

Docs: https://docs.projectdiscovery.io/templates/protocols/http/fuzzing-overview

If renaming *existing* parameter names (not injecting new ones) is still needed, open a new issue with a concrete template/example.
