### ISSUE TITLE
Support multiple uncover queries

### ISSUE THREAD

**Issue by parthmalhotra** [projectdiscovery/nuclei#5124]
### Please describe your feature request:
Currently we only support single queries when using the `-uc` flag to fetch input hosts using uncover 
```yaml
    shodan-query: http.favicon.hash:-1298131932
    fofa-query: jshERP-boot
```
### Describe the use case of this feature:
As we will be mapping out the queries from [awesome-search-queries](https://github.com/projectdiscovery/awesome-search-queries), we need to add support to run uncover when there are more than one queries of an engine in the template 
```yaml
    shodan-query:
      - title:"H5S CONSOLE"
      - title:"H5S Login"
    fofa-query:
      - title="H5S CONSOLE"
      - title="H5S Login"
```

We should fetch result from all queries and deduplicate them and scan the returned results
