### ISSUE TITLE
FUZZ: Override HTTP request method using flag

### ISSUE THREAD

**Issue by ph-hitachi** [projectdiscovery/nuclei#5127]
### Please describe your feature request:

i'm working on one project and trying to use [Fuzz Templates](https://github.com/projectdiscovery/fuzzing-templates) for **vulnerability enumeration** and all HTTP REQUEST METHOD is hard coded:

```yml
http:
  - method: GET
    path:
      - "{{BaseURL}}"
 ```
      

### Describe the use case of this feature:
``nuclei -u https://example.com -data "param=FUZZ" -x POST``

i read some commands but i don't see this feature, i don't know if this already exists but it will helpful
