### ISSUE TITLE
Negative directive in the template matcher seems to not work with the case-insensitive directive

### ISSUE THREAD

**Issue by x676f64** [projectdiscovery/nuclei#5169]
### Current Behavior: 
Nuclei fails to match on a finding when the case-insensitive directive and the negative directive are used together.
For example, the [cookies-without-httponly-secure](https://github.com/projectdiscovery/nuclei-templates/blob/6c751fa3ddebec428f58ba6aab10fee47c5849ad/http/misconfiguration/cookies-without-httponly-secure.yaml#L31-L42) matcher should only identify endpoints that lack both set httponly and secure but the strings they match on have different cases depending on the web server. I observed this issue in the wild so attempted to modify the template to use case-insensitivity with negative but it does not appear to work.

### Expected Behavior:

The expected behavior is that this template will only return a positive finding if both httponly and secure exist in the set-cookie directive but do to case variations of web servers, this is not always a match. Attempting to add the case-insensitive directive did not work.

I have to build a template like this to properly handle the potentials and this still doesn't cover some crazy edge case.

```
id: cookies-without-httponly-secure

info:
  name: Cookies without HttpOnly or Secure attribute - Detect
  author: princechaddha,Mr.Bobo HP
  severity: info
  description: |
    Checks whether cookies in the HTTP response contain the HttpOnly attribute. If the HttpOnly flag is set, it means that the cookie is HTTP-only
  impact: |
    Lack of HttpOnly flag on cookies increases the risk of client-side attacks, compromising user session security and data privacy.
  remediation: |
    Ensure that all cookies are set with the HttpOnly attribute to prevent client-side access.
  reference:
    - https://owasp.org/www-community/HttpOnly
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
  metadata:
    verified: true
    max-request: 1
  tags: misconfig,http,cookie,generic

http:
  - method: GET

    extractors:
      - type: regex
        part: header
        regex:
          - "Set-Cookie:.*"
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - 'Set-Cookie'
        condition: and
      - type: word
        part: header
        words:
          - "httponly"
          - "secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "httpOnly"
          - "secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "HttpOnly"
          - "secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "HttpOnly"
          - "Secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "httpOnly"
          - "Secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "httonly"
          - "Secure"
        negative: true
        condition: and
      - type: word
        part: header
        words:
          - "HTTPONLY"
          - "SECURE"
        negative: true```

### Steps To Reproduce:
`echo "example.com" |nuclei -id cookies-without-httponly-secure -debug`
(You will need to find affected targets as I can't share that information)
### Anything else:

**Comment by RamanaReddy0M** [comment]
Template:
```yaml
id: cookies-without-httponly-secure

info:
  name: Cookies without HttpOnly or Secure attribute - Detect
  author: princechaddha,Mr.Bobo HP
  severity: info
  metadata:
    verified: true
    max-request: 1

http:
  - method: GET

    extractors:
      - type: regex
        part: header
        regex:
          - "Set-Cookie:.*"
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - 'Set-Cookie'
        condition: and
      - type: word
        part: header
        words:
          - "httponly"
          - "secure"
        case-insensitive: true
        negative: true
        condition: and
```
Case 1:  Server with Set-Cookie as key and without `secure` and `httponly` keywords in values are supposed to found a match according to template.
  ```go
  package main
  
  import (
	  "fmt"
	  "net/http"
  )
  
  func setCookie(w http.ResponseWriter, r *http.Request) {
	  cookie := http.Cookie{
		  Name:  "test_cookie",
		  Value: "test_value",
		  // No Secure or HttpOnly attributes
	  }
  
	  http.SetCookie(w, &cookie)
	  fmt.Fprintln(w, "Cookie has been set")
  }
  
  func main() {
	  http.HandleFunc("/", setCookie)
	  fmt.Println("Server is running on http://localhost:8083")
	  http.ListenAndServe(":8083", nil)
  }
  ```
  ```console
  ✗ nuclei -u http://localhost:8083 -t test.yaml 
  
                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v3.2.9
  
                  projectdiscovery.io
  
  [INF] Current nuclei version: v3.2.9 (latest)
  [INF] Current nuclei-templates version: v9.9.1 (latest)
  [WRN] Scan results upload to cloud is disabled.
  [INF] New templates added in latest release: 75
  [INF] Templates loaded for current scan: 1
  [WRN] Loading 1 unsigned templates for scan. Use with caution.
  [INF] Targets loaded for current scan: 1
  [cookies-without-httponly-secure] [http] [info] http://localhost:8083 ["Set-Cookie: test_cookie=test_value"]
  ```
  - Match found.
  
 Case 2: If Set-Cookie values contains `secure` and `httponly` we are not supposed to find match/results.
 ```console
 ✗ curl -I https://hackerone.com                   
HTTP/2 302 
date: Wed, 10 Jul 2024 22:55:28 GMT
content-type: text/html; charset=utf-8
location: https://www.hackerone.com/
user-authenticated: false
cache-control: no-store
content-disposition: inline; filename="response."
x-request-id: 6c545b03-8678-4646-bd08-2e09bc4f19b0
...
set-cookie: _cfuvid=Jr6r0yvYqOQZywkd4rhndzqYNUSBm3RmRLHDz.W3.Og-1720652128166-0.0.1.1-604800000; path=/; domain=.hackerone.com; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 8a1424377e1d47f5-BOM
 ```

```console
✗ nuclei -u https://hackerone.com -t test.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.9

                projectdiscovery.io

[INF] Current nuclei version: v3.2.9 (latest)
[INF] Current nuclei-templates version: v9.9.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 75
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
```
- no match found.

@x676f64 Seems to be working fine!
