### ISSUE TITLE
Wrong order using raw HTTP with pipelining 

### ISSUE THREAD

**Issue by raw-phil** [projectdiscovery/nuclei#5171]
### Current Behavior:
Nuclei send raw HTTP requests in wrong order when pipelining is active.

### Expected Behavior:
Template:
```yaml
id: multiple-raw-pipeline
info:
  name: Test Raw pipeline
  author: raw-phil
  severity: info

http:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        POST /testing HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
    pipeline: true
    matchers:
      - type: word
        words:
          - "Test matcher"
```

I expect that nuclei will send first the GET and then the POST request, but the order is inverted.
```
$ nc -l 127.0.0.1 8080
POST /testing HTTP/1.1
Host: 127.0.0.1:8080

GET / HTTP/1.1
Host: 127.0.0.1:8080

```

### Steps To Reproduce:
```
nuclei -t ./wrong-order-raw.yaml -u http://127.0.0.1:8080 --debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.7

		projectdiscovery.io

[INF] Current nuclei version: v3.2.7 (latest)
[INF] Current nuclei-templates version: v9.8.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 65
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] [multiple-raw-pipeline] Dumped HTTP request for http://127.0.0.1:8080

POST / HTTP/1.1
Host: 127.0.0.1:8080

[INF] [multiple-raw-pipeline] Dumped HTTP request for http://127.0.0.1:8080

GET / HTTP/1.1
Host: 127.0.0.1:8080

...
```
