### ISSUE TITLE
Error in using url_encode function

### ISSUE THREAD

**Issue by 666asd** [projectdiscovery/nuclei#5184]
### Issue description:

```yaml
# Variable example using HTTP requests
id: variables-example

info:
  name: Variables Example
  author: pdteam
  severity: info

http:
  - payloads:
      payload:

        - '{{interactsh-url}}'

    fuzzing:

      - part: query
        mode: single
        fuzz:
          - '{{base64(payload)}}'
          - '{{url_encode(payload)}}'
```

When I use this template, the base64 function can be used normally, but url_encode will error 'unresolved variables found: contactsh url'`
![image](https://github.com/projectdiscovery/nuclei-templates/assets/16465586/02ef6ca8-e8c4-4ee4-8fd1-a05d92b4fd00)
![image](https://github.com/projectdiscovery/nuclei-templates/assets/16465586/9ee03538-8ffd-49ee-974f-0ca8c45688ba)
