### ISSUE TITLE
[issue] disable-automatic-host-header not working correctly 

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#520]
**Describe the bug**
I want to use a fixed value on the Host Header, for example 

Host: 12149n2b9XXXX6f.burpcollaborator.net

I did use the example from here https://nuclei.projectdiscovery.io/templating-guide/ but it doesn't work. 

I ran 
`nuclei -debug -t test.yaml -l input.txt `

But the value of the Host header is replace by the TARGET domain. 

**Nuclei version**
2.2.0

**Screenshot of the error or bug**

```
[INF] Dumped HTTP request for http://au518.nordvpn.com (ssrf-reverse-proxy)

POST / HTTP/1.1
Host:au518.nordvpn.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 150
Transfer-Encoding: chunked

0

[INF] Dumped HTTP request for http://au519.nordvpn.com (ssrf-reverse-proxy)

POST / HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 150
Transfer-Encoding: chunked
Host:au519.nordvpn.com
```

**Comment by Mzack9999** [comment]
@pdelteil - I can't reproduce this. Can you ensure that your template is similar to the following one (in particular that `unsafe` and `disable-automatic-host-header` are set to `true`):

```yaml
id: test-host-header

info:
  name: Test host header
  author: pdteam
  severity: none
  description: testing unsafe host header

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: anythinghere
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: close
    unsafe: true
    disable-automatic-host-header: true

    matchers:
      - type: status
        status:
          - 200
```
