### ISSUE TITLE
Nuclei doesn't not run on localhost

### ISSUE THREAD

**Issue by sauravpradhan** [projectdiscovery/nuclei#5238]
### Current Behavior:

While executing self made template to access the server nuclei throws error.

### Expected Behavior:
Should execute successfully as Windows and Postman is giving response.

### Steps To Reproduce:
1) Run  nuclei -v -u http://localhost:4000/api -t .\MyFirstTemplate.yaml
2)  Response is:
[WRN] [eOTA-vulneribility20240529] Could not execute request for http://localhost:4000/api: [:RUNTIME] got err while executing http://localhost:4000/api <- Get "http://localhost:4000/api": errKind=network-permanent-error no address found for host
[INF] No results found. Better luck next time!

### Anything else:
YAML Template:
```yaml
id: eOTA-vulneribility20240529 

info:
  name: HTTP BASICS Template
  author: __saurav
  description: Break-in
  severity: info
  tags: eota

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: word
        words:
          - "New Node Server is up and running with volumes"

```

Postman Response: 
![image](https://github.com/projectdiscovery/nuclei/assets/1622949/e9f8fb6b-0ad1-4d21-836f-48cf71ce71ba)

CURL Response:
![image](https://github.com/projectdiscovery/nuclei/assets/1622949/df34a1ff-336e-47f3-8823-7a7bb6f0f3be)

Also this was discussed in Discord sub-thread:
https://discord.com/channels/695645237418131507/1245309592573837394

**Comment by dogancanbakir** [comment]
Couldn't repro this on osx. Here's what I've did to repro the issue:

simple go server:
```go
package main

import (
	"fmt"
	"net/http"
)

func apiHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/api" {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("Access-Control-Allow-Origin", "http://localhost:4200")
	w.Header().Set("Access-Control-Allow-Methods", "GET, PUT, POST, DELETE")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
	w.Header().Set("Access-Control-Allow-Credentials", "true")
	w.WriteHeader(http.StatusOK)

	responseContent := "New Node Server is up and running with volumes. Server version: 4.0"
	fmt.Fprint(w, responseContent)
}

func main() {
	http.HandleFunc("/api", apiHandler)

	port := 4000
	fmt.Printf("Starting server on port %d\n", port)
	if err := http.ListenAndServe(fmt.Sprintf(":%d", port), nil); err != nil {
		fmt.Printf("Error starting server: %s\n", err)
	}
}

```

template:

```yaml
id: eOTA-vulneribility20240529 

info:
  name: HTTP BASICS Template
  author: __saurav
  description: Break-in
  severity: info
  tags: eota

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: word
        words:
          - "New Node Server is up and running with volumes"
```


running go server:
```console
$ go run test.go 
Starting server on port 4000
```

curl request:
```console
$ curl -I http://localhost:4000/api
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Origin: http://localhost:4200
Content-Type: text/plain
Date: Wed, 29 May 2024 11:59:48 GMT
Content-Length: 67
```


nuclei:

```console
$ go run . -t test_template.yaml -u http://localhost:4000/api

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.8

                projectdiscovery.io

[INF] Current nuclei version: v3.2.8 (latest)
[INF] Current nuclei-templates version: v9.8.7 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 62
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[eOTA-vulneribility20240529] [http] [info] http://localhost:4000/api
```
