### ISSUE TITLE
Nuclei -validate not flagging invalid ID in template

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#5247]
The Nuclei `-validate` flag is not flagging the invalid ID of the template. The following template is being validated without any error:

```yaml
id: aviatrix detect

info:
  name: Aviatrix Detect
  author: princechaddha
  severity: info
  tags: tech,aviatrix
  description: |
    Detects Aviatrix Controller API misconfigurations
  impact: |
    May lead to unauthorized access or data leakage
  remediation: |
    Review and adjust Aviatrix Controller API configurations to ensure proper access controls

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "<title>Aviatrix Controller</title>"

      - type: status
        status:
          - 200
```
