### ISSUE TITLE
introduce 'service' field/input in network/javascript templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5269]
### Proposed Changes:

- some time ago we introduced optimization in network and javascript protocol to handle redundant probes aganist http services when running a non-http template for context refer

- https://github.com/projectdiscovery/nuclei/pull/4123
- https://github.com/projectdiscovery/nuclei/pull/4401

while this is working but it poses a challenge when trying to write/send a http request from javascript protocol , example

```yaml
id: CVE-2015-2080

info:
  name: Eclipse Jetty <9.2.9.v20150224 - Sensitive Information Leakage
  author: pikpikcu
  severity: high
  description: Eclipse Jetty before 9.2.9.v20150224 allows remote attackers to obtain sensitive information from process memory via illegal characters in an HTTP header.
  remediation: |
    Upgrade to a version of Eclipse Jetty that is higher than 9.2.9.v20150224 to mitigate this vulnerability.
  reference:
    - https://github.com/eclipse/jetty.project/blob/jetty-9.2.x/advisories/2015-02-24-httpparser-error-buffer-bleed.md
    - https://blog.gdssecurity.com/labs/2015/2/25/jetleak-vulnerability-remote-leakage-of-shared-buffers-in-je.html
    - http://packetstormsecurity.com/files/130567/Jetty-9.2.8-Shared-Buffer-Leakage.html
    - https://nvd.nist.gov/vuln/detail/CVE-2015-2080
    - http://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00074.html
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2015-2080
    cwe-id: CWE-200
    epss-score: 0.95465
    epss-percentile: 0.99329
    cpe: cpe:2.3:o:fedoraproject:fedora:22:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: fedoraproject
    product: fedora
  tags: cve2015,cve,jetty,packetstorm,fedoraproject


javascript:
  - code: |
      let m = require('nuclei/net');
      let address=Host+':'+Port;
      let conn = m.Open('tcp', address);
      conn.Send('GET / HTTP/1.1\r\nHost: '+address+'\r\n');
      conn.Send('Referer: ');
      conn.SendHex('00'); // null byte
      conn.Send('\r\nConnection: close\r\n\r\n');
      resp = conn.RecvString();

    args:
      Host: "{{Host}}"
      Port: '8080' # hardcoded port

    matchers-condition: and
    matchers:
      - type: dsl
        dsl: 
          - 'contains(response, "Illegal character 0x0 in state")'
          - 'contains(response, "HTTP/1.1 400")'
   
    extractors:
      - type: dsl
        dsl:
          - response
  ```

here in this template we are trying to make a http request from javascript protocol since it requires a null byte being sent in header which is not supported in normal http requests section yet. and there could be similar scenarios as well. having this port optimization is good but it doesn't seem to scale well . 

so in addition to `port` field we can introduce a new field called `service` which could be used as filter to decide whether a template should be run or not if so using which port 

in context of this example there is no single port we can specify because http server could be on `80,443,8080,8443` or even some other port , if we add a field like

```yaml
args:
   Host: "{{Host}}
   service: http,https
```

this template will run using the port on which http service was detected ( this http,https service detection can be performed when doing http probe ) , we will not support other services yet but it will pave a way for them in feature to avoid hardcoding ports and instead rely on service type
