### ISSUE TITLE
[feature] Tag based execution support to nuclei

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#527]
**Is your feature request related to a problem? Please describe.**

We received multiple feedbacks to have more controls/ways on how the templates can be executed, for example, based on tech/product/cms and so on, as the preference can be multiple and varies from person to person and also depending on the purpose of the scans, it could be a simple audit, or only looking to scan for cves and on so on!

**Describe the solution you'd like**
Adding tag Information to existing and new templates and allow them to execute based on tags along with or without template directory information.

Example template:- 

```yaml
id: CVE-2018-3167

info:
  name: Unauthenticated Blind SSRF in Oracle EBS
  author: geeknik
  severity: low
  description: https://medium.com/@x41x41x41/unauthenticated-ssrf-in-oracle-ebs-765bd789a145
  tags: oracle,ebs
```

Example running templates based on tags:- 

```sh
nuclei -tags oracle
nuclei -tags oracle, jira
nuclei -tags oracle -t cves
```
- Single or multiple tags can be used.
- Template directory (-t flag) is optional with tags
- When the template directory is provided, templates with the matched tags under the same directory will be executed.
- In case, no `t` flag is provided along with `tags` flag, `~/nuclei-templates` will be the used as default directory to scan.
