### ISSUE TITLE
Workflow Template Execution Order Issue

### ISSUE THREAD

**Issue by Thamaraiselvan942** [projectdiscovery/nuclei#5293]
Hi Team,
I encountered an issue while executing the workflow subtemplates. The order of execution of templates is not being maintained, even though I added 'logout.yaml' as the last template. The 'logout' template executes before 'tool-check.yaml' and 'admin.yaml' are completed.

```
workflows:
  - template: /home/test/nuclei-templates/auth-scan/new/templates/accounts.yaml
    subtemplates:
      - template: /home/test/nuclei-templates/auth-scan/new/templates/site.yaml
        subtemplates:
          - template: /home/test/nuclei-templates/auth-scan/new/templates/account_csrf.yaml
            subtemplates:
              - template: /home/test/nuclei-templates/auth-scan/new/templates/login_check.yaml
              - template: /home/test/nuclei-templates/auth-scan/new/templates/admin.yaml
              - template: /home/test/nuclei-templates/auth-scan/new/templates/tool-check.yaml
              - template: /home/test/nuclei-templates/auth-scan/new/templates/logout.yaml
```
