### ISSUE TITLE
stop-at-first-match with headless/fuzzing not working

### ISSUE THREAD

**Issue by bizibabe** [projectdiscovery/nuclei#5308]
Hello,

I don't understand why stop-at-first-match doesn't work in this template:
```
echo "https://www.bing.com/?test=1" | nuclei -dast -t test.yaml -headless
```
```yaml
id: test-headless-match

info:
  name: test headless match
  author: Bizi
  severity: low
  
headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"
      - action: waitload
    payloads:
      test:
        - "1"
        - "2"
        - "3"
    
    stop-at-first-match: true
    
    fuzzing:
      - part: query
        type: replace
        mode: single
        fuzz:
        - "{{test}}"
 
    matchers:
      - type: word
        name: bing
        words:
          - "www.bing.com"
        part: body
```

![image](https://github.com/projectdiscovery/nuclei/assets/60073248/dfc26312-1d05-45fb-b029-f48e4c2d992e)

Is this normal?
Thanks,
Bizi
