### ISSUE TITLE
Add ability to use Github Application Authentication for private repos

### ISSUE THREAD

**Issue by syntacticNaCl** [projectdiscovery/nuclei#5334]
### Please describe your feature request:

We should add the ability to authenticate with the Github API via [Github Application authentication](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) to pull from private repos. The current process of using a PAT works but is not ideal for security teams.

This should add the following values to the config for authentication with corresponding environment variables:
* Github App ID
* Github App Installation ID
* Github App Private Key - ideally this would be the private key string itself and not the file as that plays better with secret storage solutions
* (Optional) Github App Private Key File - we could also offer the ability to use a key file instead of the key string but not necessary for this implementation

### Describe the use case of this feature:

Using a PAT to authenticate with the Github API works well for single users but when using nuclei for a team – especially in an automation pipeline – the preferred way is to create a Github App and use it for authentication. This removes the complexity and degraded security of having to manage a "service account" user with it's own login credentials and PAT.

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @syntacticNaCl , we'll take a look into it! :)

**Comment by Mzack9999** [comment]
Thanks for the request — GitHub App auth for private template repos is a reasonable fit for org/CI setups, but we’re closing this for now given limited demand and existing workarounds that already work with today’s flow.

### What works today
Private custom templates use:

- `GITHUB_TOKEN`
- `GITHUB_TEMPLATE_REPO` (comma-separated `owner/repo`)

Nuclei clones/pulls over HTTPS with that token. There is no native GitHub App (App ID / Installation ID / private key) path yet.

### Recommended workarounds

**1. Fine-grained PAT (simplest)**  
Create a fine-grained token with Contents: Read on the private template repo(s), then:

```bash
export GITHUB_TOKEN=github_pat_...
export GITHUB_TEMPLATE_REPO=my-org/my-nuclei-templates
nuclei -update-templates
```

**2. GitHub App → installation token → `GITHUB_TOKEN` (preferred for automation)**  
Mint a short-lived installation access token outside Nuclei and pass it as `GITHUB_TOKEN` (Nuclei does not need to know it came from an App).

Example in GitHub Actions:

```yaml
- uses: actions/create-github-app-token@v1
  id: app-token
  with:
    app-id: ${{ secrets.APP_ID }}
    private-key: ${{ secrets.APP_PRIVATE_KEY }}
    # owner/repos as required by the action for your install

- name: Sync private nuclei templates
  env:
    GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    GITHUB_TEMPLATE_REPO: my-org/my-nuclei-templates
  run: nuclei -update-templates
```

You can do the same locally/CI with `gh` or a small script: App JWT → installation access token → export as `GITHUB_TOKEN`.

**3. Clone outside Nuclei**  
Clone the private repo yourself (deploy key / App / PAT), then point Nuclei at the local path with `-t`.

---

Native App ID / Installation ID / private-key support may still make sense later as convenience env vars, but it’s not planned as a near-term change while the workarounds above cover the use case. Feel free to reopen if a native App config is still blocking you after trying these.
