### ISSUE TITLE
[Issue] RawHTTP doesn't follow defined template format

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#534]
**Is your feature request related to a problem? Please describe.**

```yaml
        GET /#get HTTP/1.1
        Host: {{Hostname}}
        Host:localhost.localdomain
        Host:fastly.com
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: close

    unsafe: true
    disable-automatic-host-header: true
```

Results into following request:-

```
GET /#get HTTP/1.1
User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept:*/*
Connection:close
Host:xxx.xxx:443
Host:localhost
Host:127.0.0.1
```
The expectation is that request will be generated in the same order as the template but the current behavior is random in terms of placing header's position while generating the request.

### Fix:-

When unsafe (rawhttp) flag is used, replicate the same order of headers for the request.
