### ISSUE TITLE
Github reporting module creates a new issue everytime for the same finding

### ISSUE THREAD

**Issue by monishbb** [projectdiscovery/nuclei#5347]
### Nuclei version:
3.2.9

### Current Behavior:
Using `update-existing` in Github reporting module does not work, it still creates a new issue for an already existing issue 

```
allow-list:
  severity: info, low, high, critical, medium

# GitHub contains configuration options for GitHub issue tracker
github:
  # issue-label is the label of the created issue type
  issue-label: security
  # update-existing is the boolean which tells if the existing, opened issue should be updated or new one should be created
  update-existing: true
  # duplicate-issue-check flag to enable duplicate tracking issue check.
  duplicate-issue-check: true
  # username of the github accont being used
  username: test-user
  # token is the token for GitLab account
  token: test-token
  # project-name is the name/id of the project(repository)
  project-name: "1234"
```

### Expected Behavior:
Existing issues on Github should have been updated instead of a new issue being created

### Steps To Reproduce:

1.  Use https://github.com/projectdiscovery/nuclei-action
2. Pass the above report config:

```
- name: Nuclei - Vulnerability Scan
          uses: projectdiscovery/nuclei-action@main
          with:
            target: https://www.example.com
            github-report: true
            github-token: ${{ github.token }}
            report-config: vapt-config/nuclei-reporting.yaml
            config: vapt-config/nuclei-config.yaml
            flags: -disable-unsigned-templates
```

3. Multiple issues are created for the same findings if run multiple times

### Anything else:
https://github.com/projectdiscovery/nuclei/issues/3429
https://github.com/projectdiscovery/nuclei-action/issues/60
