### ISSUE TITLE
Lack of error when code execution fails

### ISSUE THREAD

**Issue by cyrilvallelianks** [projectdiscovery/nuclei#5349]
### Nuclei version:
v3.2.9

### Current Behavior:
When using the code protocol, Nuclei does not display an error when there is a problem with the execution of the code. As a result, a failure in the execution cannot be easily distinguished from a unmatched template.

### Expected Behavior:
Nuclei should check the return status of the executed code and generate an error.

### Steps To Reproduce:
Nuclei template:
```yaml
id: code_exec_error_test

info:
  name: Code execution error test
  description: "Code execution error test"
  severity: HIGH
  remediation: "Code execution error test"
  author: test

self-contained: true

code:
  - engine:
      - py
      - python3
    source: |
      raise Exception("there's an error")

    matchers:
      - type: dsl
        dsl:
          - 1==1
# digest: TODO
```

Execution:
```
nuclei -t test.yaml -code -debug -v
```

Output:
```
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.9

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.9 (latest)
[INF] Current nuclei-templates version: v9.9.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 164
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from KS
[VER] [code_exec_error_test] Executed code on local machine 
[DBG] [code_exec_error_test] Dumped Executed Source Code for 

raise Exception("there's an error")

[DBG] [code_exec_error_test] Dumped Code Execution for 



[code_exec_error_test:dsl-1] [code] [high] 

```

-> When an error occured, the dumped code execution is empty and no error is displayed (even in verbose and debug mode).
