### ISSUE TITLE
An additional end of line in RAW request

### ISSUE THREAD

**Issue by gano3s** [projectdiscovery/nuclei#535]
**Describe the bug**
When the raw request is used, the additional `\r\n` is added into the end of the request. When the request if formatted with header and body fields, then this additional spaces are not added.

Since some web pages are sensitive to additional data, this may lead to the unexpected behavior.
To be more specific - the web which I am testing uses a simple PHP form to log user in. When the input data are correct, the response redirects user to the next page in workflow.
With incorrect input, the user is redirected to the `/login/error` page.

When I am using browser or when I craft my request manually, the login is successful. But when I try to use **raw** request, I am forwarded to the error page.

During the troubleshooting of the issue, I explored the latest dev branch. It seems to me, that the issue is caused by this line:
https://github.com/projectdiscovery/nuclei/blob/593e2319c4c64889a0fac0a797e4b78cdd54f18a/v2/pkg/protocols/http/build_request.go#L117
Because I am not sure what was the intended behavior, I did not blindly remove it. Instead of it, I decided to create this issue.

**Nuclei version**
Custom build from the Dev branch.
Reproducible even on the v2.2.0.

**Screenshot of the error or bug**
Manually crafted request:
![image](https://user-images.githubusercontent.com/2551605/107776450-dfcd2f00-6d41-11eb-9aaa-d58811710555.png)

```
requests:
  - method: POST
    path:
      - '{{BaseURL}}/login'
    headers:
      Content-Type: application/x-www-form-urlencoded
      User-Agent: test
    body: login=test&password=test
```

Raw request:
![image](https://user-images.githubusercontent.com/2551605/107776602-12772780-6d42-11eb-867c-e289b7016ec9.png)

```
requests:
  - payloads:
      username:
        - test
      password:
        - test

    attack: clusterbomb

    raw:
      - |
        POST /login HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        Accept: */*
        Accept-Language: en
        Content-Type: application/x-www-form-urlencoded
        User-Agent: test
        
        login={{username}}&password={{password}}
```
