### ISSUE TITLE
[feature] Adding stop-at-first-match support via template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#540]
Same support as we have via flag using `-stop-at-first-match` flag, will be helpful for the case where we have multiple possible paths for same file, in cases where we found matches at the start, we can avoid making additional requests.

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
```
