### ISSUE TITLE
stop-at-first-match does not work within a flow block

### ISSUE THREAD

**Issue by iambouali** [projectdiscovery/nuclei#5400]
When using the `stop-at-first-match` feature in combination with a flow block, it appears that the `stop-at-first-match` functionality is not working as expected. The flow block continues to execute all iterations even after a match is found.

```yaml
id: test

info:
  name: test
  author: iambouali
  severity: high

flow: |
  for (let i = 0; i < 10; i++) {
    http(1)
  }

http: 
  - raw:
     - |
       GET /?cb=test HTTP/1.1
       Host: {{Hostname}}

       stop-at-first-match: true
       matchers:
          - type: word
             part: header
             words:
                - "X-Cache: hit"
```
