### ISSUE TITLE
include cname in http output if available

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#5411]
## Proposed Changes

- since dns data is cached in fastdialer on first dial , it is now included in http protocol variables when available thereby removing need of doing one more dns request using protocol

```console
$ ./nuclei -u https://support.hackerone.com -t a.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.3.0-dev (development)
[INF] Current nuclei-templates version: v9.9.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 164
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[basic-example:cname] [http] [info] https://support.hackerone.com ["2fe254e58a0ea8096400b2fda121ee35.freshdesk.com"]
[basic-example:cname_all] [http] [info] https://support.hackerone.com ["[2fe254e58a0ea8096400b2fda121ee35.freshdesk.com fwfd-use1-lb208.freshdesk.com]"]
```

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: dsl
        name: cname
        dsl:
          - "cname"

      - type: dsl
        name: cname_all
        dsl:
          - "cname_all"
```
