### ISSUE TITLE
Network Templates with multiple CRLF-separated lines read only the first response

### ISSUE THREAD

**Issue by mhmdiaa** [projectdiscovery/nuclei#5433]
### Nuclei version:

3.3.0

### Current Behavior:

When a network template sends multiple messages separated by CRLF sequences and the server responds to each individually, the engine only reads the first response.

This pattern can lead to potential false negatives. For example, the [ftp-weak-credentials](https://github.com/projectdiscovery/nuclei-templates/blob/main/network/default-login/ftp-weak-credentials.yaml) template uses this pattern:
```
...
  - inputs:
      - data: "USER {{username}}\r\nPASS {{password}}\r\n"
...
```

Some FTP servers respond to the `USER` command with a message like a server banner or `Please specify the password`. They then read the `PASS` command and, if the credentials are correct, return the `230 Login successful` response that the template matches against. If the engine doesn't read the second response, it won't catch this.

### Expected Behavior:

The engine should keep listening on the connection after the first response.

### Steps To Reproduce:

1. Write the following template to `test-tcp-conn.yaml`:
```yaml
id: test-tcp-conn

info:
  name: Test TCP Connection
  author: mhmdiaa
  severity: info
self-contained: true

tcp:
  - inputs:
      - data: "USER anonymous\r\nPASS anonymous\r\n"
    host:
      - ftp.ietf.org:21

    matchers:
      - type: word
        words:
          - "230 Login successful"
```
2. Run `nuclei -t test-tcp-conn.yaml -debug`
3. Notice that the template doesn't get a match even though the server supports anonymous login and the debug output only contains the first response `220 (vsFTPd 3.0.5)`.
```
nuclei -t test-tcp-conn.yaml -debug

...
00000000 55 53 45 52 20 61 6e 6f 6e 79 6d 6f 75 73 0d 0a |USER anonymous..|
00000010 50 41 53 53 20 61 6e 6f 6e 79 6d 6f 75 73 0d 0a |PASS anonymous..| address=ftp.ietf.org:21
[DBG] [test-tcp-conn] Dumped Network response for ftp.ietf.org:21

00000000 32 32 30 20 28 76 73 46 54 50 64 20 33 2e 30 2e |220 (vsFTPd 3.0.|
00000010 35 29 0d 0a |5)..|
[INF] No results found. Better luck next time!
```

### Anything else:

I was about to take a stab at fixing this but noticed a couple of things:
- Other templates, like [ftp-anonymous-login](https://github.com/projectdiscovery/nuclei-templates/blob/df04445d5109a9914769eca085992b7658fac621/network/default-login/ftp-anonymous-login.yaml), use a slightly different pattern where the commands are separated into different requests (which makes a lot of sense for a protocol like FTP), which remediates the problem.
```yaml
  - inputs:
      - data: "USER anonymous\r\n"
        read: 1024
      - data: "PASS anonymous\r\n"
        read: 1024
```

- There's already a function that seems to handle this very well in [projectdiscovery/utils](https://github.com/projectdiscovery/utils/blob/main/reader/conn_read.go#L29), but it's [only used if the template's read size field is set to `-1`](https://github.com/projectdiscovery/nuclei/blob/dev/pkg/protocols/network/request.go#L481-L483) (not sure why). So if we add a `read-size: -1`, the above template works.
```yaml
id: test-tcp-conn

info:
  name: Test TCP Connection
  author: mhmdiaa
  severity: high
self-contained: true

tcp:
  - inputs:
      - data: "USER anonymous\r\nPASS anonymous\r\n"
    host:
      - ftp.ietf.org:21


    matchers:
      - type: word
        words:
          - "230 Login successful"
     read-size: -1

```

So I held off on the PR because there seem to be a few potential fixes to consider:
1. Update the templates that use the "single data field" pattern to use multiple fields with separate `read` values.
2. Replace `network.ConnReadNWithTimeout()` with `github.com/projectdiscovery/utils/reader.ConnReadNWithTimeout()` throughout.
3. Modify `network.ConnReadNWithTimeout()` to continue reading until the connection is closed.
