### ISSUE TITLE
Issue with port input parsing for network protocol in case of URL Input

### ISSUE THREAD

**Issue by qianbenhyu** [projectdiscovery/nuclei#5437]
```yaml
id: ip-port-3311-check

info:
  name: IP Port 3311 Check
  author: ProjectDiscoveryAI
  severity: medium

tcp:
  - host:
      - "{{Hostname}}"
    port: 3311

    matchers:
      - type: word
        words:
          - "mysql_native_password"
```
 when I use the poc above. My nuclei could not send messege to a right port.
![image](https://github.com/user-attachments/assets/0bb869ad-a65e-46ca-8335-e44557f22c02)
