### ISSUE TITLE
Authorization header is inserted into every raw HTTP request when using a Secret File

### ISSUE THREAD

**Issue by CodeStuffBreakThings** [projectdiscovery/nuclei#5455]
### Current Behavior:
When using a Secret File that uses static Basic authentication for a target, every raw HTTP request sent to that target has the Authorization: Basic header inserted.

### Expected Behavior:
The Authorization header should not be getting inserted into every HTTP request because not all requests require it. Could you please allow the Authorization header to be overridden and/or not used in a raw HTTP request if specified?

### Steps To Reproduce:
Create a Secret File that uses static basic authentication for a web target that uses basic authentication:
```yaml
static:
  - type: basicauth
    domains:
      - routerlogin.net
      - 192.168.1.1
    username: admin
    password: Qwerty123
```

Create a detection template that uses either no basic authentication or hardcoded basic authentication in a raw HTTP request, then scan the target web server that is specified in the Secret File:
```yaml
http:
  - raw:
      - |
        HEAD / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /IPV6_fixed.htm HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic 123123
        Referer: http://{{Host}}/IPV6_disable.htm
```

Observe the HTTP traffic in a network protocol analyzer such as Wireshark and you will see that the Authorization header either gets inserted or overridden

### Anything else:
![image](https://github.com/user-attachments/assets/8fd395f6-7888-49cc-ae6d-e487eecb8b74)
![image](https://github.com/user-attachments/assets/56794ade-0ef8-477a-84d4-720343279f41)
