### ISSUE TITLE
Does not create JSON file while there is an extractor match

### ISSUE THREAD

**Issue by marduc812** [projectdiscovery/nuclei#5471]
### Nuclei version:
```
$ nuclei -version                                                                                                                                  
[INF] Nuclei Engine Version: v3.3.0
```

### Current Behavior:
There is a match  and extract in the template, but it does not produce the JSON file output when passing the `-je` flag

### Expected Behavior:
Since there is a match and an extraction, I expected that JSON file will be generated like it did with my other custom templates.

### Steps To Reproduce:

*csp-misconfig.yaml*
``` yaml
id: csp-misconfiguration-test

info:
  name: CSP Misconfiguration
  severity: info
  author: test
  description: CSP misconf

http:
  - method: GET
    path: 
      - "{{RootURL}}"
    redirects: true
    max-redirects: 3

    matchers:
      - type: regex
        condition: or
        part: header
        regex:
          - "Content-Security-Policy"

    extractors:
      - type: regex
        name: csp-header
        regex:
          - "Content-Security-Policy: (.*)"
        part: header

```

terminal output
```
$ nuclei -target http://localhost:3000 -t csp-misconfig.yaml -fr  -je csp-misconfiguration.json -debug
                    __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

                projectdiscovery.io

[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[csp-misconfiguration-test:csp-header] [http] [info] http://localhost:3000 ["Content-Security-Policy: default-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; img-src *; connect-src *; font-src *; object-src *; media-src *; frame-src *; child-src *; form-action *; frame-ancestors *; base-uri"]
```

As you will see the information is correctly matched and extracted, but no file is created.

Also proof that the header is there indeed:
```
$ curl -s http://localhost:3000 -I | grep 'Content-Security-Policy'
Content-Security-Policy: default-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; img-src *; connect-src *; font-src *; object-src *; media-src *; frame-src *; child-src *; form-action *; frame-ancestors *; base-uri
```

### Anything else:
I also noticed that that the `-debug` flag does not show the HTTP requests and response like expected.
