### ISSUE TITLE
Missing File Protocol Variables in flow and multiprotocol

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5481]
### Nuclei version:

main | latest

### Current Behavior:

```yaml
id: aws-bucket-takeover-example

info:
  name: AWS Bucket Takeover example
  author: princechaddha
  severity: high
  description: Automatically Detects and takeover misconfigured BUkcets
  reference:
    - https://docs.spring.io/spring-security/site/docs/current/apidocs/overview-tree.html
  tags: file,aws

flow: file(1) && log(template)

file:
  - extensions:
      - all

    extractors:
      - type: regex
        internal: true
        name: bucket
        group: 1
        regex:
          - 'https://([a-z0-9-]+)\.s3\.amazonaws\.com'
          - 'https://s3\.amazonaws\.com/([a-z0-9-]+?)(?:/|$)'
 ```

```console
echo "./bbdata/test.md" | nuclei -t a.yaml -v                       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 17B/120B
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 17B/120B
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 17B/120B
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 66B/120B
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 66B/120B
[VER] [aws-bucket-takeover-example] Processing file ./bbdata/test.md chunk 115B/120B
[JS] 	1. bucket => my-s3-bucket
```

### Steps To Reproduce:

```
[JS] 	1. bucket => my-s3-bucket
	2. file_matched => ./bbdata/test.md
	3. file_path => ./bbdata/test.md
	4. file_raw => https://s3.amazonaws.com/my-s3-bucket/my-file.txt
	5. file_type => file
```
