### ISSUE TITLE
Inconvenient path parameters fuzzing

### ISSUE THREAD

**Issue by C0de4you** [projectdiscovery/nuclei#5495]
### Please describe your feature request:

It's not convenient to scan openapi path parameters right now. If you need to scan only some parameters, you have to invent hacks for that.

Let's say we have a piece of openapi 

```json
    "/books/v1/{book_title}": {
      "get": {
        "operationId": "api_views.books.get_by_title",
        "parameters": [
          {
            "description": "retrieve book data",
            "in": "path",
            "name": "book_title",
            "required": true,
            "schema": {
              "example": "bookTitle77",
              "type": "string"
            }
          }
        ],
```

If I want to check the `book_title` parameter, I have to specify in the template values with schema.example = `bookTitle77` from openapi, because at the time of fuzzing it is already this value. Also according to documentation https://docs.projectdiscovery.io/templates/protocols/http/fuzzing-overview#key-value-abstraction we must to use `values` for path parameters. Moreover, to replace only a parameter and not the whole path you need to specify `replace-regex`

```yaml
id: bola 
info:
  name: bola 
  author: test
  severity: high

http:
  - matchers:
      - type: word
        words:
          - "ALICE_SECRET"

    fuzzing:
      - part: path 
        type: replace-regex
        replace-regex: "bookTitle77"
        mode: single
        values:
          - "bookTitle77"
        fuzz:
          - "alice_book"
```

Thus I have to write a similar construction for each individual parameter. This is very inconvenient

### Describe the use case of this feature:

It would be great if path parameters could be scanned as well as query parameters, and the template had the following form

```yaml
id: bola 
info:
  name: bola 
  author: test
  severity: high

http:
  - matchers:
      - type: word
        words:
          - "ALICE_SECRET"

    fuzzing:
      - part: path 
        type: replace
        mode: single
        keys:
          - "book_title"
          - "book_name"
          - "id"
          
        fuzz:
          - "alice_book"
```
