### ISSUE TITLE
Only the last secret matching domain is used from a secret file

### ISSUE THREAD

**Issue by Th3R3p0** [projectdiscovery/nuclei#5498]
### Nuclei version:
Nuclei Engine Version: v3.3.0

## Nuclei command:
`nuclei -v -ev -t "$NUCLEI_TEMPLATES" -l "$NUCLEI_TARGETS"  -sf "$NUCLEI_TEMPLATES/secrets.yaml"`

### Current Behavior:
If a secret file contains multiple secrets for a domain, only the last secret is used. See my secret file at the bottom of this script. 

### Expected Behavior:
All secrets for a domain are used. 

### Steps To Reproduce:
Use the secret file below and route through an HTTP proxy. You will see that only the last secret for the matched domain is added. If you re-order the secrets, you can see that it will use the last item in the array. 

### Anything else:
```yaml
static:
  - type: cookie
    domains:
      - example.com
    cookies:
      - key: cookieName
        value: SuperSecretValue
  - type: bearertoken
    domains:
      - example.com
    token: rot26bearertoken
```

**Comment by kenyon-wong** [comment]
Request to Reopen This Issue  

---

**Environment**  
- OS: Microsoft Windows 10 x64-based PC  
- Nuclei: v3.3.9  

---

**Nuclei command**  
```powershell
nuclei --config check.yaml
```

---

**check.yaml**  
```yaml
list: 'list.txt'
templates:  'nuclei17482757576840036164.yaml'

prefetch-secrets: true
secret-file: 'Secret.yaml'

proxy: 'http://127.0.0.1:8080'

debug-resp: true

bulk-size: 50
cloud-upload: false
concurrency: 50
disable-update-check: true
no-interactsh: true
no-max-host-error: true
rate-limit: 500
stats: true
timeout: 5
uncover: false
update-templates: false
```

---


When using Nuclei for testing, I need to add a `Cookie` field to requests for authentication and a `secretkey` header to resolve response issues.  


---

My Nuclei template example:
```yaml
      - |
        POST /api/order/plaintext HTTP/1.1
        Host: {{Hostname}}
        Cookie:
```

---

My secret file contents:
```yaml
  - type: cookie
    domains-regex:
      - fat.example.com
    cookies:
      - key: SESSIONID
        value: f9a9a185-1e05-41c7-98f3-432de6b114b0
 
  - type: header
    domains:
      - fat.example.com
    headers:
      - key: secretkey
        value: 33626665393961652d623633652d346639382d393366362d663532343935653336376438

  - type: cookie
    domains-regex:
      - test.example.com
    cookies:
      - key: SESSIONID
        value: c9190916-1b97-401d-a223-492894deff9e

  - type: header
    domains:
      - test.example.com
    headers:
      - key: secretkey
        value: 33343063656665352d616130352d346537622d616338322d306337346339353635326466
```

---
  
Expected results:
```bash
[INF] [example] Dumped HTTP request for https://fat.example.com/api/order/plaintext

POST /api/order/plaintext HTTP/1.1
Host: fat.example.com
User-Agent: Mozilla/5.0 (Kubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
Secretkey: 33626665393961652d623633652d346639382d393366362d663532343935653336376438
Cookie: f9a9a185-1e05-41c7-98f3-432de6b114b0
Content-Length: 0
Connection: close
Accept-Encoding: gzip

[INF] [example] Dumped HTTP request for https://test.example.com/api/order/plaintext

POST /api/order/plaintext HTTP/1.1
Host: test.example.com
User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.6) Gecko/20100628 Ubuntu/10.04 (lucid) Firefox/3.6.6
Secretkey: 33343063656665352d616130352d346537622d616338322d306337346339353635326466
Cookie: c9190916-1b97-401d-a223-492894deff9e
Content-Length: 0
Connection: close
Accept-Encoding: gzip

```

---


Actual debug output:
```bash
[INF] [example] Dumped HTTP request for https://fat.example.com/api/order/plaintext

POST /api/order/plaintext HTTP/1.1
Host: fat.example.com
User-Agent: Mozilla/5.0 (Kubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
Connection: close
Content-Length: 0
Cookie:
Secretkey: 33626665393961652d623633652d346639382d393366362d663532343935653336376438
Accept-Encoding: gzip

[INF] [example] Dumped HTTP request for https://test.example.com/api/order/plaintext

POST /api/order/plaintext HTTP/1.1
Host: test.example.com
User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.6) Gecko/20100628 Ubuntu/10.04 (lucid) Firefox/3.6.6
Connection: close
Content-Length: 0
Cookie:
Secretkey: 33343063656665352d616130352d346537622d616338322d306337346339353635326466
Accept-Encoding: gzip
[INF] No results found. Better luck next time!
[0:00:04] | Templates: 1 | Hosts: 2 | RPS: 0 | Matched: 0 | Errors: 4 | Requests: 2/2 (100%)
```

---

 
Key differences observed:
- The returned `Cookie` value is empty (`Cookie:` has no value), while `Secretkey` is correctly injected.

---


Additional notes:
- Only the `Secretkey` header is being properly added, despite both Cookie and Secretkey configurations being defined.
- I'm seeking technical support to resolve abnormal Cookie value injection.
