### ISSUE TITLE
Add `skip-secret-file` field

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#5521]
Using secret auth feature enabled explicitly by user, so inputs from secret file should be applicable as default for all templates as it's primarily intended for, and can be disabled at template / protocol level optionally for the edge cases like user pointed out in one of issues.

so probably need to reverse the logic to add support for `skip-secret-auth: true` at template level.

For example:

```yaml
http:
  - raw:
      - |
        HEAD / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /IPV6_fixed.htm HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic 123123
        Referer: http://{{Host}}/IPV6_disable.htm

  skip-secret-auth: true
```

_Originally posted by @ehsandeep in https://github.com/projectdiscovery/nuclei/pull/5468#pullrequestreview-2217069233_
