### ISSUE TITLE
[feature] Global helpers / payloads support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#554]
Currently, payload support is limited for `RAW` templates in the following manner:-

```yaml
requests:

  - payloads:
      password: password.txt

    raw:
      - |
        GET /index.action?password={{password}} HTTP/1.1
        Host: {{Hostname}}
        Connection: close
```

After global support:-

```yaml
requests:

  - method: GET
    path:
      - "{{BaseURL}}/{{path}}"

    headers:
      hello: "{{md5('Hello')}}"

    payloads:
      path: api_path.txt
```
