### ISSUE TITLE
Matchers / Extractors enhancement

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#555]
- [x] Word matcher support for Global variable, Payload variable, Helper functions
- [x] DSL matcher support for Global variable, Payload variable, Helper functions

An example with **global** variable support

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: xxx
        xxx:
          - "{{Hostname}}"

    extractors:
      - type: xxx
        xxx:
          - "{{RootURL}}"
```

An example with **payload** variable support

```yaml
requests:

  - raw:
      - |
        GET /index.action?username={{xss}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
      xss:
        - XSS_1
        - XSS_2
        - XSS_3

    matchers:
      - type: xxx
        xxx:
          - '{{xss}}'
        part: body

    extractors:
      - type: xxx
        xxx:
          - '{{xss}}'
        part: body
```

An example with **helper functions** support

```yaml
requests:

  - raw:
      - |
        GET /index.action?username={{xss}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
      xss:
        - XSS_1
        - XSS_2
        - XSS_3

    matchers:
      - type: xxx
        xxx:
          - '{{url_decode(xss)}}'
        part: body

    extractors:
      - type: xxx
        xxx:
          - '{{url_decode(xss)}}'
        part: body
```
