### ISSUE TITLE
[FEATURE] Support Tamper Scripts via Javascript using passive templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5565]
### Describe your feature request

- follow up of https://github.com/projectdiscovery/nuclei/pull/4723
- based on the discussion from https://github.com/projectdiscovery/nuclei/issues/4717 , once passive template PR is merged, we can add individual tamper scripts support by introducing new field in passive templates that accepts javascript which contains logic on how to modify any portion of http requests 
- the tamper code block will consist of javascript code that will update / modify the requests based on the rules ( similar to https://github.com/sqlmapproject/sqlmap/blob/master/tamper/apostrophemask.py )

### Describe the use case of the feature

- waf bypasses ( padding , encoding and all custom use cases )
- obfuscating payloads
- replacing obvious payloads like `/etc/passwd` with custom ones to avoid waf

### Describe alternatives you've considered

- none

### Implementation / Proposed Idea

- in first iteration we can target just normal http requests + ( url ,http ,  body of unsafe template ) 
- in `pkg/fuzz` the fuzzing works by breaking a http.Request into each individual components of k-v pairs and then rebuilding requests back using those kv pairs , this tamper script js should be executed in similar fashion that way tamper scripts can work on any and every part of request without needing to parse and handle various formats 
- since parsing unsafe headers or body can be challenging or sometime we also need to explicitly expose each component as string ( ideally before parsing the request in nuclei )
- a example js syntax we can enforce

// implemented internally in nuclei
```
function TamperX(request) {
    this.url = request.url; // request url
    this.method = request.method; // request method
    this.body = request.body;   // request body
    this.headers = request.headers; // request headers
    this.params = request.params; // query params
    this.kv = request.kv; // key value store
}
```

### key-value tampering 

```yaml
id: simple-key-value-tampering

info:
  name: tamper key values
  author: pdteam
  severity: info

passive: true # this is passive template!
http: # matcher / extractors will be applied for http protocol, similarly other protocol block can be defined. 
  - key-value-tamper: |
       // user needs to implement this method TamperKeyValue 
      // in template as javascript
      TamperX.prototype.TamperKeyValue = function(key, value) {
          // example updating payload with something else
          if (value.includes("/etc/passwd")) {
              this.kv[key] = value.replace("/etc/passwd", "/etc/hostname");
          }
      }
```

### request-level tampering

```yaml
id: tamper-requests

info:
  name: tamper requests
  author: pdteam
  severity: info

passive: true # this is passive template!
http: # matcher / extractors will be applied for http protocol, similarly other protocol block can be defined. 
  - request-tamper: |
      // user needs to implement this method TamperRequest 
      // in template as javascript
      TamperX.prototype.TamperRequest = function() {
        // unsafe tampering of headers like transfer-encoding
        // a very basic and simple tampering
        if (this.headers) {
            const headerLines = this.headers.split('\r\n')
            const modifiedHeaders = headerLines.map(line => {
                if (line.toLowerCase().startsWith('transfer-encoding:')) {
                    return ' ' + line
                }
                return line
            })
            this.headers = modifiedHeaders.join('\r\n')
        }
      }
```

> this is just basic idea but it could be improved depinding on use case and ease of use
