### ISSUE TITLE
[FEATURE] Template Profile Improvements

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#5567]
### Describe your feature request

- template profiles or config.yaml file contains all flag config in yaml format which can be directly passed to nuclei instead of adding each flag , this way it is easy to maintain and scalable and shareable
- this config file is merged with flags passed to nuclei with priority given to flags that way common / regularly used configs can be maintained and passed via config files
- we should add below new features related to config or template profiles

- [ ] ignore extra fields ( if we aren't already) that way info can be specified in fields like id , name , purpose yaml keys instead of commenting it out like we do in current template profiles
- [ ] update goflags to allow embedding file content , this way instead of passing auth related data via a file we can embed it in goflags under `secrets` key and goflags can generate a temporary file to handle and pass it internally

### Describe the use case of the feature

this will allow maintaining a single config file to be used with nuclei and users can maintain a different set of configs  specific to targets thereby keeping all config modular

example: a user who intends to vuln scan pd will have their template profile for this scan in this format

```yaml
name: projectdiscovery-scan
purpose: Config File for Scanning
description: single config file that contains every config related to scanning a specific target with specific templates and features

# targets list file
list |
  cve.projectdiscovery.io
  chaos.projectdiscovery.io
  ....
  api.projectdiscovery.io

# templates related config
type:
  - http
  - tcp
  - javascript
  - dns
  - ssl

exclude-tags:
  - dos
  - fuzz
  - osint

# other options
template-concurrency: 5
host-concurrency: 100
stats: true
timeout: 30

secrets:
  static:
  # 4. Custom Header based auth
  - type: header
    domains:
      - api.projectdiscovery.io
      - cve.projectdiscovery.io
      - chaos.projectdiscovery.io
    headers:
      - key: x-pdcp-key
        value: <api-key-here>
  dynamic:
    - template: custom-oauth-flow.yaml
      variables:
        - name: username
          value: pdteam
        - name: password
          value: nuclei-fuzz
      type: cookie
      domains:
        - .*.projectdiscovery.io
      headers:
        - key: Authorization
          value: Bearer {{token}}
```

**Comment by natinew77-creator** [comment]
/attempt #5567 

I’m working on this and plan to submit a PR as soon as i'm done.

**Comment by NandanKopplu** [comment]
/attempt #5567

Implementation plan:

**Feature 1: Ignore extra fields ✅ IN PROGRESS**
- Adding ProfileID, ProfileName, ProfilePurpose, ProfileDescription fields to Options struct
- Allows metadata in profiles without parse errors

**Feature 2: Inline target lists 🔄 NEXT**
- Support `list: |` syntax with embedded content
- Handle multiline strings as inline target lists

**Feature 3: Inline secrets integration 📋 PLANNED**
- Integrate existing authx secrets system into profiles
- Support `secrets:` section in profile YAML

Working branch: `feature-template-profile-improvements`

**Comment by NandanKopplu** [comment]
/attempt #5567

PR submitted: https://github.com/projectdiscovery/nuclei/pull/6804

Implemented all three features:
 Profile metadata fields
Inline target lists  
 Inline secrets integration

All tested and working.

**Comment by Simplereally** [comment]
/claim #5567

Submitted PR #6812 implementing all requested template profile improvements:

- Profile metadata fields (id, name, purpose, description)
- Inline target lists via YAML multiline syntax
- Inline secrets configuration with static and dynamic auth support

Ready for review.

**Comment by NandanKopplu** [comment]
## Response to PR #6812 Claims

While I appreciate, I'd like to clarify some inaccuracies about my implementation:

###  Options.Copy() WAS Fixed
Commit 53ac2af added all new fields to Copy(). This claim is false.

###  Interface{} Approach is Correct
Used `interface{}` specifically to avoid import cycles (pkg/types ↔ pkg/authprovider/authx). This is standard Go practice. The conversion happens in runner.go where authx is already imported.

###  Newline Detection is Robust
Simple and effective: if content has newlines, it's inline. No extra fields needed. Follows YAML multiline string conventions.

###  All Features Work
All three features tested and working. CodeRabbit's major concerns addressed

**Comment by dogancanbakir** [comment]
Hey contributors! Please make sure your PR follows the PR template and includes proof that your changes work (before/after examples, screenshots, or terminal output). Reviewer time is limited! Incomplete PRs may be closed without review. Thanks!

**Comment by dogancanbakir** [comment]
Hey @areebahmeddd — just a heads up, you've got multiple bounty issues claimed. We ask contributors to work on one at a time. Pick the one you'd like to focus on and we'll go from there.

**Comment by areebahmeddd** [comment]
Hi @dogancanbakir,
Apologies! i didn’t mean to spam PRs on open issues

i followed the projectdiscovery contribution guidelines by setting things up locally, running tests, and validating the logic. i noticed some existing PRs didn’t go as deep and if those have had extended inactivity, I hope mine can be considered as well

Thanks 🙂

**Comment by NandanKopplu** [comment]
## Proof of Working Implementation

### Before (Without Changes)
Profiles with metadata fields would fail:
```yaml
id: test-profile
name: "Test Profile"
```
Error: `unknown field: id`

### After (With Changes)  
**Feature 1: Profile Metadata Works**
```bash
$ ./nuclei -tp test-profile.yaml -validate
[INF] All templates validated successfully
```

Profile with metadata parses without errors:
```yaml
id: test-profile
name: Test Profile
purpose: Testing new profile features
description: This profile tests the new metadata fields
severity:
  - critical
```

---

**Feature 2: Inline Target Lists Work**

Before: Required separate file
```bash
$ nuclei -l targets.txt
```

After: Embedded in profile
```yaml
list: |
  example.com
  test.com
  scan.me
```

Testing:
```bash
$ ./nuclei -tp test-inline-targets.yaml -validate
[INF] All templates validated successfully
```

---

 **Feature 3: Inline Secrets Work**

Before: Required separate secrets file
```bash
$ nuclei --secrets secrets.yaml
```

After: Embedded in profile
```yaml
secrets:
  static:
    - type: header
      domains:
        - example.com
      headers:
        - key: X-API-Key
          value: test-key-123
```

Testing:
```bash
$ ./nuclei -tp test-all-features.yaml -validate
[INF] All templates validated successfully
```

---

### Complete Test Profile
All 3 features working together:
```yaml
# Metadata (Feature 1)
id: complete-test
name: Complete Feature Test
purpose: Testing all features
description: Profile with metadata, inline targets, and inline secrets

# Inline targets (Feature 2)
list: |
  example.com
  test.com

# Configuration
severity:
  - critical
  - high
type:
  - http

# Inline secrets (Feature 3)
secrets:
  static:
    - type: header
      domains:
        - example.com
      headers:
        - key: X-API-Key
          value: test-key-123
```

**Validation output:**
```bash
$ ./nuclei -tp test-all-features.yaml -validate
[INF] All templates validated successfully
```

All three features work independently and together. ✅

**Comment by SaurabhCodesAI** [comment]
@tarunKoyalwar @dogancanbakir 
hey, i have been understanding the goflags source for this. MergeConfigFile decodes YAML into a map but only iterates registered flags via VisitAll(), so unregistered keys like name, purpose, description just get skipped. Feature 1 basically works already with zero code changes.
also Working on the inline targets and secrets parts right now. i have dealt with similar config parsing stuff before so it should not take long.

**Comment by alibader-alt** [comment]
/attempt https://github.com/projectdiscovery/nuclei/issues/5567

Proposal: Enhancing Template Profiles with In-Memory Processing and Inheritance
Subject: Technical Improvements for Issue #5567

---

### 1. Introduction
The current proposed solutions (PR #6804 and others) successfully address the need for inline targets and secrets. However, to make Nuclei more enterprise-ready and secure, I propose two major architectural enhancements: In-Memory processing (to avoid disk I/O) and Profile Inheritance (for better maintainability).

### 2. Proposed Feature: In-Memory Virtual Filesystem (VFS)
Currently, inline targets are written to temporary files (e.g., in /tmp). 
- Problem: Disk I/O can be a bottleneck and leaves a digital footprint of sensitive targets.
- Solution: Use a memory-based buffer (e.g., bytes.Buffer in Go) or a Virtual Filesystem (VFS).
- Impact: 
    * Enhanced Security: Sensitive data never touches the physical disk.
    * Performance: Faster execution in high-concurrency or containerized environments (CI/CD).

### 3. Proposed Feature: Profile Inheritance (The 'extends' Key)
As users scale their usage, they will face "Configuration Drift" where authentication secrets are duplicated across many profiles.
- Solution: Add an 'extends' field.
- Example:
    -------------------------------------------
    id: production-api-scan
    extends: global-auth-base.yaml
    list: |
      api.example.com
      dev.example.com
    -------------------------------------------
- Logic: Nuclei should perform a deep merge of the base file and the current profile, allowing local flags to override inherited ones.

### 4. Proposed Feature: Automatic Secret Masking
Since secrets are now inline within the YAML, they are more prone to accidental exposure.
- Solution: Any value defined under the 'secrets' key should be automatically redacted/masked in Nuclei's stdout, debug logs, and stats.

### 5. Implementation Roadmap
1. Refactor goflags: Modify the parser to accept io.Reader interface instead of strictly requiring OS file paths.
2. YAML Merger: Implement a recursive merge function to handle the 'extends' logic.
3. RAM Buffering: Integrate a memory-backed storage for strings passed via the 'list' key.

### Conclusion
By implementing these enhancements, Nuclei Template Profiles will not only be more functional but also more secure and easier to manage at scale.

**Comment by wh0amibjm** [comment]
/attempt #5567

I can take this and deliver a first working version within 24 hours for a clearly scoped task. I work full-time and iterate quickly with reliable communication. Starting rate: $40-$45 depending on scope.

**Comment by wh0amibjm** [comment]
Submitted implementation PR: https://github.com/projectdiscovery/nuclei/pull/6988

Highlights:
- supports inline `secrets` in template profile YAML by materializing to a temp secrets file
- sanitizes profile metadata keys before merge (`id/name/purpose/description`)
- improves inline `list` materialization + runtime cleanup for generated temp files
- enforces size guardrails for profile/inline payloads
- keeps explicit CLI `-l` / `-sf` values authoritative over profile values

/claim #5567

**Comment by tianzhuxhc-bit** [comment]
Hi maintainers, I’m actively working through bounty tasks and would like to take this one if available.

Plan:
1) Reproduce and align expected scope
2) Submit an initial PR with tests/docs
3) Iterate quickly on review feedback

I can post first progress within 12 hours.

**Comment by teredasites** [comment]
C:/Program Files/Git/attempt #5567

**Comment by OpenclawUser** [comment]
I have the answer.

**Comment by wazder** [comment]
/attempt #6812 
Hi! I'd like to work on this bounty. I have experience with Go and YAML-based configuration systems. I plan to implement the template profile improvements described here: supporting extra fields in template profiles (id, name, purpose), updating goflags to allow embedding file content for auth-related data, and ensuring config files are merged with flags (with priority rules). I will follow the contribution guidelines and submit a well-tested PR.

**Comment by Iceshen87** [comment]
Hi @projectdiscovery team! 👋

I will implement the Template Profile Improvements as described in the issue.

### Implementation Plan:

**1. Config File Enhancements**
- Support ignoring extra fields in config.yaml
- Add metadata fields (id, name, purpose, description) without errors
- Merge config file flags with CLI flags (CLI takes priority)

**2. Secrets Embedding**
- Update goflags to support embedding secrets under `secrets` key
- Generate temporary files for auth data internally
- Support both static and dynamic secrets

**3. Template Profile Structure**
```yaml
name: projectdiscovery-scan
purpose: Config File for Scanning
description: Single config file for target-specific scanning

# Targets
list: |
  cve.projectdiscovery.io
  chaos.projectdiscovery.io

# Template config
type:
  - http
  - tcp
  - javascript
exclude-tags:
  - dos
  - fuzz

# Options
template-concurrency: 5
host-concurrency: 100
stats: true
timeout: 30

# Secrets
secrets:
  static:
    - type: header
      domains: [api.projectdiscovery.io]
      headers:
        - key: x-pdcp-key
          value: <api-key>
  dynamic:
    - template: custom-oauth-flow.yaml
      variables:
        - name: username
          value: pdteam
```

### ETA:
- Config parsing: 2-3 hours
- Secrets handling: 2-3 hours  
- Testing: 1-2 hours
- PR: Ready within 24 hours

/claim #5567
