### ISSUE TITLE
[Feature]  Unicode Strings

### ISSUE THREAD

**Issue by 0xd0m7** [projectdiscovery/nuclei#557]
It seems that unicode strings are decoding as URL. It's possible to take at look this?
It is currently not possible to send payloads with unicode. They are sent with URL encoding.

**Describe the solution you'd like**
Don't encode to URL unicode characters.

**Comment by ehsandeep** [comment]
@0xd0m7 do you have an example template to share? thanks!

**Comment by 0xd0m7** [comment]
@ehsandeep 
Sometimes it is possible to detect through unicode strings the backend of some CMS can even be valid to identify S3 buckets. See the following example in a S3 Bucket:

**Request**
``GET /Ä.txt``

**Response**
```
<Code>SignatureDoesNotMatch</Code><Message>
host: redacted.s3.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20210219T152446Z
```

But Nuclei encode ä.txt then error will not work.

Best regards,
@0xd0m7

**Comment by ehsandeep** [comment]
@0xd0m7, for this you can make use of [rawhttp](https://github.com/projectdiscovery/rawhttp) support using `unsafe` flag that allows you to send requests the manner you want. 

Example:- 

```yaml
requests:
  - raw:
    - |
       GET /Ä.txt HTTP/1.1
       Host: {{Hostname}}
       Connection: close
       Accept: application/json, text/plain, */*
       Accept-Encoding: gzip, deflate
       Accept-Language: en-US,en;q=0.9
    unsafe: true
```

Request on HTTP server:-

![image](https://user-images.githubusercontent.com/8293321/108525996-a757c300-72f6-11eb-9d33-774b39562b2f.png)
