### ISSUE TITLE
[BUG] Escaping string in dsl function: "Cannot transition token types from STRING [] to VARIABLE [xxxx]"

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei#5580]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

When using dsl function like this
```yaml
id: test

info:
  name: test
  author: daffainfo
  severity: info
  tags: test

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
       - type: dsl
         dsl:
          - contains(body, '"Test"')
```
The output is always
```
[ERR] Error occurred parsing template /xxxx/test.yaml: could not compile request: could not compile operators: could not compile matcher: could not compile DSL expression "compare_versions(body, '\"Test\"')": Cannot transition token types from STRING [] to VARIABLE [Test]
```

### Expected Behavior

Im expecting there's no error at all and Im expecting the template will search string `"Test"` in the body response

### Steps To Reproduce

1. Create a template
```yaml
id: test

info:
  name: test
  author: daffainfo
  severity: info
  tags: test

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
       - type: dsl
         dsl:
          - contains(body, '"Test"')
```
2. Run this command
```
nuclei -t /xxx/test.yaml --validate
```

### Relevant log output

```shell
[ERR] Error occurred parsing template /xxxx/test.yaml: could not compile request: could not compile operators: could not compile matcher: could not compile DSL expression "compare_versions(body, '\"Test\"')": Cannot transition token types from STRING [] to VARIABLE [Test]
```

### Environment

```markdown
- OS: Mac
- Nuclei: 3.3.1
- Go: 1.22.3
```

### Anything else?

Actually my problem is the same as this issue

https://github.com/Knetic/govaluate/issues/94
