### ISSUE TITLE
[feature] Dynamic variabe reuse support for basic templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#560]
Currently, dynamic variable support is limited to RAW requests and can be used in the following manner.

```yaml
      - type: kval
        name: session
        internal: true
        part: body
        kval:
          - PHPSESSID
```
After this change, this will be supported.

```yaml
  - method: POST
    path:
      - "{{BaseURL}}/login.php"

    body: "username=admin&password=password&Login=Login&user_token={{session}}"
```
