### ISSUE TITLE
[feature] cookie-reuse to support base templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#561]
Currently, `cookie-reuse` is limited to RAW request only, we need to extend this support for basic templates as well.

After this change, this will be supported. 

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/login.php"

  - method: POST
    path:
      - "{{BaseURL}}/login.php"

    body: "username=admin&password=password&Login=Login"
    
    cookie-reuse: true
```

**Comment by ehsandeep** [comment]
Closing as this is already supported, valid example:-

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/login.php"
    
    cookie-reuse: true
    matchers:
      - type: word
        words:
          - "This is test matcher text"
```

```
echo https://hackerone.com | nuclei -test.yaml -proxy http://127.0.0.1:8080
```
