### ISSUE TITLE
[issue] misc rawhttp bugs

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#573]
- [x] Missing matched endpoint in the output when no hostname

```
echo https://bbpress.org | ./nuclei -t test.yaml
```

<details>
<summary>Test Template</summary>

```yaml
id: test
info:
  name: test
  author: test
  severity: test

requests:
  - raw:
      - |
        GET /?test HTTP/1.1
        Host:
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

    unsafe: true
    matchers:

      - type: status
        status:
          - 400
```
</details>

- [x] Request timeout error for any HTTP request

```
echo https://example.com | ./nuclei -t test.yaml
```

<details>
<summary>Test Template</summary>

```yaml
id: test
info:
  name: test
  author: test
  severity: test

requests:
  - raw:
      - |
        GET /?test HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Connection: close

    unsafe: true
    matchers:

      - type: status
        status:
          - 400
```
</details>
