### ISSUE TITLE
[BUG] DSL Responses Do Not Work Properly with Code Protocol

### ISSUE THREAD

**Issue by hipotermia** [projectdiscovery/nuclei#5748]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

When using the code protocol, DSL responses are not functioning as expected.

- `status_code_1 == 200` evaluates to true.
- `status_code_2 == 200` evaluates to true.

However, when comparing the two status codes:

- `status_code_1 == status_code_2` does not match.

And by removing the code protocol, works.

### Expected Behavior

`status_code_1 == status_code_2` should match if are equal, regardless if code is being used.

### Steps To Reproduce

The following template should hit, but it doesn't.

```yaml
id: test

info:
  name: test
  author: hipotermia
  severity: high

code:
  - engine:
      - py
      - python3
    source: |
      print('/')

http:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == status_code_2"
```

### Environment

- OS: Lunux
- Nuclei: 3.3.5
- Go: 1.22.4

**Comment by dwisiswant0** [comment]
I'll leave it here for notes:

* issue-5748-b:

```yaml
code:
  - engine:
      - sh
      - bash
    source: id

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    extractors:
      - type: dsl
        dsl:
          - 'concat("status_code_1: ", status_code_1)'
          - 'concat("status_code_2: ", status_code_2)'
```

* issue-5748-c:

```yaml
http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

    extractors:
      - type: dsl
        dsl:
          - 'concat("status_code_1: ", status_code_1)'
          - 'concat("status_code_2: ", status_code_2)'
```

Output:
```
[issue-5748-b] [http] [info] http://scanme.sh ["status_code_1: 200"]
[issue-5748-b] [http] [info] http://scanme.sh ["status_code_2: 200"]
[issue-5748-c] [http] [info] http://scanme.sh ["status_code_1: 200"]
[issue-5748-c] [http] [info] http://scanme.sh ["status_code_1: 200","status_code_2: 200"]
```
