### ISSUE TITLE
[FEATURE] Add Env variables to dynamic secret file variables

### ISSUE THREAD

**Issue by alban-stourbe-wmx** [projectdiscovery/nuclei#5834]
### Describe your feature request

Today, if we want to pass variables to Dynamic Secret Files, we have to hard-code the secret in the model. This can lead to some secrets being pushed to Github, for example. 

A simple feature is to allow env variables to pass the secret to Dynamic Secret Files. Until such time as it is directly possible to retrieve secrets via third-party solutions. 

### Describe the use case of the feature

Handle env variables in dynamic variables field : 
Example: 
```yaml
dynamic: 
  - template: path/login.yaml
    input: "https://foorbar.com/login"
    variables:
      - key: username 
        value: $FOO_BAR_USERNAME
      - key: password
        value: $FOO_BAR_PASSWORD
    type: bearertoken
    domains:
      - ".*"
    token: "{{jwt_bearer}}"
```

### Additional context
I made a very simple PR for this feature. https://github.com/projectdiscovery/nuclei/pull/5835
