### ISSUE TITLE
[feature] Adding more types to matchers/extractors

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#584]
For the response with specific types, we can add more native support to match/extract data from the response for HTTP module, for example:-

```yaml
    extractors:
      - type: json
        part: body
        json:
        - "JSON expression"
```

```yaml
    matchers:
      - type: html
        part: body
        html:
        - "HTML expression"
```
