### ISSUE TITLE
[FEATURE] Template option to limit redirects only to the same protocol

### ISSUE THREAD

**Issue by JaneX8** [projectdiscovery/nuclei#5887]
### Describe your feature request

I would like an option in nuclei-templates to restrict redirects to the protocol it was initialized with. I have a situation where I want to follow redirects (x times) but not when its switching to another protocol.

How can I ensure that redirects are only on the same protocol (eg http or https) and not switching protocols?

Right now I use something like:

```yaml
requests:
  - method: GET
    path:
      - "http://{{Hostname}}/something"
      - "https://{{Hostname}}/something
````

To ensure I test both, both can redirect but only within their own protocol.

### Describe the use case of the feature

Generic, many use cases thinkable.

### Describe alternatives you've considered

```yaml
requests:
  - method: GET
    path:
      - "https://{{Hostname}}/something
  - method: GET
    path:
      - "http://{{Hostname}}/something"
````

But still no way to limit redirects to their own protocol.
