### ISSUE TITLE
[feature] Disable base request for intruder

### ISSUE THREAD

**Issue by ldionmarcil** [projectdiscovery/nuclei#598]
**Is your feature request related to a problem? Please describe.**
Would it be possible to disable base requests for intruder payloads? I don't think I understand the value they bring, especially since it sends the custom variable template marker in them?

For example the following template:

```yaml
  - payloads:
      var:
        - foo
        - bar
        - baz

    raw:
      - |
        GET /§var§ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0
```

Issues the following requests:
```
"GET /foo HTTP/1.1" 200 50114 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"
"GET /bar HTTP/1.1" 404 466 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"
"GET /baz HTTP/1.1" 404 466 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"
"GET /%C2%A7var%C2%A7 HTTP/1.1" 404 466 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"
```
The last request has the variable name in it, which I don't think is a very useful feature. Perhaps I am misusing the intruder? Anyways, if there is no way to disable this behaviour, would you consider introducing it? Thank you!
