### ISSUE TITLE
[BUG] Can't match the body content

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/nuclei#5993]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

NUCLEI cannot match the body content

## Nuclei
![Image](https://github.com/user-attachments/assets/ea4b827a-5f15-40da-b31e-e6311d8d1df9)

## BurpSuite
![Image](https://github.com/user-attachments/assets/712219d3-2a12-4459-8a85-94ee0df03592)

## Code
```
http:
  - method: GET
    path:
      - '{{BaseURL}}/xxxx.txt'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'hello'
        condition: and

      - type: status
        status:
          - 200

```

### Steps To Reproduce

nuclei -t 1.yaml -u http://x.x.x.x/ --debug

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux
- Nuclei: 3.3.8
- Go: go1.22.5
```

**Comment by dwisiswant0** [comment]
The dumped HTTP response clearly lacks body content. Maybe something is wrong with the payload in your template.

**Comment by badboycxcc** [comment]
This is a special device that returns only this information

**Comment by dogancanbakir** [comment]
I couldn't repro this. See:

```console
$ go run . -u scanme.sh -t test_template.yaml -p http://127.0.0.1:8080

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.2

                projectdiscovery.io

[INF] Current nuclei version: v3.4.2 (latest)
[INF] Current nuclei-templates version: v10.1.7 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 64
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[test] [http] [info] https://scanme.sh
```

template:

```yaml
id: test

info:
  name: test
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'ok'
        condition: and

      - type: status
        status:
          - 200
```

<img width="1297" alt="Image" src="https://github.com/user-attachments/assets/84a4cab7-517b-46f3-8565-5012f8147dac" />


Closing this. Feel free to reopen if the issue persists.
