### ISSUE TITLE
[BUG] Hook functionality in headless mode not working as intended?

### ISSUE THREAD

**Issue by jackds-security** [projectdiscovery/nuclei#6048]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Hello, 

I've been playing around with a few examples regarding the "hook" argument for the headless protocol. The manual / examples on `https://docs.projectdiscovery.io/templates/protocols/headless` suggest the following:

> Nuclei supports running some custom Javascript, before the page load with the hook argument. This will always run the provided Javascript, before any of the pages load.

> The example provided hooks window.alert so that the alerts that are generated by the application do not stop the crawler.

> 
> - action: script
>  args:
>    code: (function() { window.alert=function(){} })()
>    hook: true

I tried a very simple example, taken from the "Example Headless Templates" section:

```
headless:
  - steps:
      - args:
          url: "{{BaseURL}}/test.html"
        action: navigate
      - action: waitload

      # Set the hook to override window.data for xss detection
      - action: script
        args:
          hook: true
          code: (function() { window.alert = function() { window.data = 'found' } })()
      - action: waitload
      - action: script
        name: alert
        args:
          code: "window.data"
    matchers:
      - part: alert
        type: word
        words:
          - "found"
```

When running this template via `nuclei -target host.com -t ./test.yaml -headless` , on a host that simply does `alert(123);`, I can see that the crawler hangs and after a number of seconds shows "[INF] No results found. Better luck next time!".

### Expected Behavior

Expected is that the alert() function is overwritten and that the example returns "found".

### Steps To Reproduce

1. Create the following template:

```
id: just-a-test

info:
  name: DVWA Reflected XSS Verification
  author: jackds
  severity: info

headless:
  - steps:
      - args:
          url: "{{BaseURL}}/test.html"
        action: navigate
      - action: waitload

      # Set the hook to override window.data for xss detection
      - action: script
        args:
          hook: true
          code: (function() { window.alert = function() { window.data = 'found' } })()
      - action: waitload
      - action: script
        name: alert
        args:
          code: "window.data"
    matchers:
      - part: alert
        type: word
        words:
          - "found"
```

2. Prepare a host that simply does `alert(123)`
3. Then run `nuclei -target host.com -t ./test.yaml -headless

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- Nuclei: Current nuclei version: v3.3.8 (latest)
- Go: go version go1.22.1 linux/amd6
```

**Comment by jackds-security** [comment]
It seems that part of the problem is within `pkg/protocols/headless/engine/page_actions.go`. The current code looks like this:

```
	if hook == "true" {
		if _, err := p.page.EvalOnNewDocument(code); err != nil {
			return err
		}
	}

	data, err := p.page.Eval(code)
	if err != nil {
		return err
	}

	if data != nil && act.Name != "" {
		out[act.Name] = data.Value.String()
	}
```

I did some testing myself and I get better results when changing this to:

```
	if hook == "true" {
		if _, err := p.page.EvalOnNewDocument(code); err != nil {
			return err
		}
	} else {
		data, err := p.page.Eval(code)
		if err != nil {
			return err
		}
	
		if data != nil && act.Name != "" {
			out[act.Name] = data.Value.String()
		}
	}
```

Furthermore I believe some of the templates that use the `headless` feature should be reworked.

**Comment by dwisiswant0** [comment]
In the `"script"` action, enabling the `hook`  ensures that the provided script `code` is executed on every frame *as* it is created. But, if the target scenario involves `"alert(123)"` being embedded within the main frame beforehand, the native execution cannot be overridden - since `"alert(123)"` has already been triggered prior to DOM content rendering.

Additionally, the `code` argument strictly requires a function reference, meaning direct expressions are invalid:

**Incorrect:**  
```js
window.data
```

**Correct:**  
```js
() => window.data
```

Here is a minimal reproducible setup to achieve the intended behavior:

HTML:

```html
<!-- index.html -->
<html><head></head><body><button onclick=alert(1+2)></button></body></html>
```

Nuclei template:

```yaml
# issue-6048.yaml
id: issue-6048

info:
  name: Issue 6048
  author: dwisiswant0
  severity: info
  tags: test

headless:
  - steps:
      - args:
          url: "{{BaseURL}}/"
        action: navigate
      - action: script
        args:
          hook: true
          code: (() => { window.alert = (v) => { window.data = v }})()
      - action: waitdom
      - action: click
        args:
          by: xpath
          xpath: /html/body/button
      - action: script
        name: alert
        args:
          code: () => window.data

    matchers:
      - part: alert
        type: word
        words:
          - "3"
```

This implementation overrides `window.alert` by redirecting its argument to `window.data`, allowing subsequent script actions to retrieve the intercepted alert value.

Besides, overriding the native `alert` function with a hook for XSS detection is not recommended, as Nuclei provides a dedicated action, `waitdialog`, explicitly designed for capturing triggered XSS payloads via browser dialogs. Ref: [waitdialog](https://docs.projectdiscovery.io/templates/protocols/headless#waitdialog) & [Simplifying XSS detection with Nuclei](https://projectdiscovery.io/blog/simplifying-xss-detection-with-nuclei).

Using `waitdialog` is a more efficient and purpose-built approach for detecting modal interactions, including alerts, prompts, and confirmations, ensuring precise identification of XSS execution points.
