### ISSUE TITLE
Unwanted GET parameters addition

### ISSUE THREAD

**Issue by pissedofftryer** [projectdiscovery/nuclei#6090]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Bug: _headless_ automatically appending query parameters to _code_ output in _url_ args for navigate action.

Here is a template example:

```yaml
id: change-get-params

info:
  name: Change get params
  author: me
  severity: low
  tags: test

variables:
  parameters: "{{Query}}"
  base_url: "{{BaseURL}}"
  p1: "param1"

code:
  - engine:
      - python3
    source: |
      import os
      import urllib.parse

      p1 = os.getenv('p1')
      parameters = os.getenv('parameters')
      base_url = os.getenv('base_url')

      query_string = parameters.lstrip('?')
      params_dict = urllib.parse.parse_qs(query_string)
      
      for key in params_dict:
        params_dict[key] = [p1]
      
      new_query = '&'.join(f"{key}={values[0]}" for key, values in params_dict.items())

      print(f'{base_url}?{new_query}')

headless:
  - steps:
      - action: navigate
        args:
          url: "{{code_response}}"
```

### Expected Behavior

For :  _-u 'https://example.com/a?search=b'_ 
We'd like a navigate to: _https://example.com/a?search=param1_
However we have: _https://exemple.com/a?search=param1&search=b_

### Steps To Reproduce

1. Run _nuclei -t template_example.yaml -u 'https://google.com/?a=b' -code -headless -debug -v -svd_
2. Look at the debug, more precisely the following lines:

```
[...]
[VER] Sent Headless request to https://google.com/?a=param1&a=b
[INF] [change-get-params] Dumped Headless request for https://google.com/?a=param1&a=b
[DBG]   navigate => https://google.com/?a=param1&a=b
[...]
"code_response": "https://google.com/?a=param1",
[...]
```

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Kali 6.12.13-1kali1
- Nuclei: v3.3.9
- Go: go1.24.0
```
