### ISSUE TITLE
[BUG] File Access Denied for Payload Helper Files

### ISSUE THREAD

**Issue by MasoudAbdaal** [projectdiscovery/nuclei#6110]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Throw an exception; Failed to validate. 

### Expected Behavior

Read wordlist content and start fuzzing. 

### Steps To Reproduce

1. **Create a Nuclei Template:**
   - Write a Nuclei template that performs fuzzing using a file-based wordlist.  
   - For example, use the following template as a starting point:

   ```yaml
   id: ASVS-4-0-3-V5-1-2

   info:
     name: ASVS 5.1.2 Check
     author: Masoud Abdaal
     severity: high
     classification:
       cwe-id: CWE-915
     reference:
       - https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation
       - https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Mass_Assignment
     tags: asvs,5.1.2
     description: |
       Verify that frameworks protect against mass parameter assignment attacks, or that the application has countermeasures to protect against unsafe parameter assignment (e.g., marking fields as private).

   http:
     - raw: 
         - |
           POST {{Path}} HTTP/1.1
           Host: {{Host}}
           Content-Type: application/json
           User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0

           { "{{properties}}": {{properties_value}} }

       attack: clusterbomb
       payloads:
         properties: "keysList.txt"
         properties_value: "valuesList.txt"
   ```

2. **Prepare the Payload Files:**
   - In the same directory as your Nuclei template, create two files:
     - **`keysList.txt`** – containing a list of property keys (one per line) that you want to fuzz.
       - hello
       - worlds
     - **`valuesList.txt`** – containing a list of values corresponding to those keys. 
        - val1
        - val2
        - val3
        - val4

   - Ensure that both files are correctly formatted and accessible.

3. **Run the Template on a Windows Machine:**
   - Execute the template using Nuclei on a Windows environment.  
   - For example, run the following command:
     ```bash
     nuclei.exe -t .\5.1.2.yaml -validate
     ```
   - Observe that the template works on Linux but fails on Windows with a file access error.

### Relevant log output

```shell
[ERR] Error occurred parsing template /home/attacker/5.1.2.yaml: could not compile request: could not parse payloads: could not load payload file: [:RUNTIME] access to helper file /home/attacker/valuesList.txt denied
[FTL] Could not validate templates: errors occurred during template validation
```

### Environment

```markdown
- OS: Windows 10 (Version 10.0.19045 Build 19045), Ubuntu 22.04.3 LTS
- Nuclei: 3.3.10 
- Go: 1.24.0 (windows/amd64)
```
