### ISSUE TITLE
[BUG] Templates with full URLs in HTTP Raw request, the URL itself is removed and only the path is retained for the request.

### ISSUE THREAD

**Issue by vortexau** [projectdiscovery/nuclei#6161]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Where a template is used with HTTP Raw, the URL itself is stripped from the request and only the path retained.

Example template HTTP raw section:

```yaml

http:
  - raw:
      - |
        GET http://127.0.0.1/some/path/here HTTP/1.1
        Host: {{Hostname}}

```

Reviewing the request in Burp Proxy reveals the request was made as follows:

```http
GET /some/path/here HTTP/1.1                                                                                                                                     
Host: hostname                                                                                                                                                                     

```

### Expected Behavior

Expected behaviour would be for the full, raw HTTP request to be sent.

Example:

Example template HTTP raw section:

```yaml

http:
  - raw:
      - |
        GET http://127.0.0.1/some/path/here HTTP/1.1
        Host: {{Hostname}}

```

Full request in Burp Proxy:

```http
                                               
GET http://127.0.0.1/some/path/here HTTP/1.1                                                                                                                                     
Host: hostname                                                                                                                                                                     

```

### Steps To Reproduce

1. Run nuclei, using existing template with a command such as this: `~/go/bin/nuclei -u somehostname -t ~/nuclei-templates/http/vulnerabilities/amazon/amazon-ec2-ssrf.yaml -debug -verbose -proxy http://localhost:8081`
2. Note in Burp Suite that the reuest is missing the full path:

```http
GET /latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance HTTP/2
Host: somehost


```

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Linux
- Nuclei: v3.4.2
- Go:
```
