### ISSUE TITLE
Negative matching in matchers

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#62]
For example, I'm looking for the page with `The specified bucket does not exist` in the body and **not** `X-GUploader-UploadID` in the response header to make sure it's not from Google storage bucket. 

here is an example of how this can be used:- 

```
      - type: word
        words:
          - "The specified bucket does not exist"

      - type: word
        words:
          - "X-GUploader-UploadID"
        part: header
        negative: true

```
