### ISSUE TITLE
[BUG] Cookie-reuse parameter not working as expected in raw templates

### ISSUE THREAD

**Issue by kenyon-wong** [projectdiscovery/nuclei#6220]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Regardless of the cookie-reuse value (true/false), when using multiple raw format request templates, the subsequent requests (from the second one onward) continue to use the Set-Cookie value from the first request's response.

### Expected Behavior

- When cookie-reuse is set to `true`: Subsequent requests should reuse cookies from previous responses
- When cookie-reuse is set to `false`: Each request should start with fresh cookies and not reuse previous values

### Steps To Reproduce

1. Create templates containing raw requests:
```yaml
id: test

info:
  name: test
  author: ffffffff0x
  severity: info
  description: |
    由插件自动生成
  metadata:
    fofa-query: 
    shodan-query: 
    hunter-query: 
  reference:
    - https://
  tags: auto

http:
  - raw:
      - |
        POST /*** HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 401
        Content-Type: application/json
        Origin: https://{{Hostname}}
        Connection: keep-alive

        ***

      - |
        GET /*** HTTP/1.1
        Host: {{Hostname}}
        Connection: keep-alive

    cookie-reuse: false
    
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - "status_code == 200"
```
2. Run the command:

```bash
nuclei -t template1.yaml -u https://example.com -debug
```

### Relevant log output

```shell
[INF] [test] Dumped HTTP request for https://www.baidu.com/***/getOrderBackInfoPage

POST /***/getOrderBackInfoPage HTTP/1.1
Host: www.baidu.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.7 Mobile/15E148 Safari/604.1
Content-Length: 401
Connection: keep-alive
Content-Type: application/json
Origin: https://www.baidu.com
Accept-Encoding: gzip

{***}
[DBG] [test] Dumped HTTP response https://www.baidu.com/***/getOrderBackInfoPage

HTTP/1.1 460 Client Error (460)
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
Date: Wed, 14 May 2025 09:20:57 GMT
*-***-Id: 19f47e0635554551888e002e1f219820
*-***-Ua: ua:fsND9Cb8O0WNvo
Server: nginx
Set-Cookie: SESSION_ID=f1852a00-747f-45a9-ad32-dcefbfedb65c.***; Path=/; Secure; SameSite=None; HttpOnly
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers

{"timestamp":"2025-05-14 17:20:57","status":460,"error":"Invalid Session","path":"/orderBackWeb/getOrderBackInfoPage"}
[INF] [test] Dumped HTTP request for https://www.baidu.com/***/getOrderBackInfo?***=***

GET /***/getOrderBackInfo?***=*** HTTP/1.1
Host: www.baidu.com
User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50
Connection: keep-alive
Cookie: SESSION_ID=f1852a00-747f-45a9-ad32-dcefbfedb65c.***
Accept-Encoding: gzip
```

### Environment

```markdown
- OS: Windows
- Nuclei: v3.4.3
- Go: N/A (installed via binary)
```

### Anything else?

**Reference documentation**: https://docs.projectdiscovery.io/templates/protocols/http/value-sharing
**Confirmed** that the latest documentation's description of `cookie-reuse` aligns with my understanding.
