### ISSUE TITLE
[BUG] Code protocol failed to use external source file and still use code snippet

### ISSUE THREAD

**Issue by charB66** [projectdiscovery/nuclei#6236]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

## Resume
When the code protocol is used, the external source file is treated as a raw code snippet.

### Files structure

```bash
.
└── templates
    ├── code
    │   └── check-wp-api.py
    └── code.yaml
```

### Command line

`nuclei -u target.tld -t templates/ -code` 

### Sources codes

1. `./templates/code.yaml`
```yaml
id: code-test-wp-api

info:
  name: test template to assert that WP API is not exposed.
  author: charB66
  severity: low

code:
  - engine:
    - py  
    - python3
    source: code/check-wp-api.py

    matchers:
      - type: word
        words:
          - "exposed"
# digest: 4a0a00473045022100be14c6136e3e03e1b9229edb075e22bde69ba6ddbe6c1f656fff3bf7de02b2c302201398e83078de7462cd51ff137b453b95cf21b37ae19c702fb03fe5ec0ece7775:f821740f503d0e268ce6860fae22ef7c
```
2. `./templates/code/check-wp-api.py`
```python
import requests, sys

url_to_test = sys.stdin.read()

resp = requests.get(f"https://{url_to_test}/wp-json")

if resp.status_code in [200, 301, 302]:
    if "namespaces" in resp.content.decode("utf-8"):
        print("exposed")
    else:
        print("not exposed")
else:
    print("No route response.")
```

### Expected Behavior

The external source code file `code/check-wp-api.py` is used as described in the documentation here: [https://docs.projectdiscovery.io/templates/protocols/code#engine](https://docs.projectdiscovery.io/templates/protocols/code#engine):

> The code to be executed can be provided either as an external file or as a code snippet directly within the template.
For an external file:
`source: helpers/code/pyfile.py`

### Steps To Reproduce

1. Run `nuclei -u target.tld -t templates/ -code`

### Relevant log output

```shell
__     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.4

                projectdiscovery.io

[INF] Current nuclei version: v3.4.4 (latest)
[INF] Current nuclei-templates version: v10.2.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 42
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from bfe
[INF] Targets loaded for current scan: 1
[DBG] [code-test-wp-api] Dumped Executed Source Code for input/stdin: 'domain.tld'
---------------
Source Code:
---------------
code/check-wp-api.py

---------------
Command Executed:
---------------
/usr/bin/python3 /tmp/nuclei-tmp-795082373/1489063862

---------------
Command Output:
---------------
Traceback (most recent call last):
  File "/tmp/nuclei-tmp-795082373/1489063862", line 1, in <module>
    code/check-wp-api.py
    ^^^^
NameError: name 'code' is not defined. Did you forget to import 'code'?

[WRN] Command Output here is stdout+sterr, in response variables they are seperate (use -v -svd flags for more details)
[DBG] [code-test-wp-api] Dumped Code Execution for domain.tld



[INF] Scan completed in 163.183665ms. No results found.
```

### Environment

```markdown
- OS: Ubuntu 24.04.2 LTS
- Nuclei:  v3.4.4
- Go: go1.24.2 linux/amd64
```

### Anything else?

Pushing the source code from `code/check-wp-api.py` directly to the template works fine:
```yaml
id: code-test-wp-api-v2

info:
  name: test template to assert that WP API is not exposed.
  author: charB66
  severity: low

code:
  - engine:
    - py  
    - python3
    source: |
      import requests, sys

      url_to_test = sys.stdin.read()

      resp = requests.get(f"https://{url_to_test}/wp-json")

      if resp.status_code in [200, 301, 302]:
          if "namespaces" in resp.content.decode("utf-8"):
              print("exposed")
          else:
              print("not exposed")
      else:
          print("No route response.")

    matchers:
      - type: word
        words:
          - "exposed"
```

**Comment by charB66** [comment]
Hello @dwisiswant0, thanks for your quick response!
I tried using the absolute path and even copied my external source code (the helper) into each directory, but it’s still not working 😔.

`template`:
```yaml
id: code-test-wp-api

info:
  name: test template to assert that WP API is not exposed.
  author: charB66
  severity: low

code:
  - engine:
    - py  
    - python3
    source: /home/user/check-wp-api.py # also tested: "check-wp-api" and each possible locations 

    matchers:
      - type: word
        words:
          - "exposed"
# digest: 4a0a00473045022100dedf9eee2414bf6c4992b3f5d841671c1eefafca704a8a4f507313483303b86002204cf45bbda0572b39d15cf58236ffdc711a59f831cdbb56dffeb858874117edb5:f821740f503d0e268ce6860fae22ef7c
```

`files hierarchy`:
```bash
.
├── Desktop
├── Documents
├── Downloads
├── Music
├── Pictures
├── Public
├── Templates
├── Videos
├── check-wp-api.py
└── dev
    ├── check-wp-api.py
    └── nuclei
        ├── check-wp-api.py
        ├── code
        │   └── check-wp-api.py
        ├── debug
        └── templates
            ├── check-wp-api.py
            ├── code.yaml
```

Am I missing something?
