### ISSUE TITLE
[BUG] Headless script throws errors in document.cookie

### ISSUE THREAD

**Issue by SamAtBugcrowd** [projectdiscovery/nuclei#6238]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

For context, I am using the following command and template:
Command:
```
nuclei -t temp.yaml -u https://example.com/ -headless -sb -debug -v
```

Template:
```yaml
id: test
info:
  name: test
  author: test
  severity: medium
headless:
- steps:
  - args:
      url: '{{BaseURL}}'
    action: navigate
  - action: waitload
  - args:
      code: document.cookie = "test=test_value; path=/" // <-- This is the line that fails
    action: script
  - args:
      code: alert(document.cookie)
    action: script
```

If you remove the commented step, the alert dialog box works fine. Also, the script `console.log("test")` fails as well. The error message is:
```
[WRN] [test] Could not execute request for example.com: could not get html element: error occurred executing action: eval js error: TypeError: Cannot read properties of undefined (reading 'apply')
    at <anonymous>:1:47 <nil>
```

Edit: The following template also fails:
```yaml
id: test
info:
  name: test
  author: test
  severity: medium
variables:
  flag: '{{rand_text_alphanumeric(15)}}'
headless:
- steps:
  - args:
      url: '{{BaseURL}}'
    action: navigate
  - action: waitdialog
  - args:
      code: alert('{{flag}}')
    action: script
  matchers-condition: and
  matchers:
  - type: word
    part: event.dialog.message
    words:
    - '{{flag}}'
  - type: word
    part: event.dialog.type
    words:
    - alert
```

### Expected Behavior

The expected behaviour is that it would execute the script provided without errors (add a cookie in the `document.cookie` example).

### Steps To Reproduce

1. Prepare the template file `temp.yaml` (using provided content)
2. Run `nuclei -t temp.yaml -u https://example.com/ -headless -sb -debug -v`

### Relevant log output

```shell
__     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.4

		projectdiscovery.io

[WRN] The current platform and privileged user will run the browser without sandbox
[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.4.4 (latest)
[INF] Current nuclei-templates version: v10.2.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 42
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[WRN] [test] Could not execute request for bugcrowd.com: could not get html element: error occurred executing action: eval js error: TypeError: Cannot read properties of undefined (reading 'apply')
    at <anonymous>:1:47 <nil>
[INF] Scan completed in 4.688623856s. No results found.
```

### Environment

```markdown
- OS: Ubuntu 24.04.1 LTS
- Nuclei: v3.4.4
- Go: go1.22.2 linux/arm64
```
