### ISSUE TITLE
interactsh-server and nuclei oob

### ISSUE THREAD

**Issue by charis3306** [projectdiscovery/nuclei#6251]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Hello, I found that the self-hosted oob using interactsh-server isn't working properly with Nuclei.

First, I generated a token using ./interactsh-server -domain microsoftooffice.sbs -wildcard (the token can also be specified). Then I configured Nuclei by modifying the configuration file at C:\Users\chari\AppData\Roaming\nuclei\config.yaml with the following settings:

```yaml
# interactsh server url for self-hosted instance (default: oast.pro,oast.live,oast.site,oast.online,oast.fun,oast.me)  
interactsh-server: "microsoftooffice.sbs"  

# authentication token for self-hosted interactsh server  
interactsh-token: "b28fb0e67a6997014b3b9a50f86283b6beb279b94d982feb3b0b5a45d898ec6e"  
```

However, it doesn't work. I'm using interactsh-server version 1.2.4 and Nuclei version v3.4.4.

### Expected Behavior

fix bug

### Steps To Reproduce

nuclei -u "xxxxx" -t C:\Users\chari\nuclei-templates\http\vulnerabilities\fastjson\

![Image](https://github.com/user-attachments/assets/07b46f48-7322-4734-b202-33b8465d3862)

### Relevant log output

```shell

```

### Environment

```markdown
- OS: widnows(interactsh-server)
- OS: widnows(nuclei)
- Nuclei: 
- Go:
```
