### ISSUE TITLE
[BUG] ...The "=" with an empty parameter in the URI is missing

### ISSUE THREAD

**Issue by qianbenhyu** [projectdiscovery/nuclei#6259]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

![Image](https://github.com/user-attachments/assets/0a263b1d-7f51-467c-8638-4a8f165383b2)

![Image](https://github.com/user-attachments/assets/35847c01-e57c-46cf-aa15-6009b1a5ce80)

The "=" with an empty parameter in the URI is missing, As shown in the picture above, the "=" of "name" is missing.

### Expected Behavior

The "=" with an empty parameter in the URI is missing, As shown in the picture above, the "=" of "name" is missing.
When I set a parameter to null, nuclei should handle it correctly.

### Steps To Reproduce

nuclei -t example.yaml -u http://URL -proxy http://127.0.0.1:8080 -debug

### Relevant log output

```shell

```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

**Comment by qianbenhyu** [comment]
```yaml
id: xx

info:
  name: xx
  author: xx
  severity: high


http:
  - raw:
      - |
        GET /api/dbconn?db=POSTGRESQL&host=localhost&port=5432&username=root&name=& HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate, br
        Accept: */*
        Accept-Language: en-US;q=0.9,en;q=0.8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
        Connection: close
        Cache-Control: max-age=0

    matchers:
      - type: word
        part: body
        words:
          - "dbconn"
```
