### ISSUE TITLE
[FEATURE] Templating variables in YAML inputs

### ISSUE THREAD

**Issue by alban-stourbe-wmx** [projectdiscovery/nuclei#6260]
### Describe your feature request

Feature request: Support placeholders in YAML input files for dynamic request variation

To improve fuzzing and testing flexibility, it would be useful to support placeholders in YAML input files. This would allow dynamically varying specific elements (e.g. form fields, request parameters) within a single template, instead of duplicating the same request multiple times to cover all possible input combinations.

This approach is particularly effective for API calls or form submissions, where the structure remains constant but the values depend on the scan context or specific fuzzing strategies. It also opens the door to advanced use cases like table-based fuzzing within forms.

A pull request already introduces support for text templating using ytt in YAML files. Extending this capability to other formats such as OpenAPI or JSON would further enhance the tool’s flexibility and reduce configuration duplication.

### Describe the use case of the feature

This feature is primarily intended to enhance fuzzing workflows where the structure of a request remains fixed, but input values need to vary dynamically based on the scan context. For example, when testing an API endpoint that accepts form data, instead of writing multiple YAML files with different values for each test case, a single templated file with placeholders allows for easier and more maintainable test generation.

This is especially useful when targeting edge cases, injecting malicious payloads, or performing combinatorial input testing without duplicating boilerplate definitions.

### Describe alternatives you've considered

None 

### Additional context

Here is a templating example : 
```
#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ def get_value(key, default=""):
#@   if hasattr(data.values, key):
#@     value = getattr(data.values, key)
#@     return str(value)
#@   else:
#@     return default
#@   end
#@ end

timestamp: 2024-02-20T19:24:13+05:32
url: https://ginandjuice.shop/users/3
request:
  #@yaml/text-templated-strings
  raw: |+
    POST /users/3 HTTP/1.1
    Host: ginandjuice.shop
    Authorization: Bearer 3x4mpl3t0k3n
    Accept-Encoding: gzip
    Content-Type: application/x-www-form-urlencoded
    Connection: close
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

    foo=(@= get_value("foo") @)&bar=(@= get_value("bar") 
```

Here the command: 
`./nuclei -dast -l pkg/input/formats/testdata/ginandjuice.ytt.yaml -im yaml -t integration_tests/fuzz/fuzz-body-generic-sqli.yaml -v -proxy http://127.0.0.1:8080 -V foo=toto -V bar=tata -vtt`

Here the result before fuzzing : 
```
POST /users/3 HTTP/1.1
Host: ginandjuice.shop
Authorization: Bearer 3x4mpl3t0k3n
Accept-Encoding: gzip
Content-Type: application/x-www-form-urlencoded
Connection: close
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

foo=toto&bar=tata
```

### Pull request 
Here is the PR : https://github.com/projectdiscovery/nuclei/pull/6261
