### ISSUE TITLE
[BUG] Template context confusion when using the flow protocol while mass-scanning

### ISSUE THREAD

**Issue by nisay759** [projectdiscovery/nuclei#6263]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

I've written a simple nuclei template that (for the sake of this example) looks for Readme files in a WordPress' website plugins/themes locations. The steps are the following:
1. Issue an http request to the wesite's webroot and extract script/style/img imports using xpath
2. Clean the imports to only include the URL up to the plugin's or theme's root
3. For each theme/plugin root, issue an http request to look for the files `README.md` or `README.txt`

The template is as follows:
```yaml
id: wordpress_readme

info:
  name: WordPress readme detection
  author: nisay759
  severity: info
  tags: readme,wordpress,themes,plugins

flow: |
  // get imports from website's root
  http(1);

  let uniq = Dedupe();

  // get unique webroot of each import
  for (let path of iterate(template["imports"])) {
    let pathArray = path.split("/");
    let rootIdx = pathArray.indexOf("wp-content") + 3;
    let finalUrl = pathArray.slice(0, rootIdx).join("/");
    uniq.Add(finalUrl);
  }

  // for each import, look for readme
  for (let url of iterate(uniq.Values())) {
    set("target", url);
    http(2);
  }

http:
  # http(1) - Query web root and extract themes/plugins imports
  - method: GET
    redirects: true
    path:
      - "{{BaseURL}}"

    extractors:
      - type: xpath
        name: "imports"
        internal: true
        xpath:
          - "/html/*/script/@src[contains(.,'wp-content/plugins/')]"
          - "/html/*/script/@src[contains(.,'wp-content/themes/')]"
          - "/html/*/style/@src[contains(.,'wp-content/themes/')]"
          - "/html/*/img/@src[contains(.,'wp-content/themes/')]"

  # http(2) - Given a theme/plugin "target", look for Readme file
  - method: GET
    path:
      - "{{target}}/README.md"
      - "{{target}}/README.txt"

    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 200
```
The template runs as expected when running against a single host. I ran it against [https://wordcamp.org/](https://wordcamp.org/) since they have a public bug bounty program:

```
../nuclei -proxy http://127.0.0.1:8080 -t wordpress_readme.yaml -u https://wordcamp.org        
                                                                                                                          
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.4

		projectdiscovery.io

[INF] Current nuclei version: v3.4.4 (unknown) - remove '-duc' flag to enable update checks
[INF] Current nuclei-templates version: v9.8.9 (unknown) - remove '-duc' flag to enable update checks
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[wordpress_readme] [http] [info] https://central.wordcamp.org/wp-content/plugins/gutenberg/README.md
[INF] Scan completed in 3.601335048s. 1 matches found.
```

But when I run the template against a list of targets that contains the same previous host, I get no results. The list size seems to matter, and for a few hosts the template works just fine. Over 30 hosts, the results start becoming inconsistent.

For example, let's consider the following list that's comprised of Alexa's Top 29 hosts + our previous host, making it 30 targets:

```
https://google.com
https://youtube.com
https://facebook.com
https://baidu.com
https://wikipedia.org
https://qq.com
https://taobao.com
https://yahoo.com
https://tmall.com
https://amazon.com
https://twitter.com
https://sohu.com
https://live.com
https://jd.com
https://vk.com
https://instagram.com
https://sina.com.cn
https://weibo.com
https://reddit.com
https://login.tmall.com
https://360.cn
https://yandex.ru
https://linkedin.com
https://blogspot.com
https://netflix.com
https://twitch.tv
https://whatsapp.com
https://yahoo.co.jp
https://csdn.net
https://wordcamp.org
```
Running nuclei against this list yields no results :

```
../nuclei -proxy http://127.0.0.1:8080 -t wordpress_readme.yaml -l list.txt                         

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.4

		projectdiscovery.io

[INF] Current nuclei version: v3.4.4 (unknown) - remove '-duc' flag to enable update checks
[INF] Current nuclei-templates version: v9.8.9 (unknown) - remove '-duc' flag to enable update checks
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 30
[INF] Scan completed in 2.540299977s. No results found.
```

The position of the target in the list file doesn't seem to change the outcome.

I have noticed one curious behaviour though: Since https://wordcamp.org redirects to https://central.wordcamp.org, using the latter URL yields the expected result (maybe some internal alphabetical sorting of hosts ?).

I've digged through the documentation, and found the following mention in [https://docs.projectdiscovery.io/tools/nuclei/mass-scanning-cli](https://docs.projectdiscovery.io/tools/nuclei/mass-scanning-cli):

```
(Note: Nuclei by default reuses javascript runtimes to avoid overhead of creating new runtimes for each request)
```
Which made me think that maybe the `uniq` variable gets overwritten with an empty `Dedupe` instance when other hosts are scanned, since they all share the same runtime. With this assumption in mind, I edited the template as following:

```yaml
id: wordpress_readme

info:
  name: WordPress readme detection
  author: nisay759
  severity: info
  tags: readme,wordpress,themes,plugins

flow: |
  // get imports from website's root
  http(1);

  template["{{BaseURL}}_results"] = Dedupe();

  // get unique webroot of each import
  for (let path of iterate(template["imports"])) {
    let pathArray = path.split("/");
    let rootIdx = pathArray.indexOf("wp-content") + 3;
    let finalUrl = pathArray.slice(0, rootIdx).join("/");
    template["{{BaseURL}}_results"].Add(finalUrl);
  }

  // for each import, look for readme
  for (let url of iterate(template["{{BaseURL}}_results"].Values())) {
    set("target", url);
    http(2);
  }

http:
  # http(1) - Query web root and extract themes/plugins imports
  - method: GET
    redirects: true
    path:
      - "{{BaseURL}}"

    extractors:
      - type: xpath
        name: "imports"
        internal: true
        xpath:
          - "/html/*/script/@src[contains(.,'wp-content/plugins/')]"
          - "/html/*/script/@src[contains(.,'wp-content/themes/')]"
          - "/html/*/style/@src[contains(.,'wp-content/themes/')]"
          - "/html/*/img/@src[contains(.,'wp-content/themes/')]"

  # http(2) - Given a theme/plugin "target", look for Readme file
  - method: GET
    path:
      - "{{target}}/README.md"
      - "{{target}}/README.txt"

    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 200
```
In this updated version of the template, `let uniq = Dedupe()` becomes `template["{{BaseURL}}_results"] = Dedupe()`, so that each host's results are stored in a unique key of the `template` map.

With this change, the template seems to work as expected:

```
../nuclei -proxy http://127.0.0.1:8080 -t wordpress_readme_2.yaml -l list.txt                       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.4.4

		projectdiscovery.io

[INF] Current nuclei version: v3.4.4 (unknown) - remove '-duc' flag to enable update checks
[INF] Current nuclei-templates version: v9.8.9 (unknown) - remove '-duc' flag to enable update checks
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 30
[wordpress_readme] [http] [info] https://central.wordcamp.org/wp-content/plugins/gutenberg/README.md
[INF] Scan completed in 13.148207118s. 1 matches found.
```
Notes:
- In the examples above, I'm running the template through a proxy (to inspect the requests that are issued by nuclei). The behavior is the same regardless of the type of proxy used, or whether a proxy is used at all. I omitted those cases for the sake of brevity.
- The issue arises when scanning in `template-spray` mode. The `host-spray` mode yields the expected results, but it's kind of counterproductive using this mode when running a single template.

### Expected Behavior

Variables defined whithin a `flow` block should be scoped to the current host being scanned.

If a fix is not possible, the documentation should be updated to mention this kind of edge-case.

### Steps To Reproduce

Steps to reproduce are described in the previous sections.

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Arch Linux
- Nuclei: v3.4.4 (from GitHub releases)
- Nuclei's `config.yaml` content:


scan-strategy: "template-spray"
exclude-tags: []
disable-update-check: true
disable-unsigned-templates: false
header:
  - User-Agent: "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
```
