### ISSUE TITLE
POST Request doesnt send

### ISSUE THREAD

**Issue by kenshinsamue** [projectdiscovery/nuclei#639]
Im testing the app with a local web service server, the template that i've built based in the documentantion is this :+1: 
```
id: basic-example

info:
  name: Example Fuzzing
  author: k1k4ss0
  severity: info

requests:

  - payloads:
      username:
        - admin

      password:
        - admin
        - guest
        - password
        - test
        - 12345
        - 123456

    attack: clusterbomb

    # Supported attack types: sniper, pitchfork and clusterbomb

    raw:
      # Request with simple header manipulation with DSL functions
      - |
        POST /login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
        Accept-Language: en-US,en;q=0.9
        Connection: keep-alive
        usuario={{username}}&password={{password}}

    matchers:
      - type: status
        status:
          - 200
```
The actual target list is this one : 
```
192.168.253.17:8080
```

I run the script with these : 

```nuclei -t mi_template.yaml -l targets.txt ```

I got the defult advise of "No results found. Better luck next time!" , but with wireshark and in the server logs it doent appears the request itself, even a bad request, it just doesnt get sent

**Comment by ehsandeep** [comment]
@kenshinsamue the RAW request is invalid as you need to make new line between headers and body, here is valid example:-


```yaml
      - |
        POST /login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
        Accept-Language: en-US,en;q=0.9
        Connection: keep-alive

        usuario={{username}}&password={{password}}
```
