### ISSUE TITLE
[feature] Adding environment variable support using helper functions

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#643]
**Is your feature request related to a problem? Please describe.**
For regression testing and authenticated tests, it's helpful to read system variables to replace values into templates at run time.

for example:- 

```
export USER=admin
export PASSWORD=admin_token
source ~/.bashrc
```

**Describe the solution you'd like**

```yaml
requests:
  - method: POST
    path:
      - "{{BaseURL}}/apps"

    body: username={{ENV_USER}}&password={{ENV_TOKEN}}

    matchers:
      - type: word
        words:
          - "Logged in"
```

Result into:- 

```http
POST /apps HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.0.1583 Yowser/2.5 Safari/537.36
Connection: close
Content-Length: 44
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

username=admin&password=admin_token
```

**Comment by Mzack9999** [comment]
Support for environment variables is already added in https://github.com/projectdiscovery/nuclei/pull/641, the template would look like the following one:

```
requests:
  - method: POST
    path:
      - "{{BaseURL}}/apps"

    body: username={{env_get("ENV_USER")}}&password={{env_get("ENV_TOKEN")}}

    matchers:
      - type: word
        words:
          - "Logged in"
```

**Comment by ehsandeep** [comment]
@toufik-airane this is now supported with the release of [v2.4.3](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3), you just need to add `-env-vars` flag, and the template will read defined variable name from a running system.

Example template:-

```yaml
id: env-example

info:
  name: ENV Template
  author: pdteam
  severity: info

requests:
  - method: POST
    path:
      - "{{BaseURL}}/apps"

    body: username={{ENV_USER}}&password={{ENV_TOKEN}}

    matchers:
      - type: word
        words:
          - "Logged in"
```

```
nuclei -env-vars -t test.yaml -u https://example.com
```
