### ISSUE TITLE
[feature] Display the extracted regex value for File requests

### ISSUE THREAD

**Issue by 0xgaurang** [projectdiscovery/nuclei#645]
Thanks for adding the file request feature in nuclei. When using this feature I observed that nuclei detect regex value or words in local files based on the template provided. But it does not display the matching regex or word on the terminal. It would be really helpful if nuclei can display them on the terminal.

I have referred your [templating guide](https://nuclei.projectdiscovery.io/template-examples/file/) but I don't see a way to display the extracted regex or word.

Screenshot attached:

<img width="865" alt="Screenshot_2021-03-25_at_10_25_19_PM" src="https://user-images.githubusercontent.com/13043764/112514169-0cea1400-8dbb-11eb-9812-1ba28163c9a8.png">

**Comment by ehsandeep** [comment]
Hey @0xgaurang, just replace that matcher with extractors and you are done.

```yaml
id: google-api-key

info:
  name: Google API key
  author: pdteam
  severity: info

file:
  - extensions:
      - all
      - txt

    extractors:
      - type: regex
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
```
