### ISSUE TITLE
[question] how to judge when two matchers rule conflict(coverage)

### ISSUE THREAD

**Issue by t43Wiu6** [projectdiscovery/nuclei#646]
there is a fingerprint in `nuclei-templates/blob/master/technologies/tech-detect.yaml`
```yaml
    matchers-condition: or
    matchers:
      - type: word
        name: apache
        words:
          - "Apache"
        part: header
```
and i append some rules

```yaml
      - type: word
        name: apache
        words:
          - "Apache"
        part: header
      - type: word
        name: tomcat
        words:
          - "successfully installed Tomcat"
        part: body
```
the detect result is tomcat when i got a page that meets both criteria， it depends on what? 
Is there a possibility that could be a conflict would interfere with normal fingerprint identification.
I had already try to modify the sequence, always hapend.
