### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by amiralkizaru** [projectdiscovery/nuclei#65]
## Summary
Thank you for the tool <3

## Issue
I have created my own config to detect url upload
```yaml
id: Url Upload

info:
   name: Url Upload Detection
   author: sicksec
   severity: info


requests:
   - method: GET
     path:
        - "{{Baseurl}}"
     matchers:
        - type: regex
          part: body
          regex:
            - "\u003cinput[^\u003e]+type=[\"']?file[\"']?"
     extractors:
        - type: regex
          part: body
          regex:
            - "\u003cinput[^\u003e]+type=[\"']?file[\"']?"
```
## Expected Behaviour

Send a get request and check if regex exists

## Behaviour
![issue123123](https://user-images.githubusercontent.com/32225186/80605407-8f8b1780-8a22-11ea-89af-73f3c965021f.JPG)
## What I did ?

Tried with list of urls that are resolved and start with `https://` and `http://`
Also tried it against url without scheme `https` nor `http`
Same thing

## Config
WSL2 
`Linux DESKTOP-75EI56B 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
`go version go1.14 linux/amd64`
`GO111MODULE=on`
