### ISSUE TITLE
[issue] Matchers are not working with redirect chain

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#652]
**Describe the bug**
when `redirects: true` is used, the request follows the redirects and we can capture the redirect chain data with matchers/extractor which is not working.

**Nuclei version**
v2.3.2

<details>
<summary>basic-redirect</summary>

```yaml
id: basic-redirect

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    matchers:
      - type: status
        status:
          - 301
          - 302
```
</details>

```
echo http://hackerone.com | nuclei -t basic-redirect.yaml
```

Note:- we can view the redirect chain with `-debug` flag, this is only an issue with matchers/extractor.

**Comment by ehsandeep** [comment]
For matching in a redirect chain, `part: redirect-chain` needs to be mentioned and `redirect-chain` does not support status matcher.

For example:-

```yaml
    redirects: true
    matchers:
      - type: word
        part: redirect-chain
        words:
          - 'Location: https://www.hackerone.com'
```

**Comment by geeknik** [comment]
Will `redirect-chain` support status matchers in the future?

**Comment by ehsandeep** [comment]
@geeknik in the case of `part: redirect-chain` status can be matched using word matchers as well.

```yaml
    redirects: true
    matchers:
      - type: word
        part: redirect-chain
        words:
          - 301 Moved
```

@savushkin-yauheni JFYI^
