### ISSUE TITLE
[feature] Workflow to support tags based execution

### ISSUE THREAD

**Issue by Techbrunch** [projectdiscovery/nuclei#716]
**Is your feature request related to a problem? Please describe.**

I think it would make workflows more powerful if it was possible to trigger subtemplates based on tags.

**Describe the solution you'd like**

Something like this to follow the way it's done in regular templates:

```yaml
workflows:

  - template: technologies/tech-detect.yaml
    matchers:
      - name: wordpress
        subtemplates:
          - template: vulnerabilities/wordpress/
          - tags: wordpress,wp-plugin,php
```

This would make it easier to maintain workflows since you would not have to edit workflows everytime you add a new template related to wordpress in this case (assuming it is added to the right folder and correctly tagged).
