### ISSUE TITLE
Invalid memory address or nil pointer dereference with HTTP pipeline 

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#739]
Reported by melbadry9

**Describe the bug**

```yaml
id: test

info:
  name: test
  author: test
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    pipeline: true
    matchers:
      - type: word
        words:
          - 'test'
```
**Nuclei version**
2.3.7

**Screenshot of the error or bug**

```yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102d1424c]

goroutine 67 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0x14000088160, 0x14000160408, 0x13, 0x140002e2960, 0x140002e20c0, 0x140002e21b0, 0x0, 0x0, 0x0)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/http/request.go:280 +0x168c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP.func1(0x140001c3120, 0x14000088160, 0x14000160408, 0x13, 0x140002e20c0, 0x140002e21b0, 0x14000038290, 0x1400015cb10, 0x140002e2960)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/http/request.go:166 +0x7c
created by github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/http/request.go:163 +0x2cc
```
