### ISSUE TITLE
Accep-Encoding decompression fails

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#75]
By default Nuclei adds automatically the header `Accept-Encoding: gzip` and it works good. But... If the user adds the `Accept-Encoding: gzip` header manually to the template, it stops to work.

To reproduce the bug, you only have to add that header to a template and you will see that matchers seems that stop working.

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    headers:
       User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"
       Referer: "{{Hostname}}"
       Accept-Language: "en-US"
       Accept-Encoding: gzip
    matchers:
      - type: word
        words:
            - "Lunar"
        part: body
```

I can confirm that adding `Accept-Encoding: deflate` works good, i can add this header and body response is decompressed correctly.

And to finish, i already expected that Nuclei doesn't support Brotli compression, thats why the header `Accept-Encoding: br` doesn't wok in websites that have brotli compression enabled. Maybe it can be added, don't know if exists a Go library to handle Brotli compression.
