### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by Rvn0xsy** [projectdiscovery/nuclei#759]
Supporting output global variables in the template, here is example:

```
requests:
  - payloads:
      data: /helpers/payloads/1.txt

    raw:
      - |
        GET /index.php HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        
    matchers:
      - type: word
        name: match_data
        words:
           - data
        part: body

    output: match success , data is : $match_data$
```

-json output :

```
{
  "templateID": "xxxxx",
  "info": {
    "severity": "high",
    "tags": "xxx",
    "reference": "https://www.xxx/docs/internals/security",
    "name": "xxxx",
    "author": "xxx"
  },
  "type": "http",
  "host": "http://xxxx",
  "matched": "true",
  "ip": "xx.xx.xx.xx",
  "timestamp": "2021-06-xxxx",
 "output":"match success , data is : 123"
}
```

I expect to output additional data after the match is successful, thank you 🤙

**Comment by ehsandeep** [comment]
@Rvn0xsy you can already do this with `extractors`, or use matchers + extractors altogether, checkout the guide at https://nuclei.projectdiscovery.io/templating-guide/

```yaml
requests:
    raw:
      - |
        GET /index.php HTTP/1.1
        Host: {{Hostname}}
        Connection: close
        
    extractors:
      - type: regex
        name: match_data
        part: body
        regex:
          - "(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"
```
