### ISSUE TITLE
Create output file if output flag specified

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#762]
**Is your feature request related to a problem? Please describe.**
Breaking the pipeline, in the pipeline if the result of nuclei used by the next tool, it gets failed.

For example:-

```yaml
      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@v1.0.2
        with:
          urls: output/active_urls.txt
          output: output/nuclei_output.txt
          templates: ./nuclei-templates/cves/

      - name: Notify Alerts
        run: |
          notify -slack -slack-webhook-url ${{ secrets.SLACK_WEBHOOK }} < output/nuclei_output.txt
```

**Describe the solution you'd like**

If output flag (`-o`) is used, produce a blank output file in case of No results as well.
