### ISSUE TITLE
[issue] 'internal: true' in an extractor disables the matchers

### ISSUE THREAD

**Issue by Saikuron** [projectdiscovery/nuclei#783]
**Describe the bug**
I noticed that if I have a template containing matchers and extractor and that I'm using 'internal: true' on the extractor, then the matchers won't match even though it should.

**Nuclei version**
2.3.8

**Screenshot of the error or bug**
I'm using httbin.org to make tests. Here are the requests.

```YAML
requests:
  - raw: 
    - |
      GET /get HTTP/1.1
      Host: httpbin.org
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) nuclei
      Connection: close
      Accept: */*
      Accept-Language: en
      Accept-Encoding: gzip
 
    - |
      POST /post HTTP/1.1
      Host: httpbin.org
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) nuclei
      Connection: close
      Accept: */*
      Accept-Language: en
      Accept-Encoding: gzip
 
      server=§server_extract§
 
    extractors:
      - type: regex
        name: server_extract
        group: 1
        part: all
        # Uncomment the following line and the matcher won't match
        # internal: true
        regex: 
          - 'Server: (.+)'
 
    matchers:
      - type: regex
        name: server
        part: all
        regex:
          - 'Server:'
```

Turn on/off the `internal: true` line to see the effect of the bug.
When the line is commented, the matcher works as expected (but the extractor can't be used as a variable). 
When the line is not commented, the matcher doesn't work anymore.
Is it a bug ? The doc doesn't mention this.
