### ISSUE TITLE
Whois protocol support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#798]
**Is your feature request related to a problem? Please describe.**
Wanted to craft templates for the output of `whois example.com`

**Describe the solution you'd like**

```yaml
id: basic-whois-example

info:
  name: Test WHOIS Template
  author: pdteam
  severity: info

whois:
    host:
      - "{{Hostname}}"

    extractors:
      - type: regex
        group: 1
        regex:
          - "Tech Organization: ([A-Z ]+)"
          - "Registrar Registration Expiration Date: ([A-Z ]+)"
```

As default, whois makes use of default whois DB and supports custom DB to connect if custom `host:port` is provided, we can expose this support via flags.
