### ISSUE TITLE
[feature] Adding Dynmaic extractor support to Network request

### ISSUE THREAD

**Issue by milo2012** [projectdiscovery/nuclei#803]
**Describe the solution you'd like**
Is it possible to add extractor support to network requests in the pipe line ?

I was trying to explore if writing a template for https://github.com/cybersecurityworks553/CVE-2021-1675_PrintNightMare was possible.
However, I hit an issue as I needed to perform regex against the data in the response and use that value in the next request.

Thank you for the awesome tool

**Comment by ehsandeep** [comment]
Thanks again @milo2012, Do you mean reusing the dynamic data in network protocol, or basic extractor which is already supported, for example:- https://github.com/projectdiscovery/nuclei-templates/blob/master/network/detect-rsyncd.yaml

**Comment by milo2012** [comment]
Hi
I was referring to reusing the dynamic data in network protocol. Thanks

**Comment by ehsandeep** [comment]
@milo2012 this support is now added into dev branch with the following PR https://github.com/projectdiscovery/nuclei/pull/811

Uses should be the same as HTTP, here is an example template.

```yaml
id: test

info:
  name: test
  author: test
  severity: high

network:
  - inputs:
      - data: "USER anonymous\r\n"
        read: 1024
        name: step1
      - data: "PASS {{user}}\r\n"
        read: 1024
        name: step2
    host:
      - "{{Hostname}}"
    read-size: 1024

    matchers:
      - type: word
        words:
          - "530 Login incorrect." 
        part: data

    extractors:
      - type: regex
        name: user
        internal: true
        group: 1
        regex:
          - "Please specify ([a-z]+) password."
        part: step1
```
