### ISSUE TITLE
[issue] sniper attack not behaving as intended when using multiple placeholders

### ISSUE THREAD

**Issue by gholamifrd** [projectdiscovery/nuclei#814]
**Describe the bug**
The documentations reads:
"The sniper attack uses only one payload set, and it replaces only one position at a time. It loops through the payload set, first replacing only the first marked position with the payload and leaving all other positions to their original value. After its done with the first position, it continues with the second position."
this statement implies the sniper attack mode should behave exaclty like BurpSuite which is not.
for example if we create a template like this:

```
requests:
  - payloads:
      payload:
        - a
        - b
        - c
    attack: sniper
    raw:
      - |
        GET /{{payload}}/{{payload}} HTTP/1.1
        Host: {{Hostname}}
```

the resulted requests will be something like this:

```
GET /a/a HTTP/1.1
GET /b/b HTTP/1.1
GET /c/c HTTP/1.1
```

which means nuclei replaces all the words {{payload}} with a value from list at once. instead it should replace one placeholder at a time.
then it should be something like this:

```
GET a/{{payload}} HTTP/1.1
GET a/{{payload}} HTTP/1.1
GET a/{{payload}} HTTP/1.1
GET {{payload}}/a HTTP/1.1
GET {{payload}}/b HTTP/1.1
GET {{payload}}/c HTTP/1.1
```

(instead of {{payload}} it could be the original value or some default value specified by user)

**Nuclei version**
 `2.3.8`

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
