### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#821]
**Describe the bug**

### While Trying Rebuild CVS's e.g. CVE-2005-2428 From 
```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/names.nsf/People?OpenView"
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: regex
        name: domino-username
        regex:
          - '(<a href\=\"/names\.nsf/[0-9a-z\/]+\?OpenDocument)'
        part: body
```

### To Do Something Like That 
```
requests:
  - payloads:
      Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
    attack: sniper
    threads: 100

    raw:
      - |
        GET /names.nsf/People?OpenView HTTP/1.1
        Host: {{Subdomains}}
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: regex
        name: domino-username
        regex:
          - '(<a href\=\"/names\.nsf/[0-9a-z\/]+\?OpenDocument)'
        part: body 
```

Some Tips To Understand My Template , I'm Trying To FUZZ Host Header e.g. If My Wordlist Contains :-
internal.company.com
dev.company.com

Nuclei Will Sent Two Requests 

```
GET /names.nsf/People?OpenView HTTP/1.1
Host: internal.company.com
```

```
GET /names.nsf/People?OpenView HTTP/1.1
Host: dev.company.com
```

**So Nuclei Will Work Fine If My Wordlist Is Small e.g. 10 Lines And URL's File Also Small But When My 
Wordlist Contains e.g. 200 Lines And URL's File 200 URL's , I Got This Error** 

![Screenshot!UNITO-UNDERSCORE!2021-07-09!UNITO-UNDERSCORE!10!UNITO-UNDERSCORE!19!UNITO-UNDERSCORE!39](https://user-images.githubusercontent.com/54332136/125050158-02216980-e0a2-11eb-833e-03acfcbd53dd.png)

Here Is My Command 

### nuclei -c 400 -list urls.txt -t "/cvs/*.yaml" -o CVE.out
Number OF Lines Into urls.txt 145 Lines
Number OF Lines Into My Wordlist That Will Use 150 Lines
Number OF CVS's 70 Yaml Files

So I Test It Multiple Times And Got The Same Error After e.g. 10-15 Minutes

**Nuclei version**
Current Version: 2.3.8

### And Also There Is Another Error While Nuclei Facing HTTP Response Contains HTTP/1.0
![Screenshot!UNITO-UNDERSCORE!2021-07-08!UNITO-UNDERSCORE!18!UNITO-UNDERSCORE!25!UNITO-UNDERSCORE!08](https://user-images.githubusercontent.com/54332136/125051632-6d1f7000-e0a3-11eb-859a-da7a7bccbc87.png)
