### ISSUE TITLE
Unknown chars in network response breaking matcher engine

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#829]
**Describe the bug**

**Nuclei version**
2.4.0

**Screenshot of the error or bug**

Network fingerprint debug:-

```yaml
{
  "data": "\ufffd\ufffd\u0001\ufffd\ufffd\u0003",
  "hex": "fffb01fffb03",
  "response": true
}
{
  "data": "Modbus/TCP to RTU Bridge\r\u0000\nSerial Number 5138264  MAC address 00204A519578\n\r\u0000Software version V2.6.0.0B1 (131112) DLX\r\u0000\n\n\r\u0000Press Enter for Setup Mode \n\r\u0000",
  "hex": "4d6f646275732f54435020746f20525455204272696467650d000a53657269616c204e756d626572203531333832363420204d41432061646472657373203030323034413531393537380a0d00536f6674776172652076657273696f6e2056322e362e302e30423120283133313131322920444c580d000a0a0d00507265737320456e74657220666f72205365747570204d6f6465200a0d00",
  "response": true
}
```

Nuclei debug:-

```sh
[INF] [detect-modbus-bridge] Dumped Network request for redacted:9999 address=redacted:9999

Hex:
[DBG] [detect-modbus-bridge] Dumped Network response for redacted9999
▒▒▒▒
Hex: fffb01fffb03
[INF] No results found. Better luck next time!
```

Netcat issue:-

```sh
~$ nc redacted 9999
▒▒▒▒Modbus/TCP to RTU Bridge
Serial Number 5138264  MAC address 00204A519578
Software version V2.6.0.0B1 (131112) DLX

Press Enter for Setup Mode
```
