### ISSUE TITLE
Debug flag does not include cookie header

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#844]
**Describe the bug**
Debug flag does not include cookie header, printing will help while testing/using templates involving multiple steps with cookie session using cookie reuse.

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/test"

    cookie-reuse: true
    matchers:
      - type: word
        words:
          - "This is test matcher text"
```

```
echo https://hackerone.com | nuclei -t test.yaml -debug-req
```

**Nuclei version**
2.5.3
