### ISSUE TITLE
[issue] Logical issue with req-condition matchers

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#846]
**Describe the bug**
Example template to run:-

```yaml
id: test

info:
  name: test
  author: test
  severity: info
  description: test

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
      - '{{BaseURL}}/na_path'

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200"
```

Expected behavior:-

```
echo https://example.com | nuclei -t test.yaml -silent

[2021-07-19 15:52:29] [test] [http] [info] https://example.com/
```

Current behavior:-

```
echo https://example.com | nuclei -t test.yaml -silent

[2021-07-19 15:52:29] [test] [http] [info] https://example.com/
[2021-07-19 15:52:31] [test] [http] [info] https://example.com/na_path
```

**Nuclei version**
2.4.0

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by Mzack9999** [comment]
Working as intended - When the second request is matched the matcher is true as it was related to the first request

**Comment by ehsandeep** [comment]
Closing, as this is expected behavior, following matcher should be use when looking for single status and not using request condition.

```yaml
    matchers:
      - type: dsl
        dsl:
          - "status_code == 200"
```
