### ISSUE TITLE
URL encoding problems

### ISSUE THREAD

**Issue by 0xspade** [projectdiscovery/nuclei#852]
Hi Team,

I came across testing some stuff, and creating my own RXSS detections however, I noticed something different.

so my payload in my nuclei template is like this: `"{{BaseURL}}/'\"><huehue"`

however, nuclei looks like encoding this one to `/%27%22%3E%3Chuehue`

So I tried this in one of the vulnerable apps (private program) so if I inject `/%27%22%3E%3Chuehue` it will print out the very same. But if I enter this one `'\"><huehue` it will trigger the XSS.

**Comment by princechaddha** [comment]
Hello @0xspade, you can use raw request with unsafe set to true. You can read more about it [here](https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#raw-http-requests) 

```
requests:
  - raw:
      - |
        GET /'\"><xdxdxd HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en
        Connection: close

    unsafe: true
```
