### ISSUE TITLE
[feature] Matching conditions on templates in debug mode

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#894]
**Is your feature request related to a problem? Please describe.**
It would be very nice to have a feature in debug mode that would notify which conditions were satisfied during the scan of a target. 

Often takes me a while figuring out which one of the conditions are TRUE (or not). 

**Describe the solution you'd like**
Let's assume we have the following AND matchers. 

```
 matchers-condition: and
    matchers:
      - type: word
      - name: alert
        words:
          - '<svg/onload=alert(/{{randstr}}/)>'
        part: body

      - type: status
      - name: status
        status:
          - 200
      - type: word
      - name: html
        part: header
        words:
          - "text/html"
```
The output would be somethig like this:

 >  
[DEBUG]  Condition alert:  Matched [or TRUE]
[DEBUG]  Condition status:  Not matched [or FALSE]
[DEBUG]  Condition html:  Matched [or TRUE]
[DEBUG] Matcher conditions: TRUE & FALSE & TRUE = FALSE
