### ISSUE TITLE
panic: interface conversion: interface

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#933]
**Describe the bug**

```yaml
id: basic-raw-example
info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{rand_int(1, 10)}}
        Connection: close
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Language: en-US,en;q=0.9

    matchers:
      - type: word
        words:
          - "Test is test matcher text"
```

```
echo https://example.com | nuclei -t test.yaml
```

```
panic: interface conversion: interface {} is float64, not int

goroutine 89 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/operators/common/dsl.glob..func33(0x14000de70e0, 0x2, 0x2, 0x0, 0x14000233498, 0x104e2c264, 0x140002334f8)
	/Users/geekboy/Github/nuclei/v2/pkg/operators/common/dsl/dsl.go:223 +0x108
github.com/Knetic/govaluate.makeFunctionStage.func1(0x0, 0x0, 0x10532bda0, 0x14000de5188, 0x10557f228, 0x14000d8dda0, 0x0, 0x0, 0xf, 0x14000dd4d20)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/evaluationStage.go:242 +0x80
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x105144393, 0x22, 0x1, 0x14000284600, 0x6, 0x8, 0x14000dd4d70, 0x140008ac66d, 0xf, 0x14000dd4d70, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:228 +0x10c
github.com/Knetic/govaluate.EvaluableExpression.Eval(0x105144393, 0x22, 0x1, 0x14000284600, 0x6, 0x8, 0x14000dd4d70, 0x140008ac66d, 0xf, 0x1055817a8, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:159 +0x60
github.com/Knetic/govaluate.EvaluableExpression.Evaluate(0x105144393, 0x22, 0x1, 0x14000284600, 0x6, 0x8, 0x14000dd4d70, 0x140008ac66d, 0xf, 0x140003e0f00, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:136 +0x54
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.Evaluate(0x140008ac640, 0x137, 0x140003e0f00, 0x0, 0x12cdbd801, 0x0, 0x140003f8901)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/expressions/expressions.go:31 +0x1fc
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).handleRawWithPayloads(0x14000de70a0, 0x105591918, 0x1400020a558, 0x140008ac3c0, 0x138, 0x140008c21b0, 0x13, 0x140003e0ed0, 0x0, 0x105342080, ...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:144 +0x4c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).makeHTTPRequestFromRaw(0x14000de70a0, 0x105591918, 0x1400020a558, 0x140008c21b0, 0x13, 0x140008ac3c0, 0x138, 0x140003e0ed0, 0x0, 0x0, ...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:133 +0x70
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).Make(0x14000de70a0, 0x140008c2198, 0x13, 0x140003e0e40, 0x0, 0x0, 0x30, 0x1054a93e0, 0x12cdbd890)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:78 +0x31c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0x14000298160, 0x140008c2198, 0x13, 0x140003e0e40, 0x140003e0e70, 0x140003e0ea0, 0x0, 0x0)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/request.go:210 +0x130
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0x14000de6f00, 0x140008c2198, 0x13, 0x10510ea00, 0x28, 0x1054a9300)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/executer/executer.go:53 +0x11c
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1(0x14000de7080, 0x14000ed0460, 0x140000be000, 0x1400003bed8, 0x140008c2198, 0x13)
	/Users/geekboy/Github/nuclei/v2/internal/runner/processor.go:21 +0x6c
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
	/Users/geekboy/Github/nuclei/v2/internal/runner/processor.go:18 +0xd8
```

**Nuclei version**
2.4.3

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
