### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by JaderKb** [projectdiscovery/nuclei#946]
**Describe the bug**

There is a bug starting from version 2.4.0 (version 2.3.8 do not happen) related to Panic: runtime error: slice bounds out of range. I didn't find a pattern to it and sometimes it works with the same command.  What I am using:
./nuclei -l ./hosts.txt -stats -rl 20 -bs 20 -t ./temaplatesError/ -irr -markdown-export ./files/ -o ./results.txt --verbose
To test it I am using 200+ hosts and maybe you had to try it repeatedly.

Here are two template where it happens but there are more that trigger the same bug, I have tried it with different computers and OS versions.

**Templates Used**
**First**

```yaml
id: Arbitrary Text Injection

info:
  name: Arbitrary Text Injection
  author: Nikhil Kumar
  severity: Low
  tags:  injection

requests:
  - method: GET
    path:
      - "{{BaseURL}}/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"

    matchers:
      - type: word
        words:
          - "!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
        part: body
```

**Second**

```yaml
id: header-reflection-body

info:
  name: Looking for reflected values from request headers
  author: panch0r3d
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/obviouslynotarealpathtoget404URLCanary1234"
      - "{{BaseURL}}/%%0D%%0|}+^$Aset-cookie%%20:mycookie=URLCKCanary1234;"
    redirects: true
    max-redirects: 5
    headers:
      User-Agent: "Mozilla UACanary12345"
      X-Forwarded-For: "panch0r3d.github.io?XFCanary12345"
      Referer: "RFcanary12345.comRF"
      Cookie: "CKCanary12345=qwertyCK"
      Origin: "ORCanary12345.comOR"
      x-request-id: "XRCanary12345"
      X-Correlation-ID: "XCIDCanary12345"
      from: "abc@FRcanary12345.comFR"
      pragma: "PRcanary12345"
      via: "VIACanary12345.comVIA"
      x-requested-with: "XRWCanary12345"
      x-att-deviceid: "XADCanary12345"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - ".*?(c|C)(a|A)(n|N)(a|A)(r|R)(y|Y)12345.*?"
        part: body
    extractors:
      - type: regex
        part: body
        regex:
          - "(c|C)(a|A)(n|N)(a|A)(r|R)(y|Y)12345.*?([\r\n]|[}]|[,][>])"
```

**Nuclei version**

starting in version 2.4.0

**Screenshot of the error or bug**

<img width="1315" alt="error2" src="https://user-images.githubusercontent.com/23459811/129476296-219e783b-e29f-46fe-8e84-d28e85409d36.png">
<img width="1350" alt="error1" src="https://user-images.githubusercontent.com/23459811/129476298-d86e0048-6488-4de5-822d-ab32a8aa33fe.png">
