### ISSUE TITLE
[feature] Allow whitespace at the begining of a line for HTTP headers in raw requests

### ISSUE THREAD

**Issue by aroly** [projectdiscovery/nuclei#954]
**Issue**

HTTP/1.1 once supported "line folding" for HTTP headers. From the RFC draft (https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01): "HTTP/1.1 headers can be folded onto multiple lines if the continuation line begins with a space or horizontal tab." This has been deprecated, but a lot of servers still supports it, so it's useful when testing. 

I tried to insert such a header in a raw HTTP request (in the " a:b" header below, with a space before "a"): 

```
requests:
  - raw:
    - |
        POST {{BaseURL}} HTTP/1.1
        Host: {{Hostname}}
        Connection: keep-alive
        Content-Type: application/x-www-form-urlencoded
        Test: folded
         a: b
        Content-Length: 11

        _method=GET

```

I also tried tab, and with url-encoded versions (%20 for space, %9 for tab), or using helper functions (` {{ url_decode("%09") }}a: b`) I always receive a request like:

```
POST /foo HTTP/1.1
Content-Length: 11
Host: foo.bar
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Test: folded
a: b
```

where the tab or space has been stripped out.

**Solution**

For raw requests, allow to insert a space or tab (or other characters for other use cases).
