### ISSUE TITLE
[feature] Supporting custom resolvers for DNS requests

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#963]
**Is your feature request related to a problem? Please describe.**

So far, if we do a template DNS query using the predefined resolver from [DefaultResolvers](https://github.com/projectdiscovery/nuclei/blob/7377dd6c54dd4464c933b7b4bcc0d5e17c2c0f74/v2/pkg/protocols/dns/dnsclientpool/clientpool.go#L19-L24).

**Describe the solution you'd like**

Adding new key for _(such as)_ resolvers:

```yaml
dns:
  - name: "{{FQDN}}"
    type: CNAME
    class: inet
    recursion: true
    retries: 3

    resolvers:
      - "8.8.8.8"
      - "1.1.1.1"
```
