### ISSUE TITLE
[feature] Add coloring to debug information

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#999]
Colorize matched content when using the `debug` flag. This functionality would come very handy to highlight relevant content when working with large requests or file templates.

Example:
Snippet from the `tech-detect.yaml` template:
```yaml
matchers:
  - type: word
     name: simplehttp
     words:
       - "SimpleHTTP"
     part: header
```

The content marked in the following screenshot should be highlighted:
![image](https://user-images.githubusercontent.com/13679401/132217094-19ca7101-85b4-454f-bef3-6c25509d283d.png)

TBD: if the whole line or just the word; or the whole line with one font/background color and the word with another font/background color

Thanks @geeknik for the idea.
